// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/Core/CoreFnMatrixReduce.toml.
//
// Tests for context-backed public overloads.
// The public overload test doubles as the kernel correctness test —
// it calls OaFnMatrix::<Op>(...) which dispatches the SPIR-V kernel directly.
// CPU references come from each op's `forward_op` field.

#include <gtest/gtest.h>
#include <Oa/Core/FnMatrix.h>
#include <Oa/Runtime/Engine.h>
#include <Oa/Runtime/Context.h>
#include <Oa/Runtime/ComputeGraph.h>
#include <Oa/Runtime/RuntimeGlobal.h>
#include <algorithm>
#include <cmath>
#include <numeric>
#include <vector>

static OaComputeEngine* GRt = nullptr;

class TestFnMatrixReduce : public ::testing::Test {
protected:
	static void SetUpTestSuite() {
		OaEngineConfig cfg{};
		cfg.AppName = "TestFnMatrixReduce";
		auto r = OaComputeEngine::Create(cfg);
		ASSERT_TRUE(r.IsOk()) << r.GetStatus().GetMessage();
		static OaUniquePtr<OaComputeEngine> rt = std::move(*r);
		GRt = rt.get();
		OaRuntimeGlobal::SetRuntime(GRt);
	}
};

TEST_VK(TestFnMatrixReduce, Sum_Context) {
	constexpr OaU32 N = 256;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::Sum(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	float want = std::accumulate(a_host.begin(), a_host.end(), 0.0f);
	float got = 0.0f;
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, &got, sizeof(float)).IsOk());
	EXPECT_NEAR(got, want, 1e-3f) << "Reduction result mismatch";
}

TEST_VK(TestFnMatrixReduce, Max_Context) {
	constexpr OaU32 N = 256;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::Max(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	float want = *std::max_element(a_host.begin(), a_host.end());
	float got = 0.0f;
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, &got, sizeof(float)).IsOk());
	EXPECT_NEAR(got, want, 1e-4f) << "Reduction result mismatch";
}

