// AUTO-GENERATED by tools/gen/fn/generate.py — DO NOT EDIT.
// Source of truth: tools/gen/fn/schema/ml/mlFnMatrixActivation.toml.
//
// Tests for context-backed public overloads.
// The public overload test doubles as the kernel correctness test —
// it calls oa::FnMatrix::<Op>(...) which dispatches the SPIR-V kernel directly.
// CPU references come from each op's `forward_op` field.

#include <gtest/gtest.h>
#include <oa/core/fnMatrix.h>
#include <oa/ml/fnMatrix.h>
#include <oa/runtime/engine.h>
#include <oa/runtime/executionSession.h>
#include <oa/runtime/executableGraph.h>
#include <algorithm>
#include <cmath>
#include <numeric>
#include <vector>

static oa::Engine* runtime = nullptr;

class TestFnMatrixActivation : public ::testing::Test {
protected:
	static void SetUpTestSuite() {
		oa::EngineConfig config{};
		config.appName = "TestFnMatrixActivation";
		auto result = oa::Engine::create(config);
		ASSERT_TRUE(result.isOk()) << result.getStatus().getMessage();
		static oa::UniquePtr<oa::Engine> engine = std::move(*result);
		runtime = engine.get();
	}
};

TEST_VK(TestFnMatrixActivation, gelu_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::gelu(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = 0.5f * aHost[i] * (1.0f + std::tanh(0.7978845608f * (aHost[i] + 0.044715f * aHost[i] * aHost[i] * aHost[i])));
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, silu_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::silu(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] / (1.0f + std::exp(-aHost[i]));
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, relu_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::relu(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::max(aHost[i], 0.0f);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, tanh_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::tanh(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::tanh(aHost[i]);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, sigmoid_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::sigmoid(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = 1.0f / (1.0f + std::exp(-aHost[i]));
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, leakyRelu_Context) {
	constexpr oa::U32 N = 256;
	constexpr oa::F32 kScalar = 0.01f;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::leakyRelu(a, kScalar);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::max(kScalar * aHost[i], aHost[i]);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, elu_Context) {
	constexpr oa::U32 N = 256;
	constexpr oa::F32 kScalar = 1.0f;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::elu(a, kScalar);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] > 0.0f ? aHost[i] : kScalar * (std::exp(aHost[i]) - 1.0f);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, mish_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::mish(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] * std::tanh(std::log(1.0f + std::exp(aHost[i])));
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, softplus_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::softplus(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::max(aHost[i], 0.0f) + std::log(1.0f + std::exp(-std::abs(aHost[i])));
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}
