// AUTO-GENERATED by tools/fnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: tools/fnAutogen/schema/core/coreFnMatrixReduce.toml.
//
// Tests for context-backed public overloads.
// The public overload test doubles as the kernel correctness test —
// it calls oa::FnMatrix::<Op>(...) which dispatches the SPIR-V kernel directly.
// CPU references come from each op's `forward_op` field.

#include <gtest/gtest.h>
#include <oa/core/fnMatrix.h>
#include <oa/runtime/engine.h>
#include <oa/runtime/executionSession.h>
#include <oa/runtime/executableGraph.h>
#include <algorithm>
#include <cmath>
#include <numeric>
#include <vector>

static oa::Engine* runtime = nullptr;

class TestFnMatrixReduce : public ::testing::Test {
protected:
	static void SetUpTestSuite() {
		oa::EngineConfig config{};
		config.appName = "TestFnMatrixReduce";
		auto result = oa::Engine::create(config);
		ASSERT_TRUE(result.isOk()) << result.getStatus().getMessage();
		static oa::UniquePtr<oa::Engine> engine = std::move(*result);
		runtime = engine.get();
	}
};

TEST_VK(TestFnMatrixReduce, sum_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::sum(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	float want = std::accumulate(aHost.begin(), aHost.end(), 0.0f);
	float got = 0.0f;
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, &got, sizeof(float)).isOk());
	EXPECT_NEAR(got, want, (1e-3f) * (1.0f + std::abs(want))) << "Reduction result mismatch";
}

TEST_VK(TestFnMatrixReduce, mean_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::mean(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	float want = std::accumulate(aHost.begin(), aHost.end(), 0.0f) / static_cast<float>(N);
	float got = 0.0f;
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, &got, sizeof(float)).isOk());
	EXPECT_NEAR(got, want, (1e-3f) * (1.0f + std::abs(want))) << "Reduction result mismatch";
}

TEST_VK(TestFnMatrixReduce, softmax_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::softmax(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::exp(aHost[i]) / std::accumulate(aHost.begin(), aHost.end(), 0.0f, [](float sum, float x) { return sum + std::exp(x); });
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixReduce, logSoftmax_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::logSoftmax(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] - std::log(std::accumulate(aHost.begin(), aHost.end(), 0.0f, [](float sum, float x) { return sum + std::exp(x); }));
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixReduce, max_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::max(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	float want = *std::max_element(aHost.begin(), aHost.end());
	float got = 0.0f;
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, &got, sizeof(float)).isOk());
	EXPECT_NEAR(got, want, (1e-4f) * (1.0f + std::abs(want))) << "Reduction result mismatch";
}
