// @generated by tool/gen/fn/generate.py; DO NOT EDIT.
// schema=matrix_elemwise.json schema_version=1 generator_version=64
// schema_sha256=6d4112435554d3615e6c2494c5062e5f93fa85815bccffa2ca49b12f97aaac75
//! Complete saved-state attachments; observer lifecycle is handwritten.

use super::super::{GradNodeMatrix, record};
use crate::{Matrix, Result};

pub(in crate::matrix) fn record_add(left: &Matrix, right: &Matrix, output: &Matrix) -> Result<()> {
	record(GradNodeMatrix::Add {
		left: left.clone(),
		right: right.clone(),
		output_id: output.value_id(),
	})
}

pub(in crate::matrix) fn record_sub(left: &Matrix, right: &Matrix, output: &Matrix) -> Result<()> {
	record(GradNodeMatrix::Sub {
		left: left.clone(),
		right: right.clone(),
		output_id: output.value_id(),
	})
}

pub(in crate::matrix) fn record_mul(left: &Matrix, right: &Matrix, output: &Matrix) -> Result<()> {
	record(GradNodeMatrix::Mul {
		left: left.clone(),
		right: right.clone(),
		output_id: output.value_id(),
	})
}

pub(in crate::matrix) fn record_div(left: &Matrix, right: &Matrix, output: &Matrix) -> Result<()> {
	record(GradNodeMatrix::Div {
		left: left.clone(),
		right: right.clone(),
		output_id: output.value_id(),
	})
}

pub(in crate::matrix) fn record_scale(input: &Matrix, output: &Matrix, scalar: f32) -> Result<()> {
	record(GradNodeMatrix::Scale {
		input: input.clone(),
		output_id: output.value_id(),
		scalar,
	})
}

pub(in crate::matrix) fn record_abs(input: &Matrix, output: &Matrix) -> Result<()> {
	record(GradNodeMatrix::Abs {
		input: input.clone(),
		output_id: output.value_id(),
	})
}

pub(in crate::matrix) fn record_log(input: &Matrix, output: &Matrix) -> Result<()> {
	record(GradNodeMatrix::Log {
		input: input.clone(),
		output_id: output.value_id(),
	})
}

pub(in crate::matrix) fn record_sqrt(input: &Matrix, output: &Matrix) -> Result<()> {
	record(GradNodeMatrix::Sqrt {
		input: input.clone(),
		output: output.clone(),
		output_id: output.value_id(),
	})
}

pub(in crate::matrix) fn record_exp(input: &Matrix, output: &Matrix) -> Result<()> {
	record(GradNodeMatrix::Exp {
		input: input.clone(),
		output: output.clone(),
		output_id: output.value_id(),
	})
}

pub(in crate::matrix) fn record_reciprocal(input: &Matrix, output: &Matrix) -> Result<()> {
	record(GradNodeMatrix::Reciprocal {
		input: input.clone(),
		output: output.clone(),
		output_id: output.value_id(),
	})
}

pub(in crate::matrix) fn record_clamp_max(
	input: &Matrix,
	output: &Matrix,
	maximum: f32,
) -> Result<()> {
	record(GradNodeMatrix::ClampMax {
		input: input.clone(),
		output_id: output.value_id(),
		maximum,
	})
}

pub(in crate::matrix) fn record_clamp_min(
	input: &Matrix,
	output: &Matrix,
	minimum: f32,
) -> Result<()> {
	record(GradNodeMatrix::ClampMin {
		input: input.clone(),
		output_id: output.value_id(),
		minimum,
	})
}

pub(in crate::matrix) fn record_copy(input: &Matrix, output: &Matrix) -> Result<()> {
	record(GradNodeMatrix::Copy {
		input: input.clone(),
		output_id: output.value_id(),
	})
}
