// @generated by tool/gen/fn/generate.py; DO NOT EDIT.
// schema=matrix_reduce.json schema_version=1 generator_version=64
// schema_sha256=82fbdb597e6fd7557a8c081a6302ceb383b2df455716387a549bed1a21f44fdd
//! Complete saved-state attachments; observer lifecycle is handwritten.

use super::super::{GradNodeMatrix, record};
use crate::{Matrix, Result};

pub(in crate::matrix) fn record_softmax(input: &Matrix, output: &Matrix, dim: i32) -> Result<()> {
	record(GradNodeMatrix::Softmax {
		input: input.clone(),
		output: output.clone(),
		output_id: output.value_id(),
		dim,
	})
}

pub(in crate::matrix) fn record_log_softmax(
	input: &Matrix,
	output: &Matrix,
	dim: i32,
) -> Result<()> {
	record(GradNodeMatrix::LogSoftmax {
		input: input.clone(),
		output: output.clone(),
		output_id: output.value_id(),
		dim,
	})
}

pub(in crate::matrix) fn record_sum(input: &Matrix, output: &Matrix, dim: i32) -> Result<()> {
	record(GradNodeMatrix::Sum {
		input: input.clone(),
		output_id: output.value_id(),
		dim,
	})
}
