// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/Vision/VisionFnImageColor.toml.
// Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live

// OaFnImage — Color overloads.

	/// Normalize: Apply per-channel normalization to an NCHW image tensor.
	[[nodiscard]] OaMatrix Normalize(OaEngine& InRt, const OaMatrix& InImage, const OaNormalizationParams& InParams);
	[[nodiscard]] OaMatrix Normalize(const OaMatrix& InImage, const OaNormalizationParams& InParams);
