// AUTO-GENERATED by tools/gen/nn/generate.py - DO NOT EDIT.
// source of truth: tools/gen/nn/schema/ml/mlNnLinear.toml.
// Regenerate via: python3 tools/gen/nn/generate.py --live

#pragma once

#include <oa/ml/module.h>

#include <initializer_list>

namespace oa {

/// Swiglu: SwiGLU MLP layer with optional weight concatenation.
class Swiglu : public Module {
public:
	Swiglu(oa::I32 inFeatures, oa::I32 inIntermediateSize, bool inBias = false);
	Matrix forward(const Matrix& inInput) override;

private:
	bool hasBias_;
};

} // namespace oa
