// AUTO-GENERATED by tools/typeAutogen/oatypeautogen.py — DO NOT EDIT.
// Source of truth: tools/typeAutogen/schema/vision/visionTypes.toml.
// Regenerate via: python3 tools/typeAutogen/oatypeautogen.py --live

#include <oa/vision/type.gen.h>
