// AUTO-GENERATED by Tools/NnAutogen/oannautogen.py - DO NOT EDIT.
// Source of truth: Tools/NnAutogen/Schema/Ml/MlNnAttention.toml.
// Regenerate via: python3 Tools/NnAutogen/oannautogen.py --live

#pragma once

/// OaMultiHeadAttention: Multi-head attention layer with causal masking.
class OaMultiHeadAttention : public OaModule {
public:
	OaMultiHeadAttention(OaI32 DModel, OaI32 NumHeads, OaF32 DropoutP = 0.0f, bool InBias = true);
	OaMatrix Forward(const OaMatrix& InInput) override;
	void SetSeqLen(OaI32 InSeqLen) { SeqLen_ = InSeqLen; }

private:
	OaI32 DModel_;
	OaI32 NumHeads_;
	OaI32 HeadDim_;
	OaF32 DropoutP_;
	OaI32 SeqLen_ = 0;
	OaMatrix Mask_;
	OaI32 MaskSeqLen_ = 0;
	OaI64 MaskT_ = 0;
};
