// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT.
// source of truth: tools/nnAutogen/schema/ml/mlNnContainer.toml.
// Regenerate via: python3 tools/nnAutogen/oannautogen.py --live
// oa::Sequential - Sequential container that chains modules together.

#include <oa/ml/nn.h>
#include <oa/core/fnMatrix.h>
#include <oa/core/validation.h>

oa::Sequential::Sequential(std::initializer_list<oa::SharedPtr<Module>> inLayers) {
	for (const auto& layer : inLayers) {
		add(layer);
	}
}

oa::Sequential& oa::Sequential::add(oa::SharedPtr<oa::Module> inModule) {
	oa::String name(oa::String("layer_") + oa::toString(static_cast<oa::U32>(children_.size())));
	return add(name, std::move(inModule));
}

oa::Sequential& oa::Sequential::add(oa::StringView inName, oa::SharedPtr<oa::Module> inModule) {
	registerModule(inName, std::move(inModule));
	return *this;
}
oa::Matrix oa::Sequential::forward(const oa::Matrix& inInput) {
	oa::Matrix x = inInput;
	for (auto& child : children_) {
		x = child.module->forward(x);
	}
	return x;
}
