# AUTO-GENERATED by tools/gen/python/generateStubs.py — DO NOT EDIT.
# Sources of truth: the live nanobind signatures and oa/_surface.py.

"""OA cryptography and GPU hashing"""

from collections.abc import Sequence

import oa
from oa import (
	Hash as Hash,
	Hasher as Hasher,
	Keypair as Keypair,
	PublicKey as PublicKey,
	SecretKey as SecretKey,
	Signature as Signature
)


def shake256(data: bytes, outLen: int = ...) -> bytes:
	"""One-shot SHAKE-256 over bytes → bytes."""

def shake128(data: bytes, outLen: int = ...) -> bytes:
	"""One-shot SHAKE-128 over bytes → bytes."""

def kmac256(key: bytes, data: bytes, custom: bytes = ..., outLen: int = ...) -> bytes:
	"""KMAC-256 keyed hash (NIST SP 800-185)."""

def merkleRoot(leaves: Sequence[oa.Hash]) -> oa.Hash:
	"""CPU Merkle root over a list of oa::Hash leaves."""

def generateKeypair() -> oa.Keypair:
	"""Generate a random ML-DSA-65 keypair."""

def sign(data: bytes, secret: oa.SecretKey) -> oa.Signature:
	"""Sign a message with an ML-DSA-65 secret key."""

def verify(data: bytes, signature: oa.Signature, pubkey: oa.PublicKey) -> bool:
	"""Verify an ML-DSA-65 signature. Returns False for any tampered input."""
