# AUTO-GENERATED by tools/gen/python/generateStubs.py — DO NOT EDIT.
# Sources of truth: the live nanobind signatures and oa/_surface.py.

"""Native Python view of C++ namespace oa::FnAdvantage"""

import oa


def gae(reward: oa.Matrix, value: oa.Matrix, nextValue: oa.Matrix, terminated: oa.Matrix, truncated: oa.Matrix, config: oa.GaeConfig = ...) -> oa.GaeResult:
	"""Compute generalized advantage estimates and returns."""

def normalize(advantage: oa.Matrix, epsilon: float = ...) -> oa.Matrix:
	"""Standardize a rollout advantage tensor."""
