# AUTO-GENERATED by tools/python/oapystubgen.py — DO NOT EDIT.
# Sources of truth: the live nanobind signatures and oa/_surface.py.

"""OA image processing and Vulkan Video"""

import oa
from oa import (
	BorderMode as BorderMode,
	CameraCapture as CameraCapture,
	CameraCaptureConfig as CameraCaptureConfig,
	DetectionMetricsResult as DetectionMetricsResult,
	Filter as Filter,
	Image as Image,
	ImageBatch as ImageBatch,
	ImageCodec as ImageCodec,
	ImageFormat as ImageFormat,
	ImageLayout as ImageLayout,
	InterpolationMode as InterpolationMode,
	NmsConfig as NmsConfig,
	NmsResult as NmsResult,
	NormalizationParams as NormalizationParams,
	PixelFormat as PixelFormat,
	ScreenCapture as ScreenCapture,
	ScreenCaptureConfig as ScreenCaptureConfig,
	ScreenCaptureCursor as ScreenCaptureCursor,
	ScreenCaptureTarget as ScreenCaptureTarget,
	SegmentationMetricsResult as SegmentationMetricsResult,
	VideoCodec as VideoCodec,
	VideoContainerInfo as VideoContainerInfo,
	VideoContainerKind as VideoContainerKind,
	VideoDecodeCapabilities as VideoDecodeCapabilities,
	VideoDemuxer as VideoDemuxer,
	VideoDemuxerConfig as VideoDemuxerConfig,
	VideoDemuxerStats as VideoDemuxerStats,
	VideoEncodeCapabilities as VideoEncodeCapabilities,
	VideoEncodeProfile as VideoEncodeProfile,
	VideoFrame as VideoFrame,
	VideoFrameResource as VideoFrameResource,
	VideoPacket as VideoPacket,
	VideoPlayer as VideoPlayer,
	VideoPlayerConfig as VideoPlayerConfig,
	VideoRateControl as VideoRateControl,
	VideoRecorder as VideoRecorder,
	VideoRecorderConfig as VideoRecorderConfig,
	YCbCrModel as YCbCrModel
)


def imageFormatChannels(format: oa.ImageFormat) -> int: ...

def queryDecodeCapabilities(codec: oa.VideoCodec) -> oa.VideoDecodeCapabilities: ...

def queryEncodeCapabilities(codec: oa.VideoCodec) -> oa.VideoEncodeCapabilities: ...
