// AUTO-GENERATED by tools/fnAutogen/oafnautogen.py — DO NOT EDIT.
// Includes schema-generated gradient-node catalogs for this domain.
// Regenerate via: python3 tools/fnAutogen/oafnautogen.py --live

#pragma once

#include <oa/core/autograd.h>
#include "matrix/autogradElemwise.gen.h"
