# AUTO-GENERATED by Tools/Python/oapystubgen.py — DO NOT EDIT.
# Sources of truth: the live nanobind signatures and oa/_surface.py.

"""OA neural-network modules, losses, autograd, optimizers, and training."""

from oa import (
	OaActivation as OaActivation,
	OaAdam as OaAdam,
	OaAdamW as OaAdamW,
	OaByteEmbedding as OaByteEmbedding,
	OaCallback as OaCallback,
	OaCbProgressBar as OaCbProgressBar,
	OaCbSummary as OaCbSummary,
	OaCbTraining as OaCbTraining,
	OaDqnLossConfig as OaDqnLossConfig,
	OaDqnLossResult as OaDqnLossResult,
	OaEmbedding as OaEmbedding,
	OaEmpyrealmCore as OaEmpyrealmCore,
	OaGaeConfig as OaGaeConfig,
	OaGaeResult as OaGaeResult,
	OaGpuTimingStats as OaGpuTimingStats,
	OaGradientTape as GradientTape,
	OaGru as OaGru,
	OaItRlTraining as OaItRlTraining,
	OaItRlTrainingConfig as OaItRlTrainingConfig,
	OaItTraining as OaItTraining,
	OaItTrainingConfig as OaItTrainingConfig,
	OaLayerNorm as OaLayerNorm,
	OaLinear as OaLinear,
	OaMamba3Module as OaMamba3Module,
	OaMetric as OaMetric,
	OaMetricAccuracy as OaMetricAccuracy,
	OaMetricLoss as OaMetricLoss,
	OaModule as OaModule,
	OaMuon as OaMuon,
	OaMuonAdamWConfig as OaMuonAdamWConfig,
	OaNlpArchitecture as OaNlpArchitecture,
	OaNlpSuiteModel as OaNlpSuiteModel,
	OaNlpSuiteRecipe as OaNlpSuiteRecipe,
	OaNlpSuiteSampler as OaNlpSuiteSampler,
	OaNlpTokenizerKind as OaNlpTokenizerKind,
	OaOptimizer as OaOptimizer,
	OaOptimizerComposite as OaOptimizerComposite,
	OaOptimizerNoOp as OaOptimizerNoOp,
	OaParameter as OaParameter,
	OaPpoLossConfig as OaPpoLossConfig,
	OaPpoLossResult as OaPpoLossResult,
	OaRlContinuousPolicyResult as OaRlContinuousPolicyResult,
	OaRlEnvironmentSpec as OaRlEnvironmentSpec,
	OaRlFieldSpec as OaRlFieldSpec,
	OaRlPolicyResult as OaRlPolicyResult,
	OaRlReplayBatch as OaRlReplayBatch,
	OaRlReplayBuffer as OaRlReplayBuffer,
	OaRlReplayConfig as OaRlReplayConfig,
	OaRlRolloutBatch as OaRlRolloutBatch,
	OaRlRolloutBuffer as OaRlRolloutBuffer,
	OaRlRolloutConfig as OaRlRolloutConfig,
	OaRlSpaceKind as OaRlSpaceKind,
	OaRlTrainingPhase as OaRlTrainingPhase,
	OaRnn as OaRnn,
	OaSGD as OaSGD,
	OaSacCriticLossResult as OaSacCriticLossResult,
	OaSacLossConfig as OaSacLossConfig,
	OaTrainingCommandDisposition as OaTrainingCommandDisposition,
	OaTrainingCommandResult as OaTrainingCommandResult,
	OaTrainingMetricSample as OaTrainingMetricSample,
	OaTrainingSession as OaTrainingSession,
	OaTrainingSnapshot as OaTrainingSnapshot,
	OaTrainingState as OaTrainingState,
	OaTransformerBlock as OaTransformerBlock
)
from oa._oa.ml import (
	Bce as Bce,
	BceBwd as BceBwd,
	ClipReward as ClipReward,
	CrossEntropy as CrossEntropy,
	CrossEntropyBwd as CrossEntropyBwd,
	Dqn as Dqn,
	EvaluateCategoricalPolicy as EvaluateCategoricalPolicy,
	EvaluateTanhNormalPolicy as EvaluateTanhNormalPolicy,
	Gae as Gae,
	GradEnabled as GradEnabled,
	IsEnabled as IsEnabled,
	L1 as L1,
	L1Bwd as L1Bwd,
	MakeMuonAdamWOptimizer as MakeMuonAdamWOptimizer,
	MetricAccuracy as MetricAccuracy,
	MetricScalarLoss as MetricScalarLoss,
	Mse as Mse,
	MseBwd as MseBwd,
	NormalizeAdvantages as NormalizeAdvantages,
	NormalizeObservation as NormalizeObservation,
	Ppo as Ppo,
	PpoClippedPolicy as PpoClippedPolicy,
	PpoClippedPolicyBwd as PpoClippedPolicyBwd,
	SacActor as SacActor,
	SacCritic as SacCritic,
	SampleCategoricalPolicy as SampleCategoricalPolicy,
	SampleTanhNormalPolicy as SampleTanhNormalPolicy,
	ScaleAction as ScaleAction,
	SetEnabled as SetEnabled,
	SetGradEnabled as SetGradEnabled,
	SmoothL1 as SmoothL1,
	SmoothL1Bwd as SmoothL1Bwd
)


OaNlpSuiteBatchSize: int = ...

OaNlpSuiteContextLength: int = ...

OaNlpSuiteGenerationPrompt: str = ...

OaNlpSuiteGenerationSourceUnits: int = ...

OaNlpSuiteHiddenWidth: int = ...

OaNlpSuiteModelWidth: int = ...

OaNlpSuiteRngSeed: int = ...

OaNlpSuiteTrainingSteps: int = ...

__all__: list = ['Bce', 'BceBwd', 'ClipReward', 'CrossEntropy', 'CrossEntropyBwd', 'Dqn', 'EvaluateCategoricalPolicy', 'EvaluateTanhNormalPolicy', 'Gae', 'GradEnabled', 'GradientTape', 'IsEnabled', 'L1', 'L1Bwd', 'MakeMuonAdamWOptimizer', 'MetricAccuracy', 'MetricScalarLoss', 'Mse', 'MseBwd', 'NormalizeAdvantages', 'NormalizeObservation', 'OaActivation', 'OaAdam', 'OaAdamW', 'OaByteEmbedding', 'OaCallback', 'OaCbProgressBar', 'OaCbSummary', 'OaCbTraining', 'OaDqnLossConfig', 'OaDqnLossResult', 'OaEmbedding', 'OaEmpyrealmCore', 'OaGaeConfig', 'OaGaeResult', 'OaGpuTimingStats', 'OaGru', 'OaItRlTraining', 'OaItRlTrainingConfig', 'OaItTraining', 'OaItTrainingConfig', 'OaLayerNorm', 'OaLinear', 'OaMamba3Module', 'OaMetric', 'OaMetricAccuracy', 'OaMetricLoss', 'OaModule', 'OaMuon', 'OaMuonAdamWConfig', 'OaNlpArchitecture', 'OaNlpSuiteBatchSize', 'OaNlpSuiteContextLength', 'OaNlpSuiteGenerationPrompt', 'OaNlpSuiteGenerationSourceUnits', 'OaNlpSuiteHiddenWidth', 'OaNlpSuiteModel', 'OaNlpSuiteModelWidth', 'OaNlpSuiteRecipe', 'OaNlpSuiteRngSeed', 'OaNlpSuiteSampler', 'OaNlpSuiteTrainingSteps', 'OaNlpTokenizerKind', 'OaOptimizer', 'OaOptimizerComposite', 'OaOptimizerNoOp', 'OaParameter', 'OaPpoLossConfig', 'OaPpoLossResult', 'OaRlContinuousPolicyResult', 'OaRlEnvironmentSpec', 'OaRlFieldSpec', 'OaRlPolicyResult', 'OaRlReplayBatch', 'OaRlReplayBuffer', 'OaRlReplayConfig', 'OaRlRolloutBatch', 'OaRlRolloutBuffer', 'OaRlRolloutConfig', 'OaRlSpaceKind', 'OaRlTrainingPhase', 'OaRnn', 'OaSGD', 'OaSacCriticLossResult', 'OaSacLossConfig', 'OaTrainingCommandDisposition', 'OaTrainingCommandResult', 'OaTrainingMetricSample', 'OaTrainingSession', 'OaTrainingSnapshot', 'OaTrainingState', 'OaTransformerBlock', 'Ppo', 'PpoClippedPolicy', 'PpoClippedPolicyBwd', 'SacActor', 'SacCritic', 'SampleCategoricalPolicy', 'SampleTanhNormalPolicy', 'ScaleAction', 'SetEnabled', 'SetGradEnabled', 'SmoothL1', 'SmoothL1Bwd']
