# AUTO-GENERATED by Tools/Python/oapystubgen.py — DO NOT EDIT.
# Sources of truth: the live nanobind signatures and oa/_surface.py.

"""Python view of C++ namespace OaFnRl."""

from oa._oa.ml import (
	ClipReward as ClipReward,
	EvaluateCategoricalPolicy as EvaluateCategoricalPolicy,
	EvaluateTanhNormalPolicy as EvaluateTanhNormalPolicy,
	Gae as Gae,
	NormalizeAdvantages as NormalizeAdvantages,
	NormalizeObservation as NormalizeObservation,
	SampleCategoricalPolicy as SampleCategoricalPolicy,
	SampleTanhNormalPolicy as SampleTanhNormalPolicy,
	ScaleAction as ScaleAction
)


__all__: tuple = ('ClipReward', 'EvaluateCategoricalPolicy', 'EvaluateTanhNormalPolicy', 'Gae', 'NormalizeAdvantages', 'NormalizeObservation', 'SampleCategoricalPolicy', 'SampleTanhNormalPolicy', 'ScaleAction')
