# AUTO-GENERATED by Tools/Python/oapystubgen.py — DO NOT EDIT.
# Sources of truth: the live nanobind signatures and oa/_surface.py.

"""Python view of C++ namespace OaFnDetection."""

from oa._oa.vision import (
	BinaryMaskCounts as BinaryMaskCounts,
	BoxIou as BoxIou,
	ConfusionMatrix as ConfusionMatrix,
	EvaluateDetections as Evaluate,
	EvaluateSegmentation as EvaluateSegmentation,
	Nms as Nms
)


__all__: tuple = ('BinaryMaskCounts', 'BoxIou', 'ConfusionMatrix', 'Evaluate', 'EvaluateSegmentation', 'Nms')
