# AUTO-GENERATED by Tools/Python/oapystubgen.py — DO NOT EDIT.
# Sources of truth: the live nanobind signatures and oa/_surface.py.

"""Python view of C++ namespace OaFnAudio."""

from oa._oa.audio import (
	AmplitudeToDb as AmplitudeToDb,
	Clip as Clip,
	Fade as Fade,
	Gain as Gain,
	MelSpectrogram as MelSpectrogram,
	Mfcc as Mfcc,
	Mix as Mix,
	Normalize as Normalize,
	PreEmphasis as PreEmphasis,
	Resample as Resample,
	Stft as Stft,
	ToMono as ToMono
)


__all__: tuple = ('AmplitudeToDb', 'Clip', 'Fade', 'Gain', 'MelSpectrogram', 'Mfcc', 'Mix', 'Normalize', 'PreEmphasis', 'Resample', 'Stft', 'ToMono')
