# AUTO-GENERATED by Tools/Python/oapystubgen.py — DO NOT EDIT.
# Sources of truth: the live nanobind signatures and oa/_surface.py.

"""OA Vulkan runtime, engine lifecycle, and execution contexts."""

from oa import OaContext as OaContext
from oa._oa.runtime import (
	OaContextGetDefault as OaContextGetDefault,
	OaInitComputeEngine as OaInitComputeEngine,
	OaShutdownComputeEngine as OaShutdownComputeEngine
)


__all__: list = ['OaContext', 'OaContextGetDefault', 'OaInitComputeEngine', 'OaShutdownComputeEngine', 'Context']

class Context:
	"""Execute and synchronize the default OA context on scope exit."""

	def __enter__(self) -> Context: ...

	def __exit__(self, exc_type, exc_value, traceback) -> None: ...
