// AUTO-GENERATED by Tools/NnAutogen/oannautogen.py - DO NOT EDIT.
// Source of truth: Tools/NnAutogen/Schema/Ml/MlNnConv.toml.
// Regenerate via: python3 Tools/NnAutogen/oannautogen.py --live
// OaConv1d - 1D convolution layer (im2col + GEMM).

#include <Oa/Ml/Nn.h>
#include <Oa/Core/FnMatrix.h>
#include <Oa/Core/Validation.h>

OaConv1d::OaConv1d(OaI32 InChannels, OaI32 OutChannels, OaI32 KernelSize, OaI32 Stride, OaI32 Padding, OaI32 Dilation)
	: InChannels_(InChannels), OutChannels_(OutChannels), KernelSize_(KernelSize), Stride_(Stride), Padding_(Padding), Dilation_(Dilation) {
	auto wd = OaFnMatrix::GetWeightDtype();
	RegisterParameter("weight", OaFnMatrix::Rand(OaMatrixShape{OutChannels, InChannels, KernelSize}, wd));
	RegisterParameter("bias", OaFnMatrix::Zeros(OaMatrixShape{OutChannels}, wd));
}

OaMatrix OaConv1d::Forward(const OaMatrix& InInput) {
	auto& weight = Params_[0].Data;
	auto& bias = Params_[1].Data;
	// im2col + GEMM path (Conv1dGemm). It composes its own autograd graph from
	// Im2Col1d + MatMulNt + BiasAdd, so no hand-written OaGradConv1d node is
	// needed. The scalar direct-conv kernel it replaced was retired (proven
	// equivalent by NN.Conv1dGemmMatchesScalar / NN.Conv1dGemmGradCheck).
	return OaFnMatrix::Conv1dGemm(InInput, weight, bias, Stride_, Padding_, Dilation_);
}
