# AUTO-GENERATED by tools/gen/example/generate.py - DO NOT EDIT.
# Source: tools/gen/example/schema/examples.toml

from pathlib import Path

import pytest

from example_runner import runExample


@pytest.mark.oa_gpu
def test_core_matrix_add(tmp_path: Path):
	output = runExample("sdk/py/examples/core/matrix.py", tmp_path)
	assert "Matrix addition verified: every value is 3" in output


@pytest.mark.oa_gpu
def test_audio_process(tmp_path: Path):
	output = runExample("sdk/py/examples/audio/audio.py", tmp_path)
	assert "Saved reverberated audio (1.5 s tail):" in output
