// @generated by tools/gen/fn/generate.py; DO NOT EDIT.
// schema=ml_training.json schema_version=1 generator_version=52
// schema_sha256=eee874e5551baed7e588871e278ac84e842609f051c8c143730604ea628c24ed
// Mechanical tape attachments; concrete saved-state node behavior remains private.

use crate::{Matrix, Result};

use super::{node::Node, tape::record_node};

pub(in crate::ml) fn record_cross_entropy(
	logits: &Matrix,
	targets: &Matrix,
	result: &Matrix,
) -> Result<()> {
	record_node(Node::CrossEntropy {
		logits: logits.clone(),
		targets: targets.clone(),
		output_id: result.value_id(),
	})
}

pub(in crate::ml) fn record_masked_cross_entropy(
	logits: &Matrix,
	targets: &Matrix,
	mask: &Matrix,
	valid_count: usize,
	result: &Matrix,
) -> Result<()> {
	record_node(Node::MaskedCrossEntropy {
		logits: logits.clone(),
		targets: targets.clone(),
		mask: mask.clone(),
		valid_count,
		output_id: result.value_id(),
	})
}

pub(in crate::ml) fn record_smooth_l1(
	prediction: &Matrix,
	target: &Matrix,
	result: &Matrix,
) -> Result<()> {
	record_node(Node::SmoothL1 {
		prediction: prediction.clone(),
		target: target.clone(),
		output_id: result.value_id(),
	})
}

pub(in crate::ml) fn record_mse(
	prediction: &Matrix,
	target: &Matrix,
	result: &Matrix,
) -> Result<()> {
	record_node(Node::Mse {
		prediction: prediction.clone(),
		target: target.clone(),
		output_id: result.value_id(),
	})
}

pub(in crate::ml) fn record_l1(
	prediction: &Matrix,
	target: &Matrix,
	result: &Matrix,
) -> Result<()> {
	record_node(Node::L1 {
		prediction: prediction.clone(),
		target: target.clone(),
		output_id: result.value_id(),
	})
}

pub(in crate::ml) fn record_bce(
	prediction: &Matrix,
	target: &Matrix,
	result: &Matrix,
) -> Result<()> {
	record_node(Node::Bce {
		prediction: prediction.clone(),
		target: target.clone(),
		output_id: result.value_id(),
	})
}
