// AUTO-GENERATED by Tools/TypeAutogen/oatypeautogen.py — DO NOT EDIT.
// Source of truth: Tools/TypeAutogen/Schema/CoreTypes.toml.
// Regenerate via: python3 Tools/TypeAutogen/oatypeautogen.py --live

#include <Oa/Core/Type.gen.h>

#include <cstring>

#include <Oa/Core/Yaml.h>

constexpr const char* OaDeterminismModeToString(OaDeterminismMode InType) noexcept {
	switch (InType) {
		case OaDeterminismMode::Fast: return "Fast";
		case OaDeterminismMode::Stable: return "Stable";
		case OaDeterminismMode::Deterministic: return "Deterministic";
		default: return "unknown";
	}
}

OaDeterminismMode OaDeterminismModeFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "Fast") == 0) return OaDeterminismMode::Fast;
	if (strcmp(InStr, "Stable") == 0) return OaDeterminismMode::Stable;
	if (strcmp(InStr, "Deterministic") == 0) return OaDeterminismMode::Deterministic;
	return OaDeterminismMode::Fast;  // Default to first value
}

constexpr const char* OaScalarTypeToString(OaScalarType InType) noexcept {
	switch (InType) {
		case OaScalarType::Float32: return "Float32";
		case OaScalarType::BFloat16: return "BFloat16";
		case OaScalarType::Float16: return "Float16";
		case OaScalarType::Int8: return "Int8";
		case OaScalarType::Int32: return "Int32";
		case OaScalarType::UInt8: return "UInt8";
		case OaScalarType::Float64: return "Float64";
		case OaScalarType::Int16: return "Int16";
		case OaScalarType::Int64: return "Int64";
		case OaScalarType::UInt16: return "UInt16";
		case OaScalarType::UInt32: return "UInt32";
		case OaScalarType::UInt64: return "UInt64";
		case OaScalarType::Bool: return "Bool";
		case OaScalarType::Complex64: return "Complex64";
		case OaScalarType::Complex128: return "Complex128";
		case OaScalarType::Q4_0: return "Q4_0";
		case OaScalarType::Q4_1: return "Q4_1";
		case OaScalarType::Q5_0: return "Q5_0";
		case OaScalarType::Q5_1: return "Q5_1";
		case OaScalarType::Q8_0: return "Q8_0";
		case OaScalarType::Q8_1: return "Q8_1";
		case OaScalarType::Q2_K: return "Q2_K";
		case OaScalarType::Q3_K: return "Q3_K";
		case OaScalarType::Q4_K: return "Q4_K";
		case OaScalarType::Q5_K: return "Q5_K";
		case OaScalarType::Q6_K: return "Q6_K";
		case OaScalarType::Q8_K: return "Q8_K";
		default: return "unknown";
	}
}

OaScalarType OaScalarTypeFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "Float32") == 0) return OaScalarType::Float32;
	if (strcmp(InStr, "BFloat16") == 0) return OaScalarType::BFloat16;
	if (strcmp(InStr, "Float16") == 0) return OaScalarType::Float16;
	if (strcmp(InStr, "Int8") == 0) return OaScalarType::Int8;
	if (strcmp(InStr, "Int32") == 0) return OaScalarType::Int32;
	if (strcmp(InStr, "UInt8") == 0) return OaScalarType::UInt8;
	if (strcmp(InStr, "Float64") == 0) return OaScalarType::Float64;
	if (strcmp(InStr, "Int16") == 0) return OaScalarType::Int16;
	if (strcmp(InStr, "Int64") == 0) return OaScalarType::Int64;
	if (strcmp(InStr, "UInt16") == 0) return OaScalarType::UInt16;
	if (strcmp(InStr, "UInt32") == 0) return OaScalarType::UInt32;
	if (strcmp(InStr, "UInt64") == 0) return OaScalarType::UInt64;
	if (strcmp(InStr, "Bool") == 0) return OaScalarType::Bool;
	if (strcmp(InStr, "Complex64") == 0) return OaScalarType::Complex64;
	if (strcmp(InStr, "Complex128") == 0) return OaScalarType::Complex128;
	if (strcmp(InStr, "Q4_0") == 0) return OaScalarType::Q4_0;
	if (strcmp(InStr, "Q4_1") == 0) return OaScalarType::Q4_1;
	if (strcmp(InStr, "Q5_0") == 0) return OaScalarType::Q5_0;
	if (strcmp(InStr, "Q5_1") == 0) return OaScalarType::Q5_1;
	if (strcmp(InStr, "Q8_0") == 0) return OaScalarType::Q8_0;
	if (strcmp(InStr, "Q8_1") == 0) return OaScalarType::Q8_1;
	if (strcmp(InStr, "Q2_K") == 0) return OaScalarType::Q2_K;
	if (strcmp(InStr, "Q3_K") == 0) return OaScalarType::Q3_K;
	if (strcmp(InStr, "Q4_K") == 0) return OaScalarType::Q4_K;
	if (strcmp(InStr, "Q5_K") == 0) return OaScalarType::Q5_K;
	if (strcmp(InStr, "Q6_K") == 0) return OaScalarType::Q6_K;
	if (strcmp(InStr, "Q8_K") == 0) return OaScalarType::Q8_K;
	return OaScalarType::Float32;  // Default to first value
}

constexpr const char* OaPrecisionToString(OaPrecision InType) noexcept {
	switch (InType) {
		case OaPrecision::FP32: return "FP32";
		case OaPrecision::TF32: return "TF32";
		case OaPrecision::BF16: return "BF16";
		case OaPrecision::FP16: return "FP16";
		case OaPrecision::INT8: return "INT8";
		default: return "unknown";
	}
}

OaPrecision OaPrecisionFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "FP32") == 0) return OaPrecision::FP32;
	if (strcmp(InStr, "TF32") == 0) return OaPrecision::TF32;
	if (strcmp(InStr, "BF16") == 0) return OaPrecision::BF16;
	if (strcmp(InStr, "FP16") == 0) return OaPrecision::FP16;
	if (strcmp(InStr, "INT8") == 0) return OaPrecision::INT8;
	return OaPrecision::FP32;  // Default to first value
}

constexpr const char* OaFilterToString(OaFilter InType) noexcept {
	switch (InType) {
		case OaFilter::Nearest: return "Nearest";
		case OaFilter::Linear: return "Linear";
		default: return "unknown";
	}
}

OaFilter OaFilterFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "Nearest") == 0) return OaFilter::Nearest;
	if (strcmp(InStr, "Linear") == 0) return OaFilter::Linear;
	return OaFilter::Nearest;  // Default to first value
}

bool OaPrecisionConfig::SerializeToYaml(const char* InPath) const {
	// TODO: Implement YAML serialization using yaml-cpp
	// For now, return false (not implemented)
	(void)InPath;
	return false;
}

bool OaPrecisionConfig::LoadFromYaml(const char* InPath) {
	// TODO: Implement YAML loading using yaml-cpp
	// For now, return false (not implemented)
	(void)InPath;
	return false;
}

bool OaPrecisionConfig::Validate() const {
	// Basic validation: check for reasonable values
	// TODO: Add field-specific validation
	return true;
}
