// AUTO-GENERATED by tools/fnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: tools/fnAutogen/schema/core/coreFnMatrixElemwise.toml.
//
// Tests for context-backed public overloads.
// The public overload test doubles as the kernel correctness test —
// it calls oa::FnMatrix::<Op>(...) which dispatches the SPIR-V kernel directly.
// CPU references come from each op's `forward_op` field.

#include <gtest/gtest.h>
#include <oa/core/fnMatrix.h>
#include <oa/runtime/engine.h>
#include <oa/runtime/executionSession.h>
#include <oa/runtime/executableGraph.h>
#include <algorithm>
#include <cmath>
#include <numeric>
#include <vector>

static oa::Engine* runtime = nullptr;

class TestFnMatrixElemwise : public ::testing::Test {
protected:
	static void SetUpTestSuite() {
		oa::EngineConfig config{};
		config.appName = "TestFnMatrixElemwise";
		auto result = oa::Engine::create(config);
		ASSERT_TRUE(result.isOk()) << result.getStatus().getMessage();
		static oa::UniquePtr<oa::Engine> engine = std::move(*result);
		runtime = engine.get();
	}
};

TEST_VK(TestFnMatrixElemwise, add_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	auto b = oa::FnMatrix::rand(oa::MatrixShape{N});
	std::vector<float> bHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(b, bHost.data(), N * sizeof(float)).isOk());
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::add(a, b);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] + bHost[i];
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, sub_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	auto b = oa::FnMatrix::rand(oa::MatrixShape{N});
	std::vector<float> bHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(b, bHost.data(), N * sizeof(float)).isOk());
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::sub(a, b);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] - bHost[i];
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, mul_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	auto b = oa::FnMatrix::rand(oa::MatrixShape{N});
	std::vector<float> bHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(b, bHost.data(), N * sizeof(float)).isOk());
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::mul(a, b);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] * bHost[i];
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, div_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	auto b = oa::FnMatrix::rand(oa::MatrixShape{N});
	std::vector<float> bHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(b, bHost.data(), N * sizeof(float)).isOk());
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::div(a, b);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] / bHost[i];
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, scale_Context) {
	constexpr oa::U32 N = 256;
	constexpr oa::F32 kScalar = 1.5f;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::scale(a, kScalar);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] * kScalar;
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, neg_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::neg(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = -aHost[i];
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, abs_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::abs(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::abs(aHost[i]);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, log_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});  // [0, 1)
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::log(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::log(aHost[i]);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, sqrt_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});  // [0, 1)
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::sqrt(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::sqrt(aHost[i]);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, pow_Context) {
	constexpr oa::U32 N = 256;
	constexpr oa::F32 kScalar = 1.5f;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});  // [0, 1)
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::pow(a, kScalar);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::pow(aHost[i], kScalar);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, addScalar_Context) {
	constexpr oa::U32 N = 256;
	constexpr oa::F32 kScalar = 1.5f;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::addScalar(a, kScalar);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] + kScalar;
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, subScalar_Context) {
	constexpr oa::U32 N = 256;
	constexpr oa::F32 kScalar = 1.5f;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::subScalar(a, kScalar);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] - kScalar;
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, divScalar_Context) {
	constexpr oa::U32 N = 256;
	constexpr oa::F32 kScalar = 1.5f;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::divScalar(a, kScalar);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] / kScalar;
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, exp_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::exp(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::exp(aHost[i]);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, sin_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::sin(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::sin(aHost[i]);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, cos_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::cos(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::cos(aHost[i]);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, reciprocal_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::reciprocal(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = 1.0f / aHost[i];
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-3f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, clampMax_Context) {
	constexpr oa::U32 N = 256;
	constexpr oa::F32 kScalar = 0.5f;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::clampMax(a, kScalar);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::min(aHost[i], kScalar);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}

TEST_VK(TestFnMatrixElemwise, clampMin_Context) {
	constexpr oa::U32 N = 256;
	constexpr oa::F32 kScalar = -0.5f;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::clampMin(a, kScalar);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = std::max(aHost[i], kScalar);
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}
