// AUTO-GENERATED by tools/gen/fn/generate.py — DO NOT EDIT.
// Source of truth: tools/gen/fn/schema/ml/mlFnMatrixEmbed.toml.
// Regenerate via: python3 tools/gen/fn/generate.py --live

// oa::FnMatrix — Embed overloads.

	/// biasAdd: Add bias vector: out = A + Bias (broadcasted).
	[[nodiscard]] oa::Matrix biasAdd(const oa::Matrix& inA, const oa::Matrix& inB);
