// AUTO-GENERATED by tools/gen/type/generate.py — DO NOT EDIT.
// Source of truth: tools/gen/type/schema/core/coreTypes.toml.
// Regenerate via: python3 tools/gen/type/generate.py --live

#include <oa/core/type.gen.h>
