# AUTO-GENERATED by tools/gen/python/generateStubs.py — DO NOT EDIT.
# Sources of truth: the live nanobind signatures and oa/_surface.py.

"""Native Python view of C++ namespace oa::FnAutograd"""



def isEnabled() -> bool: ...

def setEnabled(enabled: bool) -> None: ...
