# AUTO-GENERATED by tools/gen/python/generateStubs.py — DO NOT EDIT.
# Sources of truth: the live nanobind signatures and oa/_surface.py.

"""Native Python view of C++ namespace oa::FnMetric"""

import oa


def accuracy(predictions: oa.Matrix, labels: oa.Matrix) -> float: ...

def scalarLoss(loss: oa.Matrix) -> float: ...
