# AUTO-GENERATED by tools/gen/python/generateStubs.py — DO NOT EDIT.
# Sources of truth: the live nanobind signatures and oa/_surface.py.

"""OA machine-learning modules and training"""

from oa import (
	Activation as Activation,
	Adam as Adam,
	AdamW as AdamW,
	ByteEmbedding as ByteEmbedding,
	Callback as Callback,
	CbProgressBar as CbProgressBar,
	CbSummary as CbSummary,
	CbTraining as CbTraining,
	ContinuousPolicyResult as ContinuousPolicyResult,
	DqnLossConfig as DqnLossConfig,
	DqnLossResult as DqnLossResult,
	Embedding as Embedding,
	EmpyrealmCore as EmpyrealmCore,
	EnvironmentSpace as EnvironmentSpace,
	EnvironmentSpaceKind as EnvironmentSpaceKind,
	EnvironmentSpec as EnvironmentSpec,
	GaeConfig as GaeConfig,
	GaeResult as GaeResult,
	GpuTimingStats as GpuTimingStats,
	GradientTape as GradientTape,
	Gru as Gru,
	ItRolloutTraining as ItRolloutTraining,
	ItRolloutTrainingConfig as ItRolloutTrainingConfig,
	ItTraining as ItTraining,
	ItTrainingConfig as ItTrainingConfig,
	LayerNorm as LayerNorm,
	Linear as Linear,
	Mamba3Module as Mamba3Module,
	Metric as Metric,
	MetricAccuracy as MetricAccuracy,
	MetricLoss as MetricLoss,
	Module as Module,
	Muon as Muon,
	NlpArchitecture as NlpArchitecture,
	NlpSuiteModel as NlpSuiteModel,
	NlpSuiteRecipe as NlpSuiteRecipe,
	NlpSuiteSampler as NlpSuiteSampler,
	NlpTokenizerKind as NlpTokenizerKind,
	Optimizer as Optimizer,
	OptimizerNoOp as OptimizerNoOp,
	Parameter as Parameter,
	PolicyResult as PolicyResult,
	PpoLossConfig as PpoLossConfig,
	PpoLossResult as PpoLossResult,
	ReplayBatch as ReplayBatch,
	ReplayBuffer as ReplayBuffer,
	ReplayConfig as ReplayConfig,
	Rnn as Rnn,
	RolloutBatch as RolloutBatch,
	RolloutBuffer as RolloutBuffer,
	RolloutConfig as RolloutConfig,
	RolloutTrainingPhase as RolloutTrainingPhase,
	SacCriticLossResult as SacCriticLossResult,
	SacLossConfig as SacLossConfig,
	Sgd as Sgd,
	TrainingCommandDisposition as TrainingCommandDisposition,
	TrainingCommandResult as TrainingCommandResult,
	TrainingMetricSample as TrainingMetricSample,
	TrainingSession as TrainingSession,
	TrainingSnapshot as TrainingSnapshot,
	TrainingState as TrainingState,
	TransformerBlock as TransformerBlock
)


NlpSuiteContextLength: int = ...

NlpSuiteModelWidth: int = ...

NlpSuiteHiddenWidth: int = ...

NlpSuiteTrainingSteps: int = ...

NlpSuiteBatchSize: int = ...

NlpSuiteRngSeed: int = ...

NlpSuiteGenerationPrompt: str = ...

NlpSuiteGenerationSourceUnits: int = ...
