// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT.
// source of truth: tools/nnAutogen/schema/ml/mlNnVision.toml.
// Regenerate via: python3 tools/nnAutogen/oannautogen.py --live
// oa::Upsample - Spatial upsampling layer (Nearest or Bilinear).

#include <oa/ml/nn.h>
#include <oa/core/fnMatrix.h>
#include <oa/core/validation.h>
#include <oa/runtime/executionSession.h>

oa::Upsample::Upsample(oa::I32 inScaleFactor, oa::UpsampleMode inMode)
	: scaleFactor_(inScaleFactor), mode_(inMode) {

}

static oa::U32 divCeil(oa::U32 inA, oa::U32 inB) { return (inA + inB - 1) / inB; }
oa::Matrix oa::Upsample::forward(const oa::Matrix& inInput) {
	auto shape = inInput.getShape();
	oa::U32 b = (oa::U32)shape[0];
	oa::U32 c = (oa::U32)shape[1];
	oa::U32 h = (oa::U32)shape[2];
	oa::U32 w = (oa::U32)shape[3];
	oa::U32 outH = h * scaleFactor_;
	oa::U32 outW = w * scaleFactor_;

	auto output = oa::FnMatrix::empty(MatrixShape{b, c, outH, outW}, inInput.getDtype());

	// Use the Resize shaders: Bilinear for smooth upsampling, Nearest for pixel art
	const char *shaderName = (mode_ == oa::UpsampleMode::Nearest) ? "ResizeNearest" : "ResizeBilinear";

	struct Push {
		oa::U32 batchSize, channels, hIn, wIn, hOut, wOut;
	};
	Push push = {};
	push.batchSize = b;
	push.channels = c;
	push.hIn = h;
	push.wIn = w;
	push.hOut = outH;
	push.wOut = outW;

	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	oa::U32 gx = divCeil(outW, 16), gy = divCeil(outH, 16), gz = b * c;
	oa::ExecutionSession::getActive().add(shaderName,
		{&inInput, &output}, access, &push, sizeof(push), gx, gy, gz);

	return output;
}
