// AUTO-GENERATED by tools/fnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: tools/fnAutogen/schema/**.toml.
// Included inside the owning bind function.

	nb::class_<oa::CompactRowsResult>(m, "CompactRowsResult")
		.def_ro("values", &oa::CompactRowsResult::values)
		.def_ro("rowMap", &oa::CompactRowsResult::rowMap)
		.def_ro("count", &oa::CompactRowsResult::count)
		.def_ro("dispatchArgs", &oa::CompactRowsResult::dispatchArgs);

	nb::class_<oa::MoeExpertPlan>(m, "MoeExpertPlan")
		.def_ro("counts", &oa::MoeExpertPlan::counts)
		.def_ro("offsets", &oa::MoeExpertPlan::offsets)
		.def_ro("packedToken", &oa::MoeExpertPlan::packedToken)
		.def_ro("packedExpert", &oa::MoeExpertPlan::packedExpert)
		.def_ro("packedSlot", &oa::MoeExpertPlan::packedSlot)
		.def_ro("inverse", &oa::MoeExpertPlan::inverse);

	nb::class_<oa::TopKResult>(m, "TopKResult")
		.def_ro("values", &oa::TopKResult::values)
		.def_ro("indices", &oa::TopKResult::indices);

	m.def("abs", [](const oa::Matrix& inA) {
		return matrixPtr(oa::FnMatrix::abs(inA));
	},
	  nb::arg("a"),
	  nb::rv_policy::take_ownership,
	  "Element-wise absolute value: out = |A|.");

	m.def("add", [](const oa::Matrix& inA, const oa::Matrix& inB) {
		return matrixPtr(oa::FnMatrix::add(inA, inB));
	},
	  nb::arg("a"), nb::arg("b"),
	  nb::rv_policy::take_ownership,
	  "Element-wise matrix addition with broadcasting.");

	m.def("addScalar", [](const oa::Matrix& inA, oa::F32 inScalar) {
		return matrixPtr(oa::FnMatrix::addScalar(inA, inScalar));
	},
	  nb::arg("a"), nb::arg("scalar"),
	  nb::rv_policy::take_ownership,
	  "Scalar addition: out = A + Scalar.");

	m.def("cast", [](const oa::Matrix& inSrc, oa::ScalarType inDtype) {
		return matrixPtr(oa::FnMatrix::cast(inSrc, inDtype));
	},
	  nb::arg("src"), nb::arg("dtype"),
	  nb::rv_policy::take_ownership,
	  "Convert A to Dtype; returns an alias when the dtype is unchanged.");

	m.def("categoricalAccuracyCount", [](const oa::Matrix& inLogits, const oa::Matrix& inLabels) {
		return matrixPtr(oa::FnMatrix::categoricalAccuracyCount(inLogits, inLabels));
	},
	  nb::arg("logits"), nb::arg("labels"),
	  nb::rv_policy::take_ownership,
	  "Count correct last-axis categorical predictions into one device UInt32 scalar.");

	m.def("causalMask", [](const oa::Matrix& inScores) {
		return matrixPtr(oa::FnMatrix::causalMask(inScores));
	},
	  nb::arg("scores"),
	  nb::rv_policy::take_ownership,
	  "Apply an additive causal mask to Scores.");

	m.def("clampMax", [](const oa::Matrix& inA, oa::F32 inMax) {
		return matrixPtr(oa::FnMatrix::clampMax(inA, inMax));
	},
	  nb::arg("a"), nb::arg("max"),
	  nb::rv_policy::take_ownership,
	  "Element-wise clamp max: out = min(A, Max).");

	m.def("clampMin", [](const oa::Matrix& inA, oa::F32 inMin) {
		return matrixPtr(oa::FnMatrix::clampMin(inA, inMin));
	},
	  nb::arg("a"), nb::arg("min"),
	  nb::rv_policy::take_ownership,
	  "Element-wise clamp min: out = max(A, Min).");

	m.def("compactRows", [](const oa::Matrix& inSelf, const oa::Matrix& inMask) {
		return new oa::CompactRowsResult(oa::FnMatrix::compactRows(inSelf, inMask));
	},
	  nb::arg("self"), nb::arg("mask"),
	  nb::rv_policy::take_ownership,
	  "Compact selected rows while retaining device-authored row-map and count metadata.");

	m.def("concat", [](std::vector<oa::Matrix> inInputs, oa::I32 inDim) {
		auto result = oa::FnMatrix::concat(oa::Span<oa::Matrix>(inInputs.data(), inInputs.size()), inDim);
		if (result.isEmpty()) {
			throw std::runtime_error("Concat requires one or more shape-compatible matrices");
		}
		return matrixPtr(std::move(result));
	},
	  nb::arg("inputs"), nb::arg("dim") = 0,
	  nb::rv_policy::take_ownership,
	  "Concatenate one or more matrices along Dim.");

	m.def("copy", [](const oa::Matrix& inA) {
		return matrixPtr(oa::FnMatrix::copy(inA));
	},
	  nb::arg("a"),
	  nb::rv_policy::take_ownership,
	  "Create an independent device copy of a matrix.");

	m.def("cos", [](const oa::Matrix& inA) {
		return matrixPtr(oa::FnMatrix::cos(inA));
	},
	  nb::arg("a"),
	  nb::rv_policy::take_ownership,
	  "Element-wise cosine: out = cos(A).");

	m.def("detach", [](const oa::Matrix& inSelf) {
		return matrixPtr(oa::FnMatrix::detach(inSelf));
	},
	  nb::arg("self"),
	  nb::rv_policy::take_ownership,
	  "Return a storage-sharing stop-gradient view of A.");

	m.def("div", [](const oa::Matrix& inA, const oa::Matrix& inB) {
		return matrixPtr(oa::FnMatrix::div(inA, inB));
	},
	  nb::arg("a"), nb::arg("b"),
	  nb::rv_policy::take_ownership,
	  "Element-wise division: out = A / B.");

	m.def("divScalar", [](const oa::Matrix& inA, oa::F32 inScalar) {
		return matrixPtr(oa::FnMatrix::divScalar(inA, inScalar));
	},
	  nb::arg("a"), nb::arg("scalar"),
	  nb::rv_policy::take_ownership,
	  "Scalar division: out = A / Scalar.");

	m.def("dropout", [](const oa::Matrix& inA, oa::F32 inP, oa::U64 inSeed) {
		return matrixPtr(oa::FnMatrix::dropout(inA, inP, inSeed));
	},
	  nb::arg("a"), nb::arg("p"), nb::arg("seed") = 0,
	  nb::rv_policy::take_ownership,
	  "Apply inverted dropout to A with an optional explicit Philox seed.");

	m.def("equal", [](const oa::Matrix& inA, oa::F32 inValue) {
		return matrixPtr(oa::FnMatrix::equal(inA, inValue));
	},
	  nb::arg("a"), nb::arg("value"),
	  nb::rv_policy::take_ownership,
	  "Return a Float32 mask where A equals Value.");

	m.def("exp", [](const oa::Matrix& inA) {
		return matrixPtr(oa::FnMatrix::exp(inA));
	},
	  nb::arg("a"),
	  nb::rv_policy::take_ownership,
	  "Element-wise exponential: out = exp(A).");

	m.def("fill", [](const oa::MatrixShape& inShape, oa::F32 inValue) {
		return matrixPtr(oa::FnMatrix::fill(inShape, inValue));
	},
	  nb::arg("shape"), nb::arg("value"),
	  nb::rv_policy::take_ownership,
	  "Create a Float32 matrix of Shape filled with Value.");

	m.def("gather", [](const oa::Matrix& inA, const oa::Matrix& inIndices) {
		return matrixPtr(oa::FnMatrix::gather(inA, inIndices));
	},
	  nb::arg("a"), nb::arg("indices"),
	  nb::rv_policy::take_ownership,
	  "Gather rows from a rank-two table using UInt8 or UInt32 indices.");

	m.def("gatherLastDim", [](const oa::Matrix& inSelf, const oa::Matrix& inIndices) {
		return matrixPtr(oa::FnMatrix::gatherLastDim(inSelf, inIndices));
	},
	  nb::arg("self"), nb::arg("indices"),
	  nb::rv_policy::take_ownership,
	  "Gather Int32-selected values from the last dimension of Self.");

	m.def("greaterEqual", [](const oa::Matrix& inA, oa::F32 inValue) {
		return matrixPtr(oa::FnMatrix::greaterEqual(inA, inValue));
	},
	  nb::arg("a"), nb::arg("value"),
	  nb::rv_policy::take_ownership,
	  "Return a Float32 mask where A is greater than or equal to Value.");

	m.def("log", [](const oa::Matrix& inA) {
		return matrixPtr(oa::FnMatrix::log(inA));
	},
	  nb::arg("a"),
	  nb::rv_policy::take_ownership,
	  "Element-wise natural log: out = log(A).");

	m.def("logSoftmax", [](const oa::Matrix& inA, oa::I32 inDim) {
		return matrixPtr(oa::FnMatrix::logSoftmax(inA, inDim));
	},
	  nb::arg("a"), nb::arg("dim") = -1,
	  nb::rv_policy::take_ownership,
	  "Stable log-softmax over the selected dimension; -1 selects the last dimension.");

	m.def("maskedCategoricalAccuracyCount", [](const oa::Matrix& inLogits, const oa::Matrix& inLabels, const oa::Matrix& inMask) {
		return matrixPtr(oa::FnMatrix::maskedCategoricalAccuracyCount(inLogits, inLabels, inMask));
	},
	  nb::arg("logits"), nb::arg("labels"), nb::arg("mask"),
	  nb::rv_policy::take_ownership,
	  "Count correct masked categorical predictions into one device UInt32 scalar.");

	m.def("matMulNt", [](const oa::Matrix& inA, const oa::Matrix& inB, oa::MatMulPrecision inPrecision) {
		return matrixPtr(oa::FnMatrix::matMulNt(inA, inB, inPrecision));
	},
	  nb::arg("a"), nb::arg("b"), nb::arg("precision") = oa::MatMulPrecision::Auto,
	  nb::rv_policy::take_ownership,
	  "oa::Matrix multiplication C = A @ B^T using the OA weight-layout convention.");

	m.def("max", [](const oa::Matrix& inA, oa::I32 inDim) {
		return matrixPtr(oa::FnMatrix::max(inA, inDim));
	},
	  nb::arg("a"), nb::arg("dim") = -1,
	  nb::rv_policy::take_ownership,
	  "Reduce all matrix values by maximum; dim is currently a compatibility parameter.");

	m.def("mean", [](const oa::Matrix& inA, oa::I32 inDim) {
		return matrixPtr(oa::FnMatrix::mean(inA, inDim));
	},
	  nb::arg("a"), nb::arg("dim") = -1,
	  nb::rv_policy::take_ownership,
	  "Reduce by arithmetic mean, preserving a selected dimension or reducing all values when dim is -1.");

	m.def("moeExpertPlan", [](const oa::Matrix& inExpertIndices, oa::I32 inNumExperts) {
		return new oa::MoeExpertPlan(oa::FnMatrix::moeExpertPlan(inExpertIndices, inNumExperts));
	},
	  nb::arg("expertIndices"), nb::arg("numExperts"),
	  nb::rv_policy::take_ownership,
	  "Build a stable dropless expert-major route plan.");

	m.def("mul", [](const oa::Matrix& inA, const oa::Matrix& inB) {
		return matrixPtr(oa::FnMatrix::mul(inA, inB));
	},
	  nb::arg("a"), nb::arg("b"),
	  nb::rv_policy::take_ownership,
	  "Element-wise multiplication: out = A * B.");

	m.def("neg", [](const oa::Matrix& inA) {
		return matrixPtr(oa::FnMatrix::neg(inA));
	},
	  nb::arg("a"),
	  nb::rv_policy::take_ownership,
	  "Element-wise negation: out = -A.");

	m.def("philoxNormal", [](const oa::Matrix& inA, oa::F32 inMean, oa::F32 inStddev, oa::U64 inSeed) {
		return matrixPtr(oa::FnMatrix::philoxNormal(inA, inMean, inStddev, inSeed));
	},
	  nb::arg("a"), nb::arg("mean") = 0.0F, nb::arg("stddev") = 1.0F, nb::arg("seed") = 0,
	  nb::rv_policy::take_ownership,
	  "Generate a Philox normal sample with the input shape and dtype.");

	m.def("philoxUniform", [](const oa::Matrix& inA, oa::F32 inLow, oa::F32 inHigh, oa::U64 inSeed) {
		return matrixPtr(oa::FnMatrix::philoxUniform(inA, inLow, inHigh, inSeed));
	},
	  nb::arg("a"), nb::arg("low") = 0.0F, nb::arg("high") = 1.0F, nb::arg("seed") = 0,
	  nb::rv_policy::take_ownership,
	  "Generate a Philox uniform sample with the input shape and dtype.");

	m.def("pow", [](const oa::Matrix& inA, oa::F32 inExponent) {
		return matrixPtr(oa::FnMatrix::pow(inA, inExponent));
	},
	  nb::arg("a"), nb::arg("exponent"),
	  nb::rv_policy::take_ownership,
	  "Element-wise power: out = A^Exponent.");

	m.def("reciprocal", [](const oa::Matrix& inA) {
		return matrixPtr(oa::FnMatrix::reciprocal(inA));
	},
	  nb::arg("a"),
	  nb::rv_policy::take_ownership,
	  "Element-wise reciprocal: out = 1 / A.");

	m.def("repeatInterleave", [](const oa::Matrix& inA, oa::I32 inRepeats, oa::I32 inDim) {
		return matrixPtr(oa::FnMatrix::repeatInterleave(inA, inRepeats, inDim));
	},
	  nb::arg("a"), nb::arg("repeats"), nb::arg("dim"),
	  nb::rv_policy::take_ownership,
	  "Repeat every value in A along Dim.");

	m.def("sampleLogits", [](const oa::Matrix& inLogits, oa::F32 inTemperature, oa::I32 inTopK, oa::F32 inTopP, oa::U64 inSeed) {
		return matrixPtr(oa::FnMatrix::sampleLogits(inLogits, inTemperature, inTopK, inTopP, inSeed));
	},
	  nb::arg("logits"), nb::arg("temperature") = 1.0F, nb::arg("topK") = 0, nb::arg("topP") = 1.0F, nb::arg("seed") = 0,
	  nb::rv_policy::take_ownership,
	  "Sample one class per final-axis row of Logits.");

	m.def("scale", [](const oa::Matrix& inA, oa::F32 inScalar) {
		return matrixPtr(oa::FnMatrix::scale(inA, inScalar));
	},
	  nb::arg("a"), nb::arg("scalar"),
	  nb::rv_policy::take_ownership,
	  "Scalar multiplication: out = A * Scalar.");

	m.def("scatterRows", [](const oa::Matrix& inSelf, const oa::Matrix& inSource, const oa::Matrix& inRowMap, const oa::Matrix& inCount) {
		return matrixPtr(oa::FnMatrix::scatterRows(inSelf, inSource, inRowMap, inCount));
	},
	  nb::arg("self"), nb::arg("source"), nb::arg("rowMap"), nb::arg("count"),
	  nb::rv_policy::take_ownership,
	  "Scatter compacted Source rows over Self using a device row map and count.");

	m.def("sin", [](const oa::Matrix& inA) {
		return matrixPtr(oa::FnMatrix::sin(inA));
	},
	  nb::arg("a"),
	  nb::rv_policy::take_ownership,
	  "Element-wise sine: out = sin(A).");

	m.def("slice", [](const oa::Matrix& inSelf, oa::I32 inDim, oa::I64 inStart, oa::I64 inEnd) {
		return matrixPtr(oa::FnMatrix::slice(inSelf, inDim, inStart, inEnd));
	},
	  nb::arg("self"), nb::arg("dim"), nb::arg("start"), nb::arg("end"),
	  nb::rv_policy::take_ownership,
	  "Materialize a contiguous half-open slice [Start, End) along Dim.");

	m.def("softmax", [](const oa::Matrix& inA, oa::I32 inDim) {
		return matrixPtr(oa::FnMatrix::softmax(inA, inDim));
	},
	  nb::arg("a"), nb::arg("dim") = -1,
	  nb::rv_policy::take_ownership,
	  "Stable softmax over the selected dimension; -1 selects the last dimension.");

	m.def("softmaxBwd", [](const oa::Matrix& inForwardOutput, const oa::Matrix& inGradOutput, oa::I32 inDim) {
		return matrixPtr(oa::FnMatrix::softmaxBwd(inForwardOutput, inGradOutput, inDim));
	},
	  nb::arg("forwardOutput"), nb::arg("gradOutput"), nb::arg("dim") = -1,
	  nb::rv_policy::take_ownership,
	  "Apply the axis-aware softmax adjoint to an explicit output gradient.");

	m.def("split", [](const oa::Matrix& inSelf, std::vector<oa::I64> inSizes, oa::I32 inDim) {
		auto result = oa::FnMatrix::split(inSelf, oa::Span<oa::I64>(inSizes.data(), inSizes.size()), inDim);
		nb::list values;
		for (auto& value : result) {
			values.append(nb::cast(
				matrixPtr(std::move(value)),
				nb::rv_policy::take_ownership));
		}
		return values;
	},
	  nb::arg("self"), nb::arg("sizes"), nb::arg("dim") = 0,
	  nb::rv_policy::take_ownership,
	  "Split Self into materialized outputs with the requested Sizes along Dim.");

	m.def("sqrt", [](const oa::Matrix& inA) {
		return matrixPtr(oa::FnMatrix::sqrt(inA));
	},
	  nb::arg("a"),
	  nb::rv_policy::take_ownership,
	  "Element-wise square root: out = sqrt(A).");

	m.def("sub", [](const oa::Matrix& inA, const oa::Matrix& inB) {
		return matrixPtr(oa::FnMatrix::sub(inA, inB));
	},
	  nb::arg("a"), nb::arg("b"),
	  nb::rv_policy::take_ownership,
	  "Element-wise subtraction: out = A - B.");

	m.def("subScalar", [](const oa::Matrix& inA, oa::F32 inScalar) {
		return matrixPtr(oa::FnMatrix::subScalar(inA, inScalar));
	},
	  nb::arg("a"), nb::arg("scalar"),
	  nb::rv_policy::take_ownership,
	  "Scalar subtraction: out = A - Scalar.");

	m.def("sum", [](const oa::Matrix& inA, oa::I32 inDim) {
		return matrixPtr(oa::FnMatrix::sum(inA, inDim));
	},
	  nb::arg("a"), nb::arg("dim") = -1,
	  nb::rv_policy::take_ownership,
	  "Reduce by summation, preserving a selected dimension or reducing all values when dim is -1.");

	m.def("topK", [](const oa::Matrix& inA, oa::I32 inK, oa::I32 inDim) {
		return new oa::TopKResult(oa::FnMatrix::topK(inA, inK, inDim));
	},
	  nb::arg("a"), nb::arg("k"), nb::arg("dim") = -1,
	  nb::rv_policy::take_ownership,
	  "Return the largest K values and their Int32 indices along the last dimension.");

	m.def("topKMask", [](const oa::Matrix& inIndices, oa::I32 inNumExperts) {
		return matrixPtr(oa::FnMatrix::topKMask(inIndices, inNumExperts));
	},
	  nb::arg("indices"), nb::arg("numExperts"),
	  nb::rv_policy::take_ownership,
	  "Expand TopK indices into a dense expert-membership mask.");

	m.def("transpose", [](const oa::Matrix& inA, oa::I32 inDim0, oa::I32 inDim1) {
		return matrixPtr(oa::FnMatrix::transpose(inA, inDim0, inDim1));
	},
	  nb::arg("a"), nb::arg("dim0") = -2, nb::arg("dim1") = -1,
	  nb::rv_policy::take_ownership,
	  "Materialize a swap of the last two axes.");
