#pragma once

// OaHumanIk — the HumanIK characterization + UE mannequin reference poses.
// HumanIK is an Autodesk trademark; interop map only, not the Autodesk SDK — see NOTICE.md.
//
// HumanIK is the industry-standard retarget hub (MotionBuilder / Maya): a fixed
// set of named slots (Hips, Spine, LeftArm, …) that any skeleton is mapped onto,
// so motion can be transferred between rigs through the shared characterization.
//
// This is the data layer for OaRetarget: the slot ⇄ UE-node ⇄ HumanIK-id map
// (from oa3d's RTG_DEFINITION_UNREAL) and the per-mannequin tPose / aPose
// reference poses (from RTG_POSES_SKEL_MANNY / _QUINN). The reference pose is
// what a retarget needs to express each joint's animation *relative to its rest*
// in one rig and re-apply it in another. Generated by
// Tools/Gen3dAnim/gen_rtg_pose_data.py into RtgPoseData.inc.

#include <Core/Joint.h>
#include <Oa/Core/Types.h>

enum class OaMannequin { Manny, Quinn };
enum class OaPoseKind  { TPose, APose };

// One HumanIK characterization slot: the HumanIK name, its numeric id, and the
// UE bone it binds to on the mannequin.
struct OaHumanIkSlot {
	OaString Slot;     // HumanIK slot name, e.g. "LeftArm"
	OaI32    Id   = 0; // HumanIK slot id
	OaString Node;     // UE bone name, e.g. "upperarm_l"
};

// One joint's local reference transform within a named pose.
struct OaRefJoint {
	OaString Name;                                  // UE bone name
	VlmQuat   LocalOrient = { 0.0f, 0.0f, 0.0f, 1.0f }; // local orientation (from Maya XYZ)
	VlmVec3   LocalTrans  = {};                       // local offset to parent (cm)
};

// A full reference pose (the 25 core body joints).
struct OaRefPose {
	OaVec<OaRefJoint> Joints;

	// Local reference orientation for a bone by name; identity if absent.
	[[nodiscard]] VlmQuat OrientOf(OaStringView InName) const noexcept;
};

// The HumanIK characterization for the UE mannequin (25 core slots).
[[nodiscard]] const OaVec<OaHumanIkSlot>& OaHumanIkCharacterization();

// The reference pose for a mannequin + pose kind (manny/quinn × tPose/aPose).
[[nodiscard]] const OaRefPose& OaRefPoseFor(OaMannequin InWho, OaPoseKind InKind);
