// AUTO-GENERATED by tools/gen/nn/generate.py - DO NOT EDIT.
// source of truth: tools/gen/nn/schema/ml/mlNnConv.toml.
// Regenerate via: python3 tools/gen/nn/generate.py --live

#pragma once

#include <oa/ml/module.h>

#include <initializer_list>

namespace oa {

/// ConvTranspose1d: 1D transposed convolution (learnable upsampling); adjoint of Conv1d, no bias.
class ConvTranspose1d : public Module {
public:
	ConvTranspose1d(oa::I32 inChannels, oa::I32 outChannels, oa::I32 kernelSize, oa::I32 inStride = 1, oa::I32 inPadding = 0);
	Matrix forward(const Matrix& inInput) override;

private:
	oa::I32 inChannels_;
	oa::I32 outChannels_;
	oa::I32 kernelSize_;
	oa::I32 stride_;
	oa::I32 padding_;
};

} // namespace oa
