// AUTO-GENERATED by tools/gen/fn/generate.py — DO NOT EDIT.
// Source of truth: tools/gen/fn/schema/vision/visionFnImagePixel.toml.
// Regenerate via: python3 tools/gen/fn/generate.py --live
// oa::FnImage — Pixel GPU operations.
// Unified API: records operations to oa::ExecutionSession.

#include <oa/core/matrix.h>
#include <oa/core/fnMatrix.h>
#include <oa/core/op.h>
#include <oa/vision/fnImage.h>
#include <oa/core/status.h>
#include <oa/core/types.h>
#include <oa/core/bufferAccess.h>
#include <oa/runtime/executionSession.h>
#include <oa/core/validation.h>

// ─── thresholdBinary (Global binary threshold) ────

oa::Matrix oa::FnImage::thresholdBinary(const oa::Matrix& inImage, oa::F32 inThreshold, oa::F32 inMaxValue) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::thresholdBinary(session.engine(), inImage, inThreshold, inMaxValue);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::thresholdBinary, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("threshold", inThreshold), oa::OpAttribute::fromFloat("maxValue", inMaxValue)});
	if (not status.isOk()) return {};
	return out;
}

// ─── thresholdBinaryInv (Global inverse binary threshold) ────

oa::Matrix oa::FnImage::thresholdBinaryInv(const oa::Matrix& inImage, oa::F32 inThreshold, oa::F32 inMaxValue) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::thresholdBinaryInv(session.engine(), inImage, inThreshold, inMaxValue);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::thresholdBinaryInv, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("threshold", inThreshold), oa::OpAttribute::fromFloat("maxValue", inMaxValue)});
	if (not status.isOk()) return {};
	return out;
}

// ─── thresholdTruncate (Truncate values above a threshold) ────

oa::Matrix oa::FnImage::thresholdTruncate(const oa::Matrix& inImage, oa::F32 inThreshold) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::thresholdTruncate(session.engine(), inImage, inThreshold);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::thresholdTruncate, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("threshold", inThreshold)});
	if (not status.isOk()) return {};
	return out;
}

// ─── thresholdToZero (Set values at or below a threshold to zero) ────

oa::Matrix oa::FnImage::thresholdToZero(const oa::Matrix& inImage, oa::F32 inThreshold) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::thresholdToZero(session.engine(), inImage, inThreshold);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::thresholdToZero, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("threshold", inThreshold)});
	if (not status.isOk()) return {};
	return out;
}

// ─── thresholdToZeroInv (Set values above a threshold to zero) ────

oa::Matrix oa::FnImage::thresholdToZeroInv(const oa::Matrix& inImage, oa::F32 inThreshold) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::thresholdToZeroInv(session.engine(), inImage, inThreshold);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::thresholdToZeroInv, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("threshold", inThreshold)});
	if (not status.isOk()) return {};
	return out;
}

// ─── inRange (Inclusive scalar range mask) ────

oa::Matrix oa::FnImage::inRange(const oa::Matrix& inImage, oa::F32 inLow, oa::F32 inHigh, oa::F32 inTrueValue) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::inRange(session.engine(), inImage, inLow, inHigh, inTrueValue);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::inRange, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("low", inLow), oa::OpAttribute::fromFloat("high", inHigh), oa::OpAttribute::fromFloat("trueValue", inTrueValue)});
	if (not status.isOk()) return {};
	return out;
}

// ─── clamp (Clamp image values to a scalar interval) ────

oa::Matrix oa::FnImage::clamp(const oa::Matrix& inImage, oa::F32 inLow, oa::F32 inHigh) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::clamp(session.engine(), inImage, inLow, inHigh);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::clamp, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("low", inLow), oa::OpAttribute::fromFloat("high", inHigh)});
	if (not status.isOk()) return {};
	return out;
}

// ─── invert (Invert values around a configurable maximum) ────

oa::Matrix oa::FnImage::invert(const oa::Matrix& inImage, oa::F32 inMaxValue) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::invert(session.engine(), inImage, inMaxValue);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::invert, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("maxValue", inMaxValue)});
	if (not status.isOk()) return {};
	return out;
}

// ─── brightnessContrast (Affine brightness and contrast adjustment) ────

oa::Matrix oa::FnImage::brightnessContrast(const oa::Matrix& inImage, oa::F32 inBrightness, oa::F32 inContrast) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::brightnessContrast(session.engine(), inImage, inBrightness, inContrast);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::brightnessContrast, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("brightness", inBrightness), oa::OpAttribute::fromFloat("contrast", inContrast)});
	if (not status.isOk()) return {};
	return out;
}

// ─── gammaContrast (Gamma and gain adjustment) ────

oa::Matrix oa::FnImage::gammaContrast(const oa::Matrix& inImage, oa::F32 inGamma, oa::F32 inGain) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::gammaContrast(session.engine(), inImage, inGamma, inGain);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::gammaContrast, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("gamma", inGamma), oa::OpAttribute::fromFloat("gain", inGain)});
	if (not status.isOk()) return {};
	return out;
}

// ─── solarize (Invert values above a threshold) ────

oa::Matrix oa::FnImage::solarize(const oa::Matrix& inImage, oa::F32 inThreshold, oa::F32 inMaxValue) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::solarize(session.engine(), inImage, inThreshold, inMaxValue);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::solarize, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("threshold", inThreshold), oa::OpAttribute::fromFloat("maxValue", inMaxValue)});
	if (not status.isOk()) return {};
	return out;
}

// ─── posterize (Quantize an intensity interval to a fixed number of levels)

oa::Matrix oa::FnImage::posterize(const oa::Matrix& inImage, oa::U32 inLevels, oa::F32 inLow, oa::F32 inHigh) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::posterize(session.engine(), inImage, inLevels, inLow, inHigh);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::posterize, {&inImage}, {&out}, {oa::OpAttribute::fromUnsignedInteger("levels", inLevels), oa::OpAttribute::fromFloat("low", inLow), oa::OpAttribute::fromFloat("high", inHigh)});
	if (not status.isOk()) return {};
	return out;
}

// ─── grayscale (Rec.709 RGB to single-channel grayscale conversion) ────

oa::Matrix oa::FnImage::grayscale(const oa::Matrix& inImage) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::grayscale(session.engine(), inImage);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::grayscale, {&inImage}, {&out}, {});
	if (not status.isOk()) return {};
	return out;
}

// ─── channelReorder (Reorder one to four NCHW channels) ────

oa::Matrix oa::FnImage::channelReorder(const oa::Matrix& inImage, oa::U32 inChannel0, oa::U32 inChannel1, oa::U32 inChannel2, oa::U32 inChannel3) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::channelReorder(session.engine(), inImage, inChannel0, inChannel1, inChannel2, inChannel3);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::channelReorder, {&inImage}, {&out}, {oa::OpAttribute::fromUnsignedInteger("channel0", inChannel0), oa::OpAttribute::fromUnsignedInteger("channel1", inChannel1), oa::OpAttribute::fromUnsignedInteger("channel2", inChannel2), oa::OpAttribute::fromUnsignedInteger("channel3", inChannel3)});
	if (not status.isOk()) return {};
	return out;
}

// ─── alphaBlend (Scalar alpha blend of equal-shaped images) ────

oa::Matrix oa::FnImage::alphaBlend(const oa::Matrix& inA, const oa::Matrix& inB, oa::F32 inAlpha) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::alphaBlend(session.engine(), inA, inB, inAlpha);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::alphaBlend, {&inA, &inB}, {&out}, {oa::OpAttribute::fromFloat("alpha", inAlpha)});
	if (not status.isOk()) return {};
	return out;
}

// ─── composite (Per-pixel masked composite with one or C mask channels) ────

oa::Matrix oa::FnImage::composite(const oa::Matrix& inA, const oa::Matrix& inB, const oa::Matrix& inMask) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::composite(session.engine(), inA, inB, inMask);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::composite, {&inA, &inB, &inMask}, {&out}, {});
	if (not status.isOk()) return {};
	return out;
}

// ─── erase (Fill a rectangular region with a scalar value) ────

oa::Matrix oa::FnImage::erase(const oa::Matrix& inImage, oa::U32 inX, oa::U32 inY, oa::U32 inWidth, oa::U32 inHeight, oa::F32 inValue) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::erase(session.engine(), inImage, inX, inY, inWidth, inHeight, inValue);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::erase, {&inImage}, {&out}, {oa::OpAttribute::fromUnsignedInteger("x", inX), oa::OpAttribute::fromUnsignedInteger("y", inY), oa::OpAttribute::fromUnsignedInteger("width", inWidth), oa::OpAttribute::fromUnsignedInteger("height", inHeight), oa::OpAttribute::fromFloat("value", inValue)});
	if (not status.isOk()) return {};
	return out;
}

// ─── colorTwist (Apply a shared 3x4 RGB color transform matrix) ────

oa::Matrix oa::FnImage::colorTwist(const oa::Matrix& inImage, const oa::Matrix& inTransform) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::colorTwist(session.engine(), inImage, inTransform);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::colorTwist, {&inImage, &inTransform}, {&out}, {});
	if (not status.isOk()) return {};
	return out;
}

// ─── gaussianNoise (Add deterministic GPU-native Philox Gaussian noise) ────

oa::Matrix oa::FnImage::gaussianNoise(const oa::Matrix& inImage, oa::F32 inMean, oa::F32 inStddev, oa::U64 inSeed) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::gaussianNoise(session.engine(), inImage, inMean, inStddev, inSeed);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::gaussianNoise, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("mean", inMean), oa::OpAttribute::fromFloat("stddev", inStddev), oa::OpAttribute::fromUnsignedInteger("seed", inSeed)});
	if (not status.isOk()) return {};
	return out;
}

// ─── saltPepperNoise (Apply deterministic GPU-native salt-and-pepper noise)

oa::Matrix oa::FnImage::saltPepperNoise(const oa::Matrix& inImage, oa::F32 inProbability, oa::F32 inSaltValue, oa::F32 inPepperValue, oa::U64 inSeed) {
	auto& session = oa::ExecutionSession::getActive();
	oa::OpLoweringScope lowering(session);
	auto out = oa::FnImage::saltPepperNoise(session.engine(), inImage, inProbability, inSaltValue, inPepperValue, inSeed);
	const auto status = lowering.commit(
		oa::detail::opRegistry::FnImage::saltPepperNoise, {&inImage}, {&out}, {oa::OpAttribute::fromFloat("probability", inProbability), oa::OpAttribute::fromFloat("saltValue", inSaltValue), oa::OpAttribute::fromFloat("pepperValue", inPepperValue), oa::OpAttribute::fromUnsignedInteger("seed", inSeed)});
	if (not status.isOk()) return {};
	return out;
}
