// AUTO-GENERATED by tools/fnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: tools/fnAutogen/schema/ml/FnMatrix manifest.
// Regenerate via: python3 tools/fnAutogen/oafnautogen.py --live

// oa::FnMatrix — generated declarations for ml/FnMatrix.

#include "activation/fnMatrixActivation.gen.h"
#include "embed/fnMatrixEmbed.gen.h"
#include "norm/fnMatrixNorm.gen.h"
