// AUTO-GENERATED by tools/gen/fn/generate.py — DO NOT EDIT.
// Source of truth: tools/gen/fn/schema/ml/mlFnMatrixActivation.toml.
// Regenerate via: python3 tools/gen/fn/generate.py --live
// oa::FnMatrix — Activation GPU operations.
// Unified API: records operations to oa::ExecutionSession.

#include <oa/ml/autograd/matrix/autogradActivation.h>
#include <oa/core/matrix.h>
#include <oa/core/fnMatrix.h>
#include <oa/core/op.h>
#include <oa/ml/fnMatrix.h>
#include <oa/core/status.h>
#include <oa/core/types.h>
#include <oa/core/bufferAccess.h>
#include <oa/runtime/executionSession.h>
#include <oa/core/validation.h>

#include <assert.h>

static oa::U32 divCeil(oa::U32 inA, oa::U32 inB) { return (inA + inB - 1) / inB; }

// ─── gelu (GELU activation: out = GELU(A)) ────

oa::Matrix oa::FnMatrix::gelu(const oa::Matrix& inA) {
	auto& session = oa::ExecutionSession::getActive();
	oa::Matrix out = oa::FnMatrix::empty(inA.getShape(), inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::gelu, {&inA}, {&out},
		{});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(inA.numElements());

	struct { oa::U32 count; } push{n};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("Gelu", {&inA, &out}, access, &push, sizeof(push), divCeil(n, 256),
		1, 1, oa::detail::opRegistry::FnMatrix::gelu.name, 0,
		oa::detail::opRegistry::FnMatrix::gelu.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradGelu>();
		_gradFn->saveForBackward(inA);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}

// ─── silu (SiLU (Swish) activation: out = A * sigmoid(A)) ────

oa::Matrix oa::FnMatrix::silu(const oa::Matrix& inA) {
	auto& session = oa::ExecutionSession::getActive();
	oa::Matrix out = oa::FnMatrix::empty(inA.getShape(), inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::silu, {&inA}, {&out},
		{});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(inA.numElements());

	struct { oa::U32 count; } push{n};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("Silu", {&inA, &out}, access, &push, sizeof(push), divCeil(n, 256),
		1, 1, oa::detail::opRegistry::FnMatrix::silu.name, 0,
		oa::detail::opRegistry::FnMatrix::silu.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradSilu>();
		_gradFn->saveForBackward(inA);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}

// ─── relu (ReLU activation: out = max(0, A)) ────

oa::Matrix oa::FnMatrix::relu(const oa::Matrix& inA) {
	auto& session = oa::ExecutionSession::getActive();
	oa::Matrix out = oa::FnMatrix::empty(inA.getShape(), inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::relu, {&inA}, {&out},
		{});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(inA.numElements());

	struct { oa::U32 count; } push{n};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("Relu", {&inA, &out}, access, &push, sizeof(push), divCeil(n, 256),
		1, 1, oa::detail::opRegistry::FnMatrix::relu.name, 0,
		oa::detail::opRegistry::FnMatrix::relu.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradRelu>();
		_gradFn->saveForBackward(out);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}

// ─── tanh (Tanh activation: out = tanh(A)) ────

oa::Matrix oa::FnMatrix::tanh(const oa::Matrix& inA) {
	auto& session = oa::ExecutionSession::getActive();
	oa::Matrix out = oa::FnMatrix::empty(inA.getShape(), inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::tanh, {&inA}, {&out},
		{});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(inA.numElements());

	struct { oa::U32 count; } push{n};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("Tanh", {&inA, &out}, access, &push, sizeof(push), divCeil(n, 256),
		1, 1, oa::detail::opRegistry::FnMatrix::tanh.name, 0,
		oa::detail::opRegistry::FnMatrix::tanh.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradTanh>();
		_gradFn->saveForBackward(out);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}

// ─── sigmoid (Sigmoid activation: out = 1 / (1 + exp(-A))) ────

oa::Matrix oa::FnMatrix::sigmoid(const oa::Matrix& inA) {
	auto& session = oa::ExecutionSession::getActive();
	oa::Matrix out = oa::FnMatrix::empty(inA.getShape(), inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::sigmoid, {&inA}, {&out},
		{});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(inA.numElements());

	struct { oa::U32 count; } push{n};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("Sigmoid", {&inA, &out}, access, &push, sizeof(push), divCeil(n, 256),
		1, 1, oa::detail::opRegistry::FnMatrix::sigmoid.name, 0,
		oa::detail::opRegistry::FnMatrix::sigmoid.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradSigmoid>();
		_gradFn->saveForBackward(out);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}

// ─── leakyRelu (Leaky ReLU activation: out = max(Alpha * A, A)) ────

oa::Matrix oa::FnMatrix::leakyRelu(const oa::Matrix& inA, oa::F32 inAlpha) {
	auto& session = oa::ExecutionSession::getActive();
	oa::Matrix out = oa::FnMatrix::empty(inA.getShape(), inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::leakyRelu, {&inA}, {&out},
		{oa::OpAttribute::fromFloat("alpha", inAlpha)});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(inA.numElements());

	struct { oa::U32 count; oa::F32 alpha; } push{n, inAlpha};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("LeakyRelu", {&inA, &out}, access, &push, sizeof(push), divCeil(n, 256),
		1, 1, oa::detail::opRegistry::FnMatrix::leakyRelu.name, 0,
		oa::detail::opRegistry::FnMatrix::leakyRelu.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradLeakyRelu>(inAlpha);
		_gradFn->saveForBackward(out);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}

// ─── elu (ELU activation: out = A if A > 0 else Alpha * (exp(A) - 1)) ────

oa::Matrix oa::FnMatrix::elu(const oa::Matrix& inA, oa::F32 inAlpha) {
	auto& session = oa::ExecutionSession::getActive();
	oa::Matrix out = oa::FnMatrix::empty(inA.getShape(), inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::elu, {&inA}, {&out},
		{oa::OpAttribute::fromFloat("alpha", inAlpha)});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(inA.numElements());

	struct { oa::U32 count; oa::F32 alpha; } push{n, inAlpha};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("Elu", {&inA, &out}, access, &push, sizeof(push), divCeil(n, 256),
		1, 1, oa::detail::opRegistry::FnMatrix::elu.name, 0,
		oa::detail::opRegistry::FnMatrix::elu.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradElu>(inAlpha);
		_gradFn->saveForBackward(out);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}

// ─── mish (Mish activation: out = A * tanh(softplus(A))) ────

oa::Matrix oa::FnMatrix::mish(const oa::Matrix& inA) {
	auto& session = oa::ExecutionSession::getActive();
	oa::Matrix out = oa::FnMatrix::empty(inA.getShape(), inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::mish, {&inA}, {&out},
		{});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(inA.numElements());

	struct { oa::U32 count; } push{n};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("Mish", {&inA, &out}, access, &push, sizeof(push), divCeil(n, 256),
		1, 1, oa::detail::opRegistry::FnMatrix::mish.name, 0,
		oa::detail::opRegistry::FnMatrix::mish.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradMish>();
		_gradFn->saveForBackward(inA);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}

// ─── swiglu (SwiGLU activation: out = SiLU(gate) * up) ────

oa::Matrix oa::FnMatrix::swiglu(const oa::Matrix& inA, const oa::Matrix& inB) {
	auto& session = oa::ExecutionSession::getActive();
	oa::Matrix out = oa::FnMatrix::empty(inA.getShape(), inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::swiglu, {&inA, &inB}, {&out},
		{});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(inA.numElements());

	struct { oa::U32 count; } push{n};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("Swiglu", {&inA, &inB, &out}, access, &push, sizeof(push), divCeil(n, 256),
		1, 1, oa::detail::opRegistry::FnMatrix::swiglu.name, 0,
		oa::detail::opRegistry::FnMatrix::swiglu.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad() or inB.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradSwiglu>();
		_gradFn->saveForBackward(inA, inB, out);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA, inB});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}

// ─── siluMul (SiLU on first half, multiply with second half: out = SiLU(A[:N

oa::Matrix oa::FnMatrix::siluMul(const oa::Matrix& inA, oa::U32 inIntermediateSize) {
	auto& session = oa::ExecutionSession::getActive();
	oa::MatrixShape outShape = inA.getShape();
	assert(outShape.rank > 0 and inA.size(-1) % 2 == 0 and static_cast<oa::I64>(inIntermediateSize) == inA.size(-1) / 2);
	outShape.dims[static_cast<oa::Usize>(outShape.rank - 1)] = inA.size(-1) / 2;
	oa::Matrix out = oa::FnMatrix::empty(outShape, inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::siluMul, {&inA}, {&out},
		{oa::OpAttribute::fromUnsignedInteger("intermediateSize", inIntermediateSize)});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(out.numElements());

	struct { oa::U32 count; oa::U32 intermediate_size; } push{n, inIntermediateSize};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("SiluMul", {&inA, &out}, access, &push, sizeof(push), divCeil(static_cast<oa::U32>(out.numElements()), 256),
		1, 1, oa::detail::opRegistry::FnMatrix::siluMul.name, 0,
		oa::detail::opRegistry::FnMatrix::siluMul.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradSiluMul>();
		_gradFn->saveForBackward(inA);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}

// ─── geglu (GEGLU activation: out = A[:N] * GELU(A[N:])) ────

oa::Matrix oa::FnMatrix::geglu(const oa::Matrix& inA, oa::U32 inIntermediateSize) {
	auto& session = oa::ExecutionSession::getActive();
	oa::MatrixShape outShape = inA.getShape();
	assert(outShape.rank > 0 and inA.size(-1) % 2 == 0 and static_cast<oa::I64>(inIntermediateSize) == inA.size(-1) / 2);
	outShape.dims[static_cast<oa::Usize>(outShape.rank - 1)] = inA.size(-1) / 2;
	oa::Matrix out = oa::FnMatrix::empty(outShape, inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::geglu, {&inA}, {&out},
		{oa::OpAttribute::fromUnsignedInteger("intermediateSize", inIntermediateSize)});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(out.numElements());

	struct { oa::U32 count; oa::U32 intermediate_size; } push{n, inIntermediateSize};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("Geglu", {&inA, &out}, access, &push, sizeof(push), divCeil(static_cast<oa::U32>(out.numElements()), 256),
		1, 1, oa::detail::opRegistry::FnMatrix::geglu.name, 0,
		oa::detail::opRegistry::FnMatrix::geglu.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradGeglu>();
		_gradFn->saveForBackward(inA);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}

// ─── softplus (Softplus: out = log(1+exp(A)), computed stably as max(A,0)+lo

oa::Matrix oa::FnMatrix::softplus(const oa::Matrix& inA) {
	auto& session = oa::ExecutionSession::getActive();
	oa::Matrix out = oa::FnMatrix::empty(inA.getShape(), inA.getDtype());
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::softplus, {&inA}, {&out},
		{});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(inA.numElements());

	struct { oa::U32 count; } push{n};
	oa::BufferAccess access[] = {oa::BufferAccess::Read, oa::BufferAccess::Write};
	session.add("Softplus", {&inA, &out}, access, &push, sizeof(push), divCeil(n, 256),
		1, 1, oa::detail::opRegistry::FnMatrix::softplus.name, 0,
		oa::detail::opRegistry::FnMatrix::softplus.hash, 0, 0, semantic.getValue());
	if (oa::FnAutograd::isEnabled() and (inA.requiresGrad())) {
		auto _gradFn = oa::makeShared<oa::GradSoftplus>();
		_gradFn->saveForBackward(out);
		_gradFn->setGraphInputs(oa::Vector<oa::Matrix>{inA});
		_gradFn->sequenceNr_ = oa::FnAutograd::nextSeq();
		_gradFn->outputShape_ = out.getShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads
		const auto semanticAttached = oa::FnAutograd::attachSemantic(
			_gradFn, semantic.getValue());
		if (not semanticAttached.isOk()) return {};
		out.mutAutograd().gradFn = _gradFn;
		out.setRequiresGrad(true);
	}
	return out;
}
