// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/Ml/MlFnLoss.toml.
// Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live

// OaFnLoss — CrossEntropy overloads.

	/// CrossEntropy: Mean cross-entropy over rank-two logits and UInt8, UInt32, or non-negative Int32 class-index targets; the scalar result is Float32, and an out-of-range target produces NaN without an out-of-bounds read.
	[[nodiscard]] OaMatrix CrossEntropy(const OaMatrix& InLogits, const OaMatrix& InTargets);
