// AUTO-GENERATED by tools/gen/fn/generate.py — DO NOT EDIT.
// Includes schema-generated gradient-node catalogs for this domain.
// Regenerate via: python3 tools/gen/fn/generate.py --live

#pragma once

#include <oa/ml/autograd.h>
#include "matrix/autogradActivation.gen.h"
