from collections.abc import Sequence

class Engine:
	def __init__(self) -> None: ...
	def _ones(self, shape: Sequence[int]) -> Matrix: ...
	def _full(self, shape: Sequence[int], value: float) -> Matrix: ...

class Matrix:
	@staticmethod
	def from_f32(engine: Engine, shape: Sequence[int], values: Sequence[float]) -> Matrix: ...
	@property
	def shape(self) -> list[int]: ...
	@property
	def dtype(self) -> str: ...
	def _add(self, right: Matrix) -> Matrix: ...
	def _mat_mul_nt(self, right: Matrix) -> Matrix: ...
	def read_f32(self) -> list[float]: ...
	def to_list(self) -> list[float]: ...
	def __add__(self, right: Matrix) -> Matrix: ...
