from collections.abc import Sequence

class Engine:
	def __init__(self, device: int | None = None) -> None: ...
	def checkpoint(self) -> Event: ...
	def checkpoint_timed(self) -> Event: ...

class Event:
	def is_complete(self) -> bool: ...
	def wait(self) -> None: ...
	def device_duration_seconds(self) -> float: ...
	def try_device_duration_seconds(self) -> float | None: ...

class Matrix:
	@staticmethod
	def from_f32(engine: Engine, shape: Sequence[int], values: Sequence[float]) -> Matrix: ...
	@staticmethod
	def from_i32(engine: Engine, shape: Sequence[int], values: Sequence[int]) -> Matrix: ...
	@staticmethod
	def from_u32(engine: Engine, shape: Sequence[int], values: Sequence[int]) -> Matrix: ...
	@staticmethod
	def from_u8(engine: Engine, shape: Sequence[int], values: Sequence[int]) -> Matrix: ...
	@property
	def shape(self) -> list[int]: ...
	@property
	def dtype(self) -> str: ...
	@property
	def num_elements(self) -> int: ...
	def reshape(self, shape: Sequence[int]) -> Matrix: ...
	def read_f32(self) -> list[float]: ...
	def read_i32(self) -> list[int]: ...
	def read_u32(self) -> list[int]: ...
	def read_u8(self) -> list[int]: ...
	def to_list(self) -> list[float] | list[int]: ...
	def __add__(self, right: Matrix) -> Matrix: ...
	def __sub__(self, right: Matrix) -> Matrix: ...
	def __mul__(self, right: Matrix) -> Matrix: ...
	def __truediv__(self, right: Matrix) -> Matrix: ...
	def __neg__(self) -> Matrix: ...
	def __abs__(self) -> Matrix: ...

class Audio:
	@staticmethod
	def from_planar_f32(engine: Engine, samples: Sequence[float], channels: int,
		sample_rate: int, layout: str = "unknown") -> Audio: ...
	@property
	def channels(self) -> int: ...
	@property
	def samples(self) -> int: ...
	@property
	def sample_rate(self) -> int: ...
	@property
	def layout(self) -> str: ...
	@property
	def duration_seconds(self) -> float: ...
	def as_matrix(self) -> Matrix: ...

class Image:
	@staticmethod
	def from_matrix(matrix: Matrix, layout_name: str, format_name: str) -> Image: ...
	@property
	def width(self) -> int: ...
	@property
	def height(self) -> int: ...
	@property
	def channels(self) -> int: ...
	@property
	def batch_size(self) -> int: ...
	@property
	def layout(self) -> str: ...
	@property
	def format(self) -> str: ...
	@property
	def dtype(self) -> str: ...
	def as_matrix(self) -> Matrix: ...

def matrix_ones(engine: Engine, shape: Sequence[int]) -> Matrix: ...
def matrix_full(engine: Engine, shape: Sequence[int], value: float) -> Matrix: ...
def matrix_reshape(input: Matrix, shape: Sequence[int]) -> Matrix: ...
def matrix_add(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_sub(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_mul(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_div(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_mat_mul_nt(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_gather(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_gather_last_dim(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_neg(input: Matrix) -> Matrix: ...
def matrix_abs(input: Matrix) -> Matrix: ...
def matrix_log(input: Matrix) -> Matrix: ...
def matrix_sqrt(input: Matrix) -> Matrix: ...
def matrix_exp(input: Matrix) -> Matrix: ...
def matrix_sin(input: Matrix) -> Matrix: ...
def matrix_cos(input: Matrix) -> Matrix: ...
def matrix_reciprocal(input: Matrix) -> Matrix: ...
def matrix_copy(input: Matrix) -> Matrix: ...
def matrix_scale(input: Matrix, scalar: float) -> Matrix: ...
def matrix_pow(input: Matrix, scalar: float) -> Matrix: ...
def matrix_add_scalar(input: Matrix, scalar: float) -> Matrix: ...
def matrix_sub_scalar(input: Matrix, scalar: float) -> Matrix: ...
def matrix_div_scalar(input: Matrix, scalar: float) -> Matrix: ...
def matrix_clamp_max(input: Matrix, scalar: float) -> Matrix: ...
def matrix_clamp_min(input: Matrix, scalar: float) -> Matrix: ...
def matrix_equal(input: Matrix, scalar: float) -> Matrix: ...
def matrix_softmax(input: Matrix, dim: int) -> Matrix: ...
def matrix_log_softmax(input: Matrix, dim: int) -> Matrix: ...
def matrix_sum(input: Matrix, dim: int) -> Matrix: ...
def matrix_transpose(input: Matrix, dim0: int, dim1: int) -> Matrix: ...
def matrix_slice(input: Matrix, dim: int, start: int, end: int) -> Matrix: ...
def matrix_repeat_interleave(input: Matrix, repeats: int, dim: int) -> Matrix: ...
def matrix_concat(inputs: Sequence[Matrix], dim: int) -> Matrix: ...
def matrix_top_k(input: Matrix, k: int, dim: int) -> tuple[Matrix, Matrix]: ...
def matrix_philox_uniform(input: Matrix, low: float, high: float, seed: int) -> Matrix: ...
def matrix_philox_normal(input: Matrix, mean: float, stddev: float, seed: int) -> Matrix: ...
def matrix_dropout(input: Matrix, probability: float, seed: int) -> Matrix: ...
def matrix_sample_logits(input: Matrix, temperature: float, top_k: int,
	top_p: float, seed: int) -> Matrix: ...
def matrix_set_rng_seed(seed: int) -> None: ...

def ml_gelu(input: Matrix) -> Matrix: ...
def ml_silu(input: Matrix) -> Matrix: ...
def ml_relu(input: Matrix) -> Matrix: ...
def ml_tanh(input: Matrix) -> Matrix: ...
def ml_sigmoid(input: Matrix) -> Matrix: ...
def ml_mish(input: Matrix) -> Matrix: ...
def ml_softplus(input: Matrix) -> Matrix: ...
def ml_detach(input: Matrix) -> Matrix: ...
def ml_swiglu(left: Matrix, right: Matrix) -> Matrix: ...
def ml_leaky_relu(input: Matrix, alpha: float) -> Matrix: ...
def ml_elu(input: Matrix, alpha: float) -> Matrix: ...
def ml_silu_mul(input: Matrix, intermediate_size: int) -> Matrix: ...
def ml_loss_smooth_l1(left: Matrix, right: Matrix) -> Matrix: ...
def ml_loss_mse(left: Matrix, right: Matrix) -> Matrix: ...
def ml_loss_l1(left: Matrix, right: Matrix) -> Matrix: ...
def ml_loss_bce(left: Matrix, right: Matrix) -> Matrix: ...
def ml_loss_cross_entropy(left: Matrix, right: Matrix) -> Matrix: ...
def ml_loss_masked_cross_entropy(logits: Matrix, targets: Matrix, mask: Matrix,
	valid_count: int) -> Matrix: ...
def ml_metric_scalar_loss(loss: Matrix) -> float: ...
def ml_metric_accuracy(logits: Matrix, labels: Matrix) -> float: ...
def ml_byte_encode(engine: Engine, bytes: Sequence[int]) -> Matrix: ...
def ml_byte_encode_batched(engine: Engine, bytes: Sequence[int]) -> Matrix: ...
def ml_byte_encode_text(engine: Engine, text: str) -> Matrix: ...
def ml_byte_decode(logits: Matrix) -> list[int]: ...
def ml_byte_decode_text(logits: Matrix) -> str: ...
def ml_byte_sample(logits: Matrix, temperature: float, top_k: int,
	top_p: float, seed: int) -> list[int]: ...

def audio_decode_file(engine: Engine, path: str) -> Audio: ...
def audio_decode_memory(engine: Engine, encoded: Sequence[int]) -> Audio: ...
def audio_encode_wav_f32(input: Audio) -> bytes: ...
def audio_save_wav_f32(path: str, input: Audio) -> None: ...
def audio_normalize(input: Audio, target_db: float = -3.0, mode: str = "peak") -> Audio: ...
def audio_resample(input: Audio, out_rate: int, filter_half_width: int = 64) -> Audio: ...
def audio_gain(input: Audio, gain_db: float) -> Audio: ...
def audio_clip(input: Audio, minimum: float, maximum: float) -> Audio: ...
def audio_saturate(input: Audio, drive_db: float, mix: float) -> Audio: ...
def audio_reverb(input: Audio, decay_seconds: float, wet: float) -> Audio: ...
def audio_pre_emphasis(input: Audio, alpha: float) -> Audio: ...
def audio_to_mono(input: Audio) -> Audio: ...
def audio_fade(input: Audio, fade_in_samples: int, fade_out_samples: int) -> Audio: ...
def audio_mix(a: Audio, b: Audio, gain_a: float, gain_b: float) -> Audio: ...
def audio_amplitude_to_db(input: Audio, floor_db: float) -> Matrix: ...
def audio_waveform_envelope(input: Audio, bins: int) -> Matrix: ...
def audio_stft(input: Audio, fft_size: int = 1024, hop_size: int = 256,
	win_size: int = 0, window: str = "hann", center: bool = True) -> Matrix: ...
def audio_mel_spectrogram(input: Audio, fft_size: int = 1024, hop_size: int = 256,
	num_mels: int = 80, f_min: float = 0.0, f_max: float = 0.0,
	log_scale: bool = True, normalize: bool = False) -> Matrix: ...

def image_decode_file(engine: Engine, path: str, format_name: str) -> Image: ...
def image_decode_memory(engine: Engine, encoded: Sequence[int], format_name: str) -> Image: ...
def image_encode(input: Image, codec_name: str, quality: int = 90) -> bytes: ...
def image_save_file(path: str, input: Image, quality: int = 90) -> None: ...
def image_resize(input: Image, width: int, height: int,
	interpolation_name: str = "bilinear") -> Image: ...
def image_normalize(input: Image, mean: Sequence[float], std: Sequence[float]) -> Image: ...
def image_convert_color(input: Image, format_name: str) -> Image: ...
def image_crop(input: Image, x: int, y: int, width: int, height: int) -> Image: ...
def image_flip(input: Image, horizontal: bool, vertical: bool) -> Image: ...
def image_rotate(input: Image, degrees: int) -> Image: ...
def image_center_crop(input: Image, width: int, height: int) -> Image: ...
def image_pad(input: Image, left: int, right: int, top: int, bottom: int,
	border_name: str = "constant", border_value: float = 0.0) -> Image: ...
def image_grayscale(input: Image) -> Image: ...
def image_clamp(input: Image, low: float, high: float) -> Image: ...
def image_invert(input: Image, max_value: float = 1.0) -> Image: ...
def image_brightness_contrast(input: Image, brightness: float, contrast: float) -> Image: ...
def image_gaussian_blur(input: Image, sigma: float, kernel_size: int = 0) -> Image: ...
