// AUTO-GENERATED by Tools/NnAutogen/oannautogen.py - DO NOT EDIT.
// Source of truth: Tools/NnAutogen/Schema/Ml/MlNnUtility.toml.
// Regenerate via: python3 Tools/NnAutogen/oannautogen.py --live

#pragma once

#include <Oa/Ml/Module.h>
#include <Oa/Ml/NnType.h>

#include <initializer_list>

/// OaFlatten: Flatten layer with PyTorch-style start_dim/end_dim.
class OaFlatten : public OaModule {
public:
	explicit OaFlatten(OaI32 StartDim = 1, OaI32 EndDim = -1);
	OaMatrix Forward(const OaMatrix& InInput) override;

private:
	OaI32 StartDim_;
	OaI32 EndDim_;
};
