// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT.
// source of truth: tools/nnAutogen/schema/ml/mlNnConv.toml.
// Regenerate via: python3 tools/nnAutogen/oannautogen.py --live

#pragma once

#include <oa/ml/module.h>

#include <initializer_list>

namespace oa {

/// Conv1d: 1D convolution layer (im2col + GEMM).
class Conv1d : public Module {
public:
	Conv1d(oa::I32 inChannels, oa::I32 outChannels, oa::I32 kernelSize, oa::I32 inStride = 1, oa::I32 inPadding = 0, oa::I32 inDilation = 1);
	Matrix forward(const Matrix& inInput) override;
	[[nodiscard]] oa::I32 stride() const noexcept { return stride_; }
	[[nodiscard]] oa::I32 padding() const noexcept { return padding_; }
	[[nodiscard]] oa::I32 dilation() const noexcept { return dilation_; }

private:
	oa::I32 inChannels_;
	oa::I32 outChannels_;
	oa::I32 kernelSize_;
	oa::I32 stride_;
	oa::I32 padding_;
	oa::I32 dilation_;
};

} // namespace oa
