#pragma once

// HumanIk — the HumanIK characterization + UE mannequin reference poses.
// HumanIK is an Autodesk trademark; interop map only, not the Autodesk SDK — see NOTICE.md.
//
// HumanIK is the industry-standard retarget hub (MotionBuilder / Maya): a fixed
// set of named slots (Hips, Spine, LeftArm, …) that any skeleton is mapped onto,
// so motion can be transferred between rigs through the shared characterization.
//
// This is the data layer for Retarget: the slot ⇄ UE-node ⇄ HumanIK-id map
// (from oa3d's RTG_DEFINITION_UNREAL) and the per-mannequin tPose / aPose
// reference poses (from RTG_POSES_SKEL_MANNY / _QUINN). The reference pose is
// what a retarget needs to express each joint's animation *relative to its rest*
// in one rig and re-apply it in another. generated by
// Tools/Gen3dAnim/gen_rtg_pose_data.py into RtgPoseData.inc.

#include <core/joint.h>
#include <oa/core/types.h>

namespace oa {

enum class Mannequin { Manny, Quinn };
enum class PoseKind  { TPose, APose };

// One HumanIK characterization slot: the HumanIK name, its numeric id, and the
// UE bone it binds to on the mannequin.
struct HumanIkSlot {
	oa::String slot;     // HumanIK slot name, e.g. "LeftArm"
	oa::I32    id   = 0; // HumanIK slot id
	oa::String node;     // UE bone name, e.g. "upperarm_l"
};

// One joint's local reference transform within a named pose.
struct RefJoint {
	oa::String name;                                  // UE bone name
	oa::vlm::Quat   localOrient = { 0.0f, 0.0f, 0.0f, 1.0f }; // local orientation (from Maya XYZ)
	oa::vlm::Vec3   localTrans  = {};                       // local offset to parent (cm)
};

// A full reference pose (the 25 core body joints).
struct RefPose {
	oa::Vec<RefJoint> joints;

	// local reference orientation for a bone by name; identity if absent.
	[[nodiscard]] oa::vlm::Quat orientOf(oa::StringView inName) const noexcept;
};

// The HumanIK characterization for the UE mannequin (25 core slots).
[[nodiscard]] const oa::Vec<HumanIkSlot>& humanIkCharacterization();

// The reference pose for a mannequin + pose kind (manny/quinn × tPose/aPose).
[[nodiscard]] const RefPose& refPoseFor(Mannequin inWho, PoseKind inKind);

}  // namespace oa
