// AUTO-GENERATED by tools/gen/nn/generate.py - DO NOT EDIT.
// source of truth: tools/gen/nn/schema/ml/mlNnUtility.toml.
// Regenerate via: python3 tools/gen/nn/generate.py --live
// oa::Flatten - Flatten layer with PyTorch-style start_dim/end_dim.

#include <oa/ml/nn.h>
#include <oa/core/fnMatrix.h>
#include <oa/core/validation.h>

oa::Flatten::Flatten(oa::I32 inStartDim, oa::I32 inEndDim)
	: startDim_(inStartDim), endDim_(inEndDim) {

}

oa::Matrix oa::Flatten::forward(const oa::Matrix& inInput) {
	const oa::I32 rank = inInput.rank();
	if (rank <= 1) return inInput;

	oa::I32 startDim = startDim_ < 0 ? startDim_ + rank : startDim_;
	oa::I32 endDim = endDim_ < 0 ? endDim_ + rank : endDim_;
	if (startDim >= rank) return inInput;

	OA_ASSERT(startDim >= 0);
	OA_ASSERT(endDim >= 0);
	OA_ASSERT(startDim <= endDim);
	OA_ASSERT(endDim < rank);

	MatrixShape outShape;
	oa::I32 outRank = 0;
	for (oa::I32 dimIdx = 0; dimIdx < startDim; ++dimIdx) {
		outShape.dims[outRank++] = inInput.size(dimIdx);
	}

	oa::I64 flat = 1;
	for (oa::I32 dimIdx = startDim; dimIdx <= endDim; ++dimIdx) {
		flat *= inInput.size(dimIdx);
	}
	outShape.dims[outRank++] = flat;

	for (oa::I32 dimIdx = endDim + 1; dimIdx < rank; ++dimIdx) {
		outShape.dims[outRank++] = inInput.size(dimIdx);
	}
	outShape.rank = outRank;
	return inInput.view(outShape);
}
