// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT.
// source of truth: tools/nnAutogen/schema/ml/mlNnUtility.toml.
// Regenerate via: python3 tools/nnAutogen/oannautogen.py --live

#pragma once

#include <oa/ml/module.h>

#include <initializer_list>

namespace oa {

/// Identity: Identity passthrough layer.
class Identity : public Module {
public:
	Identity() = default;
	Matrix forward(const Matrix& inInput) override;
};

} // namespace oa
