// AUTO-GENERATED by Tools/NnAutogen/oannautogen.py - DO NOT EDIT.
// Source of truth: Tools/NnAutogen/Schema/Ml/MlNnContainer.toml.
// Regenerate via: python3 Tools/NnAutogen/oannautogen.py --live
// OaSequential - Sequential container that chains modules together.

#include <Oa/Ml/Nn.h>
#include <Oa/Core/FnMatrix.h>
#include <Oa/Core/Validation.h>

OaSequential::OaSequential(std::initializer_list<OaSharedPtr<OaModule>> InLayers) {
	for (const auto& layer : InLayers) {
		Add(layer);
	}
}

OaSequential& OaSequential::Add(OaSharedPtr<OaModule> InModule) {
	OaString name(OaString("layer_") + OaToString(static_cast<OaU32>(Children_.Size())));
	return Add(name, std::move(InModule));
}

OaSequential& OaSequential::Add(OaStringView InName, OaSharedPtr<OaModule> InModule) {
	RegisterModule(InName, std::move(InModule));
	return *this;
}
OaMatrix OaSequential::Forward(const OaMatrix& InInput) {
	OaMatrix x = InInput;
	for (auto& child : Children_) {
		x = child.Module->Forward(x);
	}
	return x;
}
