#!/usr/bin/env python3
"""Generate OA's bounded matmul implementation lattice from TOML.

The generator is stdlib-only and intentionally emits small include fragments:
CMake compile records, fixed-kernel rows/IDs, and runtime matmul metadata. The
Slang arithmetic remains in reviewed source templates.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

TOOLS_ROOT = Path(__file__).resolve().parents[1]
if str(TOOLS_ROOT) not in sys.path:
	sys.path.insert(0, str(TOOLS_ROOT))

from autogen_io import write_generated_text


REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA = REPO_ROOT / "tools/oaTile/schema/fp32Tiled.toml"
BF16_SCHEMA = REPO_ROOT / "tools/oaTile/schema/bf16Coop.toml"
BASE_SCHEMA = REPO_ROOT / "tools/oaTile/schema/base.toml"
SMALL_M_SCHEMA = REPO_ROOT / "tools/oaTile/schema/fp32SmallM.toml"
DEFAULT_OUT = REPO_ROOT / "tools/oaTile/output"
MARKER = "// AUTO-GENERATED by tools/oaTile/oatile.py -- DO NOT EDIT."


@dataclass(frozen=True)
class Epilogue:
	kind: str
	name: str
	local_id: int


@dataclass(frozen=True)
class Variant:
	name: str
	local_id: int
	tile_m: int
	tile_n: int
	tile_k: int
	thread_m: int
	thread_n: int
	workgroup: int
	group_m: int
	strided: bool
	epilogues: tuple[Epilogue, ...]

	@property
	def shared_bytes(self) -> int:
		return (self.tile_m + self.tile_n) * (self.tile_k + 1) * 4


@dataclass(frozen=True)
class CompiledVariant:
	name: str
	local_id: int
	geometry: Variant
	epilogue: str


@dataclass(frozen=True)
class SmallMVariant:
	name: str
	local_id: int
	outputs_per_group: int
	reduction_width: int
	workgroup: int
	max_m: int
	epilogues: tuple[Epilogue, ...]

	@property
	def shared_bytes(self) -> int:
		return self.workgroup * 4


@dataclass(frozen=True)
class CompiledSmallMVariant:
	name: str
	local_id: int
	geometry: SmallMVariant
	epilogue: str


@dataclass(frozen=True)
class BaseVariant:
	name: str
	source: str
	compile_group: str
	local_id: int
	public_id: bool
	kernel: str
	path: str
	precisions: tuple[str, str, str, str]
	tile_m: int
	tile_n: int
	tile_k: int
	workgroup: int
	requires_aligned: bool
	requires_transposed_b: bool
	supports_bias: bool
	supports_activation: bool
	dual_output: bool
	shared_bytes: int
	caps: str
	supports_arbitrary_layout: bool
	supports_batch: bool


@dataclass(frozen=True)
class CoopVariant:
	name: str
	kind: str
	act: int


@dataclass(frozen=True)
class CoopFamily:
	template: str
	kernel: str
	tile_m: int
	tile_n: int
	tile_k: int
	workgroup: int
	caps: str
	variants: tuple[CoopVariant, ...]


EPILOGUES = {
	"none": ("None", False, False),
	"bias": ("Bias", True, False),
	"bias_relu": ("BiasRelu", True, True),
	"bias_gelu": ("BiasGelu", True, True),
	"bias_silu": ("BiasSilu", True, True),
}

COOP_EPILOGUES = {
	"none": ("None", False, False, False),
	"bias": ("Bias", True, False, False),
	"bias_relu": ("BiasRelu", True, True, False),
	"bias_gelu": ("BiasGelu", True, True, False),
	"silu_dual": ("SiluDual", False, True, True),
	"bias_silu": ("BiasSilu", True, True, False),
}

BASE_COMPILE_GROUPS = {"standard", "coopvec"}
BASE_KERNELS = {"Naive", "StridedFp32", "CoopVec"}
BASE_PATHS = {"Standard", "CoopVec"}
BASE_PRECISIONS = {"Fp32", "Bf16"}


def load_base_schema(path: Path) -> tuple[int, int, list[BaseVariant], int]:
	raw_bytes = path.read_bytes()
	data = tomllib.loads(raw_bytes.decode("utf-8"))
	version = int(data.get("schema_version", 0))
	abi = int(data.get("generator_abi", 0))
	if version != 1 or abi <= 0:
		fail("unsupported base matmul schema contract")
	variants: list[BaseVariant] = []
	for index, item in enumerate(data.get("variant", [])):
		ctx = f"variant[{index}]"
		name = str(item.get("name", ""))
		source = str(item.get("source", ""))
		compile_group = str(item.get("compile_group", ""))
		precisions = tuple(map(str, item.get("precisions", [])))
		tile = tuple(map(int, item.get("tile", [])))
		if not name or not name.replace("_", "").isalnum() or not name[0].isalpha():
			fail(f"{ctx}: invalid name {name!r}")
		if compile_group not in BASE_COMPILE_GROUPS:
			fail(f"{ctx}: invalid compile_group {compile_group!r}")
		expected_prefix = "gemm/" if compile_group == "standard" else "util/"
		expected_basename = name[0].lower() + name[1:]
		if (not source.startswith(expected_prefix)
				or source.split("/")[-1] != expected_basename):
			fail(f"{ctx}: source must be {expected_prefix}{expected_basename}")
		if len(precisions) != 4 or any(p not in BASE_PRECISIONS for p in precisions):
			fail(f"{ctx}: precisions must contain four supported storage types")
		if len(tile) != 3 or min(tile) <= 0:
			fail(f"{ctx}: tile must contain three positive values")
		variant = BaseVariant(
			name=name,
			source=source,
			compile_group=compile_group,
			local_id=int(item.get("local_id", 0)),
			public_id=bool(item.get("public_id", False)),
			kernel=str(item.get("kernel", "")),
			path=str(item.get("path", "")),
			precisions=precisions,  # type: ignore[arg-type]
			tile_m=tile[0], tile_n=tile[1], tile_k=tile[2],
			workgroup=int(item.get("workgroup", 0)),
			requires_aligned=bool(item.get("requires_aligned", False)),
			requires_transposed_b=bool(item.get("requires_transposed_b", False)),
			supports_bias=bool(item.get("supports_bias", False)),
			supports_activation=bool(item.get("supports_activation", False)),
			dual_output=bool(item.get("dual_output", False)),
			shared_bytes=int(item.get("shared_bytes", 0)),
			caps=str(item.get("caps", "")),
			supports_arbitrary_layout=bool(item.get("supports_arbitrary_layout", False)),
			supports_batch=bool(item.get("supports_batch", False)),
		)
		if variant.local_id <= 0 or variant.workgroup <= 0 or variant.shared_bytes < 0:
			fail(f"{ctx}: ID/workgroup must be positive and shared_bytes non-negative")
		if variant.kernel not in BASE_KERNELS or variant.path not in BASE_PATHS or not variant.caps:
			fail(f"{ctx}: invalid kernel, path or capability contract")
		variants.append(variant)
	if not variants:
		fail("base matmul schema contains no variants")
	if len({v.name for v in variants}) != len(variants):
		fail("duplicate base variant name")
	if len({v.local_id for v in variants}) != len(variants):
		fail("duplicate base local_id")
	schema_hash = int.from_bytes(hashlib.sha256(raw_bytes).digest()[:8], "little")
	return version, abi, variants, schema_hash


def load_coop_schema(path: Path) -> tuple[int, int, list[CoopFamily], int]:
	raw_bytes = path.read_bytes()
	data = tomllib.loads(raw_bytes.decode("utf-8"))
	version = int(data.get("schema_version", 0))
	abi = int(data.get("generator_abi", 0))
	if version != 1 or abi <= 0:
		fail("unsupported BF16 cooperative-matrix schema contract")
	families: list[CoopFamily] = []
	all_names: set[str] = set()
	for index, item in enumerate(data.get("family", [])):
		tile = item.get("tile", [])
		if len(tile) != 3 or min(map(int, tile)) <= 0:
			fail(f"family[{index}]: tile must contain three positive values")
		variants: list[CoopVariant] = []
		for raw in item.get("variants", []):
			kind, name, act = str(raw.get("kind", "")), str(raw.get("name", "")), int(raw.get("act", -1))
			if kind not in COOP_EPILOGUES or not name or act < 0:
				fail(f"family[{index}]: invalid BF16 variant")
			if name in all_names:
				fail(f"duplicate BF16 variant name {name}")
			all_names.add(name)
			variants.append(CoopVariant(name, kind, act))
		family = CoopFamily(
			template=str(item.get("template", "")), kernel=str(item.get("kernel", "")),
			tile_m=int(tile[0]), tile_n=int(tile[1]), tile_k=int(tile[2]),
			workgroup=int(item.get("workgroup", 0)), caps=str(item.get("caps", "")),
			variants=tuple(variants))
		if not family.template or not family.kernel or not family.caps or family.workgroup <= 0 or not variants:
			fail(f"family[{index}]: incomplete BF16 family")
		families.append(family)
	if not families:
		fail("BF16 schema contains no families")
	schema_hash = int.from_bytes(hashlib.sha256(raw_bytes).digest()[:8], "little")
	return version, abi, families, schema_hash


def compiled_variants(variants: list[Variant]) -> list[CompiledVariant]:
	result: list[CompiledVariant] = []
	for variant in variants:
		result.append(CompiledVariant(
			name=variant.name, local_id=variant.local_id,
			geometry=variant, epilogue="none"))
		result.extend(CompiledVariant(
			name=epilogue.name, local_id=epilogue.local_id,
			geometry=variant, epilogue=epilogue.kind)
			for epilogue in variant.epilogues)
	return result


def compiled_small_m_variants(
	variants: list[SmallMVariant],
) -> list[CompiledSmallMVariant]:
	result: list[CompiledSmallMVariant] = []
	for variant in variants:
		result.append(CompiledSmallMVariant(
			name=variant.name, local_id=variant.local_id,
			geometry=variant, epilogue="none"))
		result.extend(CompiledSmallMVariant(
			name=epilogue.name, local_id=epilogue.local_id,
			geometry=variant, epilogue=epilogue.kind)
			for epilogue in variant.epilogues)
	return result


def fail(message: str) -> None:
	raise ValueError(message)


def load_schema(path: Path) -> tuple[int, int, list[Variant], int]:
	raw_bytes = path.read_bytes()
	data = tomllib.loads(raw_bytes.decode("utf-8"))
	schema_version = int(data.get("schema_version", 0))
	generator_abi = int(data.get("generator_abi", 0))
	if schema_version != 1:
		fail(f"unsupported schema_version={schema_version}")
	if generator_abi <= 0:
		fail("generator_abi must be positive")

	variants: list[Variant] = []
	for index, item in enumerate(data.get("variant", [])):
		ctx = f"variant[{index}]"
		base_name = str(item.get("name", ""))
		if not base_name or not base_name.replace("_", "").isalnum() or not base_name[0].isalpha():
			fail(f"{ctx}: invalid C++/shader name {base_name!r}")
		tile = item.get("tile", [])
		thread_tile = item.get("thread_tile", [])
		if len(tile) != 3 or len(thread_tile) != 2:
			fail(f"{ctx}: tile must have 3 values and thread_tile 2")
		epilogues: list[Epilogue] = []
		for epilogue_index, epilogue_item in enumerate(item.get("epilogues", [])):
			ectx = f"{ctx}.epilogues[{epilogue_index}]"
			kind = str(epilogue_item.get("kind", ""))
			epilogue_name = str(epilogue_item.get("name", ""))
			local_id = int(epilogue_item.get("local_id", 0))
			if kind == "none" or kind not in EPILOGUES:
				fail(f"{ectx}: unsupported epilogue kind {kind!r}")
			if not epilogue_name or not epilogue_name.replace("_", "").isalnum() or not epilogue_name[0].isalpha():
				fail(f"{ectx}: invalid C++/shader name {epilogue_name!r}")
			if local_id <= 0:
				fail(f"{ectx}: local_id must be positive")
			epilogues.append(Epilogue(kind=kind, name=epilogue_name, local_id=local_id))
		v = Variant(
			name=base_name,
			local_id=int(item.get("local_id", 0)),
			tile_m=int(tile[0]), tile_n=int(tile[1]), tile_k=int(tile[2]),
			thread_m=int(thread_tile[0]), thread_n=int(thread_tile[1]),
			workgroup=int(item.get("workgroup", 0)),
			group_m=int(item.get("group_m", 0)),
			strided=bool(item.get("strided", False)),
			epilogues=tuple(epilogues),
		)
		if min(v.local_id, v.tile_m, v.tile_n, v.tile_k,
		       v.thread_m, v.thread_n, v.workgroup) <= 0 or v.group_m < 0:
			fail(f"{ctx}: dimensions/IDs must be positive and group_m non-negative")
		if v.tile_m % v.thread_m or v.tile_n % v.thread_n:
			fail(f"{ctx}: tile must divide evenly into thread_tile")
		threads = (v.tile_m // v.thread_m) * (v.tile_n // v.thread_n)
		if threads != v.workgroup:
			fail(f"{ctx}: thread grid requires {threads}, schema says {v.workgroup}")
		for label, elements in (("A", v.tile_m * v.tile_k), ("B", v.tile_n * v.tile_k)):
			if elements % (v.workgroup * 4):
				fail(f"{ctx}: {label} tile cannot be distributed as float4 loads")
		if v.tile_k % 4:
			fail(f"{ctx}: tile_k must be a multiple of four")
		if v.strided and v.epilogues:
			fail(f"{ctx}: strided variants do not yet admit fused epilogues")
		variants.append(v)

	if not variants:
		fail("schema contains no variants")
	compiled = compiled_variants(variants)
	if len({v.name for v in compiled}) != len(compiled):
		fail("duplicate variant name")
	if len({v.local_id for v in compiled}) != len(compiled):
		fail("duplicate local_id")
	schema_hash = int.from_bytes(hashlib.sha256(raw_bytes).digest()[:8], "little")
	return schema_version, generator_abi, variants, schema_hash


def load_small_m_schema(
	path: Path,
) -> tuple[int, int, list[SmallMVariant], int]:
	raw_bytes = path.read_bytes()
	data = tomllib.loads(raw_bytes.decode("utf-8"))
	version = int(data.get("schema_version", 0))
	abi = int(data.get("generator_abi", 0))
	if version != 1 or abi <= 0:
		fail("unsupported small-M matmul schema contract")

	variants: list[SmallMVariant] = []
	for index, item in enumerate(data.get("variant", [])):
		ctx = f"variant[{index}]"
		name = str(item.get("name", ""))
		if not name or not name.replace("_", "").isalnum() or not name[0].isalpha():
			fail(f"{ctx}: invalid small-M variant name {name!r}")
		epilogues: list[Epilogue] = []
		for epilogue_index, epilogue_item in enumerate(item.get("epilogues", [])):
			ectx = f"{ctx}.epilogues[{epilogue_index}]"
			kind = str(epilogue_item.get("kind", ""))
			epilogue_name = str(epilogue_item.get("name", ""))
			local_id = int(epilogue_item.get("local_id", 0))
			if kind == "none" or kind not in EPILOGUES:
				fail(f"{ectx}: unsupported epilogue kind {kind!r}")
			if (not epilogue_name
				or not epilogue_name.replace("_", "").isalnum()
				or not epilogue_name[0].isalpha()
				or local_id <= 0):
				fail(f"{ectx}: invalid name or local_id")
			epilogues.append(Epilogue(kind, epilogue_name, local_id))
		variant = SmallMVariant(
			name=name,
			local_id=int(item.get("local_id", 0)),
			outputs_per_group=int(item.get("outputs_per_group", 0)),
			reduction_width=int(item.get("reduction_width", 0)),
			workgroup=int(item.get("workgroup", 0)),
			max_m=int(item.get("max_m", 0)),
			epilogues=tuple(epilogues),
		)
		if min(variant.local_id, variant.outputs_per_group,
		       variant.reduction_width, variant.workgroup, variant.max_m) <= 0:
			fail(f"{ctx}: dimensions and IDs must be positive")
		if variant.reduction_width & (variant.reduction_width - 1):
			fail(f"{ctx}: reduction_width must be a power of two")
		if variant.workgroup != (
			variant.outputs_per_group * variant.reduction_width
		):
			fail(f"{ctx}: workgroup must equal outputs_per_group * reduction_width")
		if variant.workgroup > 1024:
			fail(f"{ctx}: workgroup exceeds the Vulkan maximum")
		variants.append(variant)
	if not variants:
		fail("small-M matmul schema contains no variants")
	compiled = compiled_small_m_variants(variants)
	if len({v.name for v in compiled}) != len(compiled):
		fail("duplicate small-M variant name")
	if len({v.local_id for v in compiled}) != len(compiled):
		fail("duplicate small-M local_id")
	schema_hash = int.from_bytes(hashlib.sha256(raw_bytes).digest()[:8], "little")
	return version, abi, variants, schema_hash


def generated_header(schema_rel: str) -> list[str]:
	return [MARKER, f"// Source of truth: {schema_rel}", ""]


def generated_header_many(schema_rels: tuple[str, ...]) -> list[str]:
	return [MARKER, "// Sources of truth:", *(f"// - {path}" for path in schema_rels), ""]


def emit_base_cmake(variants: list[BaseVariant], schema_rel: str) -> str:
	lines = [
		"# AUTO-GENERATED by tools/oaTile/oatile.py -- DO NOT EDIT.",
		f"# Source of truth: {schema_rel}",
		"",
	]
	for group, variable in (
		("standard", "OA_BLAS_GEMM_KERNEL"),
		("coopvec", "OA_BLAS_UTIL_KERNEL"),
	):
		group_variants = [v for v in variants if v.compile_group == group]
		lines.append(f"set({variable}_NAMES")
		lines.extend(f"\t{v.name}" for v in group_variants)
		lines.append(")")
		lines.append(f"set({variable}_SOURCES")
		lines.extend(f"\t{v.source}" for v in group_variants)
		lines.append(")")
	return "\n".join(lines) + "\n"


def emit_cmake(variants: list[Variant], schema_rel: str) -> str:
	lines = [
		"# AUTO-GENERATED by tools/oaTile/oatile.py -- DO NOT EDIT.",
		f"# Source of truth: {schema_rel}",
		"",
	]
	compiled = compiled_variants(variants)
	fields = {
		"NAMES": [v.name for v in compiled],
		"IDS": [str(v.local_id) for v in compiled],
		"TILE_M": [str(v.geometry.tile_m) for v in compiled],
		"TILE_N": [str(v.geometry.tile_n) for v in compiled],
		"TILE_K": [str(v.geometry.tile_k) for v in compiled],
		"THREAD_M": [str(v.geometry.thread_m) for v in compiled],
		"THREAD_N": [str(v.geometry.thread_n) for v in compiled],
		"WORKGROUP": [str(v.geometry.workgroup) for v in compiled],
		"GROUP_M": [str(v.geometry.group_m) for v in compiled],
		"STRIDED": ["1" if v.geometry.strided else "0" for v in compiled],
		"EPILOGUE": [str(list(EPILOGUES).index(v.epilogue)) for v in compiled],
	}
	for suffix, values in fields.items():
		lines.append(f"set(OA_TILE_FP32_{suffix}")
		lines.extend(f"\t{value}" for value in values)
		lines.append(")")
	return "\n".join(lines) + "\n"


def emit_small_m_cmake(
	variants: list[SmallMVariant], schema_rel: str,
) -> str:
	lines = [
		"# AUTO-GENERATED by tools/oaTile/oatile.py -- DO NOT EDIT.",
		f"# Source of truth: {schema_rel}",
		"",
	]
	compiled = compiled_small_m_variants(variants)
	fields = {
		"NAMES": [v.name for v in compiled],
		"IDS": [str(v.local_id) for v in compiled],
		"OUTPUTS": [str(v.geometry.outputs_per_group) for v in compiled],
		"REDUCTION": [str(v.geometry.reduction_width) for v in compiled],
		"WORKGROUP": [str(v.geometry.workgroup) for v in compiled],
		"MAX_M": [str(v.geometry.max_m) for v in compiled],
		"EPILOGUE": [str(list(EPILOGUES).index(v.epilogue)) for v in compiled],
	}
	for suffix, values in fields.items():
		lines.append(f"set(OA_TILE_SMALL_M_{suffix}")
		lines.extend(f"\t{value}" for value in values)
		lines.append(")")
	return "\n".join(lines) + "\n"


def emit_kernel_rows(
	variants: list[Variant], small_m_variants: list[SmallMVariant],
	base_variants: list[BaseVariant], schema_rels: tuple[str, str, str],
) -> str:
	lines = generated_header_many(schema_rels)
	for v in base_variants:
		lines.append(
			f'\t{{ "{v.name}", OA_COMPUTE_KERNEL_ID(oa::computeKernelPrefix::Ml, '
			f'{v.local_id}), oa::ComputeKernelCategory::Ml, "oa" }},')
	for v in compiled_variants(variants):
		lines.append(
			f'\t{{ "{v.name}", OA_COMPUTE_KERNEL_ID(oa::computeKernelPrefix::Ml, '
			f'{v.local_id}), oa::ComputeKernelCategory::Ml, "oa" }},')
	for v in compiled_small_m_variants(small_m_variants):
		lines.append(
			f'\t{{ "{v.name}", OA_COMPUTE_KERNEL_ID(oa::computeKernelPrefix::Ml, '
			f'{v.local_id}), oa::ComputeKernelCategory::Ml, "oa" }},')
	return "\n".join(lines) + "\n"


def emit_compute_ids(
	variants: list[Variant], small_m_variants: list[SmallMVariant],
	base_variants: list[BaseVariant], schema_rels: tuple[str, str, str],
) -> str:
	lines = generated_header_many(schema_rels)
	for v in base_variants:
		if v.public_id:
			lines.append(
				f"static constexpr oa::U64 {v.name} = "
				f"OA_COMPUTE_KERNEL_ID(oa::computeKernelPrefix::Ml, {v.local_id});")
	for v in compiled_variants(variants):
		lines.append(
			f"static constexpr oa::U64 {v.name} = "
			f"OA_COMPUTE_KERNEL_ID(oa::computeKernelPrefix::Ml, {v.local_id});")
	for v in compiled_small_m_variants(small_m_variants):
		lines.append(
			f"static constexpr oa::U64 {v.name} = "
			f"OA_COMPUTE_KERNEL_ID(oa::computeKernelPrefix::Ml, {v.local_id});")
	return "\n".join(lines) + "\n"


def validate_combined_kernel_identities(
	base_variants: list[BaseVariant], variants: list[Variant],
	small_m_variants: list[SmallMVariant],
) -> None:
	records = [
		*((v.name, v.local_id) for v in base_variants),
		*((v.name, v.local_id) for v in compiled_variants(variants)),
		*((v.name, v.local_id) for v in compiled_small_m_variants(small_m_variants)),
	]
	for field_index, label in ((0, "name"), (1, "local_id")):
		values = [record[field_index] for record in records]
		if len(set(values)) != len(values):
			fail(f"duplicate OaTile {label} across generated manifests")


def emit_base_rows(variants: list[BaseVariant], schema_rel: str) -> str:
	lines = generated_header(schema_rel)
	for v in variants:
		a, b, output, accumulator = v.precisions
		lines.extend([
			f'\t{{oa::matmulVariantIdFromName("{v.name}"), "{v.name}",',
			f"\t oa::GemmKernel::{v.kernel}, oa::GemmPath::{v.path}, oa::GemmEpilogue::None,",
			f"\t oa::StoragePrecision::{a}, oa::StoragePrecision::{b},",
			f"\t oa::StoragePrecision::{output}, oa::StoragePrecision::{accumulator},",
			f"\t {v.tile_m}, {v.tile_n}, {v.tile_k}, {v.workgroup},",
			f"\t {str(v.requires_aligned).lower()}, {str(v.requires_transposed_b).lower()}, "
			f"{str(v.supports_bias).lower()}, {str(v.supports_activation).lower()}, "
			f"{str(v.dual_output).lower()}, {v.shared_bytes},",
			f"\t {v.caps}, {str(v.supports_arbitrary_layout).lower()}, "
			f"{str(v.supports_batch).lower()}}},",
			"",
		])
	if lines and lines[-1] == "":
		lines.pop()
	return "\n".join(lines) + "\n"


def emit_matmul_rows(variants: list[Variant], schema_rel: str) -> str:
	lines = generated_header(schema_rel)
	for v in compiled_variants(variants):
		ep_name, supports_bias, supports_activation = EPILOGUES[v.epilogue]
		geometry = v.geometry
		kernel = "StridedTiledFp32" if geometry.strided else "TiledFp32"
		lines.extend([
			f'\t{{oa::matmulVariantIdFromName("{v.name}"), "{v.name}",',
			f"\t oa::GemmKernel::{kernel}, oa::GemmPath::Standard, oa::GemmEpilogue::{ep_name},",
			"\t oa::StoragePrecision::Fp32, oa::StoragePrecision::Fp32,",
			"\t oa::StoragePrecision::Fp32, oa::StoragePrecision::Fp32,",
			f"\t {geometry.tile_m}, {geometry.tile_n}, {geometry.tile_k}, {geometry.workgroup},",
			f"\t false, {str(not geometry.strided).lower()}, {str(supports_bias).lower()}, "
			f"{str(supports_activation).lower()}, false, {geometry.shared_bytes},",
			f"\t kCapTiledFp32, {str(geometry.strided).lower()}, "
			f"{str(geometry.strided).lower()}}},",
			"",
		])
	if lines and lines[-1] == "":
		lines.pop()
	return "\n".join(lines) + "\n"


def emit_small_m_rows(
	variants: list[SmallMVariant], schema_rel: str,
) -> str:
	lines = generated_header(schema_rel)
	for v in compiled_small_m_variants(variants):
		ep_name, supports_bias, supports_activation = EPILOGUES[v.epilogue]
		geometry = v.geometry
		lines.extend([
			f'\t{{oa::matmulVariantIdFromName("{v.name}"), "{v.name}",',
			f"\t oa::GemmKernel::SmallMFp32, oa::GemmPath::Standard, oa::GemmEpilogue::{ep_name},",
			"\t oa::StoragePrecision::Fp32, oa::StoragePrecision::Fp32,",
			"\t oa::StoragePrecision::Fp32, oa::StoragePrecision::Fp32,",
			f"\t 1, {geometry.outputs_per_group}, {geometry.reduction_width}, {geometry.workgroup},",
			f"\t false, true, {str(supports_bias).lower()}, "
			f"{str(supports_activation).lower()}, false, {geometry.shared_bytes},",
			f"\t kCapTiledFp32, false, false, {geometry.max_m}}},",
			"",
		])
	if lines and lines[-1] == "":
		lines.pop()
	return "\n".join(lines) + "\n"


def emit_metadata(schema_version: int, generator_abi: int, schema_hash: int,
	              schema_rel: str) -> str:
	lines = generated_header(schema_rel)
	lines.extend([
		"namespace oa {",
		f"inline constexpr U32 tileFp32SchemaVersion = {schema_version}U;",
		f"inline constexpr U32 tileGeneratorAbi = {generator_abi}U;",
		f"inline constexpr U64 tileFp32SchemaHash = 0x{schema_hash:016x}ULL;",
		"} // namespace oa",
	])
	return "\n".join(lines) + "\n"


def emit_small_m_metadata(
	version: int, abi: int, schema_hash: int, schema_rel: str,
) -> str:
	lines = generated_header(schema_rel)
	lines.extend([
		"namespace oa {",
		f"inline constexpr U32 tileSmallMSchemaVersion = {version}U;",
		f"inline constexpr U32 tileSmallMGeneratorAbi = {abi}U;",
		f"inline constexpr U64 tileSmallMSchemaHash = 0x{schema_hash:016x}ULL;",
		"} // namespace oa",
	])
	return "\n".join(lines) + "\n"


def emit_base_metadata(schema_version: int, generator_abi: int, schema_hash: int,
	                   schema_rel: str) -> str:
	lines = generated_header(schema_rel)
	lines.extend([
		"namespace oa {",
		f"inline constexpr U32 tileBaseSchemaVersion = {schema_version}U;",
		f"inline constexpr U32 tileBaseGeneratorAbi = {generator_abi}U;",
		f"inline constexpr U64 tileBaseSchemaHash = 0x{schema_hash:016x}ULL;",
		"} // namespace oa",
	])
	return "\n".join(lines) + "\n"


def emit_coop_cmake(families: list[CoopFamily], schema_rel: str) -> str:
	lines = ["# AUTO-GENERATED by tools/oaTile/oatile.py -- DO NOT EDIT.",
		f"# Source of truth: {schema_rel}", ""]
	for family in families:
		var = "OA_GEMM_BF16_VARIANTS" if family.template == "GemmCmSgBf16" else "OA_GEMM_WG_BF16_VARIANTS"
		lines.append(f"set({var}")
		for variant in family.variants:
			lines.append(f'\t"{variant.name}" "{variant.act}"')
		lines.append(")")
	return "\n".join(lines) + "\n"


def emit_coop_rows(families: list[CoopFamily], schema_rel: str) -> str:
	lines = generated_header(schema_rel)
	for family in families:
		for variant in family.variants:
			ep, bias, activation, dual = COOP_EPILOGUES[variant.kind]
			lines.extend([
				f'\t{{oa::matmulVariantIdFromName("{variant.name}"), "{variant.name}",',
				f"\t oa::GemmKernel::{family.kernel}, oa::GemmPath::Standard, oa::GemmEpilogue::{ep},",
				"\t oa::StoragePrecision::Bf16, oa::StoragePrecision::Bf16,",
				"\t oa::StoragePrecision::Fp32, oa::StoragePrecision::Fp32,",
				f"\t {family.tile_m}, {family.tile_n}, {family.tile_k}, {family.workgroup},",
				f"\t false, true, {str(bias).lower()}, {str(activation).lower()}, {str(dual).lower()}, 0,",
				f"\t {family.caps}}},", ""])
	if lines and lines[-1] == "":
		lines.pop()
	return "\n".join(lines) + "\n"


def emit_coop_metadata(version: int, abi: int, schema_hash: int, schema_rel: str) -> str:
	lines = generated_header(schema_rel)
	lines.extend([
		"namespace oa {",
		f"inline constexpr U32 tileBf16SchemaVersion = {version}U;",
		f"inline constexpr U32 tileBf16GeneratorAbi = {abi}U;",
		f"inline constexpr U64 tileBf16SchemaHash = 0x{schema_hash:016x}ULL;",
		"} // namespace oa",
	])
	return "\n".join(lines) + "\n"


def write(path: Path, content: str, dry_run: bool) -> None:
	if dry_run:
		print(path)
		return
	write_generated_text(path, content)
	print(f"wrote {path.relative_to(REPO_ROOT) if path.is_relative_to(REPO_ROOT) else path}")


def main() -> int:
	parser = argparse.ArgumentParser(description="Generate OaTile matmul variants")
	parser.add_argument("--schema", type=Path, default=SCHEMA)
	parser.add_argument("--bf16-schema", type=Path, default=BF16_SCHEMA)
	parser.add_argument("--base-schema", type=Path, default=BASE_SCHEMA)
	parser.add_argument("--small-m-schema", type=Path, default=SMALL_M_SCHEMA)
	parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
	parser.add_argument("--live", action="store_true", help="write generated files into the repo Source tree")
	parser.add_argument("--dry-run", action="store_true")
	args = parser.parse_args()
	out = REPO_ROOT if args.live else args.out.resolve()
	schema = args.schema.resolve()
	schema_version, generator_abi, variants, schema_hash = load_schema(schema)
	schema_rel = schema.relative_to(REPO_ROOT).as_posix()
	bf16_schema = args.bf16_schema.resolve()
	bf16_version, bf16_abi, bf16_families, bf16_hash = load_coop_schema(bf16_schema)
	bf16_rel = bf16_schema.relative_to(REPO_ROOT).as_posix()
	base_schema = args.base_schema.resolve()
	base_version, base_abi, base_variants, base_hash = load_base_schema(base_schema)
	base_rel = base_schema.relative_to(REPO_ROOT).as_posix()
	small_m_schema = args.small_m_schema.resolve()
	small_m_version, small_m_abi, small_m_variants, small_m_hash = (
		load_small_m_schema(small_m_schema)
	)
	small_m_rel = small_m_schema.relative_to(REPO_ROOT).as_posix()
	validate_combined_kernel_identities(
		base_variants, variants, small_m_variants)

	outputs = {
		Path("source/cpp/lib/oa/core/shader/compute/blas/tile/oaTileBaseVariants.gen.cmake"):
			emit_base_cmake(base_variants, base_rel),
		Path("source/cpp/lib/oa/core/shader/compute/blas/tile/oaTileFp32Variants.gen.cmake"):
			emit_cmake(variants, schema_rel),
		Path("source/cpp/lib/oa/core/shader/compute/blas/tile/oaTileSmallMVariants.gen.cmake"):
			emit_small_m_cmake(small_m_variants, small_m_rel),
		Path("source/cpp/lib/oa/runtime/oaTileKernelRegistry.gen.inc"):
			emit_kernel_rows(variants, small_m_variants, base_variants,
				(base_rel, schema_rel, small_m_rel)),
		Path("source/cpp/include/oa/runtime/oaTileComputeKernel.gen.h"):
			emit_compute_ids(variants, small_m_variants, base_variants,
				(base_rel, schema_rel, small_m_rel)),
		Path("source/cpp/lib/oa/runtime/gemm/oaTileBaseVariants.gen.inc"):
			emit_base_rows(base_variants, base_rel),
		Path("source/cpp/lib/oa/runtime/gemm/oaTileFp32Variants.gen.inc"):
			emit_matmul_rows(variants, schema_rel),
		Path("source/cpp/lib/oa/runtime/gemm/oaTileSmallMVariants.gen.inc"):
			emit_small_m_rows(small_m_variants, small_m_rel),
		Path("source/cpp/lib/oa/runtime/gemm/oaTileBaseMetadata.gen.h"):
			emit_base_metadata(base_version, base_abi, base_hash, base_rel),
		Path("source/cpp/lib/oa/runtime/gemm/oaTileMetadata.gen.h"):
			emit_metadata(schema_version, generator_abi, schema_hash, schema_rel),
		Path("source/cpp/lib/oa/runtime/gemm/oaTileSmallMMetadata.gen.h"):
			emit_small_m_metadata(
				small_m_version, small_m_abi, small_m_hash, small_m_rel),
		Path("source/cpp/lib/oa/core/shader/compute/blas/tile/oaTileBf16Variants.gen.cmake"):
			emit_coop_cmake(bf16_families, bf16_rel),
		Path("source/cpp/lib/oa/runtime/gemm/oaTileBf16Variants.gen.inc"):
			emit_coop_rows(bf16_families, bf16_rel),
		Path("source/cpp/lib/oa/runtime/gemm/oaTileBf16Metadata.gen.h"):
			emit_coop_metadata(bf16_version, bf16_abi, bf16_hash, bf16_rel),
	}
	for rel, content in outputs.items():
		write(out / rel, content, args.dry_run)
	return 0


if __name__ == "__main__":
	try:
		sys.exit(main())
	except (OSError, ValueError, tomllib.TOMLDecodeError) as exc:
		print(f"oatile: {exc}", file=sys.stderr)
		sys.exit(1)
