// @generated by tool/gen/fn/generate.py; DO NOT EDIT.
// schemas=matrix_elemwise.json,matrix_blas.json,matrix_reduce.json,matrix_rng.json,matrix_index.json,matrix_view.json schema_version=1 generator_version=64
// schema_sha256=7b6f6f1da1e8c37efaa239e33a5b8f167641366950074285aaec120d979c658f
pub(in crate::matrix) use matrix::{
	record_abs, record_add, record_clamp_max, record_clamp_min, record_concat, record_copy,
	record_div, record_dropout, record_exp, record_gather, record_gather_last_dim, record_log,
	record_log_softmax, record_mat_mul_nt, record_mul, record_reciprocal, record_repeat_interleave,
	record_reshape, record_scale, record_slice, record_softmax, record_sqrt, record_sub, record_sum,
	record_transpose,
};
