// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/Ml/MlFnMatrixActivation.toml.
//
// Tests for context-backed public overloads.
// The public overload test doubles as the kernel correctness test —
// it calls OaFnMatrix::<Op>(...) which dispatches the SPIR-V kernel directly.
// CPU references come from each op's `forward_op` field.

#include <gtest/gtest.h>
#include <Oa/Core/FnMatrix.h>
#include <Oa/Ml/FnMatrix.h>
#include <Oa/Runtime/Engine.h>
#include <Oa/Runtime/Context.h>
#include <Oa/Runtime/ComputeGraph.h>
#include <algorithm>
#include <cmath>
#include <numeric>
#include <vector>

static OaComputeEngine* GRt = nullptr;

class TestFnMatrixActivation : public ::testing::Test {
protected:
	static void SetUpTestSuite() {
		OaEngineConfig cfg{};
		cfg.AppName = "TestFnMatrixActivation";
		auto r = OaComputeEngine::Create(cfg);
		ASSERT_TRUE(r.IsOk()) << r.GetStatus().GetMessage();
		static OaUniquePtr<OaComputeEngine> rt = std::move(*r);
		GRt = rt.get();
	}
};

TEST_VK(TestFnMatrixActivation, Gelu_Context) {
	constexpr OaU32 N = 256;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::Gelu(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	std::vector<float> want(N);
	for (OaU32 i = 0; i < N; ++i) want[i] = 0.5f * a_host[i] * (1.0f + std::tanh(0.7978845608f * (a_host[i] + 0.044715f * a_host[i] * a_host[i] * a_host[i])));
	std::vector<float> got(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, got.data(), N * sizeof(float)).IsOk());
	for (OaU32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], 1e-3f) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, Silu_Context) {
	constexpr OaU32 N = 256;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::Silu(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	std::vector<float> want(N);
	for (OaU32 i = 0; i < N; ++i) want[i] = a_host[i] / (1.0f + std::exp(-a_host[i]));
	std::vector<float> got(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, got.data(), N * sizeof(float)).IsOk());
	for (OaU32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], 1e-3f) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, Relu_Context) {
	constexpr OaU32 N = 256;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::Relu(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	std::vector<float> want(N);
	for (OaU32 i = 0; i < N; ++i) want[i] = std::max(a_host[i], 0.0f);
	std::vector<float> got(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, got.data(), N * sizeof(float)).IsOk());
	for (OaU32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], 1e-4f) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, Tanh_Context) {
	constexpr OaU32 N = 256;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::Tanh(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	std::vector<float> want(N);
	for (OaU32 i = 0; i < N; ++i) want[i] = std::tanh(a_host[i]);
	std::vector<float> got(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, got.data(), N * sizeof(float)).IsOk());
	for (OaU32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], 1e-3f) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, Sigmoid_Context) {
	constexpr OaU32 N = 256;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::Sigmoid(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	std::vector<float> want(N);
	for (OaU32 i = 0; i < N; ++i) want[i] = 1.0f / (1.0f + std::exp(-a_host[i]));
	std::vector<float> got(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, got.data(), N * sizeof(float)).IsOk());
	for (OaU32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], 1e-3f) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, LeakyRelu_Context) {
	constexpr OaU32 N = 256;
	constexpr OaF32 kScalar = 0.01f;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::LeakyRelu(a, kScalar);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	std::vector<float> want(N);
	for (OaU32 i = 0; i < N; ++i) want[i] = std::max(kScalar * a_host[i], a_host[i]);
	std::vector<float> got(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, got.data(), N * sizeof(float)).IsOk());
	for (OaU32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], 1e-4f) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, Elu_Context) {
	constexpr OaU32 N = 256;
	constexpr OaF32 kScalar = 1.0f;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::Elu(a, kScalar);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	std::vector<float> want(N);
	for (OaU32 i = 0; i < N; ++i) want[i] = a_host[i] > 0.0f ? a_host[i] : kScalar * (std::exp(a_host[i]) - 1.0f);
	std::vector<float> got(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, got.data(), N * sizeof(float)).IsOk());
	for (OaU32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], 1e-3f) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, Mish_Context) {
	constexpr OaU32 N = 256;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::Mish(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	std::vector<float> want(N);
	for (OaU32 i = 0; i < N; ++i) want[i] = a_host[i] * std::tanh(std::log(1.0f + std::exp(a_host[i])));
	std::vector<float> got(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, got.data(), N * sizeof(float)).IsOk());
	for (OaU32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], 1e-3f) << "i=" << i;
}

TEST_VK(TestFnMatrixActivation, Softplus_Context) {
	constexpr OaU32 N = 256;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::Softplus(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	std::vector<float> want(N);
	for (OaU32 i = 0; i < N; ++i) want[i] = std::max(a_host[i], 0.0f) + std::log(1.0f + std::exp(-std::abs(a_host[i])));
	std::vector<float> got(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, got.data(), N * sizeof(float)).IsOk());
	for (OaU32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], 1e-3f) << "i=" << i;
}

