// @generated by tools/gen/fn/generate.py; DO NOT EDIT.
// schema=matrix_elemwise.json schema_version=1 generator_version=52
// schema_sha256=0099910a1b1fed2e756d57ed7fbe60abc9cb191c511a24fe532a0c3d28f95b2d

const ELEMENT_COUNT: usize = 257;

fn repeated<T: Copy>(values: &[T]) -> Vec<T> {
	(0..ELEMENT_COUNT)
		.map(|index| values[index % values.len()])
		.collect()
}

fn assert_close(actual: &[f32], expected: &[f32], tolerance: f32) {
	assert_eq!(actual.len(), expected.len());
	for (index, (actual, expected)) in actual.iter().zip(expected).enumerate() {
		let error = (actual - expected).abs();
		assert!(
			error <= tolerance,
			"element {index}: expected {expected}, found {actual}, error {error} exceeds {tolerance}"
		);
	}
}

test_vk!(
	generated_elementwise_dtype_variants_match_schema_oracles,
	engine,
	{
		let add_f32_left = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let add_f32_right = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0x3e800000),
				f32::from_bits(0x40000000),
				f32::from_bits(0xc0400000),
			]),
		)?;
		let add_f32_actual: Vec<f32> = oa::matrix::add(&add_f32_left, &add_f32_right)?.read()?;
		assert_close(
			&add_f32_actual,
			&repeated(&[
				f32::from_bits(0xbfe00000),
				f32::from_bits(0x40200000),
				f32::from_bits(0x3f800000),
			]),
			f32::from_bits(0x38d1b717),
		);

		let add_i32_left = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[2147483647_i32, -2147483648_i32, -2_i32]),
		)?;
		let add_i32_right =
			oa::Matrix::from_slice(&engine, [ELEMENT_COUNT], &repeated(&[1_i32, -1_i32, 7_i32]))?;
		let add_i32_actual: Vec<i32> = oa::matrix::add(&add_i32_left, &add_i32_right)?.read()?;
		assert_eq!(
			add_i32_actual,
			repeated(&[-2147483648_i32, 2147483647_i32, 5_i32])
		);

		let sub_f32_left = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let sub_f32_right = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0x3e800000),
				f32::from_bits(0x40000000),
				f32::from_bits(0xc0400000),
			]),
		)?;
		let sub_f32_actual: Vec<f32> = oa::matrix::sub(&sub_f32_left, &sub_f32_right)?.read()?;
		assert_close(
			&sub_f32_actual,
			&repeated(&[
				f32::from_bits(0xc0100000),
				f32::from_bits(0xbfc00000),
				f32::from_bits(0x40e00000),
			]),
			f32::from_bits(0x38d1b717),
		);

		let mul_f32_left = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let mul_f32_right = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0x3e800000),
				f32::from_bits(0x40000000),
				f32::from_bits(0xc0400000),
			]),
		)?;
		let mul_f32_actual: Vec<f32> = oa::matrix::mul(&mul_f32_left, &mul_f32_right)?.read()?;
		assert_close(
			&mul_f32_actual,
			&repeated(&[
				f32::from_bits(0xbf000000),
				f32::from_bits(0x3f800000),
				f32::from_bits(0xc1400000),
			]),
			f32::from_bits(0x38d1b717),
		);

		let div_f32_left = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let div_f32_right = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0x3e800000),
				f32::from_bits(0x40000000),
				f32::from_bits(0xc0400000),
			]),
		)?;
		let div_f32_actual: Vec<f32> = oa::matrix::div(&div_f32_left, &div_f32_right)?.read()?;
		assert_close(
			&div_f32_actual,
			&repeated(&[
				f32::from_bits(0xc1000000),
				f32::from_bits(0x3e800000),
				f32::from_bits(0xbfaaaaab),
			]),
			f32::from_bits(0x38d1b717),
		);

		let scale_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let scale_f32_actual: Vec<f32> =
			oa::matrix::scale(&scale_f32_input, f32::from_bits(0x3fc00000))?.read()?;
		assert_close(
			&scale_f32_actual,
			&repeated(&[
				f32::from_bits(0xc0400000),
				f32::from_bits(0x3f400000),
				f32::from_bits(0x40c00000),
			]),
			f32::from_bits(0x38d1b717),
		);

		let neg_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let neg_f32_actual: Vec<f32> = oa::matrix::neg(&neg_f32_input)?.read()?;
		assert_close(
			&neg_f32_actual,
			&repeated(&[
				f32::from_bits(0x40000000),
				f32::from_bits(0xbf000000),
				f32::from_bits(0xc0800000),
			]),
			f32::from_bits(0x38d1b717),
		);

		let abs_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let abs_f32_actual: Vec<f32> = oa::matrix::abs(&abs_f32_input)?.read()?;
		assert_close(
			&abs_f32_actual,
			&repeated(&[
				f32::from_bits(0x40000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
			f32::from_bits(0x38d1b717),
		);

		let log_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0x3e800000),
				f32::from_bits(0x3f800000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let log_f32_actual: Vec<f32> = oa::matrix::log(&log_f32_input)?.read()?;
		assert_close(
			&log_f32_actual,
			&repeated(&[
				f32::from_bits(0xbfb17218),
				f32::from_bits(0x00000000),
				f32::from_bits(0x3fb17218),
			]),
			f32::from_bits(0x3a83126f),
		);

		let sqrt_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0x3e800000),
				f32::from_bits(0x3f800000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let sqrt_f32_actual: Vec<f32> = oa::matrix::sqrt(&sqrt_f32_input)?.read()?;
		assert_close(
			&sqrt_f32_actual,
			&repeated(&[
				f32::from_bits(0x3f000000),
				f32::from_bits(0x3f800000),
				f32::from_bits(0x40000000),
			]),
			f32::from_bits(0x3a83126f),
		);

		let pow_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0x3e800000),
				f32::from_bits(0x3f800000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let pow_f32_actual: Vec<f32> =
			oa::matrix::pow(&pow_f32_input, f32::from_bits(0x3fc00000))?.read()?;
		assert_close(
			&pow_f32_actual,
			&repeated(&[
				f32::from_bits(0x3e000000),
				f32::from_bits(0x3f800000),
				f32::from_bits(0x41000000),
			]),
			f32::from_bits(0x3a83126f),
		);

		let add_scalar_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let add_scalar_f32_actual: Vec<f32> =
			oa::matrix::add_scalar(&add_scalar_f32_input, f32::from_bits(0x3fc00000))?.read()?;
		assert_close(
			&add_scalar_f32_actual,
			&repeated(&[
				f32::from_bits(0xbf000000),
				f32::from_bits(0x40000000),
				f32::from_bits(0x40b00000),
			]),
			f32::from_bits(0x38d1b717),
		);

		let sub_scalar_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let sub_scalar_f32_actual: Vec<f32> =
			oa::matrix::sub_scalar(&sub_scalar_f32_input, f32::from_bits(0x3fc00000))?.read()?;
		assert_close(
			&sub_scalar_f32_actual,
			&repeated(&[
				f32::from_bits(0xc0600000),
				f32::from_bits(0xbf800000),
				f32::from_bits(0x40200000),
			]),
			f32::from_bits(0x38d1b717),
		);

		let div_scalar_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let div_scalar_f32_actual: Vec<f32> =
			oa::matrix::div_scalar(&div_scalar_f32_input, f32::from_bits(0x3fc00000))?.read()?;
		assert_close(
			&div_scalar_f32_actual,
			&repeated(&[
				f32::from_bits(0xbfaaaaab),
				f32::from_bits(0x3eaaaaab),
				f32::from_bits(0x402aaaab),
			]),
			f32::from_bits(0x38d1b717),
		);

		let exp_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xbf800000),
				f32::from_bits(0x00000000),
				f32::from_bits(0x3f800000),
			]),
		)?;
		let exp_f32_actual: Vec<f32> = oa::matrix::exp(&exp_f32_input)?.read()?;
		assert_close(
			&exp_f32_actual,
			&repeated(&[
				f32::from_bits(0x3ebc5ab2),
				f32::from_bits(0x3f800000),
				f32::from_bits(0x402df854),
			]),
			f32::from_bits(0x3a83126f),
		);

		let sin_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xbf800000),
				f32::from_bits(0x00000000),
				f32::from_bits(0x3f800000),
			]),
		)?;
		let sin_f32_actual: Vec<f32> = oa::matrix::sin(&sin_f32_input)?.read()?;
		assert_close(
			&sin_f32_actual,
			&repeated(&[
				f32::from_bits(0xbf576aa4),
				f32::from_bits(0x00000000),
				f32::from_bits(0x3f576aa4),
			]),
			f32::from_bits(0x3a83126f),
		);

		let cos_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xbf800000),
				f32::from_bits(0x00000000),
				f32::from_bits(0x3f800000),
			]),
		)?;
		let cos_f32_actual: Vec<f32> = oa::matrix::cos(&cos_f32_input)?.read()?;
		assert_close(
			&cos_f32_actual,
			&repeated(&[
				f32::from_bits(0x3f0a5140),
				f32::from_bits(0x3f800000),
				f32::from_bits(0x3f0a5140),
			]),
			f32::from_bits(0x3a83126f),
		);

		let reciprocal_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let reciprocal_f32_actual: Vec<f32> =
			oa::matrix::reciprocal(&reciprocal_f32_input)?.read()?;
		assert_close(
			&reciprocal_f32_actual,
			&repeated(&[
				f32::from_bits(0xbf000000),
				f32::from_bits(0x40000000),
				f32::from_bits(0x3e800000),
			]),
			f32::from_bits(0x3a83126f),
		);

		let clamp_max_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let clamp_max_f32_actual: Vec<f32> =
			oa::matrix::clamp_max(&clamp_max_f32_input, f32::from_bits(0x3f800000))?.read()?;
		assert_close(
			&clamp_max_f32_actual,
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x3f800000),
			]),
			f32::from_bits(0x38d1b717),
		);

		let clamp_min_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let clamp_min_f32_actual: Vec<f32> =
			oa::matrix::clamp_min(&clamp_min_f32_input, f32::from_bits(0x00000000))?.read()?;
		assert_close(
			&clamp_min_f32_actual,
			&repeated(&[
				f32::from_bits(0x00000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
			f32::from_bits(0x38d1b717),
		);

		let copy_f32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
		)?;
		let copy_f32_actual: Vec<f32> = oa::matrix::copy(&copy_f32_input)?.read()?;
		assert_close(
			&copy_f32_actual,
			&repeated(&[
				f32::from_bits(0xc0000000),
				f32::from_bits(0x3f000000),
				f32::from_bits(0x40800000),
			]),
			f32::from_bits(0x00000000),
		);

		let copy_u8_input =
			oa::Matrix::from_slice(&engine, [ELEMENT_COUNT], &repeated(&[0_u8, 17_u8, 255_u8]))?;
		let copy_u8_actual: Vec<u8> = oa::matrix::copy(&copy_u8_input)?.read()?;
		assert_eq!(copy_u8_actual, repeated(&[0_u8, 17_u8, 255_u8]));

		let copy_i32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[-2147483648_i32, 0_i32, 2147483647_i32]),
		)?;
		let copy_i32_actual: Vec<i32> = oa::matrix::copy(&copy_i32_input)?.read()?;
		assert_eq!(
			copy_i32_actual,
			repeated(&[-2147483648_i32, 0_i32, 2147483647_i32])
		);

		let copy_u32_input = oa::Matrix::from_slice(
			&engine,
			[ELEMENT_COUNT],
			&repeated(&[0_u32, 17_u32, 4294967295_u32]),
		)?;
		let copy_u32_actual: Vec<u32> = oa::matrix::copy(&copy_u32_input)?.read()?;
		assert_eq!(copy_u32_actual, repeated(&[0_u32, 17_u32, 4294967295_u32]));

		let typed_read_error = add_i32_left
			.read::<f32>()
			.expect_err("mismatched typed readback was accepted");
		assert_eq!(typed_read_error.kind(), oa::ErrorKind::InvalidArgument);

		let mixed_dtype_error = match oa::matrix::add(&add_f32_left, &add_i32_left) {
			Ok(_) => panic!("mixed dense dtypes were accepted"),
			Err(error) => error,
		};
		assert_eq!(mixed_dtype_error.kind(), oa::ErrorKind::InvalidArgument);

		let unsupported_dtype_error = match oa::matrix::sub(&add_i32_left, &add_i32_left) {
			Ok(_) => panic!("unsupported dense dtype was accepted"),
			Err(error) => error,
		};
		assert_eq!(
			unsupported_dtype_error.kind(),
			oa::ErrorKind::InvalidArgument
		);

		Ok(())
	}
);

test_vk!(
	generated_elementwise_dtype_variants_preserve_zero_extent,
	engine,
	{
		let empty_f32 = oa::Matrix::from_slice::<f32>(&engine, [0], &[])?;
		let empty_i32 = oa::Matrix::from_slice::<i32>(&engine, [0], &[])?;
		let empty_u32 = oa::Matrix::from_slice::<u32>(&engine, [0], &[])?;
		let empty_u8 = oa::Matrix::from_slice::<u8>(&engine, [0], &[])?;
		let add_f32_output = oa::matrix::add(&empty_f32, &empty_f32)?;
		assert_eq!(add_f32_output.shape(), [0]);
		assert_eq!(add_f32_output.dtype(), oa::DType::F32);
		assert!(add_f32_output.read::<f32>()?.is_empty());
		let add_i32_output = oa::matrix::add(&empty_i32, &empty_i32)?;
		assert_eq!(add_i32_output.shape(), [0]);
		assert_eq!(add_i32_output.dtype(), oa::DType::I32);
		assert!(add_i32_output.read::<i32>()?.is_empty());
		let sub_f32_output = oa::matrix::sub(&empty_f32, &empty_f32)?;
		assert_eq!(sub_f32_output.shape(), [0]);
		assert_eq!(sub_f32_output.dtype(), oa::DType::F32);
		assert!(sub_f32_output.read::<f32>()?.is_empty());
		let mul_f32_output = oa::matrix::mul(&empty_f32, &empty_f32)?;
		assert_eq!(mul_f32_output.shape(), [0]);
		assert_eq!(mul_f32_output.dtype(), oa::DType::F32);
		assert!(mul_f32_output.read::<f32>()?.is_empty());
		let div_f32_output = oa::matrix::div(&empty_f32, &empty_f32)?;
		assert_eq!(div_f32_output.shape(), [0]);
		assert_eq!(div_f32_output.dtype(), oa::DType::F32);
		assert!(div_f32_output.read::<f32>()?.is_empty());
		let scale_f32_output = oa::matrix::scale(&empty_f32, f32::from_bits(0x3f800000))?;
		assert_eq!(scale_f32_output.shape(), [0]);
		assert_eq!(scale_f32_output.dtype(), oa::DType::F32);
		assert!(scale_f32_output.read::<f32>()?.is_empty());
		let neg_f32_output = oa::matrix::neg(&empty_f32)?;
		assert_eq!(neg_f32_output.shape(), [0]);
		assert_eq!(neg_f32_output.dtype(), oa::DType::F32);
		assert!(neg_f32_output.read::<f32>()?.is_empty());
		let abs_f32_output = oa::matrix::abs(&empty_f32)?;
		assert_eq!(abs_f32_output.shape(), [0]);
		assert_eq!(abs_f32_output.dtype(), oa::DType::F32);
		assert!(abs_f32_output.read::<f32>()?.is_empty());
		let log_f32_output = oa::matrix::log(&empty_f32)?;
		assert_eq!(log_f32_output.shape(), [0]);
		assert_eq!(log_f32_output.dtype(), oa::DType::F32);
		assert!(log_f32_output.read::<f32>()?.is_empty());
		let sqrt_f32_output = oa::matrix::sqrt(&empty_f32)?;
		assert_eq!(sqrt_f32_output.shape(), [0]);
		assert_eq!(sqrt_f32_output.dtype(), oa::DType::F32);
		assert!(sqrt_f32_output.read::<f32>()?.is_empty());
		let pow_f32_output = oa::matrix::pow(&empty_f32, f32::from_bits(0x3f800000))?;
		assert_eq!(pow_f32_output.shape(), [0]);
		assert_eq!(pow_f32_output.dtype(), oa::DType::F32);
		assert!(pow_f32_output.read::<f32>()?.is_empty());
		let add_scalar_f32_output = oa::matrix::add_scalar(&empty_f32, f32::from_bits(0x3f800000))?;
		assert_eq!(add_scalar_f32_output.shape(), [0]);
		assert_eq!(add_scalar_f32_output.dtype(), oa::DType::F32);
		assert!(add_scalar_f32_output.read::<f32>()?.is_empty());
		let sub_scalar_f32_output = oa::matrix::sub_scalar(&empty_f32, f32::from_bits(0x3f800000))?;
		assert_eq!(sub_scalar_f32_output.shape(), [0]);
		assert_eq!(sub_scalar_f32_output.dtype(), oa::DType::F32);
		assert!(sub_scalar_f32_output.read::<f32>()?.is_empty());
		let div_scalar_f32_output = oa::matrix::div_scalar(&empty_f32, f32::from_bits(0x3f800000))?;
		assert_eq!(div_scalar_f32_output.shape(), [0]);
		assert_eq!(div_scalar_f32_output.dtype(), oa::DType::F32);
		assert!(div_scalar_f32_output.read::<f32>()?.is_empty());
		let exp_f32_output = oa::matrix::exp(&empty_f32)?;
		assert_eq!(exp_f32_output.shape(), [0]);
		assert_eq!(exp_f32_output.dtype(), oa::DType::F32);
		assert!(exp_f32_output.read::<f32>()?.is_empty());
		let sin_f32_output = oa::matrix::sin(&empty_f32)?;
		assert_eq!(sin_f32_output.shape(), [0]);
		assert_eq!(sin_f32_output.dtype(), oa::DType::F32);
		assert!(sin_f32_output.read::<f32>()?.is_empty());
		let cos_f32_output = oa::matrix::cos(&empty_f32)?;
		assert_eq!(cos_f32_output.shape(), [0]);
		assert_eq!(cos_f32_output.dtype(), oa::DType::F32);
		assert!(cos_f32_output.read::<f32>()?.is_empty());
		let reciprocal_f32_output = oa::matrix::reciprocal(&empty_f32)?;
		assert_eq!(reciprocal_f32_output.shape(), [0]);
		assert_eq!(reciprocal_f32_output.dtype(), oa::DType::F32);
		assert!(reciprocal_f32_output.read::<f32>()?.is_empty());
		let clamp_max_f32_output = oa::matrix::clamp_max(&empty_f32, f32::from_bits(0x3f800000))?;
		assert_eq!(clamp_max_f32_output.shape(), [0]);
		assert_eq!(clamp_max_f32_output.dtype(), oa::DType::F32);
		assert!(clamp_max_f32_output.read::<f32>()?.is_empty());
		let clamp_min_f32_output = oa::matrix::clamp_min(&empty_f32, f32::from_bits(0x3f800000))?;
		assert_eq!(clamp_min_f32_output.shape(), [0]);
		assert_eq!(clamp_min_f32_output.dtype(), oa::DType::F32);
		assert!(clamp_min_f32_output.read::<f32>()?.is_empty());
		let copy_f32_output = oa::matrix::copy(&empty_f32)?;
		assert_eq!(copy_f32_output.shape(), [0]);
		assert_eq!(copy_f32_output.dtype(), oa::DType::F32);
		assert!(copy_f32_output.read::<f32>()?.is_empty());
		let copy_u8_output = oa::matrix::copy(&empty_u8)?;
		assert_eq!(copy_u8_output.shape(), [0]);
		assert_eq!(copy_u8_output.dtype(), oa::DType::U8);
		assert!(copy_u8_output.read::<u8>()?.is_empty());
		let copy_i32_output = oa::matrix::copy(&empty_i32)?;
		assert_eq!(copy_i32_output.shape(), [0]);
		assert_eq!(copy_i32_output.dtype(), oa::DType::I32);
		assert!(copy_i32_output.read::<i32>()?.is_empty());
		let copy_u32_output = oa::matrix::copy(&empty_u32)?;
		assert_eq!(copy_u32_output.shape(), [0]);
		assert_eq!(copy_u32_output.dtype(), oa::DType::U32);
		assert!(copy_u32_output.read::<u32>()?.is_empty());
		Ok(())
	}
);
