// AUTO-GENERATED by Tools/TypeAutogen/oatypeautogen.py — DO NOT EDIT.
// Source of truth: Tools/TypeAutogen/Schema/MlTypes.toml.
// Regenerate via: python3 Tools/TypeAutogen/oatypeautogen.py --live

#include <Oa/Ml/Type.gen.h>

#include <cstring>

constexpr const char* OaActivationToString(OaActivation InType) noexcept {
	switch (InType) {
		case OaActivation::None: return "None";
		case OaActivation::Relu: return "Relu";
		case OaActivation::Gelu: return "Gelu";
		case OaActivation::Sigmoid: return "Sigmoid";
		case OaActivation::Tanh: return "Tanh";
		case OaActivation::Silu: return "Silu";
		case OaActivation::Mish: return "Mish";
		case OaActivation::LeakyRelu: return "LeakyRelu";
		case OaActivation::Elu: return "Elu";
		case OaActivation::Selu: return "Selu";
		default: return "unknown";
	}
}

OaActivation OaActivationFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "None") == 0) return OaActivation::None;
	if (strcmp(InStr, "Relu") == 0) return OaActivation::Relu;
	if (strcmp(InStr, "Gelu") == 0) return OaActivation::Gelu;
	if (strcmp(InStr, "Sigmoid") == 0) return OaActivation::Sigmoid;
	if (strcmp(InStr, "Tanh") == 0) return OaActivation::Tanh;
	if (strcmp(InStr, "Silu") == 0) return OaActivation::Silu;
	if (strcmp(InStr, "Mish") == 0) return OaActivation::Mish;
	if (strcmp(InStr, "LeakyRelu") == 0) return OaActivation::LeakyRelu;
	if (strcmp(InStr, "Elu") == 0) return OaActivation::Elu;
	if (strcmp(InStr, "Selu") == 0) return OaActivation::Selu;
	return OaActivation::None;  // Default to first value
}

constexpr const char* OaUpsampleModeToString(OaUpsampleMode InType) noexcept {
	switch (InType) {
		case OaUpsampleMode::Nearest: return "Nearest";
		case OaUpsampleMode::Bilinear: return "Bilinear";
		default: return "unknown";
	}
}

OaUpsampleMode OaUpsampleModeFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "Nearest") == 0) return OaUpsampleMode::Nearest;
	if (strcmp(InStr, "Bilinear") == 0) return OaUpsampleMode::Bilinear;
	return OaUpsampleMode::Nearest;  // Default to first value
}

constexpr const char* OaPrecisionTagToString(OaPrecisionTag InType) noexcept {
	switch (InType) {
		case OaPrecisionTag::None: return "None";
		case OaPrecisionTag::FP32: return "FP32";
		case OaPrecisionTag::FP16: return "FP16";
		case OaPrecisionTag::BF16: return "BF16";
		case OaPrecisionTag::INT8: return "INT8";
		default: return "unknown";
	}
}

OaPrecisionTag OaPrecisionTagFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "None") == 0) return OaPrecisionTag::None;
	if (strcmp(InStr, "FP32") == 0) return OaPrecisionTag::FP32;
	if (strcmp(InStr, "FP16") == 0) return OaPrecisionTag::FP16;
	if (strcmp(InStr, "BF16") == 0) return OaPrecisionTag::BF16;
	if (strcmp(InStr, "INT8") == 0) return OaPrecisionTag::INT8;
	return OaPrecisionTag::None;  // Default to first value
}

constexpr const char* OamCompressionToString(OamCompression InType) noexcept {
	switch (InType) {
		case OamCompression::None: return "None";
		case OamCompression::Zlib: return "Zlib";
		case OamCompression::LZ4: return "LZ4";
		case OamCompression::Zstd: return "Zstd";
		default: return "unknown";
	}
}

OamCompression OamCompressionFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "None") == 0) return OamCompression::None;
	if (strcmp(InStr, "Zlib") == 0) return OamCompression::Zlib;
	if (strcmp(InStr, "LZ4") == 0) return OamCompression::LZ4;
	if (strcmp(InStr, "Zstd") == 0) return OamCompression::Zstd;
	return OamCompression::None;  // Default to first value
}

constexpr const char* OamSectionTypeToString(OamSectionType InType) noexcept {
	switch (InType) {
		case OamSectionType::Unknown: return "Unknown";
		case OamSectionType::Header: return "Header";
		case OamSectionType::Weights: return "Weights";
		case OamSectionType::Optimizer: return "Optimizer";
		case OamSectionType::Progress: return "Progress";
		case OamSectionType::Spirv: return "Spirv";
		case OamSectionType::Metadata: return "Metadata";
		default: return "unknown";
	}
}

OamSectionType OamSectionTypeFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "Unknown") == 0) return OamSectionType::Unknown;
	if (strcmp(InStr, "Header") == 0) return OamSectionType::Header;
	if (strcmp(InStr, "Weights") == 0) return OamSectionType::Weights;
	if (strcmp(InStr, "Optimizer") == 0) return OamSectionType::Optimizer;
	if (strcmp(InStr, "Progress") == 0) return OamSectionType::Progress;
	if (strcmp(InStr, "Spirv") == 0) return OamSectionType::Spirv;
	if (strcmp(InStr, "Metadata") == 0) return OamSectionType::Metadata;
	return OamSectionType::Unknown;  // Default to first value
}
