// AUTO-GENERATED by tools/gen/nn/generate.py - DO NOT EDIT.
// source of truth: tools/gen/nn/schema/ml/mlNnEmbedding.toml.
// Regenerate via: python3 tools/gen/nn/generate.py --live

#pragma once

#include <oa/ml/module.h>

namespace oa {

/// Embedding: Embedding lookup layer.
class Embedding : public Module {
public:
	Embedding(oa::I32 inNumEmbeddings, oa::I32 inEmbeddingDim);
	Matrix forward(const Matrix& inInput) override;
	[[nodiscard]] oa::I32 numEmbeddings() const { return numEmbeddings_; }
	[[nodiscard]] oa::I32 embeddingDim() const { return embeddingDim_; }

private:
	oa::I32 numEmbeddings_;
	oa::I32 embeddingDim_;
};

} // namespace oa
