// AUTO-GENERATED by Tools/NnAutogen/oannautogen.py - DO NOT EDIT.
// Source of truth: Tools/NnAutogen/Schema/Ml/MlNnNorm.toml.
// Regenerate via: python3 Tools/NnAutogen/oannautogen.py --live

#pragma once

#include <Oa/Ml/Module.h>
#include <Oa/Ml/NnType.h>

#include <initializer_list>

/// OaRmsNorm: RMS normalization layer.
class OaRmsNorm : public OaModule {
public:
	explicit OaRmsNorm(OaI32 Dim, OaF32 Eps = 1e-6f);
	OaMatrix Forward(const OaMatrix& InInput) override;

private:
	OaF32 Eps_;
};
