// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/**.toml [ops.kernel].
// Included inside the matching OaKernelRegistry fixed-family array.
	{ "RlCartPoleReset", OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 274), OaComputeKernelCategory::Ml, "oa" },
	{ "RlCartPoleStep", OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 275), OaComputeKernelCategory::Ml, "oa" },
	{ "RlLunarLander3dReset", OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 280), OaComputeKernelCategory::Ml, "oa" },
	{ "RlLunarLander3dStep", OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 281), OaComputeKernelCategory::Ml, "oa" },
