// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/Vision/VisionFnImagePixel.toml.
// Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live

// OaFnImage — Pixel overloads.

	/// ThresholdBinary: Global binary threshold.
	[[nodiscard]] OaMatrix ThresholdBinary(OaEngine& InRt, const OaMatrix& InImage, OaF32 InThreshold, OaF32 InMaxValue = 1.0F);
	[[nodiscard]] OaMatrix ThresholdBinary(const OaMatrix& InImage, OaF32 InThreshold, OaF32 InMaxValue = 1.0F);

	/// ThresholdBinaryInv: Global inverse binary threshold.
	[[nodiscard]] OaMatrix ThresholdBinaryInv(OaEngine& InRt, const OaMatrix& InImage, OaF32 InThreshold, OaF32 InMaxValue = 1.0F);
	[[nodiscard]] OaMatrix ThresholdBinaryInv(const OaMatrix& InImage, OaF32 InThreshold, OaF32 InMaxValue = 1.0F);

	/// ThresholdTruncate: Truncate values above a threshold.
	[[nodiscard]] OaMatrix ThresholdTruncate(OaEngine& InRt, const OaMatrix& InImage, OaF32 InThreshold);
	[[nodiscard]] OaMatrix ThresholdTruncate(const OaMatrix& InImage, OaF32 InThreshold);

	/// ThresholdToZero: Set values at or below a threshold to zero.
	[[nodiscard]] OaMatrix ThresholdToZero(OaEngine& InRt, const OaMatrix& InImage, OaF32 InThreshold);
	[[nodiscard]] OaMatrix ThresholdToZero(const OaMatrix& InImage, OaF32 InThreshold);

	/// ThresholdToZeroInv: Set values above a threshold to zero.
	[[nodiscard]] OaMatrix ThresholdToZeroInv(OaEngine& InRt, const OaMatrix& InImage, OaF32 InThreshold);
	[[nodiscard]] OaMatrix ThresholdToZeroInv(const OaMatrix& InImage, OaF32 InThreshold);

	/// InRange: Inclusive scalar range mask.
	[[nodiscard]] OaMatrix InRange(OaEngine& InRt, const OaMatrix& InImage, OaF32 InLow, OaF32 InHigh, OaF32 InTrueValue = 1.0F);
	[[nodiscard]] OaMatrix InRange(const OaMatrix& InImage, OaF32 InLow, OaF32 InHigh, OaF32 InTrueValue = 1.0F);

	/// Clamp: Clamp image values to a scalar interval.
	[[nodiscard]] OaMatrix Clamp(OaEngine& InRt, const OaMatrix& InImage, OaF32 InLow, OaF32 InHigh);
	[[nodiscard]] OaMatrix Clamp(const OaMatrix& InImage, OaF32 InLow, OaF32 InHigh);

	/// Invert: Invert values around a configurable maximum.
	[[nodiscard]] OaMatrix Invert(OaEngine& InRt, const OaMatrix& InImage, OaF32 InMaxValue = 1.0F);
	[[nodiscard]] OaMatrix Invert(const OaMatrix& InImage, OaF32 InMaxValue = 1.0F);

	/// BrightnessContrast: Affine brightness and contrast adjustment.
	[[nodiscard]] OaMatrix BrightnessContrast(OaEngine& InRt, const OaMatrix& InImage, OaF32 InBrightness = 0.0F, OaF32 InContrast = 1.0F);
	[[nodiscard]] OaMatrix BrightnessContrast(const OaMatrix& InImage, OaF32 InBrightness = 0.0F, OaF32 InContrast = 1.0F);

	/// GammaContrast: Gamma and gain adjustment.
	[[nodiscard]] OaMatrix GammaContrast(OaEngine& InRt, const OaMatrix& InImage, OaF32 InGamma, OaF32 InGain = 1.0F);
	[[nodiscard]] OaMatrix GammaContrast(const OaMatrix& InImage, OaF32 InGamma, OaF32 InGain = 1.0F);

	/// Solarize: Invert values above a threshold.
	[[nodiscard]] OaMatrix Solarize(OaEngine& InRt, const OaMatrix& InImage, OaF32 InThreshold = 0.5F, OaF32 InMaxValue = 1.0F);
	[[nodiscard]] OaMatrix Solarize(const OaMatrix& InImage, OaF32 InThreshold = 0.5F, OaF32 InMaxValue = 1.0F);

	/// Posterize: Quantize an intensity interval to a fixed number of levels.
	[[nodiscard]] OaMatrix Posterize(OaEngine& InRt, const OaMatrix& InImage, OaU32 InLevels, OaF32 InLow = 0.0F, OaF32 InHigh = 1.0F);
	[[nodiscard]] OaMatrix Posterize(const OaMatrix& InImage, OaU32 InLevels, OaF32 InLow = 0.0F, OaF32 InHigh = 1.0F);

	/// Grayscale: Rec.709 RGB to single-channel grayscale conversion.
	[[nodiscard]] OaMatrix Grayscale(OaEngine& InRt, const OaMatrix& InImage);
	[[nodiscard]] OaMatrix Grayscale(const OaMatrix& InImage);

	/// ChannelReorder: Reorder one to four NCHW channels.
	[[nodiscard]] OaMatrix ChannelReorder(OaEngine& InRt, const OaMatrix& InImage, OaU32 InChannel0, OaU32 InChannel1 = 1, OaU32 InChannel2 = 2, OaU32 InChannel3 = 3);
	[[nodiscard]] OaMatrix ChannelReorder(const OaMatrix& InImage, OaU32 InChannel0, OaU32 InChannel1 = 1, OaU32 InChannel2 = 2, OaU32 InChannel3 = 3);

	/// AlphaBlend: Scalar alpha blend of equal-shaped images.
	[[nodiscard]] OaMatrix AlphaBlend(OaEngine& InRt, const OaMatrix& InA, const OaMatrix& InB, OaF32 InAlpha);
	[[nodiscard]] OaMatrix AlphaBlend(const OaMatrix& InA, const OaMatrix& InB, OaF32 InAlpha);

	/// Composite: Per-pixel masked composite with one or C mask channels.
	[[nodiscard]] OaMatrix Composite(OaEngine& InRt, const OaMatrix& InA, const OaMatrix& InB, const OaMatrix& InMask);
	[[nodiscard]] OaMatrix Composite(const OaMatrix& InA, const OaMatrix& InB, const OaMatrix& InMask);

	/// Erase: Fill a rectangular region with a scalar value.
	[[nodiscard]] OaMatrix Erase(OaEngine& InRt, const OaMatrix& InImage, OaU32 InX, OaU32 InY, OaU32 InWidth, OaU32 InHeight, OaF32 InValue = 0.0F);
	[[nodiscard]] OaMatrix Erase(const OaMatrix& InImage, OaU32 InX, OaU32 InY, OaU32 InWidth, OaU32 InHeight, OaF32 InValue = 0.0F);

	/// ColorTwist: Apply a shared 3x4 RGB color transform matrix.
	[[nodiscard]] OaMatrix ColorTwist(OaEngine& InRt, const OaMatrix& InImage, const OaMatrix& InTransform);
	[[nodiscard]] OaMatrix ColorTwist(const OaMatrix& InImage, const OaMatrix& InTransform);

	/// GaussianNoise: Add deterministic GPU-native Philox Gaussian noise.
	[[nodiscard]] OaMatrix GaussianNoise(OaEngine& InRt, const OaMatrix& InImage, OaF32 InMean = 0.0F, OaF32 InStddev = 0.01F, OaU64 InSeed = 0);
	[[nodiscard]] OaMatrix GaussianNoise(const OaMatrix& InImage, OaF32 InMean = 0.0F, OaF32 InStddev = 0.01F, OaU64 InSeed = 0);

	/// SaltPepperNoise: Apply deterministic GPU-native salt-and-pepper noise.
	[[nodiscard]] OaMatrix SaltPepperNoise(OaEngine& InRt, const OaMatrix& InImage, OaF32 InProbability = 0.01F, OaF32 InSaltValue = 1.0F, OaF32 InPepperValue = 0.0F, OaU64 InSeed = 0);
	[[nodiscard]] OaMatrix SaltPepperNoise(const OaMatrix& InImage, OaF32 InProbability = 0.01F, OaF32 InSaltValue = 1.0F, OaF32 InPepperValue = 0.0F, OaU64 InSeed = 0);
