// AUTO-GENERATED by tools/gen/nn/generate.py - DO NOT EDIT.
// source of truth: tools/gen/nn/schema/ml/mlNnContainer.toml.
// Regenerate via: python3 tools/gen/nn/generate.py --live
// oa::Sequential - Sequential container that chains modules together.

#include <oa/ml/nn.h>
#include <oa/core/fnMatrix.h>
#include <oa/core/validation.h>

oa::Sequential& oa::Sequential::add(oa::SharedPtr<oa::Module> inModule) {
	oa::String name(oa::String("layer_") + oa::toString(static_cast<oa::U32>(children_.size())));
	return add(name, oa::move(inModule));
}

oa::Sequential& oa::Sequential::add(oa::StringView inName, oa::SharedPtr<oa::Module> inModule) {
	registerModule(inName, oa::move(inModule));
	return *this;
}
oa::Matrix oa::Sequential::forward(const oa::Matrix& inInput) {
	oa::Matrix x = inInput;
	for (auto& child : children_) {
		x = child.module->forward(x);
	}
	return x;
}
