// AUTO-GENERATED by tools/gen/fn/generate.py — DO NOT EDIT.
// Source of truth: tools/gen/fn/schema/**.toml.
// Included inside the owning bind function.

	m.def("gae", [](const oa::Matrix& inReward, const oa::Matrix& inValue, const oa::Matrix& inNextValue, const oa::Matrix& inTerminated, const oa::Matrix& inTruncated, const oa::GaeConfig& inConfig) {
		auto result = oa::FnAdvantage::gae(inReward, inValue, inNextValue, inTerminated, inTruncated, inConfig);
		if (not result.isValid()) {
			throw std::runtime_error("Gae rejected its input");
		}
		return new oa::GaeResult(oa::move(result));
	},
	  nb::arg("reward"), nb::arg("value"), nb::arg("nextValue"), nb::arg("terminated"), nb::arg("truncated"), nb::arg("config") = oa::GaeConfig{},
	  nb::rv_policy::take_ownership,
	  "Compute generalized advantage estimates and returns.");

	m.def("normalize", [](const oa::Matrix& inAdvantage, oa::F32 inEpsilon) {
		auto result = oa::FnAdvantage::normalize(inAdvantage, inEpsilon);
		if (result.isEmpty()) {
			throw std::runtime_error("NormalizeAdvantages rejected its input");
		}
		return matrixPtr(oa::move(result));
	},
	  nb::arg("advantage"), nb::arg("epsilon") = 1.0e-8F,
	  nb::rv_policy::take_ownership,
	  "Standardize a rollout advantage tensor.");
