// AUTO-GENERATED by tools/gen/nn/generate.py - DO NOT EDIT.
// source of truth: tools/gen/nn/schema/ml/mlNnVision.toml.
// Regenerate via: python3 tools/gen/nn/generate.py --live

#pragma once

#include <oa/ml/module.h>

#include <initializer_list>

namespace oa {

/// Upsample: Spatial upsampling layer (Nearest or Bilinear).
class Upsample : public Module {
public:
	Upsample(oa::I32 inScaleFactor, oa::UpsampleMode inMode = oa::UpsampleMode::Bilinear);
	Matrix forward(const Matrix& inInput) override;

private:
	oa::I32 scaleFactor_;
	oa::UpsampleMode mode_;
};

} // namespace oa
