// AUTO-GENERATED by tools/fnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: tools/fnAutogen/schema/ml/mlFnMatrixNorm.toml.
// Regenerate via: python3 tools/fnAutogen/oafnautogen.py --live

// oa::FnMatrix — Norm overloads.

	/// rmsNorm: Weighted root mean square normalization over the last dimension: out = (A / sqrt(mean(A^2) + Eps)) * Weight.
	[[nodiscard]] oa::Matrix rmsNorm(const oa::Matrix& inSelf, const oa::Matrix& inWeight, oa::F32 inEps);

	/// layerNorm: Affine layer normalization over the last dimension: out = ((A - mean(A)) / sqrt(var(A) + Eps)) * Weight + Bias.
	[[nodiscard]] oa::Matrix layerNorm(const oa::Matrix& inSelf, const oa::Matrix& inWeight, const oa::Matrix& inBias, oa::F32 inEps);
