// AUTO-GENERATED by tools/oaTile/oatile.py -- DO NOT EDIT.
// Source of truth: tools/oaTile/schema/bf16Coop.toml

namespace oa {
inline constexpr U32 tileBf16SchemaVersion = 1U;
inline constexpr U32 tileBf16GeneratorAbi = 2U;
inline constexpr U64 tileBf16SchemaHash = 0x8fac19b64b986032ULL;
} // namespace oa
