// AUTO-GENERATED by tools/fnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: tools/fnAutogen/schema/vision/visionFnImageResize.toml.
// Regenerate via: python3 tools/fnAutogen/oafnautogen.py --live

// oa::FnImage — Resize overloads.

	/// resize: Resize an NCHW image using nearest or bilinear interpolation.
	[[nodiscard]] oa::Matrix resize(oa::Engine& inEngine, const oa::Matrix& inImage, oa::U32 inTargetWidth, oa::U32 inTargetHeight, oa::InterpolationMode inMode = oa::InterpolationMode::Bilinear);
	[[nodiscard]] oa::Matrix resize(const oa::Matrix& inImage, oa::U32 inTargetWidth, oa::U32 inTargetHeight, oa::InterpolationMode inMode = oa::InterpolationMode::Bilinear);
