#!/usr/bin/env python3
"""
OaFnAutogen — schema-driven generator for OaFn* C++/Slang code.

Stdlib only (tomllib + re + pathlib + argparse). No pip deps.

Discovers every TOML schema under `Schema/`, validates each op against
KernelRegistry.h, and emits per-category files:

  - <out>/Private/Oa/<Domain>/Matrix/FnMatrix<Category>.gen.h
      declaration fragment included through the public umbrella
  - <out>/Private/Oa/<Domain>/Matrix/FnMatrix<Category>.gen.cpp
      implementations for auto bodies. `manual_context` ops are declared and
      implemented by hand.
  - <out>/Private/Oa/<Domain>/Shader/Compute/<slang_path>/<Name>.slang
      shader (one per op) when generate_slang = true

See Tools/FnAutogen/README.md for the public schema and generation workflow.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from collections import defaultdict
from pathlib import Path

TOOLS_ROOT = Path(__file__).resolve().parents[1]
if str(TOOLS_ROOT) not in sys.path:
	sys.path.insert(0, str(TOOLS_ROOT))

from autogen_io import write_generated_text

from oafnautogen_lib.config import (
	DEFAULT_OUTPUT,
	DEFAULT_REGISTRY,
	DOMAIN_FILE_PREFIX,
	DOMAIN_NAMESPACE,
	LIVE_SOURCE_ROOT,
	NAMESPACE_HEADER,
	REPO_ROOT,
	SCHEMA_DIR,
)
from oafnautogen_lib.errors import fail
from oafnautogen_lib.layout import SchemaLayout, build_schema_layout, infer_domain, infer_cpp_subdir
from oafnautogen_lib.schema import (
	category_from_schema,
	load_kernel_registry,
	semantic_attribute_specs,
	validate_schema,
	validate_schema_metadata,
)


# ─── Code emission ─────────────────────────────────────────────────────────

GEN_HEADER = (
	"// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.\n"
	"// Source of truth: Tools/FnAutogen/Schema/{schema_name}.\n"
	"// Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live\n"
)


def extra_param_decls(op: dict) -> list[str]:
	"""Returns C++ param decls for non-tensor scalar/dim args, e.g. `OaI32 InDim = -1`."""
	out = []
	for ep in op.get("extra_params", []):
		decl = f"{ep['type']} In{ep['name']}"
		if "default" in ep:
			decl = f"{decl} = {ep['default']}"
		out.append(decl)
	return out


def cpp_param_list(op: dict, *, with_defaults: bool = True) -> str:
	"""Build the parameter list for a context-based forward overload.

	with_defaults: emit `= -1` defaults in declarations, but not in definitions.
	Context is obtained automatically inside the function, not passed as parameter.
	"""
	parts: list[str] = []
	kind = op["kind"]
	if kind == "binary":
		parts += ["const OaMatrix& InA", "const OaMatrix& InB"]
	elif kind in ("unary", "reduce_full"):
		parts += ["const OaMatrix& InA"]
	elif kind == "unary_scalar":
		sp = op["scalar_param"]
		parts += ["const OaMatrix& InA", f"{sp['type']} In{sp['name']}"]
	elif kind == "nullary_scalar":
		# Factory convention: shape/extra params first, then the fill value —
		# matching Full(shape, value) and torch.full(size, fill_value). The
		# scalar is appended *after* the extra params below.
		sp = op["scalar_param"]
		for ep in extra_param_decls(op):
			if not with_defaults:
				ep = re.sub(r"\s*=\s*[^,]+$", "", ep)
			parts.append(ep)
		parts += [f"{sp['type']} In{sp['name']}"]
		return ", ".join(parts)
	# extra params (after main tensor args)
	for ep in extra_param_decls(op):
		if not with_defaults:
			ep = re.sub(r"\s*=\s*[^,]+$", "", ep)
		parts.append(ep)
	return ", ".join(parts)


def _api_param_parts(param: str | dict) -> tuple[str, str, str | None]:
	if isinstance(param, str):
		decl, separator, default = param.partition("=")
		decl = decl.strip()
		param_type, name = decl.rsplit(None, 1)
		return param_type, name, default.strip() if separator else None
	name = f"In{param['name']}"
	return param["type"], name, param.get("default")


def api_param_list(op: dict, *, with_defaults: bool = True) -> str:
	"""Exact schema-owned public parameter list for non-uniform manual ops."""
	parts = []
	for param in op.get("api_params", []):
		param_type, name, default = _api_param_parts(param)
		decl = f"{param_type} {name}"
		if with_defaults and default is not None:
			decl += f" = {default}"
		parts.append(decl)
	return ", ".join(parts)


def api_arg_list(op: dict) -> str:
	return ", ".join(_api_param_parts(param)[1] for param in op.get("api_params", []))


def header_fragment_for_op(op: dict, namespace: str = "OaFnMatrix") -> list[str]:
	name = op["name"]
	notes = op.get("notes", "")
	body = op.get("body", "auto")
	if not op.get("generate_declaration", True):
		return []
	if op.get("api_params"):
		lines = [f"\t/// {name}: {notes}"]
		return_type = op.get("api_return", "OaMatrix")
		params = api_param_list(op)
		if op.get("generate_engine_overload", False):
			engine_params = f"OaEngine& InRt, {params}" if params else "OaEngine& InRt"
			lines.append(f"\t[[nodiscard]] {return_type} {name}({engine_params});")
		lines.append(f"\t[[nodiscard]] {return_type} {name}({params});")
		lines.append("")
		return lines
	# Entirely handwritten operations own no generated declaration. Emitting a
	# comment-only placeholder makes the generated surface look non-empty and
	# leaves stale noise in otherwise useful mixed-category headers.
	if body in ("manual_context", "cpu_util"):
		return []
	lines = [f"\t/// {name}: {notes}"]
	lines.append(f"\t/// Context-based: auto y = {namespace}::{name}(...);")
	lines.append(f"\t/// Records operation to thread-local default context.")
	lines.append(f"\t[[nodiscard]] OaMatrix {name}({cpp_param_list(op)});")
	lines.append("")
	return lines


def emit_manual_forwarder(op: dict, namespace: str) -> str:
	"""Generate the global-engine convenience overload for a manual GPU body."""
	if not (op.get("api_params") and op.get("generate_forwarder", False)):
		return ""
	name = op["name"]
	return_type = op.get("api_return", "OaMatrix")
	params = api_param_list(op, with_defaults=False)
	args = api_arg_list(op)
	call_args = f"*OaEngine::GetGlobal(), {args}" if args else "*OaEngine::GetGlobal()"
	return (
		f"{return_type} {namespace}::{name}({params}) {{\n"
		f"\treturn {namespace}::{name}({call_args});\n"
		f"}}\n"
	)


def schema_label(schema_path: Path) -> str:
	try:
		return schema_path.resolve().relative_to(SCHEMA_DIR.resolve()).as_posix()
	except ValueError:
		return schema_path.name


def emit_header_fragment(ops: list[dict], schema_name: str, category: str, namespace: str = "OaFnMatrix") -> str:
	lines = [GEN_HEADER.format(schema_name=schema_name)]
	lines.append(f"// {namespace} — {category} overloads.\n")
	for op in ops:
		lines.extend(header_fragment_for_op(op, namespace))
	return "\n".join(lines)


# ─── Semantic operation contracts ─────────────────────────────────────────

_VALUE_KIND_CPP = {
	"matrix": "OaOperationValueKind::Matrix",
	"image": "OaOperationValueKind::Image",
	"audio": "OaOperationValueKind::Audio",
	"video_frame": "OaOperationValueKind::VideoFrame",
}
_SHAPE_RULE_CPP = {
	"match_input": "OaOperationShapeRule::MatchInput",
	"broadcast": "OaOperationShapeRule::Broadcast",
	"matmul_nt": "OaOperationShapeRule::MatMulNt",
	"explicit": "OaOperationShapeRule::Explicit",
}
_DTYPE_RULE_CPP = {
	"match_input": "OaOperationDtypeRule::MatchInput",
	"promote_float": "OaOperationDtypeRule::PromoteFloat",
}
_DIFFERENTIATION_CPP = {
	"none": "OaOperationDifferentiation::None",
	"reverse": "OaOperationDifferentiation::Reverse",
}
_LOWERING_CPP = {
	"dispatch": "OaOperationLowering::Dispatch",
	"gemm": "OaOperationLowering::Gemm",
}
_CONTROL_FLOW_CPP = {
	"straight_line": "OaOperationControlFlow::StraightLine",
	"conditional": "OaOperationControlFlow::Conditional",
	"loop": "OaOperationControlFlow::Loop",
}
_EFFECT_CPP = {
	"read_inputs": "OaOperationEffect::ReadInputs",
	"write_outputs": "OaOperationEffect::WriteOutputs",
}
_VALUE_KIND_NIBBLE = {
	"matrix": 1,
	"image": 2,
	"audio": 3,
	"video_frame": 4,
}
_ATTRIBUTE_KIND_BYTE = {
	"boolean": 1,
	"signed_integer": 2,
	"unsigned_integer": 3,
	"float": 4,
	"string": 5,
	"shape": 6,
	"enum": 7,
}
_ATTRIBUTE_FACTORY_CPP = {
	"boolean": "FromBoolean",
	"signed_integer": "FromSignedInteger",
	"unsigned_integer": "FromUnsignedInteger",
	"float": "FromFloat",
	"string": "FromString",
	"shape": "FromShape",
	"enum": "FromEnum",
}


def _fnv1a64(data: bytes) -> int:
	value = 14695981039346656037
	for byte in data:
		value ^= byte
		value = (value * 1099511628211) & 0xffffffffffffffff
	return value


def _packed_value_kinds(kinds: list[str]) -> int:
	packed = 0
	for index, kind in enumerate(kinds):
		packed |= _VALUE_KIND_NIBBLE[kind] << (index * 4)
	return packed


def _packed_output_alias_inputs(aliases: list[int]) -> int:
	packed = 0xffffffff
	for index, input_index in enumerate(aliases):
		value = 0x0f if input_index < 0 else input_index
		packed &= ~(0x0f << (index * 4))
		packed |= value << (index * 4)
	return packed


def _mutated_input_mask(indices: list[int]) -> int:
	mask = 0
	for index in indices:
		mask |= 1 << index
	return mask


def operation_attribute_signature_hash(op: dict) -> int:
	attributes = [
		{"name": attribute["name"], "kind": attribute["kind"]}
		for attribute in semantic_attribute_specs(op)
	]
	if not attributes:
		return 0
	payload = bytearray()
	for attribute in attributes:
		payload.append(_ATTRIBUTE_KIND_BYTE[attribute["kind"]])
		payload.extend(attribute["name"].encode("utf-8"))
		payload.append(0)
	return _fnv1a64(bytes(payload))


def operation_contract_hash(namespace: str, op: dict) -> int:
	"""Stable semantic hash. Kernel/problem/runtime details are excluded."""
	contract = dict(op["contract"])
	contract.pop("attributes", None)
	payload = {
		"schema": "oa.operation_contract.v1",
		"namespace": namespace,
		"name": op["name"],
		"api_params": op.get("api_params", []),
		"api_return": op.get("api_return", "OaMatrix"),
		"contract": contract,
	}
	attributes = [
		{"name": attribute["name"], "kind": attribute["kind"]}
		for attribute in semantic_attribute_specs(op)
	]
	if attributes:
		payload["attributes"] = attributes
	canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
	return _fnv1a64(canonical.encode("utf-8"))


def emit_operation_registry(contracts: list[tuple[str, dict]]) -> str:
	lines = [
		"// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.",
		"// Source of truth: Tools/FnAutogen/Schema/**.toml [ops.contract].",
		"// Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live",
		"#pragma once",
		"",
		"#include <Oa/Core/Operation.h>",
		"",
		"namespace OaOperationRegistry {",
	]
	for namespace, op in sorted(contracts, key=lambda item: (item[0], item[1]["name"])):
		contract = op["contract"]
		input_kinds = _packed_value_kinds(contract["input_kinds"])
		output_kinds = _packed_value_kinds(contract["output_kinds"])
		effects = " | ".join(_EFFECT_CPP[effect] for effect in contract["effects"])
		mutated_inputs = _mutated_input_mask(contract["mutated_inputs"])
		output_alias_inputs = _packed_output_alias_inputs(
			contract["output_alias_inputs"]
		)
		attributes = semantic_attribute_specs(op)
		attribute_signature = operation_attribute_signature_hash(op)
		hash_value = operation_contract_hash(namespace, op)
		lines += [
			f"inline const OaOperationContract {op['name']}{{",
			f"\t.Name = \"{op['name']}\",",
			f"\t.Hash = 0x{hash_value:016x}ULL,",
			f"\t.InputKinds = 0x{input_kinds:08x}U,",
			f"\t.OutputKinds = 0x{output_kinds:08x}U,",
			f"\t.InputCount = {len(contract['input_kinds'])}U,",
			f"\t.OutputCount = {len(contract['output_kinds'])}U,",
			f"\t.AttributeCount = {len(attributes)}U,",
			f"\t.AttributeSignatureHash = 0x{attribute_signature:016x}ULL,",
			f"\t.ShapeRule = {_SHAPE_RULE_CPP[contract['shape_rule']]},",
			f"\t.DtypeRule = {_DTYPE_RULE_CPP[contract['dtype_rule']]},",
			f"\t.Differentiation = {_DIFFERENTIATION_CPP[contract['differentiation']]},",
			f"\t.Lowering = {_LOWERING_CPP[contract['lowering']]},",
			f"\t.Effects = {effects},",
			f"\t.MutatedInputMask = 0x{mutated_inputs:02x}U,",
			f"\t.OutputAliasInputs = 0x{output_alias_inputs:08x}U,",
			f"\t.ControlFlow = {_CONTROL_FLOW_CPP[contract['control_flow']]},",
			"};",
			"",
		]
	lines += ["} // namespace OaOperationRegistry", ""]
	return "\n".join(lines)


def write_operation_registry(
	schema_paths: list[Path], out_root: Path, *, dry_run: bool
) -> None:
	contracts: list[tuple[str, dict]] = []
	seen: set[tuple[str, str]] = set()
	for schema_path in schema_paths:
		with schema_path.open("rb") as file:
			data = tomllib.load(file)
		domain = infer_domain(schema_path)
		namespace = data.get("namespace", DOMAIN_NAMESPACE.get(domain, "OaFnMatrix"))
		for op in data.get("ops", []):
			if "contract" not in op:
				continue
			key = (namespace, op["name"])
			if key in seen:
				fail(f"duplicate operation contract: {namespace}::{op['name']}")
			seen.add(key)
			contracts.append((namespace, op))

	path = out_root / "Private" / "Oa" / "Core" / "OperationRegistry.gen.h"
	if dry_run:
		print(f"  would write: {path}")
		return
	write_generated_text(path, emit_operation_registry(contracts))
	legacy_path = out_root / "Public" / "Oa" / "Core" / "OperationRegistry.gen.h"
	if legacy_path != path and legacy_path.exists():
		legacy_path.unlink()


# ─── Manual-lowering autograd attachment emission ──────────────────────────

def _emit_manual_autograd_attach(op: dict) -> list[str]:
	ag = op["autograd"]
	inputs = ag["inputs"]
	saved = ag.get("saved", [])
	saved_expressions = ["Out" if name in ("Out", "out") else name for name in saved]
	# Saved tensors are not necessarily differentiable graph inputs. Losses, for
	# example, differentiate logits while retaining integer targets for backward.
	# Pass every saved-only tensor to the generated helper, but keep requires-grad
	# checks and graph edges restricted to the schema's `inputs` list. `Out`/`out`
	# already names the helper's output parameter and needs no second declaration.
	saved_parameters = []
	for name in saved:
		if name in inputs or name in ("Out", "out") or name in saved_parameters:
			continue
		saved_parameters.append(name)
	state = ag.get("state", [])
	grad_class = ag["grad_class"]
	params = ", ".join(
		["OaMatrix& Out"]
		+ [f"const OaMatrix& {name}" for name in inputs]
		+ [f"const OaMatrix& {name}" for name in saved_parameters]
		+ [f"{item['type']} {item['source']}" for item in state]
		+ ["OaSemanticOperationId InSemanticOperation"]
	)
	requires_grad = " or ".join(f"{name}.RequiresGrad()" for name in inputs)
	conditions = ["OaFnAutograd::IsEnabled()", f"({requires_grad})"]
	for name, rank in zip(inputs, ag.get("input_ranks", [])):
		conditions.append(f"{name}.Rank() == {rank}")
	condition = " and ".join(conditions)
	inputs_init = "{" + ", ".join(inputs) + "}"
	saved_init = "{" + ", ".join(saved_expressions) + "}"
	lines = [
		f"inline OaStatus {op['name']}(" + params + ") {",
		f"\tif (not ({condition})) return OaStatus::Ok();",
	]
	if ag["attach"] == "broadcast_binary":
		lines += [
			f"\tif ({inputs[0]}.GetShape() != {inputs[1]}.GetShape()) {{",
			"\t\tauto GradFn = OaMakeSharedPtr<OaGradBcastBinary>();",
			f"\t\tGradFn->Op_ = OaBcastBinOp::{ag['broadcast_op']};",
			f"\t\tGradFn->Saved_ = OaVec<OaMatrix>{inputs_init};",
			f"\t\tGradFn->SetGraphInputs(OaVec<OaMatrix>{inputs_init});",
			"\t\tGradFn->SequenceNr_ = OaFnAutograd::NextSeq();",
			"\t\tGradFn->OutputShape_ = Out.GetShape();",
			"\t\tOA_RETURN_IF_ERROR(OaFnAutograd::AttachSemantic(GradFn, InSemanticOperation));",
			"\t\tOut.MutAutograd().GradFn = GradFn;",
			"\t\treturn OaStatus::Ok();",
			"\t}",
		]
	lines += [
		f"\tauto GradFn = OaMakeSharedPtr<{grad_class}>();",
		f"\tGradFn->Saved_ = OaVec<OaMatrix>{saved_init};",
		f"\tGradFn->SetGraphInputs(OaVec<OaMatrix>{inputs_init});",
		"\tGradFn->SequenceNr_ = OaFnAutograd::NextSeq();",
	]
	lines += [
		f"\tGradFn->{item['member']} = {item['source']};" for item in state
	]
	if ag.get("output_shape", False):
		lines.append("\tGradFn->OutputShape_ = Out.GetShape();")
	lines += [
		"\tOA_RETURN_IF_ERROR(OaFnAutograd::AttachSemantic(GradFn, InSemanticOperation));",
		"\tOut.MutAutograd().GradFn = GradFn;",
		"\treturn OaStatus::Ok();",
		"}",
		"",
	]
	return lines


def emit_manual_autograd_attach_header(attachments: list[tuple[str, dict]]) -> str:
	lines = [
		"// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.",
		"// Source of truth: Tools/FnAutogen/Schema/**.toml [ops.autograd].",
		"// Attaches schema-owned differentiation policy to hand-written lowerings.",
		"// Include only after <Oa/Ml/Autograd.h> has defined the gradient nodes.",
		"#pragma once",
		"",
		"namespace OaGeneratedAutogradAttach {",
		"",
	]
	by_namespace: dict[str, list[dict]] = defaultdict(list)
	for namespace, op in attachments:
		by_namespace[namespace].append(op)
	for namespace in sorted(by_namespace):
		lines += [f"namespace {namespace} {{", ""]
		for op in sorted(by_namespace[namespace], key=lambda item: item["name"]):
			lines += _emit_manual_autograd_attach(op)
		lines += [f"}} // namespace {namespace}", ""]
	lines += ["} // namespace OaGeneratedAutogradAttach", ""]
	return "\n".join(lines)


def write_manual_autograd_attach_header(
	schema_paths: list[Path], out_root: Path, *, dry_run: bool
) -> None:
	attachments: list[tuple[str, dict]] = []
	for schema_path in schema_paths:
		with schema_path.open("rb") as file:
			data = tomllib.load(file)
		domain = infer_domain(schema_path)
		namespace = data.get("namespace", DOMAIN_NAMESPACE.get(domain, "OaFnMatrix"))
		for op in data.get("ops", []):
			if (
				op.get("body", "auto") == "manual_context"
				and op.get("autograd", {}).get("attach")
			):
				attachments.append((namespace, op))

	path = out_root / "Private" / "Oa" / "Ml" / "Autograd" / "AutogradAttach.gen.h"
	if dry_run:
		print(f"  would write: {path}")
		return
	write_generated_text(path, emit_manual_autograd_attach_header(attachments))


# ─── Python binding emission ───────────────────────────────────────────────


def emit_python_binding(namespace: str, op: dict) -> list[str]:
	python = op["python"]
	params = api_param_list(op, with_defaults=False)
	args = api_arg_list(op)
	python_name = python.get("name", op["name"])
	lines = [
		f'\tm.def("{python_name}", []({params}) {{',
		f"\t\treturn matrix_ptr({namespace}::{op['name']}({args}));",
		"\t},",
	]
	arg_specs = []
	for python_arg, api_param in zip(python["args"], op["api_params"]):
		_, _, default = _api_param_parts(api_param)
		spec = f'nb::arg("{python_arg}")'
		if default is not None:
			spec += f" = {default}"
		arg_specs.append(spec)
	lines.append("\t  " + ", ".join(arg_specs) + ",")
	lines.append("\t  nb::rv_policy::take_ownership,")
	doc = python.get("doc", op.get("notes", ""))
	lines.append(f"\t  {json.dumps(doc, ensure_ascii=True)});")
	lines.append("")
	return lines


def emit_python_bindings(bindings: list[tuple[str, dict]]) -> str:
	lines = [
		"// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.",
		"// Source of truth: Tools/FnAutogen/Schema/**.toml [ops.python].",
		"// Included inside the owning Bind* function.",
		"",
	]
	for namespace, op in sorted(bindings, key=lambda item: item[1]["name"]):
		lines.extend(emit_python_binding(namespace, op))
	return "\n".join(lines).rstrip() + "\n"


def write_python_bindings(
	schema_paths: list[Path], out_root: Path, *, dry_run: bool
) -> None:
	groups: dict[tuple[str, str], list[tuple[str, dict]]] = defaultdict(list)
	for schema_path in schema_paths:
		with schema_path.open("rb") as file:
			data = tomllib.load(file)
		domain = infer_domain(schema_path)
		namespace = data.get("namespace", DOMAIN_NAMESPACE.get(domain, "OaFnMatrix"))
		file_prefix = data.get("file_prefix", DOMAIN_FILE_PREFIX.get(domain, "FnMatrix"))
		for op in data.get("ops", []):
			if "python" in op:
				groups[(domain, file_prefix)].append((namespace, op))

	for (domain, file_prefix), bindings in sorted(groups.items()):
		path = out_root / "Python" / domain / f"{file_prefix}Ops.gen.inl"
		if dry_run:
			print(f"  would write: {path}")
			continue
		write_generated_text(path, emit_python_bindings(bindings))


# ─── Operation reference emission ─────────────────────────────────────────


def emit_operation_reference(contracts: list[tuple[str, dict]]) -> str:
	lines = [
		"<!-- AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT. -->",
		"<!-- Source of truth: Tools/FnAutogen/Schema/**.toml. -->",
		"# OA operation contracts",
		"",
		"This reference is generated from the same schemas as the C++ declarations,",
		"Python registrations, and runtime semantic hashes.",
		"",
	]
	for namespace, op in sorted(contracts, key=lambda item: (item[0], item[1]["name"])):
		contract = op["contract"]
		attributes = semantic_attribute_specs(op)
		attribute_text = ", ".join(
			f"{attribute['name']}:{attribute['kind']}"
			for attribute in attributes
		) if attributes else "none"
		cpp_surface = (
			"internal session command"
			if op.get("kind") == "session_command"
			else f"`{op.get('api_return', 'OaMatrix')} {op['name']}({api_param_list(op)})`"
		)
		lines += [
			f"## `{namespace}::{op['name']}`",
			"",
			f"- C++: {cpp_surface}",
			f"- Contract: `0x{operation_contract_hash(namespace, op):016x}`",
			f"- Values: `{', '.join(contract['input_kinds'])}` → `{', '.join(contract['output_kinds'])}`",
			f"- Shape: `{contract['shape_rule']}`",
			f"- Dtype: `{contract['dtype_rule']}`",
			f"- Effects: `{', '.join(contract['effects'])}`",
			f"- Mutated inputs: `{contract['mutated_inputs']}`",
			f"- Output aliases: `{contract['output_alias_inputs']}`",
			f"- Attributes: `{attribute_text}`",
			f"- Control flow: `{contract['control_flow']}`",
			f"- Differentiation: `{contract['differentiation']}`",
			f"- Lowering: `{contract['lowering']}`",
		]
		if contract.get("value_validation") == "session_command":
			lines += [
				"- Value validation: private session command; `match_input` is the "
				"frozen descriptor sentinel, not generic homogeneous-dtype validation",
			]
		if python := op.get("python"):
			python_params = []
			for python_arg, api_param in zip(python["args"], op["api_params"]):
				_, _, default = _api_param_parts(api_param)
				python_params.append(
					python_arg if default is None else f"{python_arg}={default}"
				)
			lines.append(
				f"- Python: `{python.get('name', op['name'])}({', '.join(python_params)})`"
			)
		if autograd := op.get("autograd"):
			if grad_class := autograd.get("grad_class"):
				lines.append(
					f"- Autograd: `{grad_class}` (`{autograd.get('formula', 'manual')}`)"
				)
		lines += ["", op.get("notes", ""), ""]
	return "\n".join(lines).rstrip() + "\n"


def write_operation_reference(
	schema_paths: list[Path], out_root: Path, *, live: bool, dry_run: bool
) -> None:
	contracts: list[tuple[str, dict]] = []
	for schema_path in schema_paths:
		with schema_path.open("rb") as file:
			data = tomllib.load(file)
		domain = infer_domain(schema_path)
		namespace = data.get("namespace", DOMAIN_NAMESPACE.get(domain, "OaFnMatrix"))
		contracts.extend(
			(namespace, op) for op in data.get("ops", []) if "contract" in op
		)
	root = REPO_ROOT if live else out_root
	path = root / "Docs" / "Internal" / "Architecture" / "OaOperations.gen.md"
	if dry_run:
		print(f"  would write: {path}")
		return
	write_generated_text(path, emit_operation_reference(contracts))


# ─── Body emitters ────────────────────────────────────────────────────────


def _dispatch_id_arg(op: dict) -> str:
	"""Argument for OaVkDispatch::Run (string literal or OaComputeKernelId::*)."""
	if "dispatch_id_macro" in op:
		return f"OaComputeKernelId::{op['dispatch_id_macro']}"
	return f'"{op["kernel_forward"]}"'


def _output_alloc_stmt(op: dict, namespace: str = "OaFnMatrix") -> str:
	"""C++ statement: `OaMatrix out = ...;` matching the op's output spec."""
	out_spec = op.get("output", {})
	shape = out_spec.get("shape", "match_input")
	dtype = out_spec.get("dtype", "match_input")
	kind = op["kind"]
	
	# For nullary ops, we need explicit shape/dtype from extra_params or output spec
	if kind == "nullary_scalar":
		dt_expr = f"OaScalarType::{dtype}" if dtype != "match_input" else "OaScalarType::Float32"
		# nullary ops must specify shape via extra_params or output.shape
		if shape == "scalar_1d":
			return f"OaMatrix out = OaFnMatrix::Zeros(OaMatrixShape{{1}}, {dt_expr});"
		# For Fill, shape comes from extra_params (InShape)
		return f"OaMatrix out = OaFnMatrix::Empty(InShape, {dt_expr});"
	
	dt_expr = "InA.Dtype_" if dtype == "match_input" else f"OaScalarType::{dtype}"
	# Always use OaFnMatrix for utility functions (Zeros, Empty)
	if shape == "scalar_1d":
		return f"OaMatrix out = OaFnMatrix::Zeros(OaMatrixShape{{1}}, {dt_expr});"
	if shape == "last_dim_half":
		scalar_name = op.get("scalar_param", {}).get("name")
		param_check = (
			f" and static_cast<OaI64>(In{scalar_name}) == InA.Size(-1) / 2"
			if scalar_name else ""
		)
		return (
			"OaMatrixShape outShape = InA.Shape_;\n"
			f"\tassert(outShape.Rank > 0 and InA.Size(-1) % 2 == 0{param_check});\n"
			"\toutShape.Dims[static_cast<OaUsize>(outShape.Rank - 1)] = InA.Size(-1) / 2;\n"
			f"\tOaMatrix out = OaFnMatrix::Empty(outShape, {dt_expr});"
		)
	# default: match input
	return f"OaMatrix out = OaFnMatrix::Empty(InA.Shape_, {dt_expr});"


def _dispatch_workgroups_expr(op: dict) -> str:
	wg = op.get("dispatch_workgroups", "elemwise")
	if isinstance(wg, int):
		return str(wg)
	if wg == "elemwise":
		return "DivCeil(n, 256)"
	if wg == "output_elemwise":
		return "DivCeil(static_cast<OaU32>(out.NumElements()), 256)"
	fail(f"{op['name']}: unsupported dispatch_workgroups {wg!r}")
	return "1"  # unreachable


def emit_autograd_attach(
	op: dict, semantic_operation: str | None = None
) -> str:
	"""Emits the forward-attach tail for an op that declares a [ops.autograd] block.

	The block is purely the *attach* — it constructs a hand-written OaGradXxx
	(defined in <Oa/Ml/Autograd.h>) and assigns it to out.MutAutograd().GradFn
	when (a) the tape is active and (b) any of the declared inputs requires grad.

	Schema (under [ops.autograd]):
	  grad_class  — name of the *Grad class (defined in Oa/Ml/Autograd.h)
	  inputs      — list of parameter names; populates SetGraphInputs in slot order
	  saved       — list of parameter names; populates Saved_ in vector order
	  ctor_args   — list of expressions passed to OaMakeSharedPtr<grad_class>(...)

	Returns the empty string when the op has no autograd block.
	"""
	ag = op.get("autograd")
	if not ag or not ag.get("grad_class"):
		return ""
	grad_class = ag["grad_class"]
	inputs     = ag.get("inputs", [])
	saved      = ag.get("saved", [])
	ctor_args  = ag.get("ctor_args", [])
	if not inputs:
		fail(f"{op['name']}: autograd.inputs must be non-empty when grad_class is set")
		return ""
	req_check = " or ".join(f"{i}.RequiresGrad()" for i in inputs)
	ctor_call = "(" + ", ".join(ctor_args) + ")" if ctor_args else "()"
	saved_init = "{" + ", ".join(saved) + "}"
	inputs_init = "{" + ", ".join(inputs) + "}"
	semantic_attach = ""
	if semantic_operation is not None:
		semantic_attach = (
			"\t\tconst auto semanticAttached = OaFnAutograd::AttachSemantic(\n"
			f"\t\t\t_gradFn, {semantic_operation});\n"
			"\t\tif (not semanticAttached.IsOk()) return {};\n"
		)
	broadcast_operation = ""
	if ag.get("attach") == "broadcast_binary":
		broadcast_operation = (
			f"\t\t_gradFn->Op_ = OaBcastBinOp::{ag['broadcast_op']};\n"
		)
	return (
		f"\tif (OaFnAutograd::IsEnabled() and ({req_check})) {{\n"
		f"\t\tauto _gradFn = OaMakeSharedPtr<{grad_class}>{ctor_call};\n"
		f"{broadcast_operation}"
		f"\t\t_gradFn->Saved_ = OaVec<OaMatrix>{saved_init};\n"
		f"\t\t_gradFn->SetGraphInputs(OaVec<OaMatrix>{inputs_init});\n"
		f"\t\t_gradFn->SequenceNr_ = OaFnAutograd::NextSeq();\n"
		f"\t\t_gradFn->OutputShape_ = out.GetShape();  // tape normalizes upstream d to this; protects elementwise bwd against viewed-shape fan-out grads\n"
		f"{semantic_attach}"
		f"\t\tout.MutAutograd().GradFn = _gradFn;\n"
		f"\t\tout.SetRequiresGrad(true);\n"
		f"\t}}\n"
	)


def _semantic_attribute_cpp_values(op: dict) -> list[str]:
	values: list[str] = []
	scalar = op.get("scalar_param")
	for index, attribute in enumerate(semantic_attribute_specs(op)):
		if scalar is not None and index == 0:
			source = f"In{scalar['name']}"
		else:
			source = attribute.get("source")
			if not source:
				fail(
					f"{op['name']}: generated semantic attribute "
					f"{attribute['name']!r} requires source"
				)
		factory = _ATTRIBUTE_FACTORY_CPP[attribute["kind"]]
		values.append(
			f'OaOperationAttribute::{factory}("{attribute["name"]}", {source})'
		)
	return values


def emit_context_body(op: dict, namespace: str = "OaFnMatrix") -> str:
	"""Body of the context-based function (records to context).

	Skipped when body = manual_context (session recorders) or cpu_util
	(host-only utilities) — those bodies are handwritten in a separate .cpp.
	"""
	if op.get("body", "auto") in ("manual_context", "cpu_util"):
		return ""
	name = op["name"]
	body = op.get("body", "auto")
	loss_name = op.get("loss_name")
	name_stmt = f'\tSetLastName("{loss_name}");\n' if namespace == "OaFnLoss" and loss_name else ""
	if body == "cpp_expr":
		if op.get("cpp_body"):
			body_src = "\n".join(f"\t{line}" if line else "" for line in op["cpp_body"].splitlines())
		else:
			body_src = f"\treturn {op['cpp_expr']};"
		return (
			f"OaMatrix {namespace}::{name}({cpp_param_list(op, with_defaults=False)}) {{\n"
			f"{name_stmt}"
			f"{body_src}\n"
			f"}}\n"
		)
	immediate = op.get("immediate", {})
	alias = immediate.get("alias_of")
	if alias:
		# Alias path (Neg → Scale(-1))
		return (
			f"OaMatrix {namespace}::{name}(const OaMatrix& InA) {{\n"
			f"\treturn Scale(InA, {alias['scalar']}f);\n"
			f"}}\n"
		)
	kind = op["kind"]
	push_struct = "struct { OaU32 Count; } push{n};"
	
	# Autograd removed - no longer tracking differentiability
	# Handle bias_add_broadcast special case
	if body == "bias_add_broadcast":
		kind = "binary"
		mats_init = "{&out, &InB}"
		access = "{OaBufferAccess::ReadWrite, OaBufferAccess::Read}"
		push_struct = (
			"OaU32 rows = static_cast<OaU32>(InA.NumElements() / InA.Size(-1));\n"
			"\tOaU32 cols = static_cast<OaU32>(InA.Size(-1));\n"
			"\tstruct { OaU32 Rows; OaU32 Cols; } push{rows, cols};"
		)
	elif kind == "binary":
		mats_init = "{&InA, &InB, &out}"
		access = "{OaBufferAccess::Read, OaBufferAccess::Read, OaBufferAccess::Write}"
	elif kind in ("unary", "reduce_full"):
		mats_init = "{&InA, &out}"
		access = "{OaBufferAccess::Read, OaBufferAccess::Write}"
	elif kind == "unary_scalar":
		sp = op["scalar_param"]
		push_struct = (
			"struct { OaU32 Count; " + sp["type"] + " " + sp["push_field"]
			+ "; } push{n, In" + sp["name"] + "};"
		)
		mats_init = "{&InA, &out}"
		access = "{OaBufferAccess::Read, OaBufferAccess::Write}"
	elif kind == "nullary_scalar":
		sp = op["scalar_param"]
		push_struct = (
			"struct { OaU32 Count; " + sp["type"] + " " + sp["push_field"]
			+ "; } push{n, In" + sp["name"] + "};"
		)
		mats_init = "{&out}"
		access = "{OaBufferAccess::Write}"
	else:
		# Unsupported kind in autogen body
		return ""
	
	# Opt-in: push extra_params after Count, matching the manual shader's
	# PushConstants field order (schema key: push_extra_params = true).
	# OaU8 params are widened to OaU32 — Slang push fields are 4-byte `uint`,
	# and a 1-byte C++ field would leave the shader reading stale padding.
	push_extras = (
		op.get("push_extra_params", False)
		and op.get("extra_params")
		and kind in ("unary", "binary")
	)
	if push_extras:
		fields = "".join(
			f" {'OaU32' if ep['type'] == 'OaU8' else ep['type']} {ep['name']};"
			for ep in op["extra_params"]
		)
		inits = "".join(
			f", static_cast<OaU32>(In{ep['name']})" if ep["type"] == "OaU8"
			else f", In{ep['name']}"
			for ep in op["extra_params"]
		)
		push_struct = "struct { OaU32 Count;" + fields + " } push{n" + inits + "};"

	semantic_record = ""
	semantic_operation = None
	if "contract" in op:
		if kind == "binary":
			semantic_inputs = "{&InA, &InB}"
		elif kind in ("unary", "unary_scalar", "reduce_full"):
			semantic_inputs = "{&InA}"
		elif kind == "nullary_scalar":
			semantic_inputs = "{}"
		else:
			fail(f"{name}: unsupported generated semantic operation kind {kind!r}")
		attribute_values = _semantic_attribute_cpp_values(op)
		semantic_attributes = "{" + ", ".join(attribute_values) + "}"
		semantic_record = (
			f"\tconst auto semantic = ctx.RecordOperation(\n"
			f"\t\tOaOperationRegistry::{name}, {semantic_inputs}, {{&out}},\n"
			f"\t\t{semantic_attributes});\n"
			"\tif (not semantic.IsOk()) return {};\n"
		)
		semantic_operation = "semantic.GetValue()"

	# Autograd attach: appended inside the function body, right before `return out;`
	autograd_block = emit_autograd_attach(op, semantic_operation)

	# Mark extra params as unused if we don't consume them
	ignore_extra = "" if push_extras else "".join(
		f"\t(void)In{ep['name']};\n" for ep in op.get("extra_params", [])
	)
	out_alloc = _output_alloc_stmt(op, namespace)
	copy_prefix = ""
	if body == "bias_add_broadcast":
		copy_dispatch = (
			",\n\t\t1, 1, "
			f"OaOperationRegistry::{name}.Name, 0,\n\t\t"
			f"OaOperationRegistry::{name}.Hash, 0, 0, semantic.GetValue()"
			if semantic_operation is not None else ""
		)
		copy_prefix = (
			"\tstruct { OaU32 Count; } copyPush{n};\n"
			"\tOaBufferAccess copyAccess[] = {OaBufferAccess::Read, OaBufferAccess::Write};\n"
			"\tctx.Add(\"Copy\", {&InA, &out}, copyAccess, &copyPush, "
			f"sizeof(copyPush), DivCeil(n, 256){copy_dispatch});\n\n"
		)
	workgroups_expr = _dispatch_workgroups_expr(op)
	if body == "bias_add_broadcast":
		workgroups_expr = "DivCeil(rows * cols, 256)"
	
	# Kernels dispatched over a shape-changing output must receive that same
	# output element count in their bounds push. Passing the input count here
	# made half-width gated activations (SiluMul/Geglu) write one complete output
	# tensor past their allocation even though their dispatch group count was
	# correctly derived from the output.
	n_expr = (
		"static_cast<OaU32>(out.NumElements())"
		if kind == "nullary_scalar" or op.get("dispatch_workgroups") == "output_elemwise"
		else "static_cast<OaU32>(InA.NumElements())"
	)
	dispatch_identity = (
		",\n\t\t1, 1, "
		f"OaOperationRegistry::{name}.Name, 0,\n\t\t"
		f"OaOperationRegistry::{name}.Hash, 0, 0, semantic.GetValue()"
		if semantic_operation is not None else ""
	)
	
	return (
		f"OaMatrix {namespace}::{name}({cpp_param_list(op, with_defaults=False)}) {{\n"
		f"\tauto& ctx = OaContext::GetDefault();\n"
		f"{ignore_extra}"
		f"\t{out_alloc}\n"
		f"{semantic_record}"
		f"\tOaU32 n = {n_expr};\n"
		f"\n"
		f"{copy_prefix}"
		f"\t{push_struct}\n"
		f"\tOaBufferAccess access[] = {access};\n"
		f'\tctx.Add("{op["kernel_forward"]}", {mats_init}, access, &push, sizeof(push), '
		f"{workgroups_expr}{dispatch_identity});\n"
		f"{autograd_block}"
		f"\treturn out;\n"
		f"}}\n"
	)


def emit_cpp_file(ops: list[dict], schema_name: str, category: str,
                  domain: str = "Core", namespace: str | None = None) -> str:
	if namespace is None:
		namespace = DOMAIN_NAMESPACE.get(domain, "OaFnMatrix")
	out: list[str] = []
	out.append(GEN_HEADER.format(schema_name=schema_name))
	out.append(f"// {namespace} — {category} GPU operations.\n")
	out.append("// Context-based unified API: records operations to OaContext.\n\n")
	any_autograd = any(
		op.get("autograd", {}).get("grad_class")
		and op.get("body", "auto") not in ("manual_context", "cpu_util")
		for op in ops
	)
	any_contract = any(
		"contract" in op
		and op.get("body", "auto") not in ("manual_context", "cpu_util")
		for op in ops
	)
	if any_autograd:
		out.append("#include <Oa/Ml/Autograd/Nodes.h>\n")
	out.append("#include <Oa/Core/Matrix.h>\n")
	out.append("#include <Oa/Core/FnMatrix.h>\n")
	if any_contract:
		out.append("#include <Oa/Core/Operation.h>\n")
	# Public header for the target namespace in this domain, when one exists.
	# Keyed by (domain, namespace) — Core/Ml/Ui all use OaFnMatrix but live in
	# different headers.
	ns_header = NAMESPACE_HEADER.get((domain, namespace))
	if ns_header:
		out.append(f"#include <{ns_header}>\n")
	out.append("#include <Oa/Core/Status.h>\n")
	out.append("#include <Oa/Core/Types.h>\n")
	out.append("#include <Oa/Core/BufferAccess.h>\n")
	out.append("#include <Oa/Runtime/Context.h>\n")
	out.append("#include <Oa/Runtime/Engine.h>\n")
	out.append("#include <Oa/Core/Validation.h>\n\n")
	out.append("#include <cassert>\n\n")
	needs_div_ceil = any(
		op.get("body", "auto") not in ("manual_context", "cpu_util", "cpp_expr")
		for op in ops
	)
	if needs_div_ceil:
		out.append("static OaU32 DivCeil(OaU32 InA, OaU32 InB) { return (InA + InB - 1) / InB; }\n\n")
	for op in ops:
		# Manual implementations can still generate their mechanical global-engine
		# forwarding overload. Validation/dispatch/composition remains hand-written.
		body = emit_manual_forwarder(op, namespace)
		if not body:
			body = emit_context_body(op, namespace)
		if body:
			hdr = f"// ─── {op['name']} ({op.get('notes', '').rstrip('.')}) " + "─" * 4
			out.append(hdr[:78].rstrip() + "\n\n")
			out.append(body + "\n")
	# Generated translation units have exactly one final newline. In particular,
	# all-manual schemas must not accumulate a second blank line at EOF.
	return "".join(out).rstrip() + "\n"


# ─── Slang emission ────────────────────────────────────────────────────────

SLANG_BINARY = """\
// AUTO-GENERATED from {schema_name} — DO NOT EDIT.
// Kernel: {kernel} ({notes})

import Storage;

struct PushConstants {{
\tuint a_idx;
\tuint b_idx;
\tuint out_idx;
\tuint count;
}};

[[vk::push_constant]] PushConstants pc;

[[vk::binding(0, 0)]] RWByteAddressBuffer heap[];

[shader("compute")]
[numthreads(256, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID) {{
\tuint idx = tid.x;
\tif (idx < pc.count) {{
\t\tlet a = OaLoad(heap[pc.a_idx], idx);
\t\tlet b = OaLoad(heap[pc.b_idx], idx);
\t\tOaStore(heap[pc.out_idx], idx, {forward_op});
\t}}
}}
"""

SLANG_UNARY = """\
// AUTO-GENERATED from {schema_name} — DO NOT EDIT.
// Kernel: {kernel} ({notes})

import Storage;

struct PushConstants {{
\tuint x_idx;
\tuint out_idx;
\tuint count;
}};

[[vk::push_constant]] PushConstants pc;

[[vk::binding(0, 0)]] RWByteAddressBuffer heap[];

[shader("compute")]
[numthreads(256, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID) {{
\tuint idx = tid.x;
\tif (idx < pc.count) {{
\t\tlet a = OaLoad(heap[pc.x_idx], idx);
\t\tOaStore(heap[pc.out_idx], idx, {forward_op});
\t}}
}}
"""

SLANG_UNARY_SCALAR = """\
// AUTO-GENERATED from {schema_name} — DO NOT EDIT.
// Kernel: {kernel} ({notes})

import Storage;

struct PushConstants {{
\tuint x_idx;
\tuint out_idx;
\tuint count;
\t{scalar_type} {scalar_field};
}};

[[vk::push_constant]] PushConstants pc;

[[vk::binding(0, 0)]] RWByteAddressBuffer heap[];

[shader("compute")]
[numthreads(256, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID) {{
\tuint idx = tid.x;
\tif (idx < pc.count) {{
\t\tlet a = OaLoad(heap[pc.x_idx], idx);
\t\tOaStore(heap[pc.out_idx], idx, {forward_op});
\t}}
}}
"""

SLANG_NULLARY_SCALAR = """\
// AUTO-GENERATED from {schema_name} — DO NOT EDIT.
// Kernel: {kernel} ({notes})

import Storage;

struct PushConstants {{
\tuint out_idx;
\tuint count;
\t{scalar_type} {scalar_field};
}};

[[vk::push_constant]] PushConstants pc;

[[vk::binding(0, 0)]] RWByteAddressBuffer heap[];

[shader("compute")]
[numthreads(256, 1, 1)]
void main(uint3 tid : SV_DispatchThreadID) {{
\tuint idx = tid.x;
\tif (idx < pc.count) {{
\t\tOaStore(heap[pc.out_idx], idx, {forward_op});
\t}}
}}
"""

SLANG_TYPE_MAP = {"OaF32": "float", "OaU32": "uint", "OaI32": "int"}


def emit_slang(op: dict, schema_name: str) -> str:
	common = {
		"schema_name": schema_name,
		"kernel": op["kernel_forward"],
		"notes": op.get("notes", "").rstrip("."),
		"forward_op": op.get("forward_op", ""),
	}
	if op["kind"] == "binary":
		return SLANG_BINARY.format(**common)
	if op["kind"] == "unary":
		return SLANG_UNARY.format(**common)
	if op["kind"] == "unary_scalar":
		sp = op["scalar_param"]
		return SLANG_UNARY_SCALAR.format(
			**common,
			scalar_type=SLANG_TYPE_MAP.get(sp["type"], "float"),
			scalar_field=sp["push_field"],
		)
	if op["kind"] == "nullary_scalar":
		sp = op["scalar_param"]
		return SLANG_NULLARY_SCALAR.format(
			**common,
			scalar_type=SLANG_TYPE_MAP.get(sp["type"], "float"),
			scalar_field=sp["push_field"],
		)
	fail(f"{op['name']}: slang emission not supported for kind {op['kind']!r}")
	return ""


# ─── Autograd class emission ──────────────────────────────────────────────


AUTOGRAD_HEADER_PREAMBLE = (
	"// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.\n"
	"// Source of truth: Tools/FnAutogen/Schema/{schema_name}.\n"
	"// Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live\n"
	"//\n"
	"// Fragment included from inside `class OaGradFn {{ ... }}` in Autograd.h.\n"
	"// Defines the OaGradNode subclasses for each differentiable op.\n"
)


def _emit_autograd_backward_body(op: dict) -> str | None:
	"""Generate the Backward() body for an op based on its formula field.
	Returns None for 'manual' or unsupported formulas."""
	ag = op.get("autograd", {})
	formula = ag.get("formula", "manual")
	if formula == "manual":
		return None

	# Determine scalar member name from ctor_args
	ctor_args = ag.get("ctor_args", [])
	scalar_member = ""
	if ctor_args:
		# InScalar -> Scalar_, InExponent -> Exponent_, etc.
		arg = ctor_args[0]
		if arg.startswith("In"):
			scalar_member = arg[2:] + "_"
		else:
			scalar_member = arg + "_"

	B = "\t\t"  # two tabs: inside class, inside Backward()
	body = ""
	if formula == "auto_binary_add":
		body = (
			f"{B}if (OutDIn.Size() > 0) OutDIn[0] = InDOut;\n"
			f"{B}if (OutDIn.Size() > 1) OutDIn[1] = InDOut;\n"
		)
	elif formula == "auto_binary_sub":
		body = (
			f"{B}if (OutDIn.Size() > 0) OutDIn[0] = InDOut;\n"
			f"{B}if (OutDIn.Size() > 1) OutDIn[1] = OaFnMatrix::Scale(InDOut, -1.0f);\n"
		)
	elif formula == "auto_binary_mul":
		body = (
			f"{B}const OaMatrix& a = Saved_[0];\n"
			f"{B}const OaMatrix& b = Saved_[1];\n"
			f"{B}if (OutDIn.Size() > 0) OutDIn[0] = OaFnMatrix::Mul(InDOut, b);\n"
			f"{B}if (OutDIn.Size() > 1) OutDIn[1] = OaFnMatrix::Mul(InDOut, a);\n"
		)
	elif formula == "auto_unary_identity":
		body = f"{B}if (OutDIn.Size() > 0) OutDIn[0] = InDOut;\n"
	elif formula == "auto_unary_neg":
		body = f"{B}if (OutDIn.Size() > 0) OutDIn[0] = OaFnMatrix::Scale(InDOut, -1.0f);\n"
	elif formula == "auto_unary_log":
		body = f"{B}if (OutDIn.Size() > 0) OutDIn[0] = OaFnMatrix::Div(InDOut, Saved_[0]);\n"
	elif formula == "auto_unary_sqrt":
		body = f"{B}if (OutDIn.Size() > 0) OutDIn[0] = OaFnMatrix::Div(InDOut, OaFnMatrix::Scale(Saved_[0], 2.0f));\n"
	elif formula == "auto_unary_exp":
		body = f"{B}if (OutDIn.Size() > 0) OutDIn[0] = OaFnMatrix::Mul(InDOut, Saved_[0]);\n"
	elif formula == "auto_unary_sin":
		body = f"{B}if (OutDIn.Size() > 0) OutDIn[0] = OaFnMatrix::Mul(InDOut, OaFnMatrix::Cos(Saved_[0]));\n"
	elif formula == "auto_unary_cos":
		body = f"{B}if (OutDIn.Size() > 0) OutDIn[0] = OaFnMatrix::Scale(OaFnMatrix::Mul(InDOut, OaFnMatrix::Sin(Saved_[0])), -1.0f);\n"
	elif formula == "auto_unary_reciprocal":
		body = (
			f"{B}if (OutDIn.Size() > 0) {{\n"
			f"{B}\tconst OaMatrix& out = Saved_[0];\n"
			f"{B}\tOutDIn[0] = OaFnMatrix::Scale(OaFnMatrix::Mul(InDOut, OaFnMatrix::Mul(out, out)), -1.0f);\n"
			f"{B}}}\n"
		)
	elif formula == "auto_unary_scalar_identity":
		body = f"{B}if (OutDIn.Size() > 0) OutDIn[0] = InDOut;\n"
	elif formula == "auto_unary_scalar_scale":
		body = f"{B}if (OutDIn.Size() > 0) OutDIn[0] = OaFnMatrix::Scale(InDOut, {scalar_member});\n"
	elif formula == "auto_unary_scalar_div_scalar":
		body = f"{B}if (OutDIn.Size() > 0) OutDIn[0] = OaFnMatrix::Scale(InDOut, 1.0f / {scalar_member});\n"
	elif formula == "auto_unary_scalar_pow":
		body = (
			f"{B}if (OutDIn.Size() > 0) {{\n"
			f"{B}\tconst OaMatrix& x = Saved_[0];\n"
			f"{B}\tauto dPow = OaFnMatrix::Pow(x, {scalar_member} - 1.0f);\n"
			f"{B}\tOutDIn[0] = OaFnMatrix::Scale(OaFnMatrix::Mul(InDOut, dPow), {scalar_member});\n"
			f"{B}}}\n"
		)
	elif formula == "auto_bwd_kernel":
		bwd_name = op["name"] + "Bwd"
		# Thread the saved scalar hyperparam (e.g. LeakyRelu/Elu alpha) into the
		# backward kernel. Without this the *Bwd call falls back to its defaulted
		# alpha, so a non-default alpha silently produces wrong input gradients.
		# scalar_member is non-empty only when the autograd block declares ctor_args.
		extra = f", {scalar_member}" if scalar_member else ""
		body = f"{B}if (OutDIn.Size() > 0) OutDIn[0] = OaFnMatrix::{bwd_name}(Saved_[0], InDOut{extra});\n"
	else:
		return None
	return body


def emit_autograd_class(op: dict) -> str:
	"""Emit `class OaGrad<Name> : public OaGradNode { ... };` for one op.
	Generates a full Backward() body when formula is auto-*. Manual gradient
	classes live in hand-written Autograd*.h files and deliberately emit
	nothing here; a generated file containing only "hand-written elsewhere"
	comments is not an API surface and must not exist."""
	ag = op.get("autograd", {})
	if not ag or not ag.get("grad_class"):
		return ""
	name = op["name"]
	grad_class = ag["grad_class"]

	# Scalar member lines
	scalar_decls = ""
	scalar_ctor = ""
	if ag.get("ctor_args"):
		# Emit ctor with typed args + member initialization
		# Derive member name from ctor arg (InScalar -> Scalar_)
		ctor_args = ag["ctor_args"]
		params = []
		inits = []
		members = []
		for arg in ctor_args:
			# Heuristic: arg like "InScalar" -> member "Scalar_"
			if arg.startswith("In"):
				member = arg[2:] + "_"
			else:
				member = arg + "_"
			params.append(f"OaF32 {arg}")
			inits.append(f"{member}({arg})")
			members.append(f"\tOaF32 {member};")
		scalar_ctor = (
			f"\texplicit {grad_class}({', '.join(params)}) noexcept "
			f": {', '.join(inits)} {{}}\n"
		)
		scalar_decls = "\n".join(members) + "\n"

	body = _emit_autograd_backward_body(op)
	if body is None:
		return ""

	# Auto-generated full class with Backward body
	return (
		f"class {grad_class} final : public OaGradNode {{\n"
		f"public:\n"
		f"{scalar_ctor}"
		f"\tvoid Backward(const OaMatrix& InDOut, OaVec<OaMatrix>& OutDIn) override {{\n"
		f"{body}"
		f"\t}}\n"
		f"{scalar_decls}"
		f"}};\n"
	)


def emit_autograd_header(ops: list[dict], schema_name: str, category: str, autograd_subdir: str = "Matrix") -> str:
	body_lines = []
	for op in ops:
		c = emit_autograd_class(op)
		if c:
			body_lines.append(c)
	if not body_lines:
		return ""
	lines = "\n".join(body_lines)
	return (
		f"// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.\n"
		f"// Source of truth: Tools/FnAutogen/Schema/{schema_name}.\n"
		f"// Output: Source/Private/Oa/Ml/Autograd/{autograd_subdir}/Autograd{category}.gen.h\n"
		f"// Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live\n"
		f"\n"
		f"#pragma once\n"
		f"\n"
		f"#include <Oa/Ml/Autograd.h>\n"
		f"#include <Oa/Core/FnMatrix.h>\n"
		f"#include <Oa/Ml/FnMatrix.h>\n"
		f"\n"
		f"// ─── {category} gradient nodes (autogenerated) ─────────────────────────────\n"
		f"\n"
		f"{lines}\n"
	)


# ─── Test emission ────────────────────────────────────────────────────────


TEST_FN_PREAMBLE = """\
// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/{schema_name}.
//
// Tests for context-backed public overloads.
// The public overload test doubles as the kernel correctness test —
// it calls OaFnMatrix::<Op>(...) which dispatches the SPIR-V kernel directly.
// CPU references come from each op's `forward_op` field.

#include <gtest/gtest.h>
#include <Oa/Core/FnMatrix.h>
{ml_include}#include <Oa/Runtime/Engine.h>
#include <Oa/Runtime/Context.h>
#include <Oa/Runtime/ComputeGraph.h>
#include <algorithm>
#include <cmath>
#include <numeric>
#include <vector>

static OaEngine* GRt = nullptr;

class TestFnMatrix{category} : public ::testing::Test {{
protected:
\tstatic void SetUpTestSuite() {{
\t\tOaEngineConfig cfg{{}};
\t\tcfg.AppName = "TestFnMatrix{category}";
\t\tauto r = OaEngine::Create(cfg);
\t\tASSERT_TRUE(r.IsOk()) << r.GetStatus().GetMessage();
\t\tstatic OaUniquePtr<OaEngine> rt = std::move(*r);
\t\tGRt = rt.get();
\t}}
}};

"""


# Operand symbols in forward_op → host array expressions for the CPU reference.
# Single-letter `a`/`b` are surrounded by `\b` (word boundary) so abs() etc.
# are not mangled. pc.<Field> → scalar (we pass via constant `kScalar`).
def _cpu_ref_expr(forward_op: str) -> str:
	expr = forward_op
	expr = re.sub(r"\bpc\.[A-Za-z_][A-Za-z0-9_]*\b", "kScalar", expr)
	expr = re.sub(r"\b(abs|log|sqrt|pow|max|min|exp|tanh)\b", r"std::\1", expr)
	# After std:: prefix, expand operand letters.
	expr = re.sub(r"(?<![A-Za-z_])a(?![A-Za-z_0-9])", "a_host[i]", expr)
	expr = re.sub(r"(?<![A-Za-z_])b(?![A-Za-z_0-9])", "b_host[i]", expr)
	return expr


def _emit_fn_test_call(op: dict) -> str:
	"""Emits the OaFnMatrix call for context-based API."""
	name = op["name"]
	kind = op["kind"]
	if kind == "binary":
		args = "a, b"
	elif kind in ("unary", "reduce_full"):
		args = "a"
	elif kind == "unary_scalar":
		args = "a, kScalar"
	elif kind == "nullary_scalar":
		# Factory convention: shape first, then value (Fill(shape, value)).
		test_config = op.get("test", {})
		scalar_value = test_config.get("scalar_value", "1.0f")
		args = f"OaMatrixShape{{N}}, {scalar_value}"
	else:
		return ""
	# Context is default parameter, so we don't need to pass it explicitly
	return f"OaFnMatrix::{name}({args})"


def _emit_fn_test(op: dict) -> str:
	"""High-level test: exercise OaFnMatrix::Op(...) with context API."""
	name = op["name"]
	kind = op["kind"]
	fwd = op.get("forward_op")
	# Check for test config - if present, use it; otherwise use forward_op
	test_config = op.get("test", {})
	if test_config.get("skip_test", False):
		return ""
	# If no test config and no forward_op, skip
	if not test_config and not fwd:
		return ""
	
	# Get CPU reference from test config or derive from forward_op
	cpu_ref = test_config.get("cpu_reference")
	if not cpu_ref:
		if not fwd:
			return ""
		cpu_ref = _cpu_ref_expr(fwd)
	
	# Get tolerance from test config or use defaults
	tolerance = test_config.get("tolerance", "1e-3f" if name in ("Log", "Sqrt", "Pow") else "1e-4f")
	test_size = test_config.get("test_sizes", [256])[0]
	
	positive_input = name in ("Log", "Sqrt", "Pow")
	rand_a = f"\tauto a = OaFnMatrix::Rand(OaMatrixShape{{N}});\n"
	if positive_input:
		rand_a = f"\tauto a = OaFnMatrix::Rand(OaMatrixShape{{N}});  // [0, 1)\n"
	
	# For nullary_scalar, we don't need input 'a'
	if kind == "nullary_scalar":
		rand_a = ""
	
	scalar_decl = ""
	if kind == "unary_scalar":
		scalar_value = test_config.get("scalar_value", "1.5f")
		scalar_decl = f"\tconstexpr OaF32 kScalar = {scalar_value};\n"
	
	binary_setup = ""
	if kind == "binary":
		binary_setup = (
			"\tauto b = OaFnMatrix::Rand(OaMatrixShape{N});\n"
			"\tstd::vector<float> b_host(N);\n"
			"\tASSERT_TRUE(OaFnMatrix::CopyToHost(b, b_host.data(), N * sizeof(float)).IsOk());\n"
		)
	
	# Select the recorder only; host reads in generated tests provide the explicit
	# observation boundary without destructor submission.
	context_setup = "\tOaContext::RecordingScope ctx_scope(OaContext::GetDefault());\n"
	
	# Handle reduce_full operations differently
	if kind == "reduce_full":
		return (
			f"TEST_VK(TestFnMatrix{op['category']}, {name}_Context) {{\n"
			f"\tconstexpr OaU32 N = {test_size};\n"
			f"{rand_a}"
			f"{context_setup}"
			f"\tauto out = {_emit_fn_test_call(op)};\n"
			f"\t// Context scope auto-executes and syncs at end of scope\n"
			f"\tstd::vector<float> a_host(N);\n"
			f"\tASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());\n"
			f"\tfloat want = {cpu_ref};\n"
			f"\tfloat got = 0.0f;\n"
			f"\tASSERT_TRUE(OaFnMatrix::CopyToHost(out, &got, sizeof(float)).IsOk());\n"
			f"\tEXPECT_NEAR(got, want, {tolerance}) << \"Reduction result mismatch\";\n"
			f"}}\n\n"
		)
	
	# Element-wise operations
	# For nullary operations, we don't need to copy input 'a'
	copy_a_host = ""
	if kind != "nullary_scalar":
		copy_a_host = (
			"\tstd::vector<float> a_host(N);\n"
			"\tASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());\n"
		)
	
	return (
		f"TEST_VK(TestFnMatrix{op['category']}, {name}_Context) {{\n"
		f"\tconstexpr OaU32 N = {test_size};\n"
		f"{scalar_decl}"
		f"{rand_a}"
		f"{binary_setup}"
		f"{context_setup}"
		f"\tauto out = {_emit_fn_test_call(op)};\n"
		f"\t// Context scope auto-executes and syncs at end of scope\n"
		f"{copy_a_host}"
		f"\tstd::vector<float> want(N);\n"
		f"\tfor (OaU32 i = 0; i < N; ++i) want[i] = {cpu_ref};\n"
		f"\tstd::vector<float> got(N);\n"
		f"\tASSERT_TRUE(OaFnMatrix::CopyToHost(out, got.data(), N * sizeof(float)).IsOk());\n"
		f"\tfor (OaU32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], {tolerance}) << \"i=\" << i;\n"
		f"}}\n\n"
	)


def _emit_backward_test(op: dict) -> str:
	"""Per-op backward smoke test: sets requires_grad, runs forward + Sum + Backward."""
	ag = op.get("autograd", {})
	if not ag.get("differentiable"):
		return ""
	# Skip backward tests for manual ops with complex signatures (extra_params)
	if op.get("body") == "manual_context" and op.get("extra_params"):
		return ""
	name = op["name"]
	kind = op["kind"]
	if kind == "binary":
		setup = (
			"\tauto a = OaFnMatrix::Full(OaMatrixShape{8}, 2.0f);\n"
			"\tauto b = OaFnMatrix::Full(OaMatrixShape{8}, 3.0f);\n"
			"\ta.SetRequiresGrad(true);\n"
			"\tb.SetRequiresGrad(true);\n"
		)
		fwd = f"OaFnMatrix::{name}(a, b)"
		checks = (
			'\tEXPECT_TRUE(a.HasGrad()) << "A should have grad after backward";\n'
			'\tEXPECT_TRUE(b.HasGrad()) << "B should have grad after backward";\n'
		)
	elif kind == "unary":
		setup = (
			"\tauto a = OaFnMatrix::Full(OaMatrixShape{8}, 2.0f);\n"
			"\ta.SetRequiresGrad(true);\n"
		)
		fwd = f"OaFnMatrix::{name}(a)"
		checks = '\tEXPECT_TRUE(a.HasGrad()) << "A should have grad after backward";\n'
	elif kind == "unary_scalar":
		setup = (
			"\tauto a = OaFnMatrix::Full(OaMatrixShape{8}, 2.0f);\n"
			"\ta.SetRequiresGrad(true);\n"
			"\tconstexpr OaF32 kScalar = 1.5f;\n"
		)
		fwd = f"OaFnMatrix::{name}(a, kScalar)"
		checks = '\tEXPECT_TRUE(a.HasGrad()) << "A should have grad after backward";\n'
	else:
		return ""
	return (
		f"TEST_VK(TestFnMatrix{op['category']}, {name}_Backward) {{\n"
		f"{setup}"
		f"\tauto c = OaFnMatrix::Sum({fwd});\n"
		f"\tc.Backward();\n"
		f"{checks}"
		f"}}\n\n"
	)


def emit_fn_tests(ops: list[dict], schema_name: str, category: str, domain: str) -> str:
	# Include ML header for ML domain tests
	ml_include = "#include <Oa/Ml/FnMatrix.h>\n" if domain == "Ml" else ""
	body = TEST_FN_PREAMBLE.format(schema_name=schema_name, category=category, ml_include=ml_include)
	for op in ops:
		# Single context-based test per op (replaces 3 mode tests)
		body += _emit_fn_test(op)
		body += _emit_backward_test(op)
	return body


def op_slang_path(op: dict, out_root: Path, *, live: bool) -> Path:
	"""Per-op .slang output path (only for ops that generate Slang)."""
	rel = op.get("slang_path", "Core/Shader/Compute/Flat").strip("/")
	name = op["name"]
	# Always use .gen.slang suffix to avoid overwriting manual .slang files
	suffix = ".gen.slang"
	# If slang_path already includes "Shader/Compute", use it directly
	if "Shader/Compute" in rel:
		return out_root / "Private" / "Oa" / rel / f"{name}{suffix}"
	# Otherwise, add Shader/Compute for backward compatibility
	parts = rel.split("/", 1)
	domain = parts[0]
	subdir = parts[1] if len(parts) > 1 else ""
	if subdir:
		return out_root / "Private" / "Oa" / domain / "Shader" / "Compute" / subdir / f"{name}{suffix}"
	return out_root / "Private" / "Oa" / domain / "Shader" / "Compute" / f"{name}{suffix}"


# ─── Schema-owned fixed-kernel metadata ─────────────────────────────────────


def collect_schema_kernels(schema_paths: list[Path]) -> list[dict]:
	"""Collect built-in kernel identities mechanically owned by operation schemas."""
	kernels: list[dict] = []
	for schema_path in schema_paths:
		with schema_path.open("rb") as file:
			data = tomllib.load(file)
		for op in data.get("ops", []):
			if "kernel" not in op:
				continue
			spec = dict(op["kernel"])
			spec["name"] = op.get("kernel_forward", "")
			spec["operation"] = op.get("name", "")
			spec["schema"] = schema_label(schema_path)
			kernels.append(spec)
	return kernels


def validate_schema_kernel_ownership(
	kernels: list[dict], registry_path: Path
) -> None:
	text = registry_path.read_text()
	pattern = re.compile(
		r'\{\s*"([^"]+)"\s*,\s*OA_COMPUTE_KERNEL_ID\('
		r'OaComputeKernelPrefix::([A-Za-z0-9_]+),\s*([0-9]+)\)'
	)
	manual_names: set[str] = set()
	manual_ids: set[tuple[str, int]] = set()
	for name, prefix, local in pattern.findall(text):
		manual_names.add(name)
		manual_ids.add((prefix, int(local)))

	seen_names: set[str] = set()
	seen_ids: set[tuple[str, int]] = set()
	seen_sources: set[str] = set()
	for kernel in kernels:
		ctx = f"{kernel.get('schema', '<schema>')}:{kernel.get('operation', '<op>')}"
		name = kernel.get("name", "")
		prefix = kernel.get("id_prefix")
		local = kernel.get("id_local")
		source = kernel.get("source")
		if not name:
			fail(f"{ctx}: schema-owned kernel is missing kernel_forward")
		if name in manual_names:
			fail(f"{ctx}: kernel {name!r} is duplicated in KernelRegistry.h")
		if name in seen_names:
			fail(f"{ctx}: duplicate schema-owned kernel name {name!r}")
		if isinstance(local, int) and not isinstance(local, bool):
			packed = (prefix, local)
			if packed in manual_ids:
				fail(f"{ctx}: kernel id {prefix}:{local} is already handwritten")
			if packed in seen_ids:
				fail(f"{ctx}: duplicate schema-owned kernel id {prefix}:{local}")
			seen_ids.add(packed)
		if source in seen_sources:
			fail(f"{ctx}: duplicate schema-owned kernel source {source!r}")
		seen_names.add(name)
		seen_sources.add(source)


def emit_schema_kernel_registry(kernels: list[dict], category: str) -> str:
	lines = [
		"// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.",
		"// Source of truth: Tools/FnAutogen/Schema/**.toml [ops.kernel].",
		"// Included inside the matching OaKernelRegistry fixed-family array.",
	]
	for kernel in sorted(
		(k for k in kernels if k["category"] == category),
		key=lambda item: (item["id_prefix"], item["id_local"], item["name"]),
	):
		lines.append(
			f'\t{{ "{kernel["name"]}", '
			f'OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::{kernel["id_prefix"]}, '
			f'{kernel["id_local"]}), OaComputeKernelCategory::{kernel["category"]}, '
			f'"{kernel["origin"]}" }},'
		)
	lines.append("")
	return "\n".join(lines)


def emit_schema_kernel_ids(kernels: list[dict]) -> str:
	lines = [
		"// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.",
		"// Source of truth: Tools/FnAutogen/Schema/**.toml [ops.kernel].",
		"// Included inside namespace OaComputeKernelId.",
	]
	for kernel in sorted(
		kernels,
		key=lambda item: (item["id_prefix"], item["id_local"], item["name"]),
	):
		lines.append(
			f"static constexpr OaKernelId {kernel['name']} = "
			f"OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::{kernel['id_prefix']}, "
			f"{kernel['id_local']});"
		)
	lines.append("")
	return "\n".join(lines)


def emit_schema_kernel_cmake(kernels: list[dict]) -> str:
	lines = [
		"# AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py -- DO NOT EDIT.",
		"# Source of truth: Tools/FnAutogen/Schema/**.toml [ops.kernel].",
	]
	by_category: dict[str, list[dict]] = defaultdict(list)
	for kernel in kernels:
		by_category[kernel["category"]].append(kernel)
	for category, entries in sorted(by_category.items()):
		variable = re.sub(r"(?<!^)(?=[A-Z])", "_", category).upper()
		entries.sort(key=lambda item: (item["id_prefix"], item["id_local"], item["name"]))
		lines += [f"set(OA_FN_AUTOGEN_{variable}_KERNEL_NAMES"]
		lines += [f"\t{entry['name']}" for entry in entries]
		lines += [")", f"set(OA_FN_AUTOGEN_{variable}_KERNEL_SOURCES"]
		lines += [f"\t{entry['source']}" for entry in entries]
		lines += [")"]
	lines.append("")
	return "\n".join(lines)


def write_schema_kernel_files(
	kernels: list[dict], out_root: Path, *, dry_run: bool
) -> None:
	for category in sorted({kernel["category"] for kernel in kernels}):
		path = (
			out_root / "Public" / "Oa" / "Core"
			/ f"KernelRegistry{category}.gen.inl"
		)
		if dry_run:
			print(f"  would write: {path}")
		else:
			write_generated_text(path, emit_schema_kernel_registry(kernels, category))
	id_path = out_root / "Public" / "Oa" / "Runtime" / "ComputeKernelIds.gen.inl"
	if dry_run:
		print(f"  would write: {id_path}")
	else:
		write_generated_text(id_path, emit_schema_kernel_ids(kernels))
	cmake_path = out_root / "Private" / "Oa" / "Core" / "FnAutogenKernels.gen.cmake"
	if dry_run:
		print(f"  would write: {cmake_path}")
	else:
		write_generated_text(cmake_path, emit_schema_kernel_cmake(kernels))


# ─── Manifest emission ───────────────────────────────────────────────────────


def _pascal_to_upper_snake(name: str) -> str:
	return re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper()


def _source_rel(path: Path, out_root: Path) -> str:
	# Always emit repo-root-relative "Source/..." paths so the .cmake content is
	# byte-identical in --live and scratch (--out) mode. The drift gate
	# (Tools/check_autogen_drift.py) relies on scratch output matching live.
	rel = path.relative_to(out_root).as_posix()
	return rel if rel.startswith("Source/") else f"Source/{rel}"


def _manifest_var(layout: SchemaLayout) -> str:
	if layout.domain == "Crypto":
		return f"OA_CRYPTO_{layout.cpp_subdir.upper()}_{_pascal_to_upper_snake(layout.file_prefix)}_GENERATED_SOURCES"
	return f"OA_{layout.domain.upper()}_{_pascal_to_upper_snake(layout.file_prefix)}_GENERATED_SOURCES"


def emit_umbrella_header(layouts: list[SchemaLayout]) -> str:
	first = layouts[0]
	lines = [
		GEN_HEADER.format(schema_name=f"{first.domain}/{first.file_prefix} manifest"),
		f"// {first.namespace} — generated declarations for {first.domain}/{first.cpp_subdir}.\n",
	]
	manifest_parent = (
		first.header_path.parents[1]
		if first.header_path.parent.name != first.cpp_subdir
		else first.header_path.parent
	)
	for layout in layouts:
		if not layout.emit_header:
			continue
		include_path = layout.header_path.relative_to(manifest_parent).as_posix()
		lines.append(f'#include "{include_path}"')
	lines.append("")
	return "\n".join(lines)


def emit_cmake_sources(layouts: list[SchemaLayout], out_root: Path) -> str:
	first = layouts[0]
	var_name = _manifest_var(first)
	lines = [
		"# AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py -- DO NOT EDIT.",
		"# Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live",
		f"set({var_name}",
	]
	for layout in layouts:
		if not layout.emit_cpp:
			continue
		lines.append(f"\t{_source_rel(layout.cpp_path, out_root)}")
	lines.append(")")
	lines.append("")
	return "\n".join(lines)


def write_manifest_files(layouts: list[SchemaLayout], out_root: Path, *, dry_run: bool) -> None:
	groups: dict[tuple[str, str, str, str], list[SchemaLayout]] = defaultdict(list)
	for layout in layouts:
		groups[(layout.domain, layout.namespace, layout.file_prefix, layout.cpp_subdir)].append(layout)

	generated_headers = {layout.header_path for layout in layouts if layout.emit_header}
	for grouped in groups.values():
		grouped.sort(key=lambda item: item.header_path.name)
		first = grouped[0]
		has_headers = any(layout.emit_header for layout in grouped)
		has_cpp = any(layout.emit_cpp for layout in grouped)
		
		manifest_parent = (
			out_root / "Private" / "Oa" / first.domain / first.cpp_subdir
		)
		manifest_header = manifest_parent / f"{first.file_prefix}.gen.h"
		# The public declaration manifest follows header_path. The build-source
		# manifest follows cpp_path and remains private.
		if first.cpp_path.parent.name == first.cpp_subdir:
			cmake_parent = first.cpp_path.parent
		else:
			cmake_parent = first.cpp_path.parent.parent
		manifest_cmake = cmake_parent / f"{first.file_prefix}Sources.gen.cmake"
		emit_header = (
			has_headers and manifest_header not in generated_headers and first.domain != "Crypto"
		)
		if dry_run:
			if emit_header:
				print(f"  would write: {manifest_header}")
			if has_cpp:
				print(f"  would write: {manifest_cmake}")
			continue
		if emit_header:
			write_generated_text(manifest_header, emit_umbrella_header(grouped))
			legacy_header = (
				out_root / "Public" / "Oa" / first.domain
				/ f"{first.file_prefix}.gen.h"
			)
			if legacy_header != manifest_header and legacy_header.exists():
				legacy_header.unlink()
			legacy_public_header = (
				out_root / "Public" / "Oa" / first.domain
				/ first.cpp_subdir / f"{first.file_prefix}.gen.h"
			)
			if legacy_public_header != manifest_header and legacy_public_header.exists():
				legacy_public_header.unlink()
		elif manifest_header.exists() and manifest_header not in generated_headers:
			manifest_header.unlink()
		legacy_public_header = (
			out_root / "Public" / "Oa" / first.domain
			/ f"{first.file_prefix}.gen.h"
		)
		if legacy_public_header != manifest_header and legacy_public_header.exists():
			legacy_public_header.unlink()
		if has_cpp:
			write_generated_text(manifest_cmake, emit_cmake_sources(grouped, out_root))
		elif manifest_cmake.exists():
			manifest_cmake.unlink()


# ─── Main ──────────────────────────────────────────────────────────────────


def process_schema(schema_path: Path, registry: set[str], out_root: Path,
                   *, live: bool, dry_run: bool) -> SchemaLayout | list[SchemaLayout]:
	with schema_path.open("rb") as f:
		data = tomllib.load(f)
	ops = data.get("ops", [])
	if not ops:
		fail(f"no [[ops]] entries in {schema_path}")
	for op in ops:
		if op.get("api_params"):
			op.setdefault("generate_engine_overload", data.get("generate_engine_overloads", False))
			op.setdefault("generate_forwarder", data.get("generate_forwarders", False))
	validate_schema_metadata(schema_path, data)
	validate_schema(schema_path, ops, registry)
	category, file_category = category_from_schema(schema_path, data)
	any_manual = any(op.get("body", "auto") == "manual_context" for op in ops)
	mode = "additive (manual bodies)" if any_manual else "full autogen"
	print(f"oafnautogen: {schema_path.name} — {len(ops)} ops, category={category}, "
	      f"file_category={file_category}, mode={mode}")
	
	# For Loss domain, emit per-function subdirectories (e.g., /Loss/Mse/FnLossMse.gen.h)
	domain = infer_domain(schema_path)
	namespace = data.get("namespace", DOMAIN_NAMESPACE.get(domain, "OaFnMatrix"))
	file_prefix = data.get("file_prefix", DOMAIN_FILE_PREFIX.get(domain, "FnMatrix"))
	cpp_subdir = data.get("cpp_subdir", infer_cpp_subdir(domain, file_category))

	def emits_header(op: dict) -> bool:
		return op.get("generate_declaration", True) and (
			op.get("body", "auto") not in ("manual_context", "cpu_util")
			or bool(op.get("api_params"))
		)

	def emits_cpp(op: dict) -> bool:
		return op.get("body", "auto") not in ("manual_context", "cpu_util") or bool(
			op.get("api_params") and op.get("generate_forwarder", False)
		)
	
	if domain == "Ml" and cpp_subdir == "FnLoss":
		# Per-function subdirectories for Loss
		layouts = []
		for op in ops:
			op_name = op["name"]
			header_subdir = out_root / "Private" / "Oa" / domain / cpp_subdir / op_name
			cpp_subdir_path = out_root / "Private" / "Oa" / domain / cpp_subdir / op_name
			h_path = header_subdir / f"{file_prefix}{op_name}.gen.h"
			cpp_path = cpp_subdir_path / f"{file_prefix}{op_name}.gen.cpp"
			schema_name = schema_label(schema_path)
			op_emit_header = emits_header(op)
			op_emit_cpp = emits_cpp(op)
			
			if dry_run:
				if op_emit_header:
					print(f"  would write: {h_path}")
				if op_emit_cpp:
					print(f"  would write: {cpp_path}")
				layouts.append(SchemaLayout(
					domain=domain,
					namespace=namespace,
					file_prefix=file_prefix,
					cpp_subdir=cpp_subdir,
					header_path=h_path,
					cpp_path=cpp_path,
					autograd_header_path=Path(""),
					test_path=Path(""),
					emit_header=op_emit_header,
					emit_cpp=op_emit_cpp,
				))
				continue
			
			header_subdir.mkdir(parents=True, exist_ok=True)
			cpp_subdir_path.mkdir(parents=True, exist_ok=True)
			if op_emit_header:
				write_generated_text(h_path, emit_header_fragment([op], schema_name, op_name, namespace))
				legacy_public_header = (
					out_root / "Public" / "Oa" / domain / cpp_subdir
					/ op_name / h_path.name
				)
				if legacy_public_header.exists():
					legacy_public_header.unlink()
			elif h_path.exists():
				h_path.unlink()
			if op_emit_cpp:
				write_generated_text(cpp_path, emit_cpp_file([op], schema_name, op_name, domain, namespace))
			elif cpp_path.exists():
				cpp_path.unlink()
			print(f"  wrote {op_name}: header={op_emit_header}, cpp={op_emit_cpp}")
			layouts.append(SchemaLayout(
				domain=domain,
				namespace=namespace,
				file_prefix=file_prefix,
				cpp_subdir=cpp_subdir,
				header_path=h_path,
				cpp_path=cpp_path,
				autograd_header_path=Path(""),
				test_path=Path(""),
				emit_header=op_emit_header,
				emit_cpp=op_emit_cpp,
			))
		# Return list of layouts for Loss domain
		return layouts
	
	# Standard processing for other domains
	emit_header = any(emits_header(op) for op in ops)
	emit_cpp = any(emits_cpp(op) for op in ops)
	layout = build_schema_layout(
		schema_path, data, file_category, out_root, live=live,
		emit_header=emit_header, emit_cpp=emit_cpp,
	)
	schema_name = schema_label(schema_path)
	test_body = emit_fn_tests(ops, schema_name, file_category, layout.domain)
	# Emit tests if any op has forward_op OR has test config
	emit_tests = any(op.get("forward_op") or op.get("test") for op in ops)
	if dry_run:
		if emit_header:
			print(f"  would write: {layout.header_path}")
		if emit_cpp:
			print(f"  would write: {layout.cpp_path}")
		if emit_tests:
			print(f"  would write: {layout.test_path}")
		for op in ops:
			if op.get("forward_op"):
				print(f"  would write: {op_slang_path(op, out_root, live=live)}")
		return layout
	if emit_header:
		write_generated_text(layout.header_path, emit_header_fragment(ops, schema_name, category, layout.namespace))
	elif layout.header_path.exists():
		layout.header_path.unlink()
	relative_header = layout.header_path.relative_to(
		out_root / "Private" / "Oa")
	legacy_public_header = out_root / "Public" / "Oa" / relative_header
	if legacy_public_header.exists():
		legacy_public_header.unlink()
	if emit_cpp:
		write_generated_text(layout.cpp_path, emit_cpp_file(ops, schema_name, category, layout.domain, layout.namespace))
	elif layout.cpp_path.exists():
		layout.cpp_path.unlink()
	if emit_tests:
		write_generated_text(layout.test_path, test_body)
	elif layout.test_path.exists():
		layout.test_path.unlink()
	n_slang = 0
	for op in ops:
		if op.get("forward_op"):
			sp = op_slang_path(op, out_root, live=live)
			# Skip if manual .slang file exists (check without .gen suffix)
			manual_path = sp.parent / f"{op['name']}.slang"
			if manual_path.exists() and sp.name.endswith('.gen.slang'):
				continue
			write_generated_text(sp, emit_slang(op, schema_name))
			n_slang += 1
	# Autograd generation
	autograd_subdir = layout.autograd_header_path.parent.name if layout.autograd_header_path else "Matrix"
	autograd_body = emit_autograd_header(ops, schema_name, file_category, autograd_subdir)
	if autograd_body and layout.autograd_header_path:
		write_generated_text(layout.autograd_header_path, autograd_body)
		print(f"  wrote {layout.autograd_header_path.name}")
	elif layout.autograd_header_path and layout.autograd_header_path.exists():
		layout.autograd_header_path.unlink()
	print(f"  wrote {schema_path.name}: header={emit_header}, cpp={emit_cpp}, slang={n_slang}")
	return layout


def main() -> int:
	ap = argparse.ArgumentParser(description="Generate OaFn* C++/Slang from schema.")
	ap.add_argument("--schema-dir", type=Path, default=SCHEMA_DIR,
	                help="Directory containing *.toml schemas (default: Schema/)")
	ap.add_argument("--schema", type=Path, default=None,
	                help="Single schema file (overrides --schema-dir)")
	ap.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY,
	                help="KernelRegistry.h to cross-check kernel names against")
	ap.add_argument("--out", type=Path, default=DEFAULT_OUTPUT,
	                help="Output root (default: Tools/FnAutogen/Output)")
	ap.add_argument("--live", action="store_true",
	                help="Write drop-in replacements directly to Source/ tree.")
	ap.add_argument("--dry-run", action="store_true",
	                help="Print summary, don't write files")
	args = ap.parse_args()
	if args.live and args.schema and not args.dry_run:
		fail("--schema cannot be combined with --live because shared manifests require the complete schema set")
	out_root = LIVE_SOURCE_ROOT if args.live else args.out
	if args.live:
		print("oafnautogen: LIVE MODE — writing to Source/ tree (overwrites hand-written files)")
	if args.schema:
		schemas = [args.schema]
	else:
		# Recursively find all .toml files in Schema/ subdirectories
		schemas = sorted(args.schema_dir.rglob("*.toml"))
		if not schemas:
			fail(f"no schemas found in {args.schema_dir}")
	schema_kernels = collect_schema_kernels(schemas)
	validate_schema_kernel_ownership(schema_kernels, args.registry)
	registry = load_kernel_registry(args.registry)
	registry.update(kernel["name"] for kernel in schema_kernels)
	print(
		f"oafnautogen: registry {args.registry.name} — {len(registry)} kernels "
		f"({len(schema_kernels)} schema-owned)"
	)
	layouts = []
	for schema_path in schemas:
		result = process_schema(schema_path, registry, out_root, live=args.live, dry_run=args.dry_run)
		# process_schema may return a list (for Loss) or a single SchemaLayout
		if isinstance(result, list):
			layouts.extend(result)
		else:
			layouts.append(result)
	write_manifest_files(layouts, out_root, dry_run=args.dry_run)
	write_operation_registry(schemas, out_root, dry_run=args.dry_run)
	write_manual_autograd_attach_header(schemas, out_root, dry_run=args.dry_run)
	write_python_bindings(schemas, out_root, dry_run=args.dry_run)
	write_schema_kernel_files(schema_kernels, out_root, dry_run=args.dry_run)
	write_operation_reference(
		schemas, out_root, live=args.live, dry_run=args.dry_run
	)
	return 0


if __name__ == "__main__":
	sys.exit(main())
