// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT.
// source of truth: tools/nnAutogen/schema/ml/mlNnPool.toml.
// Regenerate via: python3 tools/nnAutogen/oannautogen.py --live

#pragma once

#include <oa/ml/module.h>

#include <initializer_list>

namespace oa {

/// MaxPool2d: 2D max pooling layer.
class MaxPool2d : public Module {
public:
	MaxPool2d(oa::I32 inKernelSize, oa::I32 inStride = -1, oa::I32 inPadding = 0);
	Matrix forward(const Matrix& inInput) override;

private:
	oa::I32 kernelSize_;
	oa::I32 stride_;
	oa::I32 padding_;
};

} // namespace oa
