// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT.
// source of truth: tools/nnAutogen/schema/ml/mlNnActivation.toml.
// Regenerate via: python3 tools/nnAutogen/oannautogen.py --live

#pragma once

#include <oa/ml/module.h>

#include <initializer_list>

namespace oa {

/// Relu: ReLU activation layer.
class Relu : public Module {
public:
	Relu() = default;
	Matrix forward(const Matrix& inInput) override;
};

} // namespace oa
