// AUTO-GENERATED by tools/fnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: tools/fnAutogen/schema/core/coreFnMatrixRng.toml.
// Regenerate via: python3 tools/fnAutogen/oafnautogen.py --live
// oa::FnMatrix — Rng GPU operations.
// Unified API: records operations to oa::ExecutionSession.

#include <oa/core/matrix.h>
#include <oa/core/fnMatrix.h>
#include <oa/core/op.h>
#include <oa/core/status.h>
#include <oa/core/types.h>
#include <oa/core/bufferAccess.h>
#include <oa/runtime/executionSession.h>
#include <oa/core/validation.h>

static oa::U32 divCeil(oa::U32 inA, oa::U32 inB) { return (inA + inB - 1) / inB; }

// ─── fill (Create a Float32 matrix filled with a constant value) ────

oa::Matrix oa::FnMatrix::fill(const oa::MatrixShape& inShape, oa::F32 inValue) {
	auto& session = oa::ExecutionSession::getActive();
	oa::Matrix out = oa::FnMatrix::empty(inShape, oa::ScalarType::Float32);
	const auto semantic =
		session.recordOp(oa::detail::opRegistry::FnMatrix::fill, {}, {&out},
		{oa::OpAttribute::fromFloat("value", inValue), oa::OpAttribute::fromShape("shape", inShape)});
	if (not semantic.isOk()) return {};
	oa::U32 n = static_cast<oa::U32>(out.numElements());

	struct { oa::U32 count; oa::F32 value; } push{n, inValue};
	oa::BufferAccess access[] = {oa::BufferAccess::Write};
	session.add("Fill", {&out}, access, &push, sizeof(push), divCeil(n, 256),
		1, 1, oa::detail::opRegistry::FnMatrix::fill.name, 0,
		oa::detail::opRegistry::FnMatrix::fill.hash, 0, 0, semantic.getValue());
	return out;
}
