#!/usr/bin/env python3
"""Generate a deterministic single-channel SDF atlas C++ include."""

from pathlib import Path
import argparse
import math

from PIL import Image, ImageDraw, ImageFont


FIRST = 32
LAST = 126


def signed_distance(mask: Image.Image, px_range: int) -> Image.Image:
    src = mask.load()
    width, height = mask.size
    out = Image.new("L", mask.size)
    dst = out.load()
    radius = px_range + 2
    for y in range(height):
        for x in range(width):
            inside = src[x, y] >= 128
            best = float(radius)
            for oy in range(-radius, radius + 1):
                sy = y + oy
                if sy < 0 or sy >= height:
                    continue
                for ox in range(-radius, radius + 1):
                    sx = x + ox
                    if sx < 0 or sx >= width:
                        continue
                    if (src[sx, sy] >= 128) != inside:
                        best = min(best, math.hypot(ox, oy))
            signed = best if inside else -best
            dst[x, y] = max(0, min(255, round(128 + signed * 127 / px_range)))
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--size", type=int, default=48)
    parser.add_argument("--px-range", type=int, default=6)
    parser.add_argument("--cell", type=int, default=64)
    parser.add_argument("--columns", type=int, default=16)
    args = parser.parse_args()

    font = ImageFont.truetype(args.font, args.size)
    count = LAST - FIRST + 1
    rows = (count + args.columns - 1) // args.columns
    atlas = Image.new("L", (args.columns * args.cell, rows * args.cell), 0)
    glyphs = []

    for index, codepoint in enumerate(range(FIRST, LAST + 1)):
        char = chr(codepoint)
        left, top, right, bottom = font.getbbox(char, anchor="ls")
        advance = float(font.getlength(char))
        width = max(1, right - left)
        height = max(1, bottom - top)
        padding = args.px_range + 2
        mask = Image.new("L", (args.cell, args.cell), 0)
        draw = ImageDraw.Draw(mask)
        origin_x = padding - left
        baseline_y = padding - top
        draw.text((origin_x, baseline_y), char, font=font, fill=255, anchor="ls")
        sdf = signed_distance(mask, args.px_range)

        cell_x = (index % args.columns) * args.cell
        cell_y = (index // args.columns) * args.cell
        atlas.paste(sdf, (cell_x, cell_y))
        glyphs.append((
            codepoint, cell_x, cell_y, args.cell, args.cell,
            float(left - padding), float(-top + padding), advance,
            width, height,
        ))

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    pixels = list(atlas.get_flattened_data())
    with output.open("w", encoding="ascii") as stream:
        stream.write("// Generated by Tools/FontAtlas/generate_sdf_atlas.py\n")
        stream.write(f"static constexpr OaU32 kPlexAtlasWidth = {atlas.width};\n")
        stream.write(f"static constexpr OaU32 kPlexAtlasHeight = {atlas.height};\n")
        stream.write(f"static constexpr OaF32 kPlexAtlasPxRange = {float(args.px_range):.1f}F;\n")
        stream.write(f"static constexpr OaU32 kPlexGlyphCount = {len(glyphs)};\n")
        stream.write("static constexpr OaGeneratedGlyph kPlexGlyphs[] = {\n")
        for glyph in glyphs:
            stream.write(
                "\t{%d, %d, %d, %d, %d, %.3fF, %.3fF, %.3fF, %d, %d},\n"
                % glyph
            )
        stream.write("};\n")
        stream.write("static constexpr OaU8 kPlexAtlasPixels[] = {\n")
        for index in range(0, len(pixels), 24):
            stream.write("\t" + ", ".join(str(v) for v in pixels[index:index + 24]) + ",\n")
        stream.write("};\n")


if __name__ == "__main__":
    main()
