// AUTO-GENERATED by tools/gen/type/generate.py — DO NOT EDIT.
// Source of truth: tools/gen/type/schema/core/coreTypes.toml.
// Regenerate via: python3 tools/gen/type/generate.py --live

#pragma once

#include <oa/core/types.h>
#include <cstring>

namespace oa {

enum class DeterminismMode : U8 {
	Fast = 0,  // Vendor math, best throughput, non-deterministic reductions
	Stable = 1,  // Stable algorithms + FP32 accumulators, deterministic where possible
	Deterministic = 2,  // Fixed reduction order, deterministic seeds, no atomics with race-order dependence
};
[[nodiscard]] constexpr const char* determinismModeToString(DeterminismMode inType) noexcept {
	switch (inType) {
		case DeterminismMode::Fast: return "Fast";
		case DeterminismMode::Stable: return "Stable";
		case DeterminismMode::Deterministic: return "Deterministic";
		default: return "unknown";
	}
}
[[nodiscard]] inline DeterminismMode determinismModeFromString(const char* inString) noexcept {
	if (inString == nullptr) return DeterminismMode::Fast;
	if (std::strcmp(inString, "Fast") == 0) return DeterminismMode::Fast;
	if (std::strcmp(inString, "Stable") == 0) return DeterminismMode::Stable;
	if (std::strcmp(inString, "Deterministic") == 0) return DeterminismMode::Deterministic;
	return DeterminismMode::Fast;
}

enum class ScalarType : U8 {
	Float32 = 0,  // 32-bit float
	BFloat16 = 1,  // Brain float 16
	Float16 = 2,  // Half precision
	Int8 = 3,  // 8-bit signed integer
	Int32 = 4,  // 32-bit signed integer
	UInt8 = 5,  // 8-bit unsigned integer
	Float64 = 6,  // 64-bit float (extended)
	Int16 = 7,  // 16-bit signed integer (extended)
	Int64 = 8,  // 64-bit signed integer (extended)
	UInt16 = 9,  // 16-bit unsigned integer (extended)
	UInt32 = 10,  // 32-bit unsigned integer (extended)
	UInt64 = 11,  // 64-bit unsigned integer (extended)
	Bool = 12,  // Boolean (extended)
	Complex64 = 13,  // 64-bit complex (extended)
	Complex128 = 14,  // 128-bit complex (extended)
};
[[nodiscard]] constexpr const char* scalarTypeToString(ScalarType inType) noexcept {
	switch (inType) {
		case ScalarType::Float32: return "Float32";
		case ScalarType::BFloat16: return "BFloat16";
		case ScalarType::Float16: return "Float16";
		case ScalarType::Int8: return "Int8";
		case ScalarType::Int32: return "Int32";
		case ScalarType::UInt8: return "UInt8";
		case ScalarType::Float64: return "Float64";
		case ScalarType::Int16: return "Int16";
		case ScalarType::Int64: return "Int64";
		case ScalarType::UInt16: return "UInt16";
		case ScalarType::UInt32: return "UInt32";
		case ScalarType::UInt64: return "UInt64";
		case ScalarType::Bool: return "Bool";
		case ScalarType::Complex64: return "Complex64";
		case ScalarType::Complex128: return "Complex128";
		default: return "unknown";
	}
}
[[nodiscard]] inline ScalarType scalarTypeFromString(const char* inString) noexcept {
	if (inString == nullptr) return ScalarType::Float32;
	if (std::strcmp(inString, "Float32") == 0) return ScalarType::Float32;
	if (std::strcmp(inString, "BFloat16") == 0) return ScalarType::BFloat16;
	if (std::strcmp(inString, "Float16") == 0) return ScalarType::Float16;
	if (std::strcmp(inString, "Int8") == 0) return ScalarType::Int8;
	if (std::strcmp(inString, "Int32") == 0) return ScalarType::Int32;
	if (std::strcmp(inString, "UInt8") == 0) return ScalarType::UInt8;
	if (std::strcmp(inString, "Float64") == 0) return ScalarType::Float64;
	if (std::strcmp(inString, "Int16") == 0) return ScalarType::Int16;
	if (std::strcmp(inString, "Int64") == 0) return ScalarType::Int64;
	if (std::strcmp(inString, "UInt16") == 0) return ScalarType::UInt16;
	if (std::strcmp(inString, "UInt32") == 0) return ScalarType::UInt32;
	if (std::strcmp(inString, "UInt64") == 0) return ScalarType::UInt64;
	if (std::strcmp(inString, "Bool") == 0) return ScalarType::Bool;
	if (std::strcmp(inString, "Complex64") == 0) return ScalarType::Complex64;
	if (std::strcmp(inString, "Complex128") == 0) return ScalarType::Complex128;
	return ScalarType::Float32;
}

enum class Precision : U8 {
	FP32 = 0,  // Float32 storage and compute policy
	BF16 = 2,  // BFloat16 storage with Float32 accumulation policy
	FP64 = 5,  // Requested Float64 scientific-compute policy; capability-gated
};
[[nodiscard]] constexpr const char* precisionToString(Precision inType) noexcept {
	switch (inType) {
		case Precision::FP32: return "FP32";
		case Precision::BF16: return "BF16";
		case Precision::FP64: return "FP64";
		default: return "unknown";
	}
}
[[nodiscard]] inline Precision precisionFromString(const char* inString) noexcept {
	if (inString == nullptr) return Precision::FP32;
	if (std::strcmp(inString, "FP32") == 0) return Precision::FP32;
	if (std::strcmp(inString, "BF16") == 0) return Precision::BF16;
	if (std::strcmp(inString, "FP64") == 0) return Precision::FP64;
	return Precision::FP32;
}

enum class MatMulPrecision : U8 {
	Auto = 0,  // Select the best supported MatMul precision for the device and problem
	Fp32 = 1,  // Require the FP32 MatMul path
	Bf16 = 2,  // Require the BF16 MatMul path
};
[[nodiscard]] constexpr const char* matMulPrecisionToString(MatMulPrecision inType) noexcept {
	switch (inType) {
		case MatMulPrecision::Auto: return "Auto";
		case MatMulPrecision::Fp32: return "Fp32";
		case MatMulPrecision::Bf16: return "Bf16";
		default: return "unknown";
	}
}
[[nodiscard]] inline MatMulPrecision matMulPrecisionFromString(const char* inString) noexcept {
	if (inString == nullptr) return MatMulPrecision::Auto;
	if (std::strcmp(inString, "Auto") == 0) return MatMulPrecision::Auto;
	if (std::strcmp(inString, "Fp32") == 0) return MatMulPrecision::Fp32;
	if (std::strcmp(inString, "Bf16") == 0) return MatMulPrecision::Bf16;
	return MatMulPrecision::Auto;
}

enum class Filter : U8 {
	Nearest = 0,  // Nearest neighbor filtering
	Linear = 1,  // Linear interpolation
};
[[nodiscard]] constexpr const char* filterToString(Filter inType) noexcept {
	switch (inType) {
		case Filter::Nearest: return "Nearest";
		case Filter::Linear: return "Linear";
		default: return "unknown";
	}
}
[[nodiscard]] inline Filter filterFromString(const char* inString) noexcept {
	if (inString == nullptr) return Filter::Nearest;
	if (std::strcmp(inString, "Nearest") == 0) return Filter::Nearest;
	if (std::strcmp(inString, "Linear") == 0) return Filter::Linear;
	return Filter::Nearest;
}

struct PrecisionConfig {
	Precision mode = Precision::FP32;  // Computation precision
	DeterminismMode determinism = DeterminismMode::Stable;  // Determinism mode
};

} // namespace oa
