// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/Core/FnMatrix manifest.
// Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live

// OaFnMatrix — generated declarations for Core/FnMatrix.

#include "Blas/FnMatrixBlas.gen.h"
#include "Elemwise/FnMatrixElemwise.gen.h"
#include "Reduce/FnMatrixReduce.gen.h"
#include "Rng/FnMatrixRng.gen.h"
#include "Shape/FnMatrixShape.gen.h"
