// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/Core/FnMatrix manifest.
// Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live

// OaFnMatrix — generated umbrella for Core/FnMatrix.

#include "Elemwise/FnMatrixElemwise.gen.h"
#include "Rng/FnMatrixRng.gen.h"
#include "Shape/FnMatrixShape.gen.h"
