// AUTO-GENERATED by tools/gen/nn/generate.py - DO NOT EDIT.
// source of truth: tools/gen/nn/schema/ml/mlNnContainer.toml.
// Regenerate via: python3 tools/gen/nn/generate.py --live

#pragma once

#include <oa/ml/module.h>

#include <initializer_list>

namespace oa {

/// Sequential: Sequential container that chains modules together.
class Sequential : public Module {
public:
	Sequential() = default;
	Sequential(std::initializer_list<oa::SharedPtr<Module>> inLayers);
	Matrix forward(const Matrix& inInput) override;
	Sequential& add(oa::SharedPtr<Module> inModule);
	Sequential& add(oa::StringView inName, oa::SharedPtr<Module> inModule);
};

} // namespace oa
