// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT.
// source of truth: tools/nnAutogen/schema/ml/mlNnActivation.toml.
// Regenerate via: python3 tools/nnAutogen/oannautogen.py --live

#pragma once

#include <oa/ml/module.h>

#include <initializer_list>

namespace oa {

/// Softmax: Softmax activation layer.
class Softmax : public Module {
public:
	explicit Softmax(oa::I32 inDim = -1) : dim_(inDim) {}
	Matrix forward(const Matrix& inInput) override;

private:
	oa::I32 dim_;
};

} // namespace oa
