// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/Audio/AudioFnAudioSignal.toml.
// Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live

// OaFnAudio — Signal overloads.

	/// Mix: Weighted sum of two audio tracks.
	/// Context-based: auto y = OaFnAudio::Mix(...);
	/// Records operation to thread-local default context.
	[[nodiscard]] OaMatrix Mix(const OaMatrix& InA, const OaMatrix& InB, OaF32 InGainA = 1.0, OaF32 InGainB = 1.0);
