// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT.
// source of truth: tools/nnAutogen/schema/ml/mlNnEmbedding.toml.
// Regenerate via: python3 tools/nnAutogen/oannautogen.py --live
// oa::Embedding - Embedding lookup layer.

#include <oa/ml/nn.h>
#include <oa/core/fnMatrix.h>
#include <oa/core/autograd/matrix/autogradIndex.h>
#include <oa/core/validation.h>

oa::Embedding::Embedding(oa::I32 inNumEmbeddings, oa::I32 inEmbeddingDim)
	: numEmbeddings_(inNumEmbeddings), embeddingDim_(inEmbeddingDim) {
	registerParameter("weight", oa::FnMatrix::randN(MatrixShape{inNumEmbeddings, inEmbeddingDim}, oa::FnMatrix::weightDtype()));
}

oa::Matrix oa::Embedding::forward(const oa::Matrix& inInput) {
	auto& weight = params_[0].data;
	auto out = oa::FnMatrix::gather(weight, inInput);
	if (oa::FnAutograd::isEnabled() and (weight.requiresGrad())) {
		auto gradFn = oa::makeShared<oa::GradGather>();
		gradFn->saveForBackward({inInput, weight});
		gradFn->setGraphInputs(  oa::Vec<oa::Matrix>{weight, inInput});
		gradFn->sequenceNr_    = oa::FnAutograd::nextSeq();
		gradFn->outputShape_   = out.getShape();
		out.mutAutograd().gradFn = gradFn;
	}
	return out;
}
