"""Machine-learning operations matching Rust :mod:`oa::ml`."""

from . import byte, flow, loss, matrix, metric, nn, rl
from .._native import (
	CategoricalActorCritic,
	CategoricalActorCriticConfig,
	CategoricalActorCriticOutput,
	ContinuousPolicyResult,
	DqnLossConfig,
	DqnLossResult,
	EnvironmentSpace,
	EnvironmentSpaceKind,
	EnvironmentSpec,
	EnvironmentTransition,
	GaeConfig,
	GaeResult,
	PolicyResult,
	PpoLossConfig,
	PpoLossResult,
	ReplayBatch,
	ReplayBuffer,
	ReplayConfig,
	ReplayTransition,
	RolloutBuffer,
	RolloutConfig,
	RolloutTransition,
	SacCriticLossResult,
	SacLossConfig,
	ml_advantage_gae as advantage_gae,
	ml_advantage_normalize as advantage_normalize,
	ml_clip_reward as clip_reward,
	ml_loss_dqn as loss_dqn,
	ml_loss_ppo as loss_ppo,
	ml_loss_ppo_clipped_policy as loss_ppo_clipped_policy,
	ml_loss_sac_actor as loss_sac_actor,
	ml_loss_sac_critic as loss_sac_critic,
	ml_normalize_observation as normalize_observation,
	ml_policy_evaluate_categorical as policy_evaluate_categorical,
	ml_policy_evaluate_tanh_normal as policy_evaluate_tanh_normal,
	ml_policy_sample_categorical as policy_sample_categorical,
	ml_policy_sample_tanh_normal as policy_sample_tanh_normal,
	ml_scale_action as scale_action,
)
from .._native import (
	Adam,
	AdamW,
	BpeTokenizer,
	CheckpointManagerConfig,
	CosineScheduler,
	CosineWarmRestartsScheduler,
	CyclicMode,
	CyclicScheduler,
	LinearWarmupCosineScheduler,
	Muon,
	OneCycleScheduler,
	Parameter,
	PlateauMode,
	ReduceOnPlateauScheduler,
	Sgd,
	TrainingSession,
	TrainingSessionConfig,
	TrainingSessionSnapshot,
	TrainingState,
	WarmupScheduler,
	ml_clip_grad_norm as clip_grad_norm,
	ml_load_checkpoint as load_checkpoint,
	ml_save_checkpoint as save_checkpoint,
)
# ── Flow matching ─────────────────────────────────────────────────────────────
from .._native import (
	FlowMatchBatch,
	ml_flow_euler_step as flow_euler_step,
	ml_flow_linear_match as flow_linear_match,
	ml_flow_masked_mse as flow_masked_mse,
)
from .._native import (
	AdaptiveAvgPool2d,
	AttentionBackend,
	AttentionMode,
	AvgPool2d,
	BatchNorm2d,
	ByteEmbedding,
	ByteHead,
	Conv1d,
	Conv2d,
	ConvTranspose1d,
	ConvTranspose2d,
	Dropout,
	EmpyrealmCore,
	Embedding,
	Ffn,
	Flatten,
	FlowDenoiser,
	FlowDenoiserConfig,
	FlowTimeEmbedding,
	FlowTransformer,
	FlowTransformerConfig,
	Gelu,
	GradientTape,
	Gru,
	GruCell,
	Identity,
	LayerNorm,
	Linear,
	LogSoftmax,
	Mamba3,
	Mamba3Config,
	Mamba3State,
	MaxPool2d,
	Moe,
	MoeRouteStats,
	MultiHeadAttention,
	Relu,
	ResidualVectorQuantizer,
	ResidualVqResult,
	RmsNorm,
	Rnn,
	RnnCell,
	Rope,
	Sequential,
	Silu,
	Softmax,
	Swiglu,
	Transformer,
	TransformerBlock,
	Upsample,
	UpsampleMode,
	VectorQuantizer,
	VectorQuantizerConfig,
	VqResult,
)
# ── NLP presets ────────────────────────────────────────────────────────────────
from .._native import (
	BpeGru,
	BpeMamba3,
	BpeMoeTransformer,
	BpeRnn,
	BpeSampler,
	BpeTransformer,
	ByteEmpyrealm,
	ByteGru,
	ByteMamba3,
	ByteMoeTransformer,
	ByteRnn,
	ByteSampler,
	ByteTransformer,
	CharGru,
	CharMamba3,
	CharMoeTransformer,
	CharRnn,
	CharSampler,
	CharTransformer,
	ml_nlp_generate_bpe_greedy as nlp_generate_bpe_greedy,
	ml_nlp_generate_bytes_greedy as nlp_generate_bytes_greedy,
	ml_nlp_generate_greedy as nlp_generate_greedy,
)
# ── Training data / callbacks / metrics ───────────────────────────────────────
from .._native import (
	CsvLogger,
	DqnTrainerConfig,
	DqnTrainerMetrics,
	EarlyStopping,
	EarlyStopMode,
	GpuTimingStats,
	ItRolloutTrainingConfig,
	ItTrainingConfig,
	LearningRateScheduler,
	LossAggregation,
	LossMetric,
	PhaseSchedule,
	PolicyEvaluationConfig,
	PolicyEvaluationMetrics,
	PpoTrainerConfig,
	PpoTrainerMetrics,
	ProgressBar,
	RolloutCollectorConfig,
	RolloutCollectorMetrics,
	RolloutTrainingPhase,
	SacTrainerConfig,
	SacTrainerMetrics,
	SequentialScheduler,
	TrainingPhase,
	TrainingSnapshot,
	TrainingSummary,
	Validation,
	ValidationMetric,
	ValidationResult,
)
# ── RL trainers ────────────────────────────────────────────────────────────────
from .._native import (
	DqnTrainer,
	PpoTrainer,
	SacTrainer,
)
# ── Checkpoint manager ────────────────────────────────────────────────────────
from .._native import (
	CheckpointManager,
)
# ── Training program ──────────────────────────────────────────────────────────
from .._native import (
	TrainingCompilationStage,
	TrainingCompilationStageRecord,
	TrainingCompilationState,
	TrainingProgram,
)

__all__ = [
	# Optimizers
	"Adam",
	"AdamW",
	"Muon",
	"Parameter",
	"Sgd",
	"clip_grad_norm",
	# LR schedulers
	"CosineScheduler",
	"CosineWarmRestartsScheduler",
	"CyclicMode",
	"CyclicScheduler",
	"LinearWarmupCosineScheduler",
	"OneCycleScheduler",
	"PlateauMode",
	"ReduceOnPlateauScheduler",
	"SequentialScheduler",
	"WarmupScheduler",
	# Training loop / session
	"TrainingSession",
	"TrainingSessionConfig",
	"TrainingSessionSnapshot",
	"TrainingState",
	# Checkpoint
	"CheckpointManager",
	"CheckpointManagerConfig",
	"load_checkpoint",
	"save_checkpoint",
	# Training data / callbacks / metrics
	"CsvLogger",
	"DqnTrainerConfig",
	"DqnTrainerMetrics",
	"EarlyStopping",
	"EarlyStopMode",
	"GpuTimingStats",
	"ItRolloutTrainingConfig",
	"ItTrainingConfig",
	"LearningRateScheduler",
	"LossAggregation",
	"LossMetric",
	"PhaseSchedule",
	"PolicyEvaluationConfig",
	"PolicyEvaluationMetrics",
	"PpoTrainerConfig",
	"PpoTrainerMetrics",
	"ProgressBar",
	"RolloutCollectorConfig",
	"RolloutCollectorMetrics",
	"RolloutTrainingPhase",
	"SacTrainerConfig",
	"SacTrainerMetrics",
	"TrainingPhase",
	"TrainingSnapshot",
	"TrainingSummary",
	"Validation",
	"ValidationMetric",
	"ValidationResult",
	# RL trainers
	"DqnTrainer",
	"PpoTrainer",
	"SacTrainer",
	# Training program / compilation
	"TrainingCompilationStage",
	"TrainingCompilationStageRecord",
	"TrainingCompilationState",
	"TrainingProgram",
	# NLP presets
	"BpeGru",
	"BpeMamba3",
	"BpeMoeTransformer",
	"BpeRnn",
	"BpeSampler",
	"BpeTransformer",
	"BpeTokenizer",
	"ByteEmpyrealm",
	"ByteGru",
	"ByteMamba3",
	"ByteMoeTransformer",
	"ByteRnn",
	"ByteSampler",
	"ByteTransformer",
	"CharGru",
	"CharMamba3",
	"CharMoeTransformer",
	"CharRnn",
	"CharSampler",
	"CharTransformer",
	"nlp_generate_bpe_greedy",
	"nlp_generate_bytes_greedy",
	"nlp_generate_greedy",
	# NN layers
	"AdaptiveAvgPool2d",
	"AttentionBackend",
	"AttentionMode",
	"AvgPool2d",
	"BatchNorm2d",
	"ByteEmbedding",
	"ByteHead",
	"Conv1d",
	"Conv2d",
	"ConvTranspose1d",
	"ConvTranspose2d",
	"Dropout",
	"EmpyrealmCore",
	"Embedding",
	"Ffn",
	"Flatten",
	"FlowDenoiser",
	"FlowDenoiserConfig",
	"FlowTimeEmbedding",
	"FlowTransformer",
	"FlowTransformerConfig",
	"Gelu",
	"GradientTape",
	"Gru",
	"GruCell",
	"Identity",
	"LayerNorm",
	"Linear",
	"LogSoftmax",
	"Mamba3",
	"Mamba3Config",
	"Mamba3State",
	"MaxPool2d",
	"Moe",
	"MoeRouteStats",
	"MultiHeadAttention",
	"Relu",
	"ResidualVectorQuantizer",
	"ResidualVqResult",
	"RmsNorm",
	"Rnn",
	"RnnCell",
	"Rope",
	"Sequential",
	"Silu",
	"Softmax",
	"Swiglu",
	"Transformer",
	"TransformerBlock",
	"Upsample",
	"UpsampleMode",
	"VectorQuantizer",
	"VectorQuantizerConfig",
	"VqResult",
	# Flow matching
	"FlowMatchBatch",
	"flow_euler_step",
	"flow_linear_match",
	"flow_masked_mse",
	# Submodules
	"byte",
	"flow",
	"loss",
	"matrix",
	"metric",
	"nn",
	"rl",
	# RL env / policy
	"CategoricalActorCritic",
	"CategoricalActorCriticConfig",
	"CategoricalActorCriticOutput",
	"ContinuousPolicyResult",
	"DqnLossConfig",
	"DqnLossResult",
	"EnvironmentSpace",
	"EnvironmentSpaceKind",
	"EnvironmentSpec",
	"EnvironmentTransition",
	"GaeConfig",
	"GaeResult",
	"PolicyResult",
	"PpoLossConfig",
	"PpoLossResult",
	"ReplayBatch",
	"ReplayBuffer",
	"ReplayConfig",
	"ReplayTransition",
	"RolloutBuffer",
	"RolloutConfig",
	"RolloutTransition",
	"SacCriticLossResult",
	"SacLossConfig",
	"advantage_gae",
	"advantage_normalize",
	"clip_reward",
	"loss_dqn",
	"loss_ppo",
	"loss_ppo_clipped_policy",
	"loss_sac_actor",
	"loss_sac_critic",
	"normalize_observation",
	"policy_evaluate_categorical",
	"policy_evaluate_tanh_normal",
	"policy_sample_categorical",
	"policy_sample_tanh_normal",
	"scale_action",
]
