// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT.
// source of truth: tools/nnAutogen/schema/ml/mlNnAttention.toml.
// Regenerate via: python3 tools/nnAutogen/oannautogen.py --live

#pragma once

#include <oa/ml/module.h>
#include <oa/ml/nn/attention.h>

#include <initializer_list>

namespace oa {

/// MultiHeadAttention: Multi-head scaled dot-product self-attention with explicit causal/bidirectional visibility and interchangeable standard/fused causal Flash backends.
class MultiHeadAttention : public Module {
public:
	MultiHeadAttention(oa::I32 inDModel, oa::I32 inNumHeads, oa::F32 inDropoutP = 0.0f, bool inBias = true, oa::AttentionBackend inBackend = oa::AttentionBackend::Auto, oa::AttentionMode inMode = oa::AttentionMode::Causal);
	Matrix forward(const Matrix& inInput) override;
	void setSeqLen(oa::I32 inSeqLen) { seqLen_ = inSeqLen; mask_ = {}; maskSeqLen_ = 0; maskBatch_ = 0; }
	oa::Matrix forwardMasked(const oa::Matrix& inInput, const oa::Matrix& inAdditiveMask);
	[[nodiscard]] oa::I32 numHeads() const noexcept { return numHeads_; }
	[[nodiscard]] oa::I32 headDim() const noexcept { return headDim_; }
	void setBackend(oa::AttentionBackend inBackend) noexcept { backend_ = inBackend; }
	[[nodiscard]] oa::AttentionBackend backend() const noexcept { return backend_; }
	[[nodiscard]] oa::AttentionBackend lastBackend() const noexcept { return lastBackend_; }
	void setMode(oa::AttentionMode inMode) noexcept { mode_ = inMode; mask_ = {}; maskSeqLen_ = 0; maskBatch_ = 0; }
	[[nodiscard]] oa::AttentionMode mode() const noexcept { return mode_; }

private:
	oa::I32 dModel_;
	oa::I32 numHeads_;
	oa::I32 headDim_;
	oa::F32 dropoutP_;
	oa::AttentionBackend backend_;
	oa::AttentionBackend lastBackend_ = oa::AttentionBackend::Standard;
	oa::AttentionMode mode_;
	oa::SharedPtr<Module> qProj_;
	oa::SharedPtr<Module> kProj_;
	oa::SharedPtr<Module> vProj_;
	oa::SharedPtr<Module> outProj_;
	oa::I32 seqLen_ = 0;
	oa::Matrix mask_;
	oa::I32 maskSeqLen_ = 0;
	oa::I32 maskBatch_ = 0;
	oa::AttentionMode maskMode_ = oa::AttentionMode::Causal;
	oa::Vec<oa::Matrix> projectQkv(const oa::Matrix& inInput);
	const oa::Matrix& attentionMask(oa::I32 inBatch);
	oa::Matrix forwardStandard(const oa::Matrix& inInput, const oa::Matrix& inAdditiveMask);
	oa::Matrix forwardFlash(const oa::Matrix& inInput);
	[[nodiscard]] bool canUseFlash(const oa::Matrix& inInput) const noexcept;
};

} // namespace oa
