// AUTO-GENERATED by Tools/NnAutogen/oannautogen.py - DO NOT EDIT.
// Source of truth: Tools/NnAutogen/Schema/all NN schemas.
// Regenerate via: python3 Tools/NnAutogen/oannautogen.py --live

#pragma once

#include "Relu/Relu.gen.h"
#include "Gelu/Gelu.gen.h"
#include "Silu/Silu.gen.h"
#include "Softmax/Softmax.gen.h"
#include "MultiHeadAttention/MultiHeadAttention.gen.h"
#include "Sequential/Sequential.gen.h"
#include "Conv1d/Conv1d.gen.h"
#include "Conv2d/Conv2d.gen.h"
#include "Embedding/Embedding.gen.h"
#include "Linear/Linear.gen.h"
#include "SwiGLU/SwiGLU.gen.h"
#include "LayerNorm/LayerNorm.gen.h"
#include "RmsNorm/RmsNorm.gen.h"
#include "MaxPool2d/MaxPool2d.gen.h"
#include "AvgPool2d/AvgPool2d.gen.h"
#include "Identity/Identity.gen.h"
#include "Flatten/Flatten.gen.h"
#include "Upsample/Upsample.gen.h"
#include "BatchNorm2d/BatchNorm2d.gen.h"
#include "AdaptiveAvgPool2d/AdaptiveAvgPool2d.gen.h"
