// @generated by tools/gen/fn/generate.py; DO NOT EDIT.
// schemas=matrix_elemwise.json,matrix_blas.json,ml_training.json generator_version=18
// matrix_elemwise_sha256=e183d086f7c960a7baabe867f2e01f911abc08a0304bc3883fd4979b9bf579e5
// matrix_blas_sha256=3a57ef7c728eeeaf671fad241d8ced4248ebbd404ebed05ff94dd48e8dd3e1c6
// ml_training_sha256=7f5e52a7522027123d86c67724a7563fa9345e976d8439cd7d51de68960d8d50

use std::sync::OnceLock;

use super::ShaderArtifact;

static MATRIX_ADD_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_add_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_ADD_I32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_add_i32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_SUB_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_sub_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_MUL_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_mul_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_DIV_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_div_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_SCALE_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_scale_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_NEG_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_neg_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_ABS_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_abs_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_LOG_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_log_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_SQRT_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_sqrt_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_POW_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_pow_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_ADD_SCALAR_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_add_scalar_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_SUB_SCALAR_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_sub_scalar_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_DIV_SCALAR_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_div_scalar_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_EXP_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_exp_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_SIN_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_sin_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_COS_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_cos_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_RECIPROCAL_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_reciprocal_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_CLAMP_MAX_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_clamp_max_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_CLAMP_MIN_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_clamp_min_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static MATRIX_MAT_MUL_NT_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/matrix_mat_mul_nt_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [64, 64, 1],
	content_id: OnceLock::new(),
};

static ML_LINEAR_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_linear_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_LINEAR_BACKWARD_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_linear_backward_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_LINEAR_PARAMETER_BACKWARD_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(
		env!("OUT_DIR"),
		"/ml_linear_parameter_backward_f32.spv"
	)),
	workgroup_size: [32, 8, 1],
	dispatch_tile_size: [32, 8, 1],
	content_id: OnceLock::new(),
};

static ML_CROSS_ENTROPY_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_cross_entropy_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_CROSS_ENTROPY_BACKWARD_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(
		env!("OUT_DIR"),
		"/ml_cross_entropy_backward_f32.spv"
	)),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_ADAMW_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_adamw_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_ADAMW_GRAPH_ADVANCE_U32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_adamw_graph_advance_u32.spv")),
	workgroup_size: [1, 1, 1],
	dispatch_tile_size: [1, 1, 1],
	content_id: OnceLock::new(),
};

static ML_ADAMW_GRAPH_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_adamw_graph_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_EMBEDDING_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_embedding_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_EMBEDDING_BACKWARD_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_embedding_backward_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_RNN_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_rnn_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_RNN_BACKWARD_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_rnn_backward_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_LAYER_NORM_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_layer_norm_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_LAYER_NORM_BACKWARD_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_layer_norm_backward_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_LAYER_NORM_PARAMETER_BACKWARD_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(
		env!("OUT_DIR"),
		"/ml_layer_norm_parameter_backward_f32.spv"
	)),
	workgroup_size: [32, 8, 1],
	dispatch_tile_size: [32, 8, 1],
	content_id: OnceLock::new(),
};

static ML_GELU_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_gelu_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_GELU_BACKWARD_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_gelu_backward_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_SCALED_DOT_PRODUCT_ATTENTION_CAUSAL_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(
		env!("OUT_DIR"),
		"/ml_scaled_dot_product_attention_causal_f32.spv"
	)),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_SCALED_DOT_PRODUCT_ATTENTION_CAUSAL_PROBABILITY_BACKWARD_F32: ShaderArtifact =
	ShaderArtifact {
		bytes: include_bytes!(concat!(
			env!("OUT_DIR"),
			"/ml_scaled_dot_product_attention_causal_probability_backward_f32.spv"
		)),
		workgroup_size: [256, 1, 1],
		dispatch_tile_size: [256, 1, 1],
		content_id: OnceLock::new(),
	};

static ML_SCALED_DOT_PRODUCT_ATTENTION_CAUSAL_BACKWARD_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(
		env!("OUT_DIR"),
		"/ml_scaled_dot_product_attention_causal_backward_f32.spv"
	)),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_QKV_PROJECTION_BIAS_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_qkv_projection_bias_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_SWIGLU_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_swiglu_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_SWIGLU_BACKWARD_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_swiglu_backward_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

static ML_GATE_UP_SWIGLU_BIAS_F32: ShaderArtifact = ShaderArtifact {
	bytes: include_bytes!(concat!(env!("OUT_DIR"), "/ml_gate_up_swiglu_bias_f32.spv")),
	workgroup_size: [256, 1, 1],
	dispatch_tile_size: [256, 1, 1],
	content_id: OnceLock::new(),
};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum TrainingReplayRole {
	Safe,
	HostSteppedOptimizer,
	OptimizerStateAdvance,
	OptimizerStateUpdate,
}

#[repr(u16)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum KernelId {
	MatrixAddF32 = 1,
	MatrixAddI32 = 20,
	MatrixSubF32 = 2,
	MatrixMulF32 = 3,
	MatrixDivF32 = 4,
	MatrixScaleF32 = 5,
	MatrixNegF32 = 6,
	MatrixAbsF32 = 7,
	MatrixLogF32 = 8,
	MatrixSqrtF32 = 9,
	MatrixPowF32 = 10,
	MatrixAddScalarF32 = 11,
	MatrixSubScalarF32 = 12,
	MatrixDivScalarF32 = 13,
	MatrixExpF32 = 14,
	MatrixSinF32 = 15,
	MatrixCosF32 = 16,
	MatrixReciprocalF32 = 17,
	MatrixClampMaxF32 = 18,
	MatrixClampMinF32 = 19,
	MatrixMatMulNtTiledF32 = 21,
	MlLinearF32 = 22,
	MlLinearBackwardF32 = 23,
	MlLinearParameterBackwardF32 = 38,
	MlCrossEntropyF32 = 24,
	MlCrossEntropyBackwardF32 = 25,
	MlAdamWF32 = 26,
	MlAdamWGraphAdvanceU32 = 40,
	MlAdamWGraphF32 = 41,
	MlEmbeddingF32 = 27,
	MlEmbeddingBackwardF32 = 28,
	MlRnnF32 = 29,
	MlRnnBackwardF32 = 30,
	MlLayerNormF32 = 31,
	MlLayerNormBackwardF32 = 32,
	MlLayerNormParameterBackwardF32 = 39,
	MlGeluF32 = 33,
	MlGeluBackwardF32 = 34,
	MlScaledDotProductAttentionCausalF32 = 35,
	MlScaledDotProductAttentionCausalProbabilityBackwardF32 = 37,
	MlScaledDotProductAttentionCausalBackwardF32 = 36,
	MlQkvProjectionBiasF32 = 42,
	MlSwigluF32 = 43,
	MlSwigluBackwardF32 = 44,
	MlGateUpSwigluBiasF32 = 45,
}

impl KernelId {
	pub(crate) const ALL: [Self; 45] = [
		Self::MatrixAddF32,
		Self::MatrixAddI32,
		Self::MatrixSubF32,
		Self::MatrixMulF32,
		Self::MatrixDivF32,
		Self::MatrixScaleF32,
		Self::MatrixNegF32,
		Self::MatrixAbsF32,
		Self::MatrixLogF32,
		Self::MatrixSqrtF32,
		Self::MatrixPowF32,
		Self::MatrixAddScalarF32,
		Self::MatrixSubScalarF32,
		Self::MatrixDivScalarF32,
		Self::MatrixExpF32,
		Self::MatrixSinF32,
		Self::MatrixCosF32,
		Self::MatrixReciprocalF32,
		Self::MatrixClampMaxF32,
		Self::MatrixClampMinF32,
		Self::MatrixMatMulNtTiledF32,
		Self::MlLinearF32,
		Self::MlLinearBackwardF32,
		Self::MlLinearParameterBackwardF32,
		Self::MlCrossEntropyF32,
		Self::MlCrossEntropyBackwardF32,
		Self::MlAdamWF32,
		Self::MlAdamWGraphAdvanceU32,
		Self::MlAdamWGraphF32,
		Self::MlEmbeddingF32,
		Self::MlEmbeddingBackwardF32,
		Self::MlRnnF32,
		Self::MlRnnBackwardF32,
		Self::MlLayerNormF32,
		Self::MlLayerNormBackwardF32,
		Self::MlLayerNormParameterBackwardF32,
		Self::MlGeluF32,
		Self::MlGeluBackwardF32,
		Self::MlScaledDotProductAttentionCausalF32,
		Self::MlScaledDotProductAttentionCausalProbabilityBackwardF32,
		Self::MlScaledDotProductAttentionCausalBackwardF32,
		Self::MlQkvProjectionBiasF32,
		Self::MlSwigluF32,
		Self::MlSwigluBackwardF32,
		Self::MlGateUpSwigluBiasF32,
	];

	pub(crate) const fn artifact(self) -> &'static ShaderArtifact {
		match self {
			Self::MatrixAddF32 => &MATRIX_ADD_F32,
			Self::MatrixAddI32 => &MATRIX_ADD_I32,
			Self::MatrixSubF32 => &MATRIX_SUB_F32,
			Self::MatrixMulF32 => &MATRIX_MUL_F32,
			Self::MatrixDivF32 => &MATRIX_DIV_F32,
			Self::MatrixScaleF32 => &MATRIX_SCALE_F32,
			Self::MatrixNegF32 => &MATRIX_NEG_F32,
			Self::MatrixAbsF32 => &MATRIX_ABS_F32,
			Self::MatrixLogF32 => &MATRIX_LOG_F32,
			Self::MatrixSqrtF32 => &MATRIX_SQRT_F32,
			Self::MatrixPowF32 => &MATRIX_POW_F32,
			Self::MatrixAddScalarF32 => &MATRIX_ADD_SCALAR_F32,
			Self::MatrixSubScalarF32 => &MATRIX_SUB_SCALAR_F32,
			Self::MatrixDivScalarF32 => &MATRIX_DIV_SCALAR_F32,
			Self::MatrixExpF32 => &MATRIX_EXP_F32,
			Self::MatrixSinF32 => &MATRIX_SIN_F32,
			Self::MatrixCosF32 => &MATRIX_COS_F32,
			Self::MatrixReciprocalF32 => &MATRIX_RECIPROCAL_F32,
			Self::MatrixClampMaxF32 => &MATRIX_CLAMP_MAX_F32,
			Self::MatrixClampMinF32 => &MATRIX_CLAMP_MIN_F32,
			Self::MatrixMatMulNtTiledF32 => &MATRIX_MAT_MUL_NT_F32,
			Self::MlLinearF32 => &ML_LINEAR_F32,
			Self::MlLinearBackwardF32 => &ML_LINEAR_BACKWARD_F32,
			Self::MlLinearParameterBackwardF32 => &ML_LINEAR_PARAMETER_BACKWARD_F32,
			Self::MlCrossEntropyF32 => &ML_CROSS_ENTROPY_F32,
			Self::MlCrossEntropyBackwardF32 => &ML_CROSS_ENTROPY_BACKWARD_F32,
			Self::MlAdamWF32 => &ML_ADAMW_F32,
			Self::MlAdamWGraphAdvanceU32 => &ML_ADAMW_GRAPH_ADVANCE_U32,
			Self::MlAdamWGraphF32 => &ML_ADAMW_GRAPH_F32,
			Self::MlEmbeddingF32 => &ML_EMBEDDING_F32,
			Self::MlEmbeddingBackwardF32 => &ML_EMBEDDING_BACKWARD_F32,
			Self::MlRnnF32 => &ML_RNN_F32,
			Self::MlRnnBackwardF32 => &ML_RNN_BACKWARD_F32,
			Self::MlLayerNormF32 => &ML_LAYER_NORM_F32,
			Self::MlLayerNormBackwardF32 => &ML_LAYER_NORM_BACKWARD_F32,
			Self::MlLayerNormParameterBackwardF32 => &ML_LAYER_NORM_PARAMETER_BACKWARD_F32,
			Self::MlGeluF32 => &ML_GELU_F32,
			Self::MlGeluBackwardF32 => &ML_GELU_BACKWARD_F32,
			Self::MlScaledDotProductAttentionCausalF32 => {
				&ML_SCALED_DOT_PRODUCT_ATTENTION_CAUSAL_F32
			}
			Self::MlScaledDotProductAttentionCausalProbabilityBackwardF32 => {
				&ML_SCALED_DOT_PRODUCT_ATTENTION_CAUSAL_PROBABILITY_BACKWARD_F32
			}
			Self::MlScaledDotProductAttentionCausalBackwardF32 => {
				&ML_SCALED_DOT_PRODUCT_ATTENTION_CAUSAL_BACKWARD_F32
			}
			Self::MlQkvProjectionBiasF32 => &ML_QKV_PROJECTION_BIAS_F32,
			Self::MlSwigluF32 => &ML_SWIGLU_F32,
			Self::MlSwigluBackwardF32 => &ML_SWIGLU_BACKWARD_F32,
			Self::MlGateUpSwigluBiasF32 => &ML_GATE_UP_SWIGLU_BIAS_F32,
		}
	}

	pub(crate) const fn index(self) -> usize {
		match self {
			Self::MatrixAddF32 => 0,
			Self::MatrixAddI32 => 1,
			Self::MatrixSubF32 => 2,
			Self::MatrixMulF32 => 3,
			Self::MatrixDivF32 => 4,
			Self::MatrixScaleF32 => 5,
			Self::MatrixNegF32 => 6,
			Self::MatrixAbsF32 => 7,
			Self::MatrixLogF32 => 8,
			Self::MatrixSqrtF32 => 9,
			Self::MatrixPowF32 => 10,
			Self::MatrixAddScalarF32 => 11,
			Self::MatrixSubScalarF32 => 12,
			Self::MatrixDivScalarF32 => 13,
			Self::MatrixExpF32 => 14,
			Self::MatrixSinF32 => 15,
			Self::MatrixCosF32 => 16,
			Self::MatrixReciprocalF32 => 17,
			Self::MatrixClampMaxF32 => 18,
			Self::MatrixClampMinF32 => 19,
			Self::MatrixMatMulNtTiledF32 => 20,
			Self::MlLinearF32 => 21,
			Self::MlLinearBackwardF32 => 22,
			Self::MlLinearParameterBackwardF32 => 23,
			Self::MlCrossEntropyF32 => 24,
			Self::MlCrossEntropyBackwardF32 => 25,
			Self::MlAdamWF32 => 26,
			Self::MlAdamWGraphAdvanceU32 => 27,
			Self::MlAdamWGraphF32 => 28,
			Self::MlEmbeddingF32 => 29,
			Self::MlEmbeddingBackwardF32 => 30,
			Self::MlRnnF32 => 31,
			Self::MlRnnBackwardF32 => 32,
			Self::MlLayerNormF32 => 33,
			Self::MlLayerNormBackwardF32 => 34,
			Self::MlLayerNormParameterBackwardF32 => 35,
			Self::MlGeluF32 => 36,
			Self::MlGeluBackwardF32 => 37,
			Self::MlScaledDotProductAttentionCausalF32 => 38,
			Self::MlScaledDotProductAttentionCausalProbabilityBackwardF32 => 39,
			Self::MlScaledDotProductAttentionCausalBackwardF32 => 40,
			Self::MlQkvProjectionBiasF32 => 41,
			Self::MlSwigluF32 => 42,
			Self::MlSwigluBackwardF32 => 43,
			Self::MlGateUpSwigluBiasF32 => 44,
		}
	}

	pub(crate) const fn report_name(self) -> &'static str {
		match self {
			Self::MatrixAddF32 => "matrix.add.f32",
			Self::MatrixAddI32 => "matrix.add.i32",
			Self::MatrixSubF32 => "matrix.sub.f32",
			Self::MatrixMulF32 => "matrix.mul.f32",
			Self::MatrixDivF32 => "matrix.div.f32",
			Self::MatrixScaleF32 => "matrix.scale.f32",
			Self::MatrixNegF32 => "matrix.neg.f32",
			Self::MatrixAbsF32 => "matrix.abs.f32",
			Self::MatrixLogF32 => "matrix.log.f32",
			Self::MatrixSqrtF32 => "matrix.sqrt.f32",
			Self::MatrixPowF32 => "matrix.pow.f32",
			Self::MatrixAddScalarF32 => "matrix.add_scalar.f32",
			Self::MatrixSubScalarF32 => "matrix.sub_scalar.f32",
			Self::MatrixDivScalarF32 => "matrix.div_scalar.f32",
			Self::MatrixExpF32 => "matrix.exp.f32",
			Self::MatrixSinF32 => "matrix.sin.f32",
			Self::MatrixCosF32 => "matrix.cos.f32",
			Self::MatrixReciprocalF32 => "matrix.reciprocal.f32",
			Self::MatrixClampMaxF32 => "matrix.clamp_max.f32",
			Self::MatrixClampMinF32 => "matrix.clamp_min.f32",
			Self::MatrixMatMulNtTiledF32 => "matrix.mat_mul_nt.f32",
			Self::MlLinearF32 => "ml.linear.f32",
			Self::MlLinearBackwardF32 => "ml.linear_backward.f32",
			Self::MlLinearParameterBackwardF32 => "ml.linear_parameter_backward.f32",
			Self::MlCrossEntropyF32 => "ml.cross_entropy.f32",
			Self::MlCrossEntropyBackwardF32 => "ml.cross_entropy_backward.f32",
			Self::MlAdamWF32 => "ml.adamw.f32",
			Self::MlAdamWGraphAdvanceU32 => "ml.adamw_graph_advance.u32",
			Self::MlAdamWGraphF32 => "ml.adamw_graph.f32",
			Self::MlEmbeddingF32 => "ml.embedding.f32",
			Self::MlEmbeddingBackwardF32 => "ml.embedding_backward.f32",
			Self::MlRnnF32 => "ml.rnn.f32",
			Self::MlRnnBackwardF32 => "ml.rnn_backward.f32",
			Self::MlLayerNormF32 => "ml.layer_norm.f32",
			Self::MlLayerNormBackwardF32 => "ml.layer_norm_backward.f32",
			Self::MlLayerNormParameterBackwardF32 => "ml.layer_norm_parameter_backward.f32",
			Self::MlGeluF32 => "ml.gelu.f32",
			Self::MlGeluBackwardF32 => "ml.gelu_backward.f32",
			Self::MlScaledDotProductAttentionCausalF32 => {
				"ml.scaled_dot_product_attention_causal.f32"
			}
			Self::MlScaledDotProductAttentionCausalProbabilityBackwardF32 => {
				"ml.scaled_dot_product_attention_causal_probability_backward.f32"
			}
			Self::MlScaledDotProductAttentionCausalBackwardF32 => {
				"ml.scaled_dot_product_attention_causal_backward.f32"
			}
			Self::MlQkvProjectionBiasF32 => "ml.qkv_projection_bias.f32",
			Self::MlSwigluF32 => "ml.swiglu.f32",
			Self::MlSwigluBackwardF32 => "ml.swiglu_backward.f32",
			Self::MlGateUpSwigluBiasF32 => "ml.gate_up_swiglu_bias.f32",
		}
	}

	pub(crate) const fn dtype_report_token(self) -> &'static str {
		match self {
			Self::MatrixAddF32 => "float32",
			Self::MatrixAddI32 => "int32",
			Self::MatrixSubF32 => "float32",
			Self::MatrixMulF32 => "float32",
			Self::MatrixDivF32 => "float32",
			Self::MatrixScaleF32 => "float32",
			Self::MatrixNegF32 => "float32",
			Self::MatrixAbsF32 => "float32",
			Self::MatrixLogF32 => "float32",
			Self::MatrixSqrtF32 => "float32",
			Self::MatrixPowF32 => "float32",
			Self::MatrixAddScalarF32 => "float32",
			Self::MatrixSubScalarF32 => "float32",
			Self::MatrixDivScalarF32 => "float32",
			Self::MatrixExpF32 => "float32",
			Self::MatrixSinF32 => "float32",
			Self::MatrixCosF32 => "float32",
			Self::MatrixReciprocalF32 => "float32",
			Self::MatrixClampMaxF32 => "float32",
			Self::MatrixClampMinF32 => "float32",
			Self::MatrixMatMulNtTiledF32 => "float32",
			Self::MlLinearF32 => "float32",
			Self::MlLinearBackwardF32 => "float32",
			Self::MlLinearParameterBackwardF32 => "float32",
			Self::MlCrossEntropyF32 => "float32",
			Self::MlCrossEntropyBackwardF32 => "float32",
			Self::MlAdamWF32 => "float32",
			Self::MlAdamWGraphAdvanceU32 => "uint32",
			Self::MlAdamWGraphF32 => "float32",
			Self::MlEmbeddingF32 => "float32",
			Self::MlEmbeddingBackwardF32 => "float32",
			Self::MlRnnF32 => "float32",
			Self::MlRnnBackwardF32 => "float32",
			Self::MlLayerNormF32 => "float32",
			Self::MlLayerNormBackwardF32 => "float32",
			Self::MlLayerNormParameterBackwardF32 => "float32",
			Self::MlGeluF32 => "float32",
			Self::MlGeluBackwardF32 => "float32",
			Self::MlScaledDotProductAttentionCausalF32 => "float32",
			Self::MlScaledDotProductAttentionCausalProbabilityBackwardF32 => "float32",
			Self::MlScaledDotProductAttentionCausalBackwardF32 => "float32",
			Self::MlQkvProjectionBiasF32 => "float32",
			Self::MlSwigluF32 => "float32",
			Self::MlSwigluBackwardF32 => "float32",
			Self::MlGateUpSwigluBiasF32 => "float32",
		}
	}

	pub(crate) const fn training_replay_role(self) -> TrainingReplayRole {
		match self {
			Self::MatrixAddF32 => TrainingReplayRole::Safe,
			Self::MatrixAddI32 => TrainingReplayRole::Safe,
			Self::MatrixSubF32 => TrainingReplayRole::Safe,
			Self::MatrixMulF32 => TrainingReplayRole::Safe,
			Self::MatrixDivF32 => TrainingReplayRole::Safe,
			Self::MatrixScaleF32 => TrainingReplayRole::Safe,
			Self::MatrixNegF32 => TrainingReplayRole::Safe,
			Self::MatrixAbsF32 => TrainingReplayRole::Safe,
			Self::MatrixLogF32 => TrainingReplayRole::Safe,
			Self::MatrixSqrtF32 => TrainingReplayRole::Safe,
			Self::MatrixPowF32 => TrainingReplayRole::Safe,
			Self::MatrixAddScalarF32 => TrainingReplayRole::Safe,
			Self::MatrixSubScalarF32 => TrainingReplayRole::Safe,
			Self::MatrixDivScalarF32 => TrainingReplayRole::Safe,
			Self::MatrixExpF32 => TrainingReplayRole::Safe,
			Self::MatrixSinF32 => TrainingReplayRole::Safe,
			Self::MatrixCosF32 => TrainingReplayRole::Safe,
			Self::MatrixReciprocalF32 => TrainingReplayRole::Safe,
			Self::MatrixClampMaxF32 => TrainingReplayRole::Safe,
			Self::MatrixClampMinF32 => TrainingReplayRole::Safe,
			Self::MatrixMatMulNtTiledF32 => TrainingReplayRole::Safe,
			Self::MlLinearF32 => TrainingReplayRole::Safe,
			Self::MlLinearBackwardF32 => TrainingReplayRole::Safe,
			Self::MlLinearParameterBackwardF32 => TrainingReplayRole::Safe,
			Self::MlCrossEntropyF32 => TrainingReplayRole::Safe,
			Self::MlCrossEntropyBackwardF32 => TrainingReplayRole::Safe,
			Self::MlAdamWF32 => TrainingReplayRole::HostSteppedOptimizer,
			Self::MlAdamWGraphAdvanceU32 => TrainingReplayRole::OptimizerStateAdvance,
			Self::MlAdamWGraphF32 => TrainingReplayRole::OptimizerStateUpdate,
			Self::MlEmbeddingF32 => TrainingReplayRole::Safe,
			Self::MlEmbeddingBackwardF32 => TrainingReplayRole::Safe,
			Self::MlRnnF32 => TrainingReplayRole::Safe,
			Self::MlRnnBackwardF32 => TrainingReplayRole::Safe,
			Self::MlLayerNormF32 => TrainingReplayRole::Safe,
			Self::MlLayerNormBackwardF32 => TrainingReplayRole::Safe,
			Self::MlLayerNormParameterBackwardF32 => TrainingReplayRole::Safe,
			Self::MlGeluF32 => TrainingReplayRole::Safe,
			Self::MlGeluBackwardF32 => TrainingReplayRole::Safe,
			Self::MlScaledDotProductAttentionCausalF32 => TrainingReplayRole::Safe,
			Self::MlScaledDotProductAttentionCausalProbabilityBackwardF32 => {
				TrainingReplayRole::Safe
			}
			Self::MlScaledDotProductAttentionCausalBackwardF32 => TrainingReplayRole::Safe,
			Self::MlQkvProjectionBiasF32 => TrainingReplayRole::Safe,
			Self::MlSwigluF32 => TrainingReplayRole::Safe,
			Self::MlSwigluBackwardF32 => TrainingReplayRole::Safe,
			Self::MlGateUpSwigluBiasF32 => TrainingReplayRole::Safe,
		}
	}

	pub(crate) fn linear_workgroups(self, element_count: u32) -> [u32; 3] {
		let width = self.artifact().dispatch_tile_size[0];
		[element_count.div_ceil(width), 1, 1]
	}

	pub(crate) fn output_workgroups(self, rows: u32, columns: u32) -> [u32; 3] {
		let tile = self.artifact().dispatch_tile_size;
		[rows.div_ceil(tile[0]), columns.div_ceil(tile[1]), 1]
	}
}
