// AUTO-GENERATED by Tools/NnAutogen/oannautogen.py - DO NOT EDIT.
// Source of truth: Tools/NnAutogen/Schema/Ml/MlNnActivation.toml.
// Regenerate via: python3 Tools/NnAutogen/oannautogen.py --live
// OaSoftmax - Softmax activation layer.

#include <Oa/Ml/Nn.h>
#include <Oa/Core/FnMatrix.h>
#include <Oa/Core/Validation.h>

OaMatrix OaSoftmax::Forward(const OaMatrix& InInput) {
	return OaFnMatrix::Softmax(InInput, Dim_);
}
