// AUTO-GENERATED by Tools/NnAutogen/oannautogen.py - DO NOT EDIT.
// Source of truth: Tools/NnAutogen/Schema/Ml/MlNnUtility.toml.
// Regenerate via: python3 Tools/NnAutogen/oannautogen.py --live

#pragma once

#include <Oa/Ml/Module.h>
#include <Oa/Ml/NnType.h>

#include <initializer_list>

/// OaIdentity: Identity passthrough layer.
class OaIdentity : public OaModule {
public:
	OaIdentity() = default;
	OaMatrix Forward(const OaMatrix& InInput) override;
};
