"""Python bindings for OA's Rust semantic API."""

from importlib.metadata import PackageNotFoundError, version

from . import audio, core, cryptography, image, matrix, ml, plot, runtime, ui, video, viewer, vision
from ._native import (
	Audio,
	AudioCapture,
	AudioCaptureChunk,
	AudioCaptureConfig,
	AudioEncodeProfile,
	AudioEncoder,
	AudioPlayer,
	AudioPlayerConfig,
	Engine,
	EncodedAudioPacket,
	EncodedVideoPacket,
	Event,
	Filesystem,
	Image,
	LogLevel,
	LogOptions,
	Matrix,
	Path,
	Viewer,
	ViewerAudioView,
	ViewerCanvasBackground,
	ViewerConfig,
	ViewerMode,
	VideoCodec,
	VideoColorInfo,
	VideoColorMatrix,
	VideoColorRange,
	VideoContainerInfo,
	VideoContainerKind,
	VideoDecoder,
	VideoDemuxer,
	VideoFrame,
	VideoFrameTiming,
	VideoMuxer,
	VideoMuxerAudioConfig,
	VideoMuxerConfig,
	VideoPacket,
	VideoPlayer,
	VideoPlayerConfig,
	VideoPlayerStats,
)

__all__ = [
	"Audio",
	"AudioCapture",
	"AudioCaptureChunk",
	"AudioCaptureConfig",
	"AudioEncodeProfile",
	"AudioEncoder",
	"AudioPlayer",
	"AudioPlayerConfig",
	"Engine",
	"EncodedAudioPacket",
	"EncodedVideoPacket",
	"Event",
	"Filesystem",
	"Image",
	"LogLevel",
	"LogOptions",
	"Matrix",
	"Path",
	"Viewer",
	"ViewerAudioView",
	"ViewerCanvasBackground",
	"ViewerConfig",
	"ViewerMode",
	"VideoCodec",
	"VideoColorInfo",
	"VideoColorMatrix",
	"VideoColorRange",
	"VideoContainerInfo",
	"VideoContainerKind",
	"VideoDecoder",
	"VideoDemuxer",
	"VideoFrame",
	"VideoFrameTiming",
	"VideoMuxer",
	"VideoMuxerAudioConfig",
	"VideoMuxerConfig",
	"VideoPacket",
	"VideoPlayer",
	"VideoPlayerConfig",
	"VideoPlayerStats",
	"audio",
	"core",
	"cryptography",
	"image",
	"matrix",
	"ml",
	"plot",
	"runtime",
	"ui",
	"video",
	"viewer",
	"vision",
]
try:
	__version__ = version("oapython")
except PackageNotFoundError:
	# Source-tree contract tests load the built extension without installing a
	# wheel, so distribution metadata is intentionally absent.
	__version__ = "0+unknown"
