"""Python bindings for OA's Rust semantic API."""

from importlib.metadata import version

from . import audio, core, cryptography, image, matrix, ml, render, runtime, video, vision
from ._native import (
	Audio,
	AudioCapture,
	AudioCaptureChunk,
	AudioCaptureConfig,
	AudioEncodeProfile,
	AudioEncoder,
	AudioPlayer,
	AudioPlayerConfig,
	Engine,
	EncodedAudioPacket,
	EncodedVideoPacket,
	Event,
	Image,
	LogLevel,
	LogOptions,
	Matrix,
	Texture,
	VideoCodec,
	VideoColorInfo,
	VideoColorMatrix,
	VideoColorRange,
	VideoContainerInfo,
	VideoContainerKind,
	VideoDecoder,
	VideoDemuxer,
	VideoFrame,
	VideoFrameTiming,
	VideoMuxer,
	VideoMuxerAudioConfig,
	VideoMuxerConfig,
	VideoPacket,
	VideoPlayer,
	VideoPlayerConfig,
	VideoPlayerStats,
)

__all__ = [
	"Audio",
	"AudioCapture",
	"AudioCaptureChunk",
	"AudioCaptureConfig",
	"AudioEncodeProfile",
	"AudioEncoder",
	"AudioPlayer",
	"AudioPlayerConfig",
	"Engine",
	"EncodedAudioPacket",
	"EncodedVideoPacket",
	"Event",
	"Image",
	"LogLevel",
	"LogOptions",
	"Matrix",
	"Texture",
	"VideoCodec",
	"VideoColorInfo",
	"VideoColorMatrix",
	"VideoColorRange",
	"VideoContainerInfo",
	"VideoContainerKind",
	"VideoDecoder",
	"VideoDemuxer",
	"VideoFrame",
	"VideoFrameTiming",
	"VideoMuxer",
	"VideoMuxerAudioConfig",
	"VideoMuxerConfig",
	"VideoPacket",
	"VideoPlayer",
	"VideoPlayerConfig",
	"VideoPlayerStats",
	"audio",
	"core",
	"cryptography",
	"image",
	"matrix",
	"ml",
	"render",
	"runtime",
	"video",
	"vision",
]
__version__ = version("oapython")
