from collections.abc import Sequence

class Engine:
	def __init__(self, device: int | None = None) -> None: ...
	def checkpoint(self) -> Event: ...
	def checkpoint_timed(self) -> Event: ...

class Event:
	def is_complete(self) -> bool: ...
	def wait(self) -> None: ...
	def device_duration_seconds(self) -> float: ...
	def try_device_duration_seconds(self) -> float | None: ...

class Matrix:
	@staticmethod
	def from_f32(engine: Engine, shape: Sequence[int], values: Sequence[float]) -> Matrix: ...
	@staticmethod
	def from_i32(engine: Engine, shape: Sequence[int], values: Sequence[int]) -> Matrix: ...
	@staticmethod
	def from_u32(engine: Engine, shape: Sequence[int], values: Sequence[int]) -> Matrix: ...
	@staticmethod
	def from_u8(engine: Engine, shape: Sequence[int], values: Sequence[int]) -> Matrix: ...
	@property
	def shape(self) -> list[int]: ...
	@property
	def dtype(self) -> str: ...
	@property
	def num_elements(self) -> int: ...
	def reshape(self, shape: Sequence[int]) -> Matrix: ...
	def read_f32(self) -> list[float]: ...
	def read_i32(self) -> list[int]: ...
	def read_u32(self) -> list[int]: ...
	def read_u8(self) -> list[int]: ...
	def to_list(self) -> list[float] | list[int]: ...
	def __add__(self, right: Matrix) -> Matrix: ...
	def __sub__(self, right: Matrix) -> Matrix: ...
	def __mul__(self, right: Matrix) -> Matrix: ...
	def __truediv__(self, right: Matrix) -> Matrix: ...
	def __neg__(self) -> Matrix: ...
	def __abs__(self) -> Matrix: ...

class Audio:
	@staticmethod
	def from_planar_f32(engine: Engine, samples: Sequence[float], channels: int,
		sample_rate: int, layout: str = "unknown") -> Audio: ...
	@property
	def channels(self) -> int: ...
	@property
	def samples(self) -> int: ...
	@property
	def sample_rate(self) -> int: ...
	@property
	def layout(self) -> str: ...
	@property
	def duration_seconds(self) -> float: ...
	def as_matrix(self) -> Matrix: ...

class Image:
	@staticmethod
	def from_matrix(matrix: Matrix, layout_name: str, format_name: str) -> Image: ...
	@property
	def width(self) -> int: ...
	@property
	def height(self) -> int: ...
	@property
	def channels(self) -> int: ...
	@property
	def batch_size(self) -> int: ...
	@property
	def layout(self) -> str: ...
	@property
	def format(self) -> str: ...
	@property
	def dtype(self) -> str: ...
	def as_matrix(self) -> Matrix: ...

class Texture:
	@staticmethod
	def from_rgba8(engine: Engine, rgba: Sequence[int], width: int, height: int) -> Texture: ...
	def read_rgba8(self) -> list[int]: ...
	def width(self) -> int: ...
	def height(self) -> int: ...

# ── Matrix result types ────────────────────────────────────────────────────────

class MoeExpertPlan:
	@property
	def counts(self) -> Matrix: ...
	@property
	def offsets(self) -> Matrix: ...
	@property
	def packed_token(self) -> Matrix: ...
	@property
	def packed_expert(self) -> Matrix: ...
	@property
	def packed_slot(self) -> Matrix: ...
	@property
	def inverse(self) -> Matrix: ...

# ── Vision result types ────────────────────────────────────────────────────────

class NmsResult:
	@property
	def indices(self) -> Matrix: ...
	@property
	def count(self) -> Matrix: ...

class DetectionMetricsResult:
	@property
	def counts(self) -> Matrix: ...
	@property
	def per_class(self) -> Matrix: ...
	@property
	def mean_average_precision_by_threshold(self) -> Matrix: ...
	@property
	def mean_average_precision(self) -> Matrix: ...

class SegmentationMetricsResult:
	@property
	def confusion(self) -> Matrix: ...
	@property
	def per_class(self) -> Matrix: ...
	@property
	def mean_iou(self) -> Matrix: ...
	@property
	def pixel_accuracy(self) -> Matrix: ...

# ── Cryptography types ─────────────────────────────────────────────────────────

class Hasher:
	def __init__(self) -> None: ...
	def update(self, data: bytes | Sequence[int]) -> None: ...
	def finalize(self) -> list[int]: ...
	def reset(self) -> None: ...

class MerkleTree:
	@staticmethod
	def build(leaves: Sequence[Sequence[int]]) -> MerkleTree: ...
	def root(self) -> list[int]: ...
	def proof(self, leaf_index: int) -> MerkleProof: ...

class MerkleProof:
	def verify(self, leaf: Sequence[int], root: Sequence[int]) -> bool: ...
	def siblings(self) -> list[list[int]]: ...
	def sibling_is_left(self) -> list[bool]: ...

class PublicKey:
	@staticmethod
	def from_bytes(bytes: Sequence[int]) -> PublicKey: ...
	def to_bytes(self) -> list[int]: ...
	def is_zero(self) -> bool: ...
	def to_short_hex(self) -> str: ...

class Signature:
	@staticmethod
	def from_bytes(bytes: Sequence[int]) -> Signature: ...
	def to_bytes(self) -> list[int]: ...
	def is_zero(self) -> bool: ...
	def to_short_hex(self) -> str: ...

class Keypair:
	@property
	def public_key(self) -> PublicKey: ...
	def sign(self, message: Sequence[int]) -> Signature: ...
	def sign_hash(self, hash: Sequence[int]) -> Signature: ...

# ── Matrix operations ──────────────────────────────────────────────────────────

def matrix_ones(engine: Engine, shape: Sequence[int]) -> Matrix: ...
def matrix_full(engine: Engine, shape: Sequence[int], value: float) -> Matrix: ...
def matrix_reshape(input: Matrix, shape: Sequence[int]) -> Matrix: ...
def matrix_add(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_sub(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_mul(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_div(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_mat_mul_nt(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_gather(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_gather_last_dim(left: Matrix, right: Matrix) -> Matrix: ...
def matrix_neg(input: Matrix) -> Matrix: ...
def matrix_abs(input: Matrix) -> Matrix: ...
def matrix_log(input: Matrix) -> Matrix: ...
def matrix_sqrt(input: Matrix) -> Matrix: ...
def matrix_exp(input: Matrix) -> Matrix: ...
def matrix_sin(input: Matrix) -> Matrix: ...
def matrix_cos(input: Matrix) -> Matrix: ...
def matrix_reciprocal(input: Matrix) -> Matrix: ...
def matrix_copy(input: Matrix) -> Matrix: ...
def matrix_scale(input: Matrix, scalar: float) -> Matrix: ...
def matrix_pow(input: Matrix, scalar: float) -> Matrix: ...
def matrix_add_scalar(input: Matrix, scalar: float) -> Matrix: ...
def matrix_sub_scalar(input: Matrix, scalar: float) -> Matrix: ...
def matrix_div_scalar(input: Matrix, scalar: float) -> Matrix: ...
def matrix_clamp_max(input: Matrix, scalar: float) -> Matrix: ...
def matrix_clamp_min(input: Matrix, scalar: float) -> Matrix: ...
def matrix_equal(input: Matrix, scalar: float) -> Matrix: ...
def matrix_softmax(input: Matrix, dim: int) -> Matrix: ...
def matrix_log_softmax(input: Matrix, dim: int) -> Matrix: ...
def matrix_sum(input: Matrix, dim: int) -> Matrix: ...
def matrix_transpose(input: Matrix, dim0: int, dim1: int) -> Matrix: ...
def matrix_slice(input: Matrix, dim: int, start: int, end: int) -> Matrix: ...
def matrix_repeat_interleave(input: Matrix, repeats: int, dim: int) -> Matrix: ...
def matrix_concat(inputs: Sequence[Matrix], dim: int) -> Matrix: ...
def matrix_top_k(input: Matrix, k: int, dim: int) -> tuple[Matrix, Matrix]: ...
def matrix_top_k_mask(indices: Matrix, num_experts: int) -> Matrix: ...
def matrix_moe_expert_plan(indices: Matrix, num_experts: int) -> MoeExpertPlan: ...
def matrix_moe_routing_bias_update(
	selection_mask: Matrix, bias: Matrix,
	experts_per_token: int, gamma: float) -> None: ...
def matrix_philox_uniform(input: Matrix, low: float, high: float, seed: int) -> Matrix: ...
def matrix_philox_normal(input: Matrix, mean: float, stddev: float, seed: int) -> Matrix: ...
def matrix_dropout(input: Matrix, probability: float, seed: int) -> Matrix: ...
def matrix_sample_logits(input: Matrix, temperature: float, top_k: int,
	top_p: float, seed: int) -> Matrix: ...
def matrix_set_rng_seed(seed: int) -> None: ...

# ── ML classes ────────────────────────────────────────────────────────────────

class Parameter:
	def __init__(self, name: str, data: Matrix) -> None: ...
	@property
	def name(self) -> str: ...
	def data(self) -> Matrix: ...
	def gradient(self) -> Matrix | None: ...
	def set_requires_grad(self, requires_grad: bool) -> None: ...
	@property
	def requires_grad(self) -> bool: ...

class GradientTape:
	def __init__(self) -> None: ...
	def backward(self, root: Matrix) -> None: ...
	def close(self) -> None: ...
	def __enter__(self) -> GradientTape: ...
	def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> bool: ...

class Sgd:
	def __init__(self, parameters: list[Parameter], learning_rate: float,
		momentum: float = 0.0, weight_decay: float = 0.0) -> None: ...
	def zero_grad(self) -> None: ...
	def step(self) -> None: ...
	@property
	def learning_rate(self) -> float: ...
	def set_learning_rate(self, lr: float) -> None: ...
	@property
	def step_count(self) -> int: ...

class Adam:
	def __init__(self, parameters: list[Parameter], learning_rate: float,
		beta1: float = 0.9, beta2: float = 0.999, epsilon: float = 1e-8) -> None: ...
	def zero_grad(self) -> None: ...
	def step(self) -> None: ...
	@property
	def learning_rate(self) -> float: ...
	def set_learning_rate(self, lr: float) -> None: ...
	@property
	def step_count(self) -> int: ...

class AdamW:
	def __init__(self, parameters: list[Parameter], learning_rate: float,
		beta1: float = 0.9, beta2: float = 0.999, epsilon: float = 1e-8,
		weight_decay: float = 0.01) -> None: ...
	def zero_grad(self) -> None: ...
	def step(self) -> None: ...
	@property
	def learning_rate(self) -> float: ...
	def set_learning_rate(self, lr: float) -> None: ...
	@property
	def step_count(self) -> int: ...

class Muon:
	def __init__(self, parameters: list[Parameter], learning_rate: float,
		beta: float = 0.95, weight_decay: float = 0.1, epsilon: float = 1e-7,
		ns5_iterations: int = 5) -> None: ...
	def zero_grad(self) -> None: ...
	def step(self) -> None: ...
	@property
	def learning_rate(self) -> float: ...
	def set_learning_rate(self, lr: float) -> None: ...
	@property
	def step_count(self) -> int: ...

class BpeTokenizer:
	def __init__(self, target_vocab: int = 512) -> None: ...
	def train(self, bytes: bytes | Sequence[int], num_merges: int) -> None: ...
	def train_text(self, text: str, num_merges: int) -> None: ...
	def encode(self, bytes: bytes | Sequence[int]) -> list[int]: ...
	def encode_text(self, text: str) -> list[int]: ...
	def encode_prompt(self, bytes: bytes | Sequence[int], context_length: int) -> list[int]: ...
	def decode(self, tokens: Sequence[int]) -> bytes: ...
	def decode_text(self, tokens: Sequence[int]) -> str: ...
	@property
	def num_merges(self) -> int: ...
	@property
	def vocab_size(self) -> int: ...
	def save(self, path: str) -> None: ...
	def load(self, path: str) -> None: ...

# ── ML NN layer classes ────────────────────────────────────────────────────────

class Linear:
	def __init__(self, engine: Engine, input_features: int, output_features: int,
		seed: int, bias: bool = True) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def input_features(self) -> int: ...
	@property
	def output_features(self) -> int: ...
	@property
	def has_bias(self) -> bool: ...
	def weight(self) -> Parameter: ...
	def bias(self) -> Parameter | None: ...
	def parameters(self) -> list[Parameter]: ...

class Embedding:
	def __init__(self, engine: Engine, num_embeddings: int, embedding_dim: int,
		seed: int) -> None: ...
	def forward(self, indices: Matrix) -> Matrix: ...
	@property
	def num_embeddings(self) -> int: ...
	@property
	def embedding_dim(self) -> int: ...
	def weight(self) -> Parameter: ...
	def parameters(self) -> list[Parameter]: ...

class LayerNorm:
	def __init__(self, engine: Engine, normalized_shape: int,
		epsilon: float = 1e-5) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	def forward_channel(self, input: Matrix) -> Matrix: ...
	def forward_channel_relu(self, input: Matrix) -> Matrix: ...
	@property
	def normalized_shape(self) -> int: ...
	@property
	def epsilon(self) -> float: ...
	def weight(self) -> Parameter: ...
	def bias(self) -> Parameter: ...
	def parameters(self) -> list[Parameter]: ...

class RmsNorm:
	def __init__(self, engine: Engine, dimension: int,
		epsilon: float = 1e-5) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def dimension(self) -> int: ...
	@property
	def epsilon(self) -> float: ...
	def weight(self) -> Parameter: ...
	def parameters(self) -> list[Parameter]: ...

class Dropout:
	def __init__(self, probability: float, seed: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def probability(self) -> float: ...
	@property
	def training(self) -> bool: ...
	def train(self) -> None: ...
	def eval(self) -> None: ...

class RnnCell:
	def __init__(self, engine: Engine, input_size: int, hidden_size: int,
		bias: bool = True, seed: int = 0) -> None: ...
	def zero_state(self, batch: int) -> Matrix: ...
	def step(self, input: Matrix, hidden: Matrix) -> Matrix: ...
	@property
	def input_size(self) -> int: ...
	@property
	def hidden_size(self) -> int: ...
	@property
	def has_bias(self) -> bool: ...
	def all_parameters(self) -> list[Parameter]: ...

class Rnn:
	def __init__(self, engine: Engine, input_size: int, hidden_size: int,
		num_layers: int = 1, bias: bool = True, seed: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def input_size(self) -> int: ...
	@property
	def hidden_size(self) -> int: ...
	@property
	def num_layers(self) -> int: ...
	@property
	def has_bias(self) -> bool: ...
	def all_parameters(self) -> list[Parameter]: ...
	def layer_parameters(self, layer: int) -> list[Parameter] | None: ...

class GruCell:
	def __init__(self, engine: Engine, input_size: int, hidden_size: int,
		bias: bool = True, seed: int = 0) -> None: ...
	def zero_state(self, batch: int) -> Matrix: ...
	def step(self, input: Matrix, hidden: Matrix) -> Matrix: ...
	@property
	def input_size(self) -> int: ...
	@property
	def hidden_size(self) -> int: ...
	@property
	def has_bias(self) -> bool: ...
	def all_parameters(self) -> list[Parameter]: ...

class Gru:
	def __init__(self, engine: Engine, input_size: int, hidden_size: int,
		num_layers: int = 1, bias: bool = True, seed: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def input_size(self) -> int: ...
	@property
	def hidden_size(self) -> int: ...
	@property
	def num_layers(self) -> int: ...
	@property
	def has_bias(self) -> bool: ...
	def all_parameters(self) -> list[Parameter]: ...
	def layer_parameters(self, layer: int) -> list[Parameter] | None: ...

class AttentionMode:
	Causal: AttentionMode
	Bidirectional: AttentionMode

class TransformerBlock:
	def __init__(self, engine: Engine, model_width: int, hidden_width: int,
		sequence_length: int, num_heads: int, epsilon: float = 1e-5,
		seed: int = 0) -> None: ...
	@staticmethod
	def with_conditioning(engine: Engine, model_width: int, hidden_width: int,
		sequence_length: int, num_heads: int, condition_dim: int,
		epsilon: float = 1e-5, seed: int = 0) -> TransformerBlock: ...
	@staticmethod
	def with_moe(engine: Engine, model_width: int, expert_hidden_width: int,
		sequence_length: int, num_heads: int, num_experts: int,
		experts_per_token: int, epsilon: float = 1e-5,
		seed: int = 0) -> TransformerBlock: ...
	def forward(self, input: Matrix) -> Matrix: ...
	def forward_masked(self, input: Matrix, additive_mask: Matrix) -> Matrix: ...
	def forward_conditioned(self, input: Matrix, condition: Matrix) -> Matrix: ...
	def forward_conditioned_masked(self, input: Matrix, condition: Matrix,
		additive_mask: Matrix) -> Matrix: ...
	@property
	def model_width(self) -> int: ...
	@property
	def hidden_width(self) -> int: ...
	@property
	def sequence_length(self) -> int: ...
	@property
	def num_heads(self) -> int: ...
	@property
	def is_moe(self) -> bool: ...
	@property
	def is_adaptively_conditioned(self) -> bool: ...
	@property
	def condition_dim(self) -> int | None: ...
	def set_attention_mode(self, mode: AttentionMode) -> None: ...
	def attention_mode(self) -> AttentionMode: ...
	def set_sequence_length(self, sequence_length: int) -> None: ...

class Transformer:
	def __init__(self, engine: Engine, vocab_size: int, context_length: int,
		model_width: int, hidden_width: int, num_layers: int, num_heads: int,
		epsilon: float = 1e-5, seed: int = 0) -> None: ...
	@staticmethod
	def with_moe(engine: Engine, vocab_size: int, context_length: int,
		model_width: int, expert_hidden_width: int, num_layers: int,
		num_heads: int, num_experts: int, experts_per_token: int,
		epsilon: float = 1e-5, seed: int = 0) -> Transformer: ...
	def forward(self, tokens: Matrix) -> Matrix: ...
	@property
	def vocab_size(self) -> int: ...
	@property
	def context_length(self) -> int: ...
	@property
	def model_width(self) -> int: ...
	@property
	def hidden_width(self) -> int: ...
	@property
	def num_layers(self) -> int: ...
	@property
	def num_heads(self) -> int: ...
	@property
	def is_moe(self) -> bool: ...
	def all_parameters(self) -> list[Parameter]: ...

class Mamba3Config:
	def __init__(self, model_width: int) -> None: ...
	@property
	def model_width(self) -> int: ...
	@model_width.setter
	def model_width(self, value: int) -> None: ...
	@property
	def state_size(self) -> int: ...
	@state_size.setter
	def state_size(self, value: int) -> None: ...
	@property
	def expand(self) -> int: ...
	@expand.setter
	def expand(self, value: int) -> None: ...
	@property
	def head_dim(self) -> int: ...
	@head_dim.setter
	def head_dim(self, value: int) -> None: ...
	@property
	def num_groups(self) -> int: ...
	@num_groups.setter
	def num_groups(self, value: int) -> None: ...
	@property
	def mimo_rank(self) -> int: ...
	@mimo_rank.setter
	def mimo_rank(self, value: int) -> None: ...
	@property
	def rope_fraction(self) -> float: ...
	@rope_fraction.setter
	def rope_fraction(self, value: float) -> None: ...
	@property
	def dt_min(self) -> float: ...
	@dt_min.setter
	def dt_min(self, value: float) -> None: ...
	@property
	def dt_max(self) -> float: ...
	@dt_max.setter
	def dt_max(self, value: float) -> None: ...
	@property
	def dt_init_floor(self) -> float: ...
	@dt_init_floor.setter
	def dt_init_floor(self, value: float) -> None: ...
	@property
	def a_floor(self) -> float: ...
	@a_floor.setter
	def a_floor(self, value: float) -> None: ...
	@property
	def output_norm(self) -> bool: ...
	@output_norm.setter
	def output_norm(self, value: bool) -> None: ...

class Mamba3State:
	@property
	def batch_size(self) -> int: ...

class Mamba3:
	def __init__(self, engine: Engine, config: Mamba3Config, seed: int) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	def new_state(self, batch_size: int) -> Mamba3State: ...
	def step(self, input: Matrix, state: Mamba3State) -> Matrix: ...
	def all_parameters(self) -> list[Parameter]: ...

class CheckpointManagerConfig:
	def __init__(self, directory: str = "var/model/dev", model_name: str = "Module",
		context: str = "", max_keep: int = 5, save_best: bool = True,
		metric_name: str = "loss", lower_is_better: bool = True) -> None: ...
	@property
	def directory(self) -> str: ...
	@property
	def model_name(self) -> str: ...
	@property
	def context(self) -> str: ...
	@property
	def max_keep(self) -> int: ...
	@property
	def save_best(self) -> bool: ...
	@property
	def metric_name(self) -> str: ...
	@property
	def lower_is_better(self) -> bool: ...

# ── ML NN additional classes ──────────────────────────────────────────────────

class Relu:
	def __init__(self) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...

class Gelu:
	def __init__(self) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...

class Silu:
	def __init__(self) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...

class Softmax:
	def __init__(self, dim: int = -1) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def dim(self) -> int: ...

class LogSoftmax:
	def __init__(self, dim: int = -1) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def dim(self) -> int: ...

class Identity:
	def __init__(self) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...

class Flatten:
	def __init__(self, start_dim: int = 1, end_dim: int = -1) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def start_dim(self) -> int: ...
	@property
	def end_dim(self) -> int: ...

class Swiglu:
	def __init__(self, engine: Engine, input_features: int, intermediate_size: int,
		bias: bool = True, seed: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def input_features(self) -> int: ...
	@property
	def intermediate_size(self) -> int: ...
	@property
	def has_bias(self) -> bool: ...
	def all_parameters(self) -> list[Parameter]: ...

class Ffn:
	def __init__(self, engine: Engine, model_width: int, hidden_width: int,
		epsilon: float = 1e-5, seed: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def model_width(self) -> int: ...
	@property
	def hidden_width(self) -> int: ...
	@property
	def epsilon(self) -> float: ...
	def all_parameters(self) -> list[Parameter]: ...

class AttentionBackend:
	Auto: AttentionBackend
	Standard: AttentionBackend
	Flash: AttentionBackend

class MultiHeadAttention:
	def __init__(self, engine: Engine, model_width: int, num_heads: int,
		sequence_length: int, dropout_probability: float = 0.0,
		bias: bool = True, seed: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	def forward_masked(self, input: Matrix, additive_mask: Matrix) -> Matrix: ...
	def set_backend(self, backend: AttentionBackend) -> None: ...
	def backend(self) -> AttentionBackend: ...
	def last_backend(self) -> AttentionBackend: ...
	def set_mode(self, mode: AttentionMode) -> None: ...
	def mode(self) -> AttentionMode: ...
	@property
	def model_width(self) -> int: ...
	@property
	def num_heads(self) -> int: ...
	@property
	def sequence_length(self) -> int: ...
	def set_sequence_length(self, sequence_length: int) -> None: ...
	@property
	def has_bias(self) -> bool: ...
	@property
	def dropout_probability(self) -> float: ...
	def all_parameters(self) -> list[Parameter]: ...

# ── Conv layers ───────────────────────────────────────────────────────────────

class Conv1d:
	def __init__(self, engine: Engine, input_channels: int, output_channels: int,
		kernel_size: int, stride: int = 1, padding: int = 0, dilation: int = 1,
		seed: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def input_channels(self) -> int: ...
	@property
	def output_channels(self) -> int: ...
	@property
	def kernel_size(self) -> int: ...
	@property
	def stride(self) -> int: ...
	@property
	def padding(self) -> int: ...
	@property
	def dilation(self) -> int: ...
	def weight(self) -> Parameter: ...
	def bias(self) -> Parameter: ...
	def all_parameters(self) -> list[Parameter]: ...

class ConvTranspose1d:
	def __init__(self, engine: Engine, input_channels: int, output_channels: int,
		kernel_size: int, stride: int = 1, padding: int = 0,
		seed: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def input_channels(self) -> int: ...
	@property
	def output_channels(self) -> int: ...
	@property
	def kernel_size(self) -> int: ...
	@property
	def stride(self) -> int: ...
	@property
	def padding(self) -> int: ...
	def weight(self) -> Parameter: ...
	def all_parameters(self) -> list[Parameter]: ...

class ConvTranspose2d:
	def __init__(self, engine: Engine, input_channels: int, output_channels: int,
		kernel_size: int, stride: int = 1, padding: int = 0,
		seed: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def input_channels(self) -> int: ...
	@property
	def output_channels(self) -> int: ...
	@property
	def kernel_size(self) -> int: ...
	@property
	def stride(self) -> int: ...
	@property
	def padding(self) -> int: ...
	def weight(self) -> Parameter: ...
	def bias(self) -> Parameter: ...
	def all_parameters(self) -> list[Parameter]: ...

class Conv2d:
	def __init__(self, engine: Engine, input_channels: int, output_channels: int,
		kernel_size: int, stride: int = 1, padding: int = 0, groups: int = 1,
		seed: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def input_channels(self) -> int: ...
	@property
	def output_channels(self) -> int: ...
	@property
	def kernel_size(self) -> int: ...
	@property
	def stride(self) -> int: ...
	@property
	def padding(self) -> int: ...
	@property
	def groups(self) -> int: ...
	def weight(self) -> Parameter: ...
	def bias(self) -> Parameter: ...
	def all_parameters(self) -> list[Parameter]: ...

# ── Pool / Upsample layers ────────────────────────────────────────────────────

class AvgPool2d:
	def __init__(self, kernel_size: int, stride: int = 0, padding: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def kernel_size(self) -> int: ...
	@property
	def stride(self) -> int: ...
	@property
	def padding(self) -> int: ...

class MaxPool2d:
	def __init__(self, kernel_size: int, stride: int = 0, padding: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def kernel_size(self) -> int: ...
	@property
	def stride(self) -> int: ...
	@property
	def padding(self) -> int: ...

class AdaptiveAvgPool2d:
	def __init__(self, output_height: int, output_width: int = 0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def output_height(self) -> int: ...
	@property
	def output_width(self) -> int: ...

class UpsampleMode:
	Nearest: UpsampleMode
	Bilinear: UpsampleMode

class Upsample:
	def __init__(self, scale_factor: int, mode: UpsampleMode = ...) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def scale_factor(self) -> int: ...
	@property
	def mode(self) -> UpsampleMode: ...

# ── Rope ──────────────────────────────────────────────────────────────────────

class Rope:
	def __init__(self, num_heads: int, head_dim: int, theta_base: float = 10000.0) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def num_heads(self) -> int: ...
	@property
	def head_dim(self) -> int: ...
	@property
	def theta_base(self) -> float: ...

# ── ByteEmbedding / ByteHead ──────────────────────────────────────────────────

class ByteEmbedding:
	def __init__(self, engine: Engine, embedding_dim: int, seed: int = 0) -> None: ...
	def forward(self, byte_ids: Matrix) -> Matrix: ...
	@property
	def embedding_dim(self) -> int: ...
	def weight(self) -> Parameter: ...
	def all_parameters(self) -> list[Parameter]: ...

class ByteHead:
	def __init__(self, engine: Engine, input_features: int, seed: int = 0) -> None: ...
	def forward(self, hidden: Matrix) -> Matrix: ...
	@property
	def input_features(self) -> int: ...
	def weight(self) -> Parameter: ...
	def bias(self) -> Parameter: ...
	def all_parameters(self) -> list[Parameter]: ...

# ── BatchNorm2d ───────────────────────────────────────────────────────────────

class BatchNorm2d:
	def __init__(self, engine: Engine, num_features: int,
		epsilon: float = 1e-5, momentum: float = 0.1) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def num_features(self) -> int: ...
	@property
	def epsilon(self) -> float: ...
	@property
	def momentum(self) -> float: ...
	def weight(self) -> Parameter: ...
	def bias(self) -> Parameter: ...
	def running_mean(self) -> Matrix: ...
	def running_variance(self) -> Matrix: ...
	def train(self) -> None: ...
	def eval(self) -> None: ...
	@property
	def is_training(self) -> bool: ...
	def all_parameters(self) -> list[Parameter]: ...

# ── VQ ────────────────────────────────────────────────────────────────────────

class VectorQuantizerConfig:
	def __init__(self, num_codes: int = 256, code_dim: int = 64,
		commitment_beta: float = 0.25, ema_decay: float = 0.99,
		ema_epsilon: float = 1e-5, dead_threshold: float = 1.0,
		normalize_codes: bool = False) -> None: ...
	@property
	def num_codes(self) -> int: ...
	@property
	def code_dim(self) -> int: ...
	@property
	def commitment_beta(self) -> float: ...
	@property
	def ema_decay(self) -> float: ...
	@property
	def ema_epsilon(self) -> float: ...
	@property
	def dead_threshold(self) -> float: ...
	@property
	def normalize_codes(self) -> bool: ...

class VqResult:
	@property
	def quantized(self) -> Matrix: ...
	@property
	def indices(self) -> Matrix: ...
	@property
	def commitment_loss(self) -> Matrix: ...

class ResidualVqResult:
	@property
	def quantized(self) -> Matrix: ...
	@property
	def indices(self) -> list[Matrix]: ...
	@property
	def residuals(self) -> list[Matrix]: ...
	@property
	def commitment_loss(self) -> Matrix: ...

class VectorQuantizer:
	def __init__(self, engine: Engine, config: VectorQuantizerConfig,
		seed: int = 0) -> None: ...
	def quantize(self, latent: Matrix) -> VqResult: ...
	def ema_update(self, latent: Matrix, indices: Matrix) -> None: ...
	def lookup(self, indices: Matrix) -> Matrix: ...
	def seed(self, latents: Matrix) -> None: ...
	def codebook(self) -> Matrix: ...
	def ema_step(self) -> int: ...
	@property
	def num_codes(self) -> int: ...
	@property
	def code_dim(self) -> int: ...

class ResidualVectorQuantizer:
	def __init__(self, engine: Engine, config: VectorQuantizerConfig,
		num_levels: int, seed: int = 0) -> None: ...
	def quantize(self, latent: Matrix) -> ResidualVqResult: ...
	def ema_update(self, result: ResidualVqResult) -> None: ...
	def lookup(self, indices: list[Matrix]) -> Matrix: ...
	def seed(self, latents: Matrix) -> None: ...
	@property
	def num_levels(self) -> int: ...

def ml_save_checkpoint(path: str, params: list[Parameter],
	optimizer: Sgd | Adam | AdamW | Muon) -> None: ...
def ml_load_checkpoint(engine: Engine, path: str, params: list[Parameter],
	optimizer: Sgd | Adam | AdamW | Muon) -> None: ...
def ml_clip_grad_norm(gradients: list[Matrix], max_norm: float) -> None: ...

# ── LR Schedulers ──────────────────────────────────────────────────────────────

class CosineScheduler:
	def __init__(self, max_learning_rate: float, min_learning_rate: float,
		total_steps: int) -> None: ...
	def learning_rate(self, step: int) -> float: ...

class WarmupScheduler:
	def __init__(self, target_learning_rate: float, warmup_steps: int) -> None: ...
	def learning_rate(self, step: int) -> float: ...

class OneCycleScheduler:
	def __init__(self, max_learning_rate: float, total_steps: int,
		percent_start: float = 0.3, division_factor: float = 25.0,
		final_division_factor: float = 10000.0) -> None: ...
	def learning_rate(self, step: int) -> float: ...

class CyclicMode:
	Triangular: CyclicMode
	Triangular2: CyclicMode
	ExpRange: CyclicMode

class CyclicScheduler:
	def __init__(self, base_learning_rate: float, max_learning_rate: float,
		step_size_up: int, mode: CyclicMode = ..., gamma: float = 1.0) -> None: ...
	def learning_rate(self, step: int) -> float: ...

class CosineWarmRestartsScheduler:
	def __init__(self, max_learning_rate: float, initial_period: int,
		period_multiplier: int = 1, min_learning_rate: float = 0.0) -> None: ...
	def learning_rate(self, step: int) -> float: ...

class PlateauMode:
	Min: PlateauMode
	Max: PlateauMode

class ReduceOnPlateauScheduler:
	def __init__(self, initial_learning_rate: float, factor: float = 0.1,
		patience: int = 10, threshold: float = 1e-4, min_learning_rate: float = 0.0,
		mode: PlateauMode = ...) -> None: ...
	def step(self, metric: float) -> None: ...
	def learning_rate(self, step: int) -> float: ...

class LinearWarmupCosineScheduler:
	def __init__(self, warmup_steps: int, total_steps: int,
		max_learning_rate: float, min_learning_rate: float) -> None: ...
	def learning_rate(self, step: int) -> float: ...

# ── TrainingSession ───────────────────────────────────────────────────────────

class TrainingState:
	Running: TrainingState
	Paused: TrainingState
	Stopping: TrainingState
	Completed: TrainingState
	Failed: TrainingState

class TrainingSessionSnapshot:
	@property
	def revision(self) -> int: ...
	@property
	def state(self) -> TrainingState: ...
	@property
	def step(self) -> int: ...
	@property
	def epoch(self) -> int: ...
	@property
	def learning_rate(self) -> float: ...
	@property
	def loss(self) -> float: ...
	@property
	def gpu_ms(self) -> float: ...
	@property
	def wall_ms(self) -> float: ...
	def metrics(self) -> list[tuple[str, float]]: ...

class TrainingSessionConfig:
	def __init__(self, command_capacity: int = 64, result_capacity: int = 128,
		snapshot_capacity: int = 32) -> None: ...
	@property
	def command_capacity(self) -> int: ...
	@property
	def result_capacity(self) -> int: ...
	@property
	def snapshot_capacity(self) -> int: ...

class TrainingSession:
	def __init__(self, config: TrainingSessionConfig | None = None) -> None: ...
	def pause(self, expected_revision: int) -> int: ...
	def resume(self, expected_revision: int) -> int: ...
	def stop(self, expected_revision: int) -> int: ...
	def checkpoint(self, expected_revision: int) -> int: ...
	def evaluate(self, expected_revision: int) -> int: ...
	def request_recapture(self, expected_revision: int) -> int: ...
	def publish_metric(self, name: str, value: float) -> None: ...
	def state(self) -> TrainingState: ...
	def revision(self) -> int: ...
	def current_snapshot(self) -> TrainingSessionSnapshot: ...
	def latest_snapshot(self) -> TrainingSessionSnapshot | None: ...

# ── ML operations ──────────────────────────────────────────────────────────────

def ml_gelu(input: Matrix) -> Matrix: ...
def ml_silu(input: Matrix) -> Matrix: ...
def ml_relu(input: Matrix) -> Matrix: ...
def ml_tanh(input: Matrix) -> Matrix: ...
def ml_sigmoid(input: Matrix) -> Matrix: ...
def ml_mish(input: Matrix) -> Matrix: ...
def ml_softplus(input: Matrix) -> Matrix: ...
def ml_detach(input: Matrix) -> Matrix: ...
def ml_swiglu(left: Matrix, right: Matrix) -> Matrix: ...
def ml_leaky_relu(input: Matrix, alpha: float) -> Matrix: ...
def ml_elu(input: Matrix, alpha: float) -> Matrix: ...
def ml_silu_mul(input: Matrix, intermediate_size: int) -> Matrix: ...
def ml_loss_smooth_l1(left: Matrix, right: Matrix) -> Matrix: ...
def ml_loss_mse(left: Matrix, right: Matrix) -> Matrix: ...
def ml_loss_l1(left: Matrix, right: Matrix) -> Matrix: ...
def ml_loss_bce(left: Matrix, right: Matrix) -> Matrix: ...
def ml_loss_cross_entropy(left: Matrix, right: Matrix) -> Matrix: ...
def ml_loss_masked_cross_entropy(logits: Matrix, targets: Matrix, mask: Matrix,
	valid_count: int) -> Matrix: ...
def ml_metric_scalar_loss(loss: Matrix) -> float: ...
def ml_metric_accuracy(logits: Matrix, labels: Matrix) -> float: ...
def ml_byte_encode(engine: Engine, bytes: Sequence[int]) -> Matrix: ...
def ml_byte_encode_batched(engine: Engine, bytes: Sequence[int]) -> Matrix: ...
def ml_byte_encode_text(engine: Engine, text: str) -> Matrix: ...
def ml_byte_decode(logits: Matrix) -> list[int]: ...
def ml_byte_decode_text(logits: Matrix) -> str: ...
def ml_byte_sample(logits: Matrix, temperature: float, top_k: int,
	top_p: float, seed: int) -> list[int]: ...

# ── Audio sessions ────────────────────────────────────────────────────────────

class AudioCaptureConfig:
	def __init__(self, sample_rate: int = 48000, channel_count: int = 2,
		ring_milliseconds: int = 500) -> None: ...
	@property
	def sample_rate(self) -> int: ...
	@property
	def channel_count(self) -> int: ...
	@property
	def ring_milliseconds(self) -> int: ...

class AudioCaptureChunk:
	@property
	def interleaved(self) -> list[float]: ...
	@property
	def sample_rate(self) -> int: ...
	@property
	def channel_count(self) -> int: ...
	@property
	def frame_count(self) -> int: ...
	@property
	def first_frame_index(self) -> int: ...
	@property
	def presentation_timestamp_us(self) -> int: ...

class AudioCapture:
	def __init__(self, engine: Engine,
		config: AudioCaptureConfig | None = None) -> None: ...
	def start(self) -> None: ...
	def stop(self) -> None: ...
	def poll(self, max_frames: int = 4096) -> AudioCaptureChunk | None: ...
	def close(self) -> None: ...
	@property
	def is_open(self) -> bool: ...
	@property
	def is_started(self) -> bool: ...
	def dropped_frame_count(self) -> int: ...
	def device_error_count(self) -> int: ...

class AudioPlayerConfig:
	def __init__(self, uri: str, loop_playback: bool = False,
		ring_milliseconds: int = 500) -> None: ...
	@property
	def uri(self) -> str: ...
	@property
	def loop_playback(self) -> bool: ...
	@property
	def ring_milliseconds(self) -> int: ...

class AudioPlayer:
	def __init__(self, engine: Engine, config: AudioPlayerConfig) -> None: ...
	@staticmethod
	def open_uri(engine: Engine, uri: str) -> "AudioPlayer": ...
	def play(self) -> None: ...
	def pause(self) -> None: ...
	def seek(self, timestamp_us: int) -> None: ...
	def set_loop(self, enabled: bool) -> None: ...
	def set_muted(self, muted: bool) -> None: ...
	def close(self) -> None: ...
	@property
	def is_open(self) -> bool: ...
	@property
	def is_playing(self) -> bool: ...
	@property
	def is_eos(self) -> bool: ...
	@property
	def is_muted(self) -> bool: ...
	@property
	def sample_rate(self) -> int: ...
	@property
	def channel_count(self) -> int: ...
	@property
	def duration_us(self) -> int: ...
	@property
	def position_us(self) -> int: ...
	def underrun_frame_count(self) -> int: ...
	def device_error_count(self) -> int: ...

class AudioEncodeProfile:
	def __init__(self, sample_rate: int = 48000, channel_count: int = 2,
		frames_per_packet: int = 1024) -> None: ...
	@property
	def sample_rate(self) -> int: ...
	@property
	def channel_count(self) -> int: ...
	@property
	def frames_per_packet(self) -> int: ...

class EncodedAudioPacket:
	def bitstream(self) -> bytes: ...
	@property
	def presentation_frame(self) -> int: ...
	@property
	def duration_frames(self) -> int: ...

class AudioEncoder:
	def __init__(self, profile: AudioEncodeProfile | None = None) -> None: ...
	def encode(self, interleaved: Sequence[float]) -> list[EncodedAudioPacket]: ...
	def flush(self) -> list[EncodedAudioPacket]: ...
	def close(self) -> None: ...
	@property
	def is_open(self) -> bool: ...

def audio_player_from_audio(engine: Engine, audio: Audio) -> AudioPlayer: ...

# ── Audio operations ───────────────────────────────────────────────────────────

def audio_decode_file(engine: Engine, path: str) -> Audio: ...
def audio_decode_memory(engine: Engine, encoded: Sequence[int]) -> Audio: ...
def audio_encode_wav_f32(input: Audio) -> bytes: ...
def audio_encode_interleaved_wav_f32(samples: Sequence[float], sample_rate: int,
	channels: int) -> bytes: ...
def audio_save_wav_f32(path: str, input: Audio) -> None: ...
def audio_normalize(input: Audio, target_db: float = -3.0, mode: str = "peak") -> Audio: ...
def audio_resample(input: Audio, out_rate: int, filter_half_width: int = 64) -> Audio: ...
def audio_gain(input: Audio, gain_db: float) -> Audio: ...
def audio_clip(input: Audio, minimum: float, maximum: float) -> Audio: ...
def audio_saturate(input: Audio, drive_db: float, mix: float) -> Audio: ...
def audio_reverb(input: Audio, decay_seconds: float, wet: float) -> Audio: ...
def audio_pre_emphasis(input: Audio, alpha: float) -> Audio: ...
def audio_to_mono(input: Audio) -> Audio: ...
def audio_fade(input: Audio, fade_in_samples: int, fade_out_samples: int) -> Audio: ...
def audio_mix(a: Audio, b: Audio, gain_a: float, gain_b: float) -> Audio: ...
def audio_amplitude_to_db(input: Audio, floor_db: float) -> Matrix: ...
def audio_waveform_envelope(input: Audio, bins: int) -> Matrix: ...
def audio_stft(input: Audio, fft_size: int = 1024, hop_size: int = 256,
	win_size: int = 0, window: str = "hann", center: bool = True) -> Matrix: ...
def audio_mel_spectrogram(input: Audio, fft_size: int = 1024, hop_size: int = 256,
	num_mels: int = 80, f_min: float = 0.0, f_max: float = 0.0,
	log_scale: bool = True, normalize: bool = False) -> Matrix: ...
def audio_mfcc(input: Audio, num_coeffs: int = 13, num_mels: int = 80,
	fft_size: int = 1024, hop_size: int = 256, f_min: float = 0.0,
	f_max: float = 0.0, log_scale: bool = True, normalize: bool = False) -> Matrix: ...
def audio_biquad(input: Audio, b0: float, b1: float, b2: float,
	a1: float, a2: float) -> Audio: ...
def audio_sos_filter(input: Audio,
	sections: Sequence[Sequence[float]]) -> Audio: ...

# ── Image operations ───────────────────────────────────────────────────────────

def image_decode_file(engine: Engine, path: str, format_name: str) -> Image: ...
def image_decode_memory(engine: Engine, encoded: Sequence[int], format_name: str) -> Image: ...
def image_encode(input: Image, codec_name: str, quality: int = 90) -> bytes: ...
def image_save_file(path: str, input: Image, quality: int = 90) -> None: ...
def image_save_rgba_file(path: str, rgba: Sequence[int], width: int, height: int,
	quality: int = 90) -> None: ...
def image_can_decode(codec_name: str) -> bool: ...
def image_can_encode(codec_name: str) -> bool: ...
def image_resize(input: Image, width: int, height: int,
	interpolation_name: str = "bilinear") -> Image: ...
def image_normalize(input: Image, mean: Sequence[float], std: Sequence[float]) -> Image: ...
def image_convert_color(input: Image, format_name: str) -> Image: ...
def image_resize_normalize(input: Image, width: int, height: int,
	mean: Sequence[float], std: Sequence[float]) -> Image: ...
def image_segmentation_overlay(input: Image, mask: Matrix, palette: Matrix,
	alpha: float) -> Image: ...
def image_crop(input: Image, x: int, y: int, width: int, height: int) -> Image: ...
def image_flip(input: Image, horizontal: bool, vertical: bool) -> Image: ...
def image_rotate(input: Image, degrees: int) -> Image: ...
def image_center_crop(input: Image, width: int, height: int) -> Image: ...
def image_pad(input: Image, left: int, right: int, top: int, bottom: int,
	border_name: str = "constant", border_value: float = 0.0) -> Image: ...
def image_remap(input: Image, map: Matrix, interpolation_name: str = "bilinear",
	border_name: str = "constant", border_value: float = 0.0) -> Image: ...
def image_warp_affine(input: Image, transform: Matrix, width: int, height: int,
	interpolation_name: str = "bilinear", border_name: str = "constant",
	border_value: float = 0.0) -> Image: ...
def image_warp_perspective(input: Image, transform: Matrix, width: int, height: int,
	interpolation_name: str = "bilinear", border_name: str = "constant",
	border_value: float = 0.0) -> Image: ...
def image_grayscale(input: Image) -> Image: ...
def image_clamp(input: Image, low: float, high: float) -> Image: ...
def image_invert(input: Image, max_value: float = 1.0) -> Image: ...
def image_brightness_contrast(input: Image, brightness: float, contrast: float) -> Image: ...
def image_gamma_contrast(input: Image, gamma: float, gain: float) -> Image: ...
def image_solarize(input: Image, threshold: float, max_value: float) -> Image: ...
def image_posterize(input: Image, levels: int, low: float, high: float) -> Image: ...
def image_threshold_binary(input: Image, threshold: float, max_value: float) -> Image: ...
def image_threshold_binary_inv(input: Image, threshold: float, max_value: float) -> Image: ...
def image_threshold_truncate(input: Image, threshold: float) -> Image: ...
def image_threshold_to_zero(input: Image, threshold: float) -> Image: ...
def image_threshold_to_zero_inv(input: Image, threshold: float) -> Image: ...
def image_in_range(input: Image, low: float, high: float, true_value: float) -> Image: ...
def image_alpha_blend(a: Image, b: Image, alpha: float) -> Image: ...
def image_composite(a: Image, b: Image, mask: Image) -> Image: ...
def image_erase(input: Image, x: int, y: int, width: int, height: int,
	value: float) -> Image: ...
def image_color_twist(input: Image, transform: Matrix) -> Image: ...
def image_channel_reorder(input: Image, order: Sequence[int],
	format_name: str) -> Image: ...
def image_gaussian_noise(input: Image, mean: float, stddev: float, seed: int) -> Image: ...
def image_salt_pepper_noise(input: Image, probability: float, salt_value: float,
	pepper_value: float, seed: int) -> Image: ...
def image_gaussian_blur(input: Image, sigma: float, kernel_size: int = 0) -> Image: ...
def image_unsharp_mask(input: Image, sigma: float, amount: float,
	kernel_size: int = 0) -> Image: ...
def image_average_blur(input: Image, width: int, height: int,
	border_name: str = "constant") -> Image: ...
def image_median_blur(input: Image, kernel_size: int,
	border_name: str = "constant") -> Image: ...
def image_bilateral_filter(input: Image, kernel_size: int, sigma_color: float,
	sigma_space: float, border_name: str = "constant") -> Image: ...
def image_sobel(input: Image, dx: int, dy: int,
	border_name: str = "constant") -> Image: ...
def image_scharr(input: Image, dx: int, dy: int,
	border_name: str = "constant") -> Image: ...
def image_laplacian(input: Image, border_name: str = "constant") -> Image: ...
def image_sharpen(input: Image, amount: float, border_name: str = "constant") -> Image: ...
def image_erode(input: Image, width: int, height: int,
	border_name: str = "constant", border_value: float = 0.0) -> Image: ...
def image_dilate(input: Image, width: int, height: int,
	border_name: str = "constant", border_value: float = 0.0) -> Image: ...
def image_morphology_open(input: Image, width: int, height: int,
	border_name: str = "constant", border_value: float = 0.0) -> Image: ...
def image_morphology_close(input: Image, width: int, height: int,
	border_name: str = "constant", border_value: float = 0.0) -> Image: ...
def image_morphology_gradient(input: Image, width: int, height: int,
	border_name: str = "constant", border_value: float = 0.0) -> Image: ...
def image_morphology_top_hat(input: Image, width: int, height: int,
	border_name: str = "constant", border_value: float = 0.0) -> Image: ...
def image_morphology_black_hat(input: Image, width: int, height: int,
	border_name: str = "constant", border_value: float = 0.0) -> Image: ...
def image_convolve_2d(input: Image, kernel: Matrix, border_name: str,
	border_value: float) -> Image: ...
def image_separable_convolve_2d(input: Image, kernel_x: Matrix, kernel_y: Matrix,
	border_name: str = "constant", border_value: float = 0.0) -> Image: ...
def image_adaptive_threshold_mean(input: Image, kernel_size: int, c: float,
	max_value: float, border_name: str = "constant") -> Image: ...
def image_adaptive_threshold_gaussian(input: Image, kernel_size: int, c: float,
	max_value: float, sigma: float, border_name: str = "constant") -> Image: ...

# ── Render operations ──────────────────────────────────────────────────────────

def render_save_texture_file(texture: Texture, path: str, quality: int = 90) -> None: ...

# ── Cryptography operations ────────────────────────────────────────────────────

def crypto_hash(data: bytes | Sequence[int]) -> list[int]: ...
def crypto_hash_combine(left: bytes | Sequence[int],
	right: bytes | Sequence[int]) -> list[int]: ...
def crypto_keccak_f1600(data: bytes | Sequence[int]) -> list[int]: ...
def crypto_kmac256(key: bytes | Sequence[int], data: bytes | Sequence[int],
	custom: bytes | Sequence[int], output_len: int = 32) -> list[int]: ...
def crypto_generate_keypair() -> Keypair: ...
def crypto_pqc_verify(message: bytes | Sequence[int], signature: Signature,
	public_key: PublicKey) -> bool: ...
def crypto_pqc_verify_hash(hash: bytes | Sequence[int], signature: Signature,
	public_key: PublicKey) -> bool: ...

# ── Vision operations ──────────────────────────────────────────────────────────

def vision_box_iou(boxes1: Matrix, boxes2: Matrix) -> Matrix: ...
def vision_confusion_matrix(predictions: Matrix, targets: Matrix, num_classes: int) -> Matrix: ...
def vision_binary_mask_counts(predicted: Matrix, target: Matrix) -> Matrix: ...
def vision_nms(boxes: Matrix, scores: Matrix, classes: Matrix,
	iou_threshold: float = 0.45, score_threshold: float = 0.0,
	max_detections: int = 100, class_agnostic: bool = False) -> NmsResult: ...
def vision_evaluate(predicted_boxes: Matrix, predicted_scores: Matrix,
	predicted_classes: Matrix, predicted_images: Matrix,
	target_boxes: Matrix, target_classes: Matrix, target_images: Matrix,
	thresholds: Matrix, num_classes: int, score_threshold: float) -> DetectionMetricsResult: ...
def vision_evaluate_segmentation(predicted: Matrix, target: Matrix,
	num_classes: int) -> SegmentationMetricsResult: ...

# ── ML NN — Sequential ────────────────────────────────────────────────────────

class Sequential:
	def __init__(self) -> None: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def len(self) -> int: ...
	@property
	def is_empty(self) -> bool: ...
	def train(self) -> None: ...
	def eval(self) -> None: ...
	def all_parameters(self) -> list[Parameter]: ...

# ── ML NN — Moe ───────────────────────────────────────────────────────────────

class MoeRouteStats:
	@property
	def load_fraction(self) -> list[float]: ...
	@property
	def mean_probability(self) -> list[float]: ...
	@property
	def entropy(self) -> float: ...
	@property
	def max_load_ratio(self) -> float: ...
	@property
	def dead_experts(self) -> int: ...

class Moe:
	def __init__(self, engine: Engine, model_width: int, hidden_width: int,
		num_experts: int, experts_per_token: int,
		epsilon: float = 1e-5, seed: int = 0) -> None: ...
	@staticmethod
	def with_shared_experts(engine: Engine, model_width: int, hidden_width: int,
		num_experts: int, experts_per_token: int, num_shared_experts: int,
		epsilon: float = 1e-5, seed: int = 0) -> Moe: ...
	def forward(self, input: Matrix) -> Matrix: ...
	@property
	def model_width(self) -> int: ...
	@property
	def hidden_width(self) -> int: ...
	@property
	def num_experts(self) -> int: ...
	@property
	def experts_per_token(self) -> int: ...
	@property
	def epsilon(self) -> float: ...
	@property
	def num_shared_experts(self) -> int: ...
	def set_sparse_execution(self, sparse: bool) -> None: ...
	def sparse_execution(self) -> bool: ...
	def set_balance_rate(self, gamma: float) -> None: ...
	def balance_rate(self) -> float: ...
	def routing_bias(self) -> Matrix: ...
	def set_aux_loss_alpha(self, alpha: float) -> None: ...
	def aux_loss_alpha(self) -> float: ...
	def set_router_z_loss_beta(self, beta: float) -> None: ...
	def router_z_loss_beta(self) -> float: ...
	def aux_loss(self) -> Matrix: ...
	def update_routing_bias(self) -> None: ...
	def last_selection_mask(self) -> Matrix | None: ...
	def last_gate_probabilities(self) -> Matrix | None: ...
	def route_stats(self) -> MoeRouteStats: ...
	def expert_gate_up_weight(self) -> Parameter: ...
	def expert_gate_up_bias(self) -> Parameter: ...
	def expert_down_weight(self) -> Parameter: ...
	def expert_down_bias(self) -> Parameter: ...
	def train(self) -> None: ...
	def eval(self) -> None: ...
	def all_parameters(self) -> list[Parameter]: ...

# ── ML NN — EmpyrealmCore ─────────────────────────────────────────────────────

class EmpyrealmCore:
	def __init__(self, engine: Engine, vocab_size: int,
		config: Mamba3Config, seed: int) -> None: ...
	def forward(self, tokens: Matrix) -> Matrix: ...
	def forward_embedded(self, embedded: Matrix) -> Matrix: ...
	def new_state(self, batch_size: int) -> Mamba3State: ...
	def step_embedded(self, embedded: Matrix, state: Mamba3State) -> Matrix: ...
	def train(self) -> None: ...
	def eval(self) -> None: ...
	def all_parameters(self) -> list[Parameter]: ...

# ── ML NN — Flow ──────────────────────────────────────────────────────────────

class FlowTimeEmbedding:
	def __init__(self, engine: Engine, embedding_dim: int,
		max_period: float = 10000.0, time_scale: float = 1000.0) -> None: ...
	def forward(self, time: Matrix) -> Matrix: ...
	@property
	def embedding_dim(self) -> int: ...
	@property
	def max_period(self) -> float: ...
	@property
	def time_scale(self) -> float: ...

class FlowTransformerConfig:
	def __init__(self, model_width: int, hidden_width: int, sequence_length: int,
		num_layers: int = 1, num_heads: int = 1,
		num_experts: int = 0, experts_per_token: int = 0,
		epsilon: float = 1e-5, adaptive_conditioning: bool = True) -> None: ...
	@property
	def model_width(self) -> int: ...
	@property
	def hidden_width(self) -> int: ...
	@property
	def sequence_length(self) -> int: ...
	@property
	def num_layers(self) -> int: ...
	@property
	def num_heads(self) -> int: ...
	@property
	def num_experts(self) -> int: ...
	@property
	def experts_per_token(self) -> int: ...
	@property
	def epsilon(self) -> float: ...
	@property
	def adaptive_conditioning(self) -> bool: ...

class FlowTransformer:
	def __init__(self, engine: Engine, config: FlowTransformerConfig,
		seed: int) -> None: ...
	def forward(self, tokens: Matrix) -> Matrix: ...
	def forward_masked(self, tokens: Matrix, token_mask: Matrix) -> Matrix: ...
	def forward_conditioned(self, tokens: Matrix, condition: Matrix,
		token_mask: Matrix | None = None) -> Matrix: ...
	def set_sequence_length(self, sequence_length: int) -> None: ...
	def config(self) -> FlowTransformerConfig: ...
	@property
	def is_moe(self) -> bool: ...
	@property
	def num_layers(self) -> int: ...
	def train(self) -> None: ...
	def eval(self) -> None: ...
	def all_parameters(self) -> list[Parameter]: ...

class FlowDenoiserConfig:
	def __init__(self, input_dim: int, backbone: FlowTransformerConfig,
		condition_dim: int = 0, time_max_period: float = 10000.0,
		time_scale: float = 1000.0,
		condition_dropout_probability: float = 0.0) -> None: ...
	@property
	def input_dim(self) -> int: ...
	@property
	def condition_dim(self) -> int: ...
	@property
	def time_max_period(self) -> float: ...
	@property
	def time_scale(self) -> float: ...
	@property
	def condition_dropout_probability(self) -> float: ...

class FlowDenoiser:
	def __init__(self, engine: Engine, config: FlowDenoiserConfig,
		seed: int) -> None: ...
	def forward(self, sample: Matrix) -> Matrix: ...
	def forward_conditioned(self, sample: Matrix, time: Matrix,
		condition: Matrix | None = None,
		token_mask: Matrix | None = None) -> Matrix: ...
	def forward_guided(self, sample: Matrix, time: Matrix, condition: Matrix,
		guidance_scale: float,
		token_mask: Matrix | None = None) -> Matrix: ...
	def config(self) -> FlowDenoiserConfig: ...
	@property
	def is_moe(self) -> bool: ...
	def position(self) -> Parameter: ...
	def train(self) -> None: ...
	def eval(self) -> None: ...
	def all_parameters(self) -> list[Parameter]: ...

# ── RL — Environment schema ───────────────────────────────────────────────────

class EnvironmentSpaceKind:
	Box: EnvironmentSpaceKind
	Discrete: EnvironmentSpaceKind
	Binary: EnvironmentSpaceKind

class EnvironmentSpace:
	@staticmethod
	def continuous(name: str, shape: Sequence[int], dtype: str,
		minimum: float, maximum: float) -> EnvironmentSpace: ...
	@staticmethod
	def discrete(name: str, cardinality: int, dtype: str) -> EnvironmentSpace: ...
	@staticmethod
	def binary(name: str, shape: Sequence[int]) -> EnvironmentSpace: ...
	@property
	def name(self) -> str: ...
	@property
	def kind(self) -> EnvironmentSpaceKind: ...
	@property
	def shape(self) -> list[int]: ...
	@property
	def dtype(self) -> str: ...
	@property
	def minimum(self) -> float: ...
	@property
	def maximum(self) -> float: ...
	@property
	def cardinality(self) -> int: ...
	@property
	def elements_per_environment(self) -> int: ...
	def batched_shape(self, environments: int) -> list[int]: ...
	def validate_matrix(self, matrix: Matrix, environments: int) -> None: ...

class EnvironmentSpec:
	def __init__(self, observation: EnvironmentSpace, action: EnvironmentSpace,
		reward: EnvironmentSpace, terminated: EnvironmentSpace,
		truncated: EnvironmentSpace) -> None: ...
	@property
	def observation(self) -> EnvironmentSpace: ...
	@property
	def action(self) -> EnvironmentSpace: ...
	@property
	def reward(self) -> EnvironmentSpace: ...
	@property
	def terminated(self) -> EnvironmentSpace: ...
	@property
	def truncated(self) -> EnvironmentSpace: ...
	def validate_reset(self, observation: Matrix, environments: int) -> None: ...
	def validate_action(self, action: Matrix, environments: int) -> None: ...

class EnvironmentTransition:
	def __init__(self, observation: Matrix, next_observation: Matrix,
		reward: Matrix, terminated: Matrix, truncated: Matrix) -> None: ...
	@property
	def observation(self) -> Matrix: ...
	@property
	def next_observation(self) -> Matrix: ...
	@property
	def reward(self) -> Matrix: ...
	@property
	def terminated(self) -> Matrix: ...
	@property
	def truncated(self) -> Matrix: ...

def ml_normalize_observation(observation: Matrix, mean: Matrix, stddev: Matrix,
	epsilon: float, clip: float) -> Matrix: ...
def ml_scale_action(action: Matrix, source_minimum: float, source_maximum: float,
	target_minimum: float, target_maximum: float, clamp_source: bool) -> Matrix: ...
def ml_clip_reward(reward: Matrix, minimum: float, maximum: float) -> Matrix: ...

# ── RL — Replay buffer ────────────────────────────────────────────────────────

class ReplayConfig:
	def __init__(self, capacity: int, observation_shape: Sequence[int],
		action_shape: Sequence[int] | None = None,
		action_dtype: str = "f32") -> None: ...
	@property
	def capacity(self) -> int: ...
	@property
	def observation_shape(self) -> list[int]: ...
	@property
	def action_shape(self) -> list[int]: ...
	@property
	def action_dtype(self) -> str: ...

class ReplayTransition:
	def __init__(self, observation: Matrix, action: Matrix,
		next_observation: Matrix, reward: Matrix,
		terminated: Matrix, truncated: Matrix) -> None: ...
	@property
	def observation(self) -> Matrix: ...
	@property
	def action(self) -> Matrix: ...
	@property
	def next_observation(self) -> Matrix: ...
	@property
	def reward(self) -> Matrix: ...
	@property
	def terminated(self) -> Matrix: ...
	@property
	def truncated(self) -> Matrix: ...

class ReplayBatch:
	@property
	def observation(self) -> Matrix: ...
	@property
	def action(self) -> Matrix: ...
	@property
	def next_observation(self) -> Matrix: ...
	@property
	def reward(self) -> Matrix: ...
	@property
	def terminated(self) -> Matrix: ...
	@property
	def truncated(self) -> Matrix: ...
	@property
	def index(self) -> Matrix: ...

class ReplayBuffer:
	def __init__(self, engine: Engine, config: ReplayConfig) -> None: ...
	def append(self, transition: ReplayTransition) -> None: ...
	def sample(self, batch_size: int, seed: int) -> ReplayBatch: ...
	def reset(self) -> None: ...
	def is_full(self) -> bool: ...
	def len(self) -> int: ...
	def is_empty(self) -> bool: ...
	def capacity(self) -> int: ...
	def cursor(self) -> int: ...

# ── RL — Rollout buffer ───────────────────────────────────────────────────────

class RolloutConfig:
	def __init__(self, time: int, environments: int,
		observation_shape: Sequence[int]) -> None: ...
	@property
	def time(self) -> int: ...
	@property
	def environments(self) -> int: ...
	@property
	def observation_shape(self) -> list[int]: ...

class RolloutTransition:
	def __init__(self, observation: Matrix, action: Matrix, reward: Matrix,
		value: Matrix, next_value: Matrix, log_probability: Matrix,
		terminated: Matrix, truncated: Matrix) -> None: ...
	@property
	def observation(self) -> Matrix: ...
	@property
	def action(self) -> Matrix: ...
	@property
	def reward(self) -> Matrix: ...
	@property
	def value(self) -> Matrix: ...
	@property
	def next_value(self) -> Matrix: ...
	@property
	def log_probability(self) -> Matrix: ...
	@property
	def terminated(self) -> Matrix: ...
	@property
	def truncated(self) -> Matrix: ...

class RolloutBuffer:
	def __init__(self, engine: Engine, config: RolloutConfig) -> None: ...
	def append(self, transition: RolloutTransition) -> None: ...
	def finalize(self, config: GaeConfig) -> None: ...
	def reset(self) -> None: ...
	def is_full(self) -> bool: ...
	def is_finalized(self) -> bool: ...
	def len(self) -> int: ...
	def is_empty(self) -> bool: ...
	def capacity(self) -> int: ...
	def batch_observation(self) -> Matrix: ...
	def batch_action(self) -> Matrix: ...
	def batch_reward(self) -> Matrix: ...
	def batch_value(self) -> Matrix: ...
	def batch_next_value(self) -> Matrix: ...
	def batch_old_log_probability(self) -> Matrix: ...
	def batch_terminated(self) -> Matrix: ...
	def batch_truncated(self) -> Matrix: ...
	def batch_valid(self) -> Matrix: ...
	def batch_advantage(self) -> Matrix: ...
	def batch_returns(self) -> Matrix: ...

# ── RL — Actor-Critic ─────────────────────────────────────────────────────────

class CategoricalActorCriticConfig:
	def __init__(self, observation_size: int, action_count: int,
		hidden_size: int, seed: int) -> None: ...
	@property
	def observation_size(self) -> int: ...
	@property
	def action_count(self) -> int: ...
	@property
	def hidden_size(self) -> int: ...
	@property
	def seed(self) -> int: ...

class CategoricalActorCriticOutput:
	@property
	def logits(self) -> Matrix: ...
	@property
	def value(self) -> Matrix: ...

class CategoricalActorCritic:
	def __init__(self, engine: Engine,
		config: CategoricalActorCriticConfig) -> None: ...
	def evaluate(self, observation: Matrix) -> CategoricalActorCriticOutput: ...
	def config(self) -> CategoricalActorCriticConfig: ...

# ── RL — Loss configs/results ─────────────────────────────────────────────────

class PpoLossConfig:
	def __init__(self, clip_epsilon: float = 0.2, value_coefficient: float = 0.5,
		entropy_coefficient: float = 0.01) -> None: ...
	@property
	def clip_epsilon(self) -> float: ...
	@property
	def value_coefficient(self) -> float: ...
	@property
	def entropy_coefficient(self) -> float: ...

class PpoLossResult:
	@property
	def policy_loss(self) -> Matrix: ...
	@property
	def value_loss(self) -> Matrix: ...
	@property
	def entropy(self) -> Matrix: ...
	@property
	def total_loss(self) -> Matrix: ...

class DqnLossConfig:
	def __init__(self, discount: float = 0.99) -> None: ...
	@property
	def discount(self) -> float: ...

class DqnLossResult:
	@property
	def selected_q(self) -> Matrix: ...
	@property
	def target_q(self) -> Matrix: ...
	@property
	def loss(self) -> Matrix: ...

class SacLossConfig:
	def __init__(self, discount: float = 0.99,
		entropy_coefficient: float = 0.2) -> None: ...
	@property
	def discount(self) -> float: ...
	@property
	def entropy_coefficient(self) -> float: ...

class SacCriticLossResult:
	@property
	def target_q(self) -> Matrix: ...
	@property
	def q1_loss(self) -> Matrix: ...
	@property
	def q2_loss(self) -> Matrix: ...
	@property
	def total_loss(self) -> Matrix: ...

# ── RL — Advantage ────────────────────────────────────────────────────────────

class GaeConfig:
	def __init__(self, gamma: float = 0.99, lambda_: float = 0.95) -> None: ...
	@property
	def gamma(self) -> float: ...
	@property
	def lambda_(self) -> float: ...

class GaeResult:
	@property
	def advantage(self) -> Matrix: ...
	@property
	def returns(self) -> Matrix: ...

# ── RL — Policy results ───────────────────────────────────────────────────────

class PolicyResult:
	@property
	def action(self) -> Matrix: ...
	@property
	def log_probability(self) -> Matrix: ...
	@property
	def entropy(self) -> Matrix: ...
	@property
	def value(self) -> Matrix: ...

class ContinuousPolicyResult:
	@property
	def action(self) -> Matrix: ...
	@property
	def raw_action(self) -> Matrix: ...
	@property
	def log_probability(self) -> Matrix: ...
	@property
	def entropy(self) -> Matrix: ...
	@property
	def value(self) -> Matrix: ...

# ── RL — Loss functions ───────────────────────────────────────────────────────

def ml_loss_ppo_clipped_policy(new_log_probability: Matrix, old_log_probability: Matrix,
	advantage: Matrix, clip_epsilon: float) -> Matrix: ...
def ml_loss_ppo(new_log_probability: Matrix, old_log_probability: Matrix,
	advantage: Matrix, value: Matrix, target_return: Matrix,
	entropy: Matrix, config: PpoLossConfig) -> PpoLossResult: ...
def ml_loss_dqn(q: Matrix, action: Matrix, reward: Matrix, next_q: Matrix,
	terminated: Matrix, truncated: Matrix, config: DqnLossConfig) -> DqnLossResult: ...
def ml_loss_sac_critic(q1: Matrix, q2: Matrix, reward: Matrix, next_q1: Matrix,
	next_q2: Matrix, next_log_probability: Matrix, terminated: Matrix,
	truncated: Matrix, config: SacLossConfig) -> SacCriticLossResult: ...
def ml_loss_sac_actor(q1: Matrix, q2: Matrix, log_probability: Matrix,
	entropy_coefficient: float) -> Matrix: ...

# ── RL — Advantage functions ──────────────────────────────────────────────────

def ml_advantage_normalize(advantage: Matrix, epsilon: float) -> Matrix: ...
def ml_advantage_gae(reward: Matrix, value: Matrix, next_value: Matrix,
	terminated: Matrix, truncated: Matrix, config: GaeConfig) -> GaeResult: ...

# ── RL — Policy functions ─────────────────────────────────────────────────────

def ml_policy_evaluate_categorical(logits: Matrix, action: Matrix,
	value: Matrix) -> PolicyResult: ...
def ml_policy_sample_categorical(logits: Matrix, value: Matrix,
	seed: int) -> PolicyResult: ...
def ml_policy_evaluate_tanh_normal(mean: Matrix, log_stddev: Matrix,
	raw_action: Matrix, value: Matrix, minimum: float, maximum: float,
	epsilon: float) -> ContinuousPolicyResult: ...
def ml_policy_sample_tanh_normal(mean: Matrix, log_stddev: Matrix,
	value: Matrix, minimum: float, maximum: float, seed: int,
	epsilon: float) -> ContinuousPolicyResult: ...
