// AUTO-GENERATED by Tools/TypeAutogen/oatypeautogen.py — DO NOT EDIT.
// Source of truth: Tools/TypeAutogen/Schema/UiTypes.toml.
// Regenerate via: python3 Tools/TypeAutogen/oatypeautogen.py --live

#include <Oa/Ui/Type.gen.h>

#include <cstring>

constexpr const char* OaViewerNavigationModeToString(OaViewerNavigationMode InType) noexcept {
	switch (InType) {
		case OaViewerNavigationMode::Default: return "Default";
		case OaViewerNavigationMode::Orbit: return "Orbit";
		case OaViewerNavigationMode::Fly: return "Fly";
		case OaViewerNavigationMode::Pan: return "Pan";
		case OaViewerNavigationMode::Zoom: return "Zoom";
		default: return "unknown";
	}
}

OaViewerNavigationMode OaViewerNavigationModeFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "Default") == 0) return OaViewerNavigationMode::Default;
	if (strcmp(InStr, "Orbit") == 0) return OaViewerNavigationMode::Orbit;
	if (strcmp(InStr, "Fly") == 0) return OaViewerNavigationMode::Fly;
	if (strcmp(InStr, "Pan") == 0) return OaViewerNavigationMode::Pan;
	if (strcmp(InStr, "Zoom") == 0) return OaViewerNavigationMode::Zoom;
	return OaViewerNavigationMode::Default;  // Default to first value
}
