// AUTO-GENERATED by tools/oaTile/oatile.py -- DO NOT EDIT.
// Source of truth: tools/oaTile/schema/fp32Tiled.toml

namespace oa {
inline constexpr U32 tileFp32SchemaVersion = 1U;
inline constexpr U32 tileGeneratorAbi = 4U;
inline constexpr U64 tileFp32SchemaHash = 0x6ee8201b83cf4c68ULL;
} // namespace oa
