// AUTO-GENERATED by tools/fnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: tools/fnAutogen/schema/core/coreFnMatrixIndex.toml.
// Regenerate via: python3 tools/fnAutogen/oafnautogen.py --live

// oa::FnMatrix — Index overloads.

	/// argmax: Find index of maximum value: out = argmax(A).
	[[nodiscard]] oa::I64 argmax(const oa::Matrix& inA, oa::I32 inDim = -1);

	/// reshape: Reshape tensor to new shape (view operation, no copy).
	[[nodiscard]] oa::Matrix reshape(const oa::Matrix& inA, oa::MatrixShape inShape);

	/// slice: Materialize the half-open interval [Start, End) along one dimension.
	[[nodiscard]] oa::Matrix slice(const oa::Matrix& inSelf, oa::I32 inDim, oa::I64 inStart, oa::I64 inEnd);
