// AUTO-GENERATED by tools/fnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: tools/fnAutogen/schema/ml/mlFnMatrixEmbed.toml.
//
// Tests for context-backed public overloads.
// The public overload test doubles as the kernel correctness test —
// it calls oa::FnMatrix::<Op>(...) which dispatches the SPIR-V kernel directly.
// CPU references come from each op's `forward_op` field.

#include <gtest/gtest.h>
#include <oa/core/fnMatrix.h>
#include <oa/ml/fnMatrix.h>
#include <oa/runtime/engine.h>
#include <oa/runtime/executionSession.h>
#include <oa/runtime/executableGraph.h>
#include <algorithm>
#include <cmath>
#include <numeric>
#include <vector>

static oa::Engine* runtime = nullptr;

class TestFnMatrixEmbed : public ::testing::Test {
protected:
	static void SetUpTestSuite() {
		oa::EngineConfig config{};
		config.appName = "TestFnMatrixEmbed";
		auto result = oa::Engine::create(config);
		ASSERT_TRUE(result.isOk()) << result.getStatus().getMessage();
		static oa::UniquePtr<oa::Engine> engine = std::move(*result);
		runtime = engine.get();
	}
};

TEST_VK(TestFnMatrixEmbed, biasAdd_Context) {
	constexpr oa::U32 N = 256;
	auto a = oa::FnMatrix::rand(oa::MatrixShape{N});
	auto b = oa::FnMatrix::rand(oa::MatrixShape{N});
	std::vector<float> bHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(b, bHost.data(), N * sizeof(float)).isOk());
	oa::ExecutionSession::RecordingScope recordingScope(oa::ExecutionSession::getActive());
	auto out = oa::FnMatrix::biasAdd(a, b);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> aHost(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(a, aHost.data(), N * sizeof(float)).isOk());
	std::vector<float> want(N);
	for (oa::U32 i = 0; i < N; ++i) want[i] = aHost[i] + bHost[i];
	std::vector<float> got(N);
	ASSERT_TRUE(oa::FnMatrix::copyToHost(out, got.data(), N * sizeof(float)).isOk());
	for (oa::U32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], (1e-4f) * (1.0f + std::abs(want[i]))) << "i=" << i;
}
