"""
Code emitters for OaTypeAutogen.
Generates C++ header and implementation files from type schemas.
"""
from oatypeautogen_lib.schema import EnumDef, StructDef, TypeSchema


GEN_HEADER = (
	"// AUTO-GENERATED by tools/typeAutogen/oatypeautogen.py — DO NOT EDIT.\n"
	"// Source of truth: tools/typeAutogen/schema/{schema_name}.\n"
	"// Regenerate via: python3 tools/typeAutogen/oatypeautogen.py --live\n"
)


def camel_name(name: str) -> str:
	return name[:1].lower() + name[1:]


def serialized_name(value) -> str:
	return value.serialized_name or value.name


def emit_enum_header(enum_def: EnumDef, namespace: str) -> str:
	"""Emit enum class declaration for header."""
	lines = [f"enum class {enum_def.name} : {enum_def.underlying_type} {{"]
	
	for val in enum_def.values:
		if val.comment:
			lines.append(f"\t{val.name} = {val.value if val.value is not None else ''},  // {val.comment}")
		else:
			if val.value is not None:
				lines.append(f"\t{val.name} = {val.value},")
			else:
				lines.append(f"\t{val.name},")
	
	lines.append("};")
	
	# Enum conversions are header-complete so generated types never depend on an
	# untracked or uncompiled implementation file.
	if enum_def.generate_tostring:
		lines.append(emit_enum_tostring(enum_def).rstrip())
	
	if enum_def.generate_fromstring:
		lines.append(emit_enum_fromstring(enum_def).rstrip())
	
	lines.append("")
	return "\n".join(lines)


def emit_enum_tostring(enum_def: EnumDef) -> str:
	"""Emit ToString implementation for enum."""
	lines = [
		f"[[nodiscard]] constexpr const char* "
		f"{camel_name(enum_def.name)}ToString({enum_def.name} inType) noexcept {{"
	]
	lines.append("\tswitch (inType) {")
	
	for val in enum_def.values:
		lines.append(
			f"\t\tcase {enum_def.name}::{val.name}: "
			f"return \"{serialized_name(val)}\";"
		)
	
	lines.append("\t\tdefault: return \"unknown\";")
	lines.append("\t}")
	lines.append("}")
	lines.append("")
	return "\n".join(lines)


def emit_enum_fromstring(enum_def: EnumDef) -> str:
	"""Emit FromString implementation for enum (non-constexpr for strcmp)."""
	default_value = f"{enum_def.name}::{enum_def.values[0].name}"
	lines = [
		f"[[nodiscard]] inline {enum_def.name} "
		f"{camel_name(enum_def.name)}FromString(const char* inString) noexcept {{"
	]
	lines.append(f"\tif (inString == nullptr) return {default_value};")
	
	for val in enum_def.values:
		lines.append(
			f"\tif (std::strcmp(inString, \"{serialized_name(val)}\") == 0) "
			f"return {enum_def.name}::{val.name};"
		)
	
	lines.append(f"\treturn {default_value};")
	lines.append("}")
	lines.append("")
	return "\n".join(lines)


def emit_struct_header(struct_def: StructDef, namespace: str) -> str:
	"""Emit struct declaration for header."""
	lines = [f"struct {struct_def.name} {{"]
	
	for field in struct_def.fields:
		declaration = f"\t{field.type} {field.name}"
		if field.default:
			declaration += f" = {field.default}"
		declaration += ";"
		if field.comment:
			declaration += f"  // {field.comment}"
		lines.append(declaration)
	
	lines.append("};")
	lines.append("")
	return "\n".join(lines)


def emit_header_file(schema: TypeSchema, schema_name: str) -> str:
	"""Emit complete header file."""
	lines = [GEN_HEADER.format(schema_name=schema_name)]
	lines.append(f"#pragma once")
	lines.append("")
	lines.append("#include <oa/core/types.h>")
	if any(enum.generate_fromstring for enum in schema.enums):
		lines.append(f"#include <cstring>")
	lines.append("")
	
	lines.append(f"namespace {schema.namespace} {{")
	lines.append("")

	for enum in schema.enums:
		lines.append(emit_enum_header(enum, schema.namespace))
	
	for struct in schema.structs:
		lines.append(emit_struct_header(struct, schema.namespace))

	lines.append(f"}} // namespace {schema.namespace}")
	lines.append("")
	
	return "\n".join(lines)


def emit_cpp_file(schema: TypeSchema, schema_name: str) -> str:
	"""Emit complete implementation file."""
	lines = [GEN_HEADER.format(schema_name=schema_name)]
	
	# Include the generated header
	domain = schema.domain
	header_path = f"<oa/{domain.lower()}/type.gen.h>"
	lines.append(f"#include {header_path}")
	lines.append("")
	
	return "\n".join(lines)
