// AUTO-GENERATED by tools/gen/nn/generate.py - DO NOT EDIT.
// source of truth: tools/gen/nn/schema/all NN schemas.
// Regenerate via: python3 tools/gen/nn/generate.py --live

#pragma once

#include "relu/relu.h"
#include "gelu/gelu.h"
#include "silu/silu.h"
#include "softmax/softmax.h"
#include "attention/multiheadattention/multiHeadAttention.h"
#include "sequential/sequential.h"
#include "conv1d/conv1d.h"
#include "convtranspose1d/convTranspose1d.h"
#include "conv2d/conv2d.h"
#include "convtranspose2d/convTranspose2d.h"
#include "embedding/embedding.h"
#include "linear/linear.h"
#include "swiglu/swiglu.h"
#include "layernorm/layerNorm.h"
#include "rmsnorm/rmsNorm.h"
#include "maxpool2d/maxPool2d.h"
#include "avgpool2d/avgPool2d.h"
#include "identity/identity.h"
#include "flatten/flatten.h"
#include "upsample/upsample.h"
#include "batchnorm2d/batchNorm2d.h"
#include "adaptiveavgpool2d/adaptiveAvgPool2d.h"
