// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT.
// source of truth: tools/nnAutogen/schema/ml/mlNnLinear.toml.
// Regenerate via: python3 tools/nnAutogen/oannautogen.py --live

#pragma once

#include <oa/ml/module.h>

#include <initializer_list>

namespace oa {

/// Linear: Fully connected linear layer.
class Linear : public Module {
public:
	Linear(oa::I32 inFeatures, oa::I32 outFeatures, bool inBias = true);
	Matrix forward(const Matrix& inInput) override;
	void setActivation(oa::Activation inAct) { activation_ = inAct; }

private:
	bool hasBias_;
	oa::Activation activation_ = oa::Activation::None;
};

} // namespace oa
