// @generated by tools/gen/fn/generate.py; DO NOT EDIT.
// schema=matrix_elemwise.json schema_version=1 generator_version=52
// schema_sha256=0099910a1b1fed2e756d57ed7fbe60abc9cb191c511a24fe532a0c3d28f95b2d
// matrix_blas_sha256=d6e487cde1afe16d74d04add639b570dda78d8a1404722e72ca0bb1d145c9385
// matrix_reduce_sha256=3d19602cebc66c26057cdb581aac03a244d971ba66d7cffc49fa5ed75e909444
// matrix_rng_sha256=69eed5c6190ddac53512aee48f3705713d2edaddf0876b557ada5a2a043b130e
// ml_training_sha256=eee874e5551baed7e588871e278ac84e842609f051c8c143730604ea628c24ed
// Candidate roles mirror OA DNN vocabulary while retaining OARS compatibility identities.

pub(super) static DNN_OP_ROLES: &[DnnOpRole] = &[
	DnnOpRole {
		contract: crate::core::operation::matrix::ADD,
		op_type: DnnOpType::Add,
		epilogue: DnnEpilogue::None,
		epilogue_required_input: None,
		provider_mask: DnnProvider::ResidualNorm.bit(),
	},
	DnnOpRole {
		contract: crate::core::operation::matrix::MUL,
		op_type: DnnOpType::Multiply,
		epilogue: DnnEpilogue::None,
		epilogue_required_input: None,
		provider_mask: DnnProvider::GatedFfn.bit(),
	},
	DnnOpRole {
		contract: crate::core::operation::matrix::MAT_MUL_NT,
		op_type: DnnOpType::Matmul,
		epilogue: DnnEpilogue::None,
		epilogue_required_input: None,
		provider_mask: DnnProvider::BlasLtEpilogue.bit()
			| DnnProvider::QkvProjectionGroup.bit()
			| DnnProvider::GatedFfn.bit(),
	},
	DnnOpRole {
		contract: crate::core::operation::ml::LINEAR,
		op_type: DnnOpType::Matmul,
		epilogue: DnnEpilogue::Bias,
		epilogue_required_input: Some(2),
		provider_mask: DnnProvider::BlasLtEpilogue.bit()
			| DnnProvider::QkvProjectionGroup.bit()
			| DnnProvider::GatedFfn.bit(),
	},
	DnnOpRole {
		contract: crate::core::operation::ml::RMS_NORM,
		op_type: DnnOpType::RmsNorm,
		epilogue: DnnEpilogue::None,
		epilogue_required_input: None,
		provider_mask: DnnProvider::ResidualNorm.bit(),
	},
	DnnOpRole {
		contract: crate::core::operation::ml::GELU,
		op_type: DnnOpType::Gelu,
		epilogue: DnnEpilogue::None,
		epilogue_required_input: None,
		provider_mask: DnnProvider::BlasLtEpilogue.bit(),
	},
	DnnOpRole {
		contract: crate::core::operation::ml::SILU,
		op_type: DnnOpType::Silu,
		epilogue: DnnEpilogue::None,
		epilogue_required_input: None,
		provider_mask: DnnProvider::BlasLtEpilogue.bit() | DnnProvider::GatedFfn.bit(),
	},
	DnnOpRole {
		contract: crate::core::operation::ml::RELU,
		op_type: DnnOpType::Relu,
		epilogue: DnnEpilogue::None,
		epilogue_required_input: None,
		provider_mask: DnnProvider::BlasLtEpilogue.bit(),
	},
	DnnOpRole {
		contract: crate::core::operation::ml::SWIGLU,
		op_type: DnnOpType::GatedMultiply,
		epilogue: DnnEpilogue::None,
		epilogue_required_input: None,
		provider_mask: DnnProvider::GatedFfn.bit(),
	},
	DnnOpRole {
		contract: crate::core::operation::ml::SCALED_DOT_PRODUCT_ATTENTION,
		op_type: DnnOpType::ScaledDotProductAttention,
		epilogue: DnnEpilogue::None,
		epilogue_required_input: None,
		provider_mask: DnnProvider::Attention.bit(),
	},
];
