#!/usr/bin/env python3
"""Generate Extensions/Private/Retarget/RtgPoseData.inc from the oa3d rtg def.

Bakes the 25-joint core-body reference poses (tPose + aPose for manny & quinn)
and the HumanIK characterization map (slot -> id -> UE node) into a C++ include
consumed by Retarget/HumanIk.cpp. Reproducible: re-run if the rtg def changes.

    python Tools/Gen3dAnim/gen_rtg_pose_data.py
"""
import importlib.util
import os

# Path to the private rtg-definition module (Epic/Autodesk-derived interop data;
# see NOTICE.md). Set OA3D_RTG to point at your local copy; this generator is not
# needed to build OA — the baked .inc is checked in.
RTG = os.environ.get("OA3D_RTG", "")
if not RTG:
    raise SystemExit("Set OA3D_RTG to your rtgdefinition/unreal.py (see NOTICE.md).")
OUT = os.path.join(os.path.dirname(__file__), "..", "..",
                   "Extensions", "Private", "Retarget", "RtgPoseData.inc")

# The 25 core body joints, in OaSkMetaHuman() hierarchy order.
CORE = [
    "root", "pelvis", "spine_01", "spine_02", "spine_03", "spine_04",
    "neck_01", "neck_02", "head",
    "clavicle_l", "upperarm_l", "lowerarm_l", "hand_l",
    "clavicle_r", "upperarm_r", "lowerarm_r", "hand_r",
    "thigh_l", "calf_l", "foot_l", "ball_l",
    "thigh_r", "calf_r", "foot_r", "ball_r",
]


def load():
    spec = importlib.util.spec_from_file_location("unreal_rtg", RTG)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def flush(v):
    # Flatten rtg float epsilons (e.g. 7e-15) to 0 for clean tables.
    return 0.0 if abs(v) < 1e-6 else v


def emit_pose(out, sym, pose):
    out.append(f"constexpr RtgRefJoint {sym}[] = {{")
    out.append("\t// name            rx           ry           rz"
               "           tx           ty           tz")
    for n in CORE:
        j = pose[n]
        rx, ry, rz = flush(j["rotateX"]), flush(j["rotateY"]), flush(j["rotateZ"])
        tx, ty, tz = flush(j["translateX"]), flush(j["translateY"]), flush(j["translateZ"])
        out.append(
            f'\t{{ "{n}",{" " * (14 - len(n))}'
            f"{rx:>11.6f}f, {ry:>11.6f}f, {rz:>11.6f}f, "
            f"{tx:>11.6f}f, {ty:>11.6f}f, {tz:>11.6f}f }},")
    out.append("};")
    out.append("")


def main():
    m = load()
    defn = m.RTG_DEFINITION_UNREAL["definition"]
    node_to_slot = {v["node"]: (k, v["id"]) for k, v in defn.items()}

    out = []
    out.append("// RtgPoseData.inc - GENERATED by Tools/Gen3dAnim/gen_rtg_pose_data.py")
    out.append("// Source: rtgdefinition (UE mannequin poses + HumanIK map); see NOTICE.md.")
    out.append("// 25-joint core-body reference poses (Maya XYZ deg, cm) + HumanIK map.")
    out.append("// Do not edit by hand - re-run the generator.")
    out.append("//")
    out.append("// Included inside an anonymous namespace by Retarget/HumanIk.cpp.")
    out.append("")
    out.append("struct RtgRefJoint {")
    out.append("\tconst char* Name;")
    out.append("\tOaF32       Rx, Ry, Rz;   // local orientation (Maya XYZ, degrees)")
    out.append("\tOaF32       Tx, Ty, Tz;   // local offset to parent (cm)")
    out.append("};")
    out.append("")
    out.append("struct RtgHikSlot { const char* Slot; OaI32 Id; const char* Node; };")
    out.append("")

    # clang-format off marker so the wide tables survive formatting.
    out.append("// clang-format off")
    emit_pose(out, "kRtgPoseMannyT", m.RTG_POSES_SKEL_MANNY["tPose"])
    emit_pose(out, "kRtgPoseMannyA", m.RTG_POSES_SKEL_MANNY["aPose"])
    emit_pose(out, "kRtgPoseQuinnT", m.RTG_POSES_SKEL_QUINN["tPose"])
    emit_pose(out, "kRtgPoseQuinnA", m.RTG_POSES_SKEL_QUINN["aPose"])

    out.append("constexpr RtgHikSlot kHumanIkMap[] = {")
    for n in CORE:
        slot, sid = node_to_slot[n]
        out.append(f'\t{{ "{slot}",{" " * (16 - len(slot))}{sid:>4}, "{n}" }},')
    out.append("};")
    out.append("// clang-format on")
    out.append("")

    with open(os.path.normpath(OUT), "w", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.normpath(OUT)} ({len(CORE)} joints x4 poses + "
          f"{len(CORE)} hik slots)")


if __name__ == "__main__":
    main()
