#!/usr/bin/env python3
"""Generate Extensions/Private/Rig/MetaHumanData.inc — the 64-joint clean
MetaHuman base (LIST_SKEL_MH minus individual toes), with rest pose + per-joint
channel spec, from the authoritative sources:

  - joint set:        oa3d .../core/constants.py  LIST_SKEL_MH  (drop *toe* joints)
  - hierarchy:        the real CitySample USD joint paths (root/pelvis/spine_01/…)
  - rest translate/orient: oa3d .../rtgdefinition/unreal.py  RTG_POSES_SKEL_MANNY tPose
  - HumanIK ids:      RTG_DEFINITION_UNREAL["definition"]
  - channel locks:    mrigbuild.py MBuildRigCharacter.LockSkeleton
                      root/pelvis keep translate; hinges (elbow/knee/finger _02/_03)
                      keep only rotateZ (1 DOF); everything else full 3-axis rotation.

    python Tools/Gen3dAnim/gen_skeleton_data.py
"""
import importlib.util, os, re

import glob as _glob

# Private, Epic/Autodesk-derived interop sources (see NOTICE.md). This generator is
# not required to build OA — the baked .inc is checked in. Point these at your copies:
#   OA3D_MAYA  -> the rtg/constants module root
#   OA3D_USD   -> glob for a reference UE-mannequin USD clip
OA3D = os.environ.get("OA3D_MAYA", "")
USD_SEARCH = os.environ.get("OA3D_USD", "")
if not OA3D or not USD_SEARCH:
    raise SystemExit("Set OA3D_MAYA and OA3D_USD (see NOTICE.md).")
OUT  = os.path.join(os.path.dirname(__file__), "..", "..",
                    "Extensions", "Private", "Rig", "MetaHumanData.inc")


def find_ref_usd():
    hits = sorted(_glob.glob(USD_SEARCH, recursive=True))
    if not hits:
        raise SystemExit(f"no reference USD found under {USD_SEARCH}")
    return hits[0]


def load(p, n):
    s = importlib.util.spec_from_file_location(n, p)
    m = importlib.util.module_from_spec(s); s.loader.exec_module(m); return m


def flush(v):
    return 0.0 if abs(v) < 1e-6 else v


# Hinge joints (rotateZ only) per LockSkeleton.
HINGE = {"lowerarm_l", "lowerarm_r", "calf_l", "calf_r"}
for side in ("l", "r"):
    for f in ("thumb", "index", "middle", "ring", "pinky"):
        HINGE.add(f"{f}_02_{side}")
        HINGE.add(f"{f}_03_{side}")

MASS = {  # rough segment kg; fingers tiny
    "root": 0.0, "pelvis": 11.2,
    "spine_01": 9.6, "spine_02": 8.0, "spine_03": 6.4, "spine_04": 4.6, "spine_05": 3.0,
    "neck_01": 0.8, "neck_02": 0.4, "head": 5.0,
    "clavicle": 0.8, "upperarm": 2.2, "lowerarm": 1.3, "hand": 0.5,
    "thigh": 8.0, "calf": 3.7, "foot": 1.2, "ball": 0.2,
}
def mass_for(name):
    base = re.sub(r"_(l|r)$", "", name)
    if base in MASS:
        return MASS[base]
    if any(base.startswith(f) for f in ("thumb", "index", "middle", "ring", "pinky")):
        return 0.02
    return 0.1


def main():
    c = load(os.path.join(OA3D, "api/core/constants.py"), "constants")
    u = load(os.path.join(OA3D, "resources/rtgdefinition/unreal.py"), "unreal")

    base = [j for j in c.LIST_SKEL_MH if "toe" not in j]   # drop 20 toe joints -> 64

    # Hierarchy + ordering from the real USD joint paths (already hierarchy-ordered).
    ref_usd = find_ref_usd()
    print(f"  reference USD: {ref_usd}")
    txt = open(ref_usd, encoding="utf-8", errors="ignore").read()
    paths = re.findall(r'"([^"]+)"',
                       re.search(r'token\[\] joints = \[(.*?)\]', txt, re.S).group(1))
    parent = {}
    order = []
    for p in paths:
        segs = p.split("/")
        leaf = segs[-1]
        if leaf in base:
            parent[leaf] = segs[-2] if len(segs) > 1 else ""
            order.append(leaf)
    # Any base joint not present in the clip (shouldn't happen for CitySample) -> skip.
    missing = [j for j in base if j not in order]
    if missing:
        print("WARN: base joints absent from reference USD, omitted:", missing)

    defn = u.RTG_DEFINITION_UNREAL["definition"]
    node_to_id = {v["node"]: v["id"] for v in defn.values()}
    node_to_slot = {v["node"]: k for k, v in defn.items()}
    tpose = u.RTG_POSES_SKEL_MANNY["tPose"]

    out = []
    out.append("// MetaHumanData.inc - GENERATED by Tools/Gen3dAnim/gen_skeleton_data.py")
    out.append("// 64-joint clean MetaHuman base (LIST_SKEL_MH minus individual toes).")
    out.append("// Hierarchy from CitySample USD; rest from manny tPose (Maya XYZ deg, cm);")
    out.append("// HumanIK ids from RTG_DEFINITION_UNREAL; channel locks from LockSkeleton.")
    out.append("// Do not edit by hand - re-run the generator.")
    out.append("//")
    out.append("// RotDof: 3 = full rotation (packed 6D), 1 = hinge (rotateZ only).")
    out.append("// HasTranslate: joint carries a live translate channel (root + pelvis).")
    out.append("// Included inside an anonymous namespace by Skeleton.cpp.")
    out.append("")
    out.append("struct BuiltinJoint {")
    out.append("\tconst char* Name;")
    out.append("\tconst char* Parent;        // \"\" = root")
    out.append("\tOaI32       HumanIkId;")
    out.append("\tOaF32       Tx, Ty, Tz;    // local offset to parent (cm)")
    out.append("\tOaF32       Rx, Ry, Rz;    // rest orientation (Maya XYZ, degrees)")
    out.append("\tOaF32       Mass;          // kg")
    out.append("\tbool        HasTranslate;  // live translate channel")
    out.append("\tOaU8        RotDof;        // 3 = full 6D, 1 = hinge rotateZ")
    out.append("\tconst char* HikSlot;       // HumanIK slot name (\"\" = none)")
    out.append("};")
    out.append("")
    out.append("// clang-format off")
    out.append("constexpr BuiltinJoint kMetaHumanBody[] = {")
	for n in order:
		j = tpose[n]
		rx, ry, rz = flush(j["rotateX"]), flush(j["rotateY"]), flush(j["rotateZ"])
		tx, ty, tz = flush(j["translateX"]), flush(j["translateY"]), flush(j["translateZ"])
		if n == "root":
			# The Maya-exported UsdSkel root carries the Y-up/Z-forward basis as a
			# -90deg X rest orientation, even though RTG's named tPose lists zero
			# Euler channels for root.
			rx, ry, rz = -90.0, 0.0, 0.0
		par = parent[n]
        hik = node_to_id.get(n, 0)
        dof = 1 if n in HINGE else 3
        has_t = "true " if n in ("root", "pelvis") else "false"
        slot = node_to_slot.get(n, "")
        out.append(
            f'\t{{ "{n}",{" " * (20 - len(n))}"{par}",{" " * (16 - len(par))}'
            f"{hik:>4}, {tx:>11.5f}f,{ty:>11.5f}f,{tz:>11.5f}f, "
            f"{rx:>11.5f}f,{ry:>11.5f}f,{rz:>11.5f}f, {mass_for(n):>5.2f}f, "
            f'{has_t}, {dof}, "{slot}" }},')
    out.append("};")
    out.append("// clang-format on")
    out.append("")

    with open(os.path.normpath(OUT), "w", newline="\n") as f:
        f.write("\n".join(out))

    n_hinge = sum(1 for n in order if n in HINGE)
    posedim = 0
    for n in order:
        if n in ("root", "pelvis"):
            posedim += 3
        posedim += 1 if n in HINGE else 6
    posedim += 2  # contacts
    print(f"wrote {os.path.normpath(OUT)}")
    print(f"  joints={len(order)}  hinges={n_hinge}  compact PoseDim={posedim}")


if __name__ == "__main__":
    main()
