// AUTO-GENERATED by Tools/OaTile/oatile.py -- DO NOT EDIT.
// Source of truth: Tools/OaTile/Schema/Fp32Tiled.toml

static constexpr OaKernelId GemmTiled = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 73);
static constexpr OaKernelId GemmBiasTiled = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 109);
static constexpr OaKernelId GemmBiasReluTiled = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 110);
static constexpr OaKernelId GemmBiasGeluTiled = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 111);
static constexpr OaKernelId GemmTiledSwizzle4 = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 75);
static constexpr OaKernelId GemmBiasTiledSwizzle4 = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 241);
static constexpr OaKernelId GemmBiasReluTiledSwizzle4 = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 242);
static constexpr OaKernelId GemmBiasGeluTiledSwizzle4 = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 243);
static constexpr OaKernelId GemmTiledSwizzle = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 74);
static constexpr OaKernelId GemmBiasTiledSwizzle = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 244);
static constexpr OaKernelId GemmBiasReluTiledSwizzle = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 245);
static constexpr OaKernelId GemmBiasGeluTiledSwizzle = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 246);
static constexpr OaKernelId GemmTiledK32 = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 240);
static constexpr OaKernelId GemmBiasTiledK32 = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 247);
static constexpr OaKernelId GemmBiasReluTiledK32 = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 248);
static constexpr OaKernelId GemmBiasGeluTiledK32 = OA_COMPUTE_KERNEL_ID(OaComputeKernelPrefix::Ml, 249);
