// AUTO-GENERATED by Tools/TypeAutogen/oatypeautogen.py — DO NOT EDIT.
// Source of truth: Tools/TypeAutogen/Schema/RuntimeTypes.toml.
// Regenerate via: python3 Tools/TypeAutogen/oatypeautogen.py --live

#include <Oa/Runtime/Type.gen.h>

#include <cstring>

constexpr const char* OaShaderProviderModeToString(OaShaderProviderMode InType) noexcept {
	switch (InType) {
		case OaShaderProviderMode::Disk: return "Disk";
		case OaShaderProviderMode::Embedded: return "Embedded";
		case OaShaderProviderMode::Cache: return "Cache";
		default: return "unknown";
	}
}

OaShaderProviderMode OaShaderProviderModeFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "Disk") == 0) return OaShaderProviderMode::Disk;
	if (strcmp(InStr, "Embedded") == 0) return OaShaderProviderMode::Embedded;
	if (strcmp(InStr, "Cache") == 0) return OaShaderProviderMode::Cache;
	return OaShaderProviderMode::Disk;  // Default to first value
}

constexpr const char* OaStoragePrecisionToString(OaStoragePrecision InType) noexcept {
	switch (InType) {
		case OaStoragePrecision::Unknown: return "Unknown";
		case OaStoragePrecision::FP32: return "FP32";
		case OaStoragePrecision::FP16: return "FP16";
		case OaStoragePrecision::BF16: return "BF16";
		case OaStoragePrecision::INT8: return "INT8";
		case OaStoragePrecision::TF32: return "TF32";
		default: return "unknown";
	}
}

OaStoragePrecision OaStoragePrecisionFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "Unknown") == 0) return OaStoragePrecision::Unknown;
	if (strcmp(InStr, "FP32") == 0) return OaStoragePrecision::FP32;
	if (strcmp(InStr, "FP16") == 0) return OaStoragePrecision::FP16;
	if (strcmp(InStr, "BF16") == 0) return OaStoragePrecision::BF16;
	if (strcmp(InStr, "INT8") == 0) return OaStoragePrecision::INT8;
	if (strcmp(InStr, "TF32") == 0) return OaStoragePrecision::TF32;
	return OaStoragePrecision::Unknown;  // Default to first value
}

constexpr const char* OaGemmKernelToString(OaGemmKernel InType) noexcept {
	switch (InType) {
		case OaGemmKernel::Unknown: return "Unknown";
		case OaGemmKernel::Simt: return "Simt";
		case OaGemmKernel::TensorCore: return "TensorCore";
		case OaGemmKernel::Wmma: return "Wmma";
		case OaGemmKernel::VendorBlas: return "VendorBlas";
		default: return "unknown";
	}
}

OaGemmKernel OaGemmKernelFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "Unknown") == 0) return OaGemmKernel::Unknown;
	if (strcmp(InStr, "Simt") == 0) return OaGemmKernel::Simt;
	if (strcmp(InStr, "TensorCore") == 0) return OaGemmKernel::TensorCore;
	if (strcmp(InStr, "Wmma") == 0) return OaGemmKernel::Wmma;
	if (strcmp(InStr, "VendorBlas") == 0) return OaGemmKernel::VendorBlas;
	return OaGemmKernel::Unknown;  // Default to first value
}

constexpr const char* OaGemmPathToString(OaGemmPath InType) noexcept {
	switch (InType) {
		case OaGemmPath::Unknown: return "Unknown";
		case OaGemmPath::Direct: return "Direct";
		case OaGemmPath::Fused: return "Fused";
		case OaGemmPath::SplitK: return "SplitK";
		default: return "unknown";
	}
}

OaGemmPath OaGemmPathFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "Unknown") == 0) return OaGemmPath::Unknown;
	if (strcmp(InStr, "Direct") == 0) return OaGemmPath::Direct;
	if (strcmp(InStr, "Fused") == 0) return OaGemmPath::Fused;
	if (strcmp(InStr, "SplitK") == 0) return OaGemmPath::SplitK;
	return OaGemmPath::Unknown;  // Default to first value
}

constexpr const char* OaGemmPrecisionToString(OaGemmPrecision InType) noexcept {
	switch (InType) {
		case OaGemmPrecision::Unknown: return "Unknown";
		case OaGemmPrecision::FP32: return "FP32";
		case OaGemmPrecision::TF32: return "TF32";
		case OaGemmPrecision::FP16: return "FP16";
		case OaGemmPrecision::BF16: return "BF16";
		case OaGemmPrecision::INT8: return "INT8";
		default: return "unknown";
	}
}

OaGemmPrecision OaGemmPrecisionFromString(const char* InStr) noexcept {
	// Simple string comparison (could be optimized with hash)
	if (strcmp(InStr, "Unknown") == 0) return OaGemmPrecision::Unknown;
	if (strcmp(InStr, "FP32") == 0) return OaGemmPrecision::FP32;
	if (strcmp(InStr, "TF32") == 0) return OaGemmPrecision::TF32;
	if (strcmp(InStr, "FP16") == 0) return OaGemmPrecision::FP16;
	if (strcmp(InStr, "BF16") == 0) return OaGemmPrecision::BF16;
	if (strcmp(InStr, "INT8") == 0) return OaGemmPrecision::INT8;
	return OaGemmPrecision::Unknown;  // Default to first value
}
