# AUTO-GENERATED by Tools/OaTile/oatile.py -- DO NOT EDIT.
# Source of truth: Tools/OaTile/Schema/Bf16Coop.toml

set(OA_GEMM_BF16_VARIANTS
	"GemmCmSgBf16" "0"
	"GemmBiasCmSgBf16" "1"
	"GemmBiasReluCmSgBf16" "2"
	"GemmBiasGeluCmSgBf16" "3"
	"GemmSiluCmSgBf16" "4"
)
set(OA_GEMM_WG_BF16_VARIANTS
	"GemmCmWgBf16" "0"
	"GemmBiasCmWgBf16" "1"
	"GemmBiasReluCmWgBf16" "2"
	"GemmBiasGeluCmWgBf16" "3"
	"GemmSiluCmWgBf16" "4"
)
