// AUTO-GENERATED by tools/fnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: tools/fnAutogen/schema/**.toml.
// Included inside the owning bind function.

	m.def("keccakF1600", [](const oa::Matrix& inA) {
		return matrixPtr(oa::FnHash::keccakF1600(inA));
	},
	  nb::arg("a"),
	  nb::rv_policy::take_ownership,
	  "Apply Keccak-f[1600] to each UInt8 [200] state row.");

	m.def("merkleRoot", [](const oa::Matrix& inA) {
		return matrixPtr(oa::FnHash::merkleRoot(inA));
	},
	  nb::arg("a"),
	  nb::rv_policy::take_ownership,
	  "Compute a SHAKE-256 Merkle root from a power-of-two UInt8 [N, 32] leaf matrix.");

	m.def("shake128", [](const oa::Matrix& inA, oa::U32 inOutputLength) {
		return matrixPtr(oa::FnHash::shake128(inA, inOutputLength));
	},
	  nb::arg("a"), nb::arg("outputLength") = 16,
	  nb::rv_policy::take_ownership,
	  "Batch SHAKE-128 over rows of a UInt8 [N, MessageLength] matrix.");

	m.def("shake256", [](const oa::Matrix& inA, oa::U32 inOutputLength) {
		return matrixPtr(oa::FnHash::shake256(inA, inOutputLength));
	},
	  nb::arg("a"), nb::arg("outputLength") = 32,
	  nb::rv_policy::take_ownership,
	  "Batch SHAKE-256 over rows of a UInt8 [N, MessageLength] matrix.");
