// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/Ml/FnLoss manifest.
// Regenerate via: python3 Tools/FnAutogen/oafnautogen.py --live

// OaFnLoss — generated declarations for Ml/FnLoss.

#include "CrossEntropy/FnLossCrossEntropy.gen.h"
