// AUTO-GENERATED by Tools/FnAutogen/oafnautogen.py — DO NOT EDIT.
// Source of truth: Tools/FnAutogen/Schema/Ml/MlFnMatrixNorm.toml.
//
// Tests for context-backed public overloads.
// The public overload test doubles as the kernel correctness test —
// it calls OaFnMatrix::<Op>(...) which dispatches the SPIR-V kernel directly.
// CPU references come from each op's `forward_op` field.

#include <gtest/gtest.h>
#include <Oa/Core/FnMatrix.h>
#include <Oa/Ml/FnMatrix.h>
#include <Oa/Runtime/Engine.h>
#include <Oa/Runtime/Context.h>
#include <Oa/Runtime/ComputeGraph.h>
#include <algorithm>
#include <cmath>
#include <numeric>
#include <vector>

static OaComputeEngine* GRt = nullptr;

class TestFnMatrixNorm : public ::testing::Test {
protected:
	static void SetUpTestSuite() {
		OaEngineConfig cfg{};
		cfg.AppName = "TestFnMatrixNorm";
		auto r = OaComputeEngine::Create(cfg);
		ASSERT_TRUE(r.IsOk()) << r.GetStatus().GetMessage();
		static OaUniquePtr<OaComputeEngine> rt = std::move(*r);
		GRt = rt.get();
	}
};

TEST_VK(TestFnMatrixNorm, Softmax_Context) {
	constexpr OaU32 N = 256;
	auto a = OaFnMatrix::Rand(OaMatrixShape{N});
	OaContext::Scope ctx_scope(OaContext::GetDefault());
	auto out = OaFnMatrix::Softmax(a);
	// Context scope auto-executes and syncs at end of scope
	std::vector<float> a_host(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(a, a_host.data(), N * sizeof(float)).IsOk());
	std::vector<float> want(N);
	for (OaU32 i = 0; i < N; ++i) want[i] = std::exp(a_host[i]) / std::accumulate(a_host.begin(), a_host.end(), 0.0f, [](float sum, float x) { return sum + std::exp(x); });
	std::vector<float> got(N);
	ASSERT_TRUE(OaFnMatrix::CopyToHost(out, got.data(), N * sizeof(float)).IsOk());
	for (OaU32 i = 0; i < N; ++i) EXPECT_NEAR(got[i], want[i], 1e-3f) << "i=" << i;
}

