#!/usr/bin/env python3
"""
OA NN Autogen - schema-driven generator for oa::Module layer wrappers.

This is intentionally small: NN layers are public API classes, so the first
slice only generates simple oa::FnMatrix-backed modules where the boilerplate is
mechanical and runtime policy stays inside oa::ExecutionSession and oa::Fn*.
"""
from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

TOOLS_ROOT = Path(__file__).resolve().parents[1]
if str(TOOLS_ROOT) not in sys.path:
	sys.path.insert(0, str(TOOLS_ROOT))

from autogen_io import write_generated_text


REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_DIR = REPO_ROOT / "tools" / "nnAutogen" / "schema"
DEFAULT_OUTPUT = REPO_ROOT / "tools" / "nnAutogen" / "output"
LIVE_SOURCE_ROOT = REPO_ROOT / "source" / "cpp"


GEN_HEADER = """// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT.
// source of truth: tools/nnAutogen/schema/{schema_name}.
// Regenerate via: python3 tools/nnAutogen/oannautogen.py --live
"""
GEN_SOURCE_MARKER = "// AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT."
GEN_CMAKE_MARKER = "# AUTO-GENERATED by tools/nnAutogen/oannautogen.py - DO NOT EDIT."


def fail(message: str) -> None:
	print(f"oannautogen: ERROR: {message}", file=sys.stderr)
	raise SystemExit(1)


def schema_label(schema_path: Path) -> str:
	try:
		return schema_path.relative_to(SCHEMA_DIR).as_posix()
	except ValueError:
		return schema_path.name


def validate_layer(schema_path: Path, layer: dict) -> None:
	name = layer.get("name")
	if not isinstance(name, str) or not name:
		fail(f"{schema_path}: layer missing non-empty name")
	if not name[0].isupper() or any(ch == "_" for ch in name):
		fail(f"{schema_path}:{name}: layer name must be PascalCase")
	if name != "Silu" and any(part in name for part in ("ReLU", "GELU", "SiLU")):
		fail(f"{schema_path}:{name}: use PascalCase names such as Relu/Gelu/Silu")
	fn = layer.get("fn")
	forward_body = layer.get("forward_body")
	if (not isinstance(fn, str) or not fn) and (not isinstance(forward_body, str) or not forward_body.strip()):
		fail(f"{schema_path}:{name}: layer missing fn expression or forward_body")
	if "fn" in layer and (not isinstance(fn, str) or not fn):
		fail(f"{schema_path}:{name}: fn must be a non-empty string")
	if "forward_body" in layer and (not isinstance(forward_body, str) or not forward_body.strip()):
		fail(f"{schema_path}:{name}: forward_body must be a non-empty string")
	if "constructor_args" in layer and not isinstance(layer["constructor_args"], str):
		fail(f"{schema_path}:{name}: constructor_args must be a string")
	if "constructor_body" in layer and not isinstance(layer["constructor_body"], list):
		fail(f"{schema_path}:{name}: constructor_body must be a list of strings")
	if "extra_methods" in layer and not isinstance(layer["extra_methods"], str):
		fail(f"{schema_path}:{name}: extra_methods must be a string containing raw C++ code")
	if "extra_includes" in layer and not isinstance(layer["extra_includes"], str):
		fail(f"{schema_path}:{name}: extra_includes must be a string containing #include directives")
	header_includes = layer.get("header_includes", [])
	if not isinstance(header_includes, list) or any(
		not isinstance(include, str)
		or not re.fullmatch(r"oa/[A-Za-z0-9_/]+\.h", include)
		for include in header_includes
	):
		fail(f"{schema_path}:{name}: header_includes must be a list of oa/... .h paths")
	autograd_node_header = layer.get("autograd_node_header")
	if autograd_node_header is not None:
		if not isinstance(autograd_node_header, str) or not re.fullmatch(r"oa/[A-Za-z0-9_/]+\.h", autograd_node_header):
			fail(f"{schema_path}:{name}: autograd_node_header must be an oa/... .h include path")
	if isinstance(forward_body, str) and "oa::makeShared<oa::Grad" in forward_body and autograd_node_header is None:
		fail(f"{schema_path}:{name}: custom gradient-node construction requires autograd_node_header")
	path = layer.get("path", name.lower())
	if not isinstance(path, str) or not path or Path(path).is_absolute() or ".." in Path(path).parts:
		fail(f"{schema_path}:{name}: path must be a safe relative output directory")
	if not re.fullmatch(r"[a-z0-9]+(?:/[a-z0-9]+)*", path):
		fail(f"{schema_path}:{name}: path components must be lowercase alphanumeric names")
	if Path(path).name != name.lower():
		fail(f"{schema_path}:{name}: path must end in the lowercase layer name")


def out_paths(layer: dict, out_root: Path, *, live: bool) -> tuple[Path, Path]:
	layer_name = layer["name"]
	# File names follow camelCase convention: first char lowercase.
	file_stem = layer_name[0].lower() + layer_name[1:]
	path_val = layer.get("path", layer_name.lower())
	path_obj = Path(path_val)
	dir_relative = Path("oa") / "ml" / "nn" / path_obj
	header_base = out_root / "include" / dir_relative
	cpp_base = out_root / "lib" / dir_relative
	return header_base / f"{file_stem}.h", cpp_base / f"{file_stem}.cpp"


def cpp_param_list_without_defaults(params: str) -> str:
	return re.sub(r"\s*=\s*[^,]+", "", params)


def emit_header(layer: dict, schema_name: str) -> str:
	name = layer["name"]
	# Classes live inside namespace oa with camelCase methods.
	notes = layer.get("notes", "")
	constructor = layer.get("constructor")
	constructor_args = layer.get("constructor_args")
	constructor_explicit = layer.get("constructor_explicit", False)
	methods = layer.get("methods", [])
	members = layer.get("members", [])
	lines = [GEN_HEADER.format(schema_name=schema_name)]
	lines.append("#pragma once\n")
	lines.append("#include <oa/ml/module.h>")
	for include in layer.get("header_includes", []):
		lines.append(f"#include <{include}>")
	lines.append("")
	lines.append("#include <initializer_list>\n")
	lines.append("namespace oa {")
	lines.append("")
	lines.append(f"/// {name}: {notes}")
	lines.append(f"class {name} : public Module {{")
	lines.append("public:")
	# Emit both default constructor (if specified) and parameterized constructor
	if constructor:
		lines.append(f"\t{constructor}")
	if constructor_args is not None:
		explicit_prefix = "explicit " if constructor_explicit else ""
		lines.append(f"\t{explicit_prefix}{name}({constructor_args});")
	elif not constructor:
		lines.append(f"\t{name}() = default;")
	lines.append("\tMatrix forward(const Matrix& inInput) override;")
	for method in methods:
		lines.append(f"\t{method}")
	if members:
		lines.append("")
		lines.append("private:")
		for member in members:
			lines.append(f"\t{member}")
	lines.append("};")
	lines.append("")
	lines.append("} // namespace oa")
	lines.append("")
	return "\n".join(lines)


def emit_cpp(layer: dict, schema_name: str) -> str:
	name = layer["name"]
	fn = layer.get("fn")
	forward_body = layer.get("forward_body")
	notes = layer.get("notes", "")
	constructor_args = layer.get("constructor_args")
	constructor_init = layer.get("constructor_init", "")
	constructor_body = layer.get("constructor_body", [])
	extra_methods = layer.get("extra_methods", "")
	extra_includes = layer.get("extra_includes", "")
	constructor_def = ""
	if constructor_args is not None:
		cpp_constructor_args = cpp_param_list_without_defaults(constructor_args)
		init = f"\n\t: {constructor_init}" if constructor_init else ""
		body_lines = "\n".join(f"\t{line}" for line in constructor_body)
		constructor_def = (
			f"oa::{name}::{name}({cpp_constructor_args})"
			f"{init} {{\n"
			f"{body_lines}\n"
			"}\n\n"
		)
	if forward_body is None:
		forward_body = f"\treturn {fn};\n"
	elif not forward_body.endswith("\n"):
		forward_body += "\n"
	body_constructs_grad_node = "oa::makeShared<oa::Grad" in forward_body
	autograd_include = (
		f"#include <{layer['autograd_node_header']}>\n"
		if body_constructs_grad_node else ""
	)

	return (
		GEN_HEADER.format(schema_name=schema_name)
		+ f"// oa::{name} - {notes}\n\n"
		+ "#include <oa/ml/nn.h>\n"
		+ "#include <oa/core/fnMatrix.h>\n"
		+ autograd_include
		+ "#include <oa/core/validation.h>\n"
		+ extra_includes
		+ "\n"
		+ constructor_def
		+ extra_methods
		+ f"oa::Matrix oa::{name}::forward(const oa::Matrix& inInput) {{\n"
		+ forward_body
		+ "}\n"
	)


def generated_cpp_base(out_root: Path) -> Path:
	return out_root / "lib" / "oa" / "ml" / "nn"


def generated_header_base(out_root: Path) -> Path:
	return out_root / "include" / "oa" / "ml" / "nn"


def emit_umbrella(layers: list[tuple[Path, Path]], out_root: Path) -> str:
	lines = [GEN_HEADER.format(schema_name="all NN schemas")]
	lines.append("#pragma once\n")
	nn_base = generated_header_base(out_root)
	for header_path, _cpp_path in layers:
		# Include path relative to the include/oa/ml/nn root (e.g. "relu/relu.h")
		try:
			rel = header_path.relative_to(nn_base)
		except ValueError:
			rel = Path(header_path.name)
		lines.append(f'#include "{rel.as_posix()}"')
	lines.append("")
	return "\n".join(lines)


def emit_cmake_sources(
	layers: list[tuple[Path, Path]], out_root: Path
) -> str:
	lines = [
		GEN_CMAKE_MARKER,
		"# Regenerate via: python3 tools/nnAutogen/oannautogen.py --live",
		"",
		"set(OA_NN_GENERATED_SOURCES",
	]
	for _header_path, cpp_path in layers:
		# Manifests are reproducible from live and scratch output roots alike.
		rel = Path("source") / "cpp" / cpp_path.relative_to(out_root)
		lines.append(f"\t{rel.as_posix()}")
	lines.append(")")
	lines.append("")
	return "\n".join(lines)


def write_manifest_files(layers: list[tuple[Path, Path]], out_root: Path, *, dry_run: bool) -> None:
	umbrella_path = generated_header_base(out_root) / "layers.h"
	cmake_path = generated_cpp_base(out_root) / "nnSources.gen.cmake"
	if dry_run:
		print(f"  would write: {umbrella_path}")
		print(f"  would write: {cmake_path}")
		return
	write_generated_text(umbrella_path, emit_umbrella(layers, out_root))
	write_generated_text(cmake_path, emit_cmake_sources(layers, out_root))
	legacy_umbrellas = (
		out_root / "include" / "oa" / "ml" / "nn.gen.h",
		generated_header_base(out_root) / "nn.gen.h",
		generated_cpp_base(out_root) / "nn.gen.h",
	)
	for legacy_umbrella in legacy_umbrellas:
		if legacy_umbrella != umbrella_path and legacy_umbrella.exists():
			legacy_umbrella.unlink()
	print(f"  wrote {umbrella_path.name}, {cmake_path.name}")


def remove_stale_outputs(
	layers: list[tuple[Path, Path]],
	out_root: Path,
	*,
	dry_run: bool,
) -> None:
	expected = {header_path for header_path, _ in layers}
	expected.update(cpp_path for _, cpp_path in layers)
	expected.add(generated_header_base(out_root) / "layers.h")
	expected.add(generated_cpp_base(out_root) / "nnSources.gen.cmake")

	for base in (generated_header_base(out_root), generated_cpp_base(out_root)):
		if not base.exists():
			continue
		for candidate in base.rglob("*"):
			if not candidate.is_file() or candidate in expected:
				continue
			try:
				first_line = candidate.open(encoding="utf-8").readline().rstrip("\r\n")
			except (OSError, UnicodeError):
				continue
			if first_line not in (GEN_SOURCE_MARKER, GEN_CMAKE_MARKER):
				continue
			if dry_run:
				print(f"  would remove stale: {candidate}")
			else:
				candidate.unlink()
				print(f"  removed stale: {candidate}")


def process_schema(schema_path: Path, out_root: Path, *, live: bool, dry_run: bool) -> list[tuple[Path, Path]]:
	with schema_path.open("rb") as f:
		data = tomllib.load(f)
	layers = data.get("layers", [])
	if not layers:
		fail(f"{schema_path}: no [[layers]] entries")
	for layer in layers:
		validate_layer(schema_path, layer)
	schema_name = schema_label(schema_path)
	print(f"oannautogen: {schema_path.name} - {len(layers)} layers")
	result: list[tuple[Path, Path]] = []
	for layer in layers:
		header_path, cpp_path = out_paths(layer, out_root, live=live)
		result.append((header_path, cpp_path))
		if dry_run:
			print(f"  would write: {header_path}")
			print(f"  would write: {cpp_path}")
			continue
		write_generated_text(header_path, emit_header(layer, schema_name))
		write_generated_text(cpp_path, emit_cpp(layer, schema_name))
		relative_header = header_path.relative_to(
			out_root / "include" / "oa")
		legacy_private_header = out_root / "lib" / "oa" / relative_header
		if legacy_private_header.exists():
			legacy_private_header.unlink()
		print(f"  wrote {header_path.name}, {cpp_path.name}")
	return result


def main() -> int:
	parser = argparse.ArgumentParser(description="Generate oa::Module NN layer wrappers from schema.")
	parser.add_argument("--schema-dir", type=Path, default=SCHEMA_DIR)
	parser.add_argument("--schema", type=Path, default=None)
	parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
	parser.add_argument("--live", action="store_true")
	parser.add_argument("--dry-run", action="store_true")
	args = parser.parse_args()
	if args.live and args.schema and not args.dry_run:
		fail("--schema cannot be combined with --live because Layers.h and NnSources.gen.cmake require every schema")

	out_root = LIVE_SOURCE_ROOT if args.live else args.out
	if args.live:
		print("oannautogen: LIVE MODE - writing to source/ tree")
	schemas = [args.schema] if args.schema else sorted(args.schema_dir.rglob("*.toml"))
	if not schemas:
		fail(f"no schemas found in {args.schema_dir}")
	layers: list[tuple[Path, Path]] = []
	for schema_path in schemas:
		layers.extend(process_schema(schema_path, out_root, live=args.live, dry_run=args.dry_run))
	print(f"oannautogen: generated NN manifest - {len(layers)} layers")
	write_manifest_files(layers, out_root, dry_run=args.dry_run)
	if args.schema is None:
		remove_stale_outputs(layers, out_root, dry_run=args.dry_run)
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
