// @generated by tool/gen/fn/generate.py; DO NOT EDIT.
// schema=matrix_index.json schema_version=1 generator_version=64
// schema_sha256=d8dcc521d7c0f1e349c806b97571addc859ed4779ca094dfdc7791e6fd641c5e
//! Tape traversal adapters; numerical adjoints live in Matrix operation providers.

use super::GradientContext;
use crate::matrix;
use crate::{Matrix, Result};

pub(super) fn slice(
	input: &Matrix,
	output_id: &u64,
	dim: &usize,
	start: &usize,
	end: &usize,
	gradients: &mut impl GradientContext,
) -> Result<bool> {
	let Some(output_gradient) = gradients.take_output(*output_id) else {
		return Ok(false);
	};
	let input_gradient = matrix::slice_backward(input.shape(), *dim, *start, *end, &output_gradient)?;
	gradients.accumulate(input.value_id(), input_gradient)?;
	Ok(true)
}

pub(super) fn repeat_interleave(
	input: &Matrix,
	output_id: &u64,
	repeats: &usize,
	dim: &usize,
	gradients: &mut impl GradientContext,
) -> Result<bool> {
	let Some(output_gradient) = gradients.take_output(*output_id) else {
		return Ok(false);
	};
	let input_gradient =
		matrix::repeat_interleave_backward(input.shape(), *repeats, *dim, &output_gradient)?;
	gradients.accumulate(input.value_id(), input_gradient)?;
	Ok(true)
}

pub(super) fn gather(
	input: &Matrix,
	indices: &Matrix,
	output_id: &u64,
	gradients: &mut impl GradientContext,
) -> Result<bool> {
	let Some(output_gradient) = gradients.take_output(*output_id) else {
		return Ok(false);
	};
	let input_gradient = matrix::gather_backward(input.shape(), indices, &output_gradient)?;
	gradients.accumulate(input.value_id(), input_gradient)?;
	Ok(true)
}

pub(super) fn gather_last_dim(
	input: &Matrix,
	indices: &Matrix,
	output_id: &u64,
	input_width: &usize,
	gradients: &mut impl GradientContext,
) -> Result<bool> {
	let Some(output_gradient) = gradients.take_output(*output_id) else {
		return Ok(false);
	};
	let input_gradient = matrix::gather_last_dim_backward(&output_gradient, indices, *input_width)?;
	gradients.accumulate(input.value_id(), input_gradient)?;
	Ok(true)
}

pub(super) fn concat(
	inputs: &[Matrix],
	output_id: &u64,
	dim: &usize,
	sizes: &[usize],
	gradients: &mut impl GradientContext,
) -> Result<bool> {
	let Some(output_gradient) = gradients.take_output(*output_id) else {
		return Ok(false);
	};
	let input_gradients = matrix::concat_backward(&output_gradient, *dim, sizes)?;
	for (input, input_gradient) in inputs.iter().zip(input_gradients) {
		if let Some(input_gradient) = input_gradient {
			gradients.accumulate(input.value_id(), input_gradient)?;
		}
	}
	Ok(true)
}

pub(super) fn transpose(
	input: &Matrix,
	output_id: &u64,
	dim0: &usize,
	dim1: &usize,
	gradients: &mut impl GradientContext,
) -> Result<bool> {
	let Some(output_gradient) = gradients.take_output(*output_id) else {
		return Ok(false);
	};
	let input_gradient = matrix::transpose_backward(&output_gradient, *dim0, *dim1)?;
	gradients.accumulate(input.value_id(), input_gradient)?;
	Ok(true)
}
