// AUTO-GENERATED by Tools/NnAutogen/oannautogen.py - DO NOT EDIT.
// Source of truth: Tools/NnAutogen/Schema/Ml/MlNnEmbedding.toml.
// Regenerate via: python3 Tools/NnAutogen/oannautogen.py --live
// OaEmbedding - Embedding lookup layer.

#include <Oa/Ml/Nn.h>
#include <Oa/Core/FnMatrix.h>
#include <Oa/Ml/Autograd.h>
#include <Oa/Core/Validation.h>

OaEmbedding::OaEmbedding(OaI32 NumEmbeddings, OaI32 EmbeddingDim)
	: NumEmbeddings_(NumEmbeddings), EmbeddingDim_(EmbeddingDim) {
	RegisterParameter("weight", OaFnMatrix::RandN(OaMatrixShape{NumEmbeddings, EmbeddingDim}, OaFnMatrix::GetWeightDtype()));
}

OaMatrix OaEmbedding::Forward(const OaMatrix& InInput) {
	auto& weight = Params_[0].Data;
	auto out = OaFnMatrix::Gather(weight, InInput);
	if (OaFnAutograd::IsEnabled() and (weight.RequiresGrad())) {
		auto gradFn = OaMakeSharedPtr<OaGradGather>();
		gradFn->Saved_         = OaVec<OaMatrix>{InInput, weight};
		gradFn->SetGraphInputs(  OaVec<OaMatrix>{weight, InInput});
		gradFn->SequenceNr_    = OaFnAutograd::NextSeq();
		gradFn->OutputShape_   = out.GetShape();
		out.MutAutograd().GradFn = gradFn;
	}
	return out;
}
