// AUTO-GENERATED by Tools/NnAutogen/oannautogen.py - DO NOT EDIT.
// Source of truth: Tools/NnAutogen/Schema/Ml/MlNnEmbedding.toml.
// Regenerate via: python3 Tools/NnAutogen/oannautogen.py --live

#pragma once

/// OaEmbedding: Embedding lookup layer.
class OaEmbedding : public OaModule {
public:
	OaEmbedding(OaI32 NumEmbeddings, OaI32 EmbeddingDim);
	OaMatrix Forward(const OaMatrix& InInput) override;
	[[nodiscard]] OaI32 NumEmbeddings() const { return NumEmbeddings_; }
	[[nodiscard]] OaI32 EmbeddingDim() const { return EmbeddingDim_; }

private:
	OaI32 NumEmbeddings_;
	OaI32 EmbeddingDim_;
};
