// AUTO-GENERATED by Tools/NnAutogen/oannautogen.py - DO NOT EDIT.
// Source of truth: Tools/NnAutogen/Schema/Ml/MlNnLinear.toml.
// Regenerate via: python3 Tools/NnAutogen/oannautogen.py --live
// OaSwiGLU - SwiGLU MLP layer with optional weight concatenation.

#include <Oa/Ml/Nn.h>
#include <Oa/Core/FnMatrix.h>
#include <Oa/Core/Validation.h>

OaSwiGLU::OaSwiGLU(OaI32 InFeatures, OaI32 IntermediateSize, bool InBias)
	: HasBias_(InBias) {
	auto wd = OaFnMatrix::GetWeightDtype();
	RegisterParameter("gate_weight", OaFnMatrix::RandXavier(OaMatrixShape{IntermediateSize, InFeatures}, wd));
	RegisterParameter("up_weight", OaFnMatrix::RandXavier(OaMatrixShape{IntermediateSize, InFeatures}, wd));
	RegisterParameter("down_weight", OaFnMatrix::RandXavier(OaMatrixShape{InFeatures, IntermediateSize}, wd));
	if (InBias) {
		RegisterParameter("gate_bias", OaFnMatrix::Zeros(OaMatrixShape{IntermediateSize}, wd));
		RegisterParameter("up_bias", OaFnMatrix::Zeros(OaMatrixShape{IntermediateSize}, wd));
		RegisterParameter("down_bias", OaFnMatrix::Zeros(OaMatrixShape{InFeatures}, wd));
	}
}

OaMatrix OaSwiGLU::Forward(const OaMatrix& InInput) {
	// Step 1: Fused gate+up projection (if fused weights available)
	auto& gate_weight = Params_[0].Data;
	auto& up_weight = Params_[1].Data;
	auto& down_weight = Params_[2].Data;

	// TODO: Use fused GEMM when FusedGateUpWeight is initialized
	// For now, use separate GEMMs
	auto gate = OaFnMatrix::MatMulNt(InInput, gate_weight);
	auto up = OaFnMatrix::MatMulNt(InInput, up_weight);

	// Step 2: SwiGLU activation
	auto glu = OaFnMatrix::Swiglu(gate, up);

	// Step 3: Down projection
	if (HasBias_ && Params_.Size() > 5) {
		auto& down_bias = Params_[5].Data;
		return OaFnMatrix::Linear(glu, down_weight, down_bias);
	}
	return OaFnMatrix::MatMulNt(glu, down_weight);
}
